//! Cell C.2 — slot interface emitter per L0 #3 §8.
//!
//! Each `cells <field> @client.<slot>` binding in a `.lzx` view
//! materialises a typed `*Props` interface that the user-authored
//! `features/<feat>/<target>/cells/<slot>.tsx` implements. The
//! generated file lives at
//! `dist/ts-<target>/<feat>/cells/<slot>.gen.ts`:
//!
//! ```typescript
//! // Code generated by lazuli; DO NOT EDIT.
//! import type { Slug } from "../slug.gen.js";
//!
//! export interface TypeBadgeProps {
//!   value: Slug["tags"];
//!   row: Slug;
//! }
//! ```
//!
//! Naming convention: a slot named `type_badge` pascal-cases to
//! `TypeBadge`, and the interface name is `<PascalSlot>Props` →
//! `TypeBadgeProps`.
//!
//! ### Multi-binding rules (§8 v0)
//!
//! A slot may be bound in multiple views (e.g. `cells tags
//! @client.type_badge` in both `slug_list` AND `slug_detail`). For v0
//! the emitter picks the FIRST encountered binding's field type as
//! authoritative and emits a comment listing the alternative binding
//! sites. A discriminated-union upgrade is reserved for a future
//! follow-up cell.
//!
//! ### Section slots
//!
//! When a slot name matches a view detail's `sections` entry (rather
//! than a `cells <field>` binding), the slot receives the whole row,
//! not a single field. The emitter then drops `value: Resource["field"]`
//! in favour of `value: void; row: <Resource>;`.
//!
//! ### Graceful missing-resource fallback
//!
//! If the slot's source query cannot be resolved to a feature
//! resource (e.g. cross-feature query whose returning resource is
//! not in this feature's `resources` list, or a `Sql` query without
//! a typed `returns`), the emitter falls back to `unknown`-typed
//! props and embeds a `// TODO` comment naming the unresolved source.
//! This keeps `tsc --noEmit` green while flagging the gap.

use lazuli_codegen_spec::RuntimeFeature;

use crate::lzx_audience_slot::ir::{Surface, View, ViewCreate, ViewDetail, ViewList};
use crate::lzx_audience_slot::pascal_case;

mod emit;

#[cfg(test)]
mod tests;

/// Emit the `<slot>.gen.ts` file body for a given slot reference. The
/// caller pairs this with the canonical file path
/// (`dist/ts-<target>/<feat>/cells/<slot>.gen.ts`) when writing.
///
/// Walks every view in `surface` looking for `cells.field == ... &&
/// cells.slot == slot_name`. The first match wins; alternative
/// bindings are listed as a `// Also bound by:` comment block so
/// human reviewers see the divergence.
///
/// ## Examples
///
/// ```ignore
/// use lazuli_codegen_ts::slot_interface::emit_slot_interface;
/// use lazuli_codegen_ts::lzx_audience_slot::ir::Surface;
/// use lazuli_ir::runtime::RuntimeFeature;
///
/// let surface: Surface = /* … */ unimplemented!();
/// let feature: RuntimeFeature = /* … */ unimplemented!();
/// let _src = emit_slot_interface(&surface, &feature, "type_badge");
/// ```
pub fn emit_slot_interface(surface: &Surface, feature: &RuntimeFeature, slot_name: &str) -> String {
    let pascal_slot = pascal_case(slot_name);
    let interface_name = format!("{pascal_slot}Props");
    let resource_pascal = pascal_case(&feature.name);

    // Walk every view to collect bindings + section matches. Track
    // bindings in source order so the FIRST encountered is the
    // authoritative type for the multi-binding case (§8 v0).
    let mut field_bindings: Vec<FieldBinding> = Vec::new();
    let mut section_bindings: Vec<SectionBinding> = Vec::new();

    for audience in &surface.audiences {
        for view in &audience.views {
            collect_bindings(
                view,
                &audience.name,
                slot_name,
                &mut field_bindings,
                &mut section_bindings,
            );
        }
    }

    // No binding at all — emit a typed-`unknown` shape with a TODO so
    // the user knows the slot file was generated but the contract is
    // unresolved. Matches the "missing source resource" graceful
    // fallback case.
    if field_bindings.is_empty() && section_bindings.is_empty() {
        return emit::emit_unresolved_slot(slot_name, &interface_name);
    }

    // Section-only binding — slot receives the whole row.
    if field_bindings.is_empty() {
        return emit::emit_section_slot(
            slot_name,
            &interface_name,
            &resource_pascal,
            feature,
            &section_bindings,
        );
    }

    // Cell binding present — pick the first, embed others as a comment.
    emit::emit_cell_slot(
        slot_name,
        &interface_name,
        &resource_pascal,
        feature,
        &field_bindings,
        &section_bindings,
    )
}

// ---------------------------------------------------------------------------
// Binding collection
// ---------------------------------------------------------------------------

#[derive(Debug)]
pub(crate) struct FieldBinding {
    pub(crate) audience: String,
    pub(crate) view: String,
    pub(crate) field: String,
}

#[derive(Debug)]
pub(crate) struct SectionBinding {
    pub(crate) audience: String,
    pub(crate) view: String,
}

fn collect_bindings(
    view: &View,
    audience: &str,
    slot_name: &str,
    field_bindings: &mut Vec<FieldBinding>,
    section_bindings: &mut Vec<SectionBinding>,
) {
    match view {
        View::List(v) => collect_from_list(v, audience, slot_name, field_bindings),
        View::Detail(v) => {
            collect_from_detail(v, audience, slot_name, field_bindings, section_bindings)
        }
        View::Create(v) => collect_from_create(v, audience, slot_name, field_bindings),
    }
}

fn collect_from_list(
    v: &ViewList,
    audience: &str,
    slot_name: &str,
    bindings: &mut Vec<FieldBinding>,
) {
    for cell in &v.cells {
        if cell.slot == slot_name {
            bindings.push(FieldBinding {
                audience: audience.to_owned(),
                view: v.name.clone(),
                field: cell.field.clone(),
            });
        }
    }
}

fn collect_from_detail(
    v: &ViewDetail,
    audience: &str,
    slot_name: &str,
    field_bindings: &mut Vec<FieldBinding>,
    section_bindings: &mut Vec<SectionBinding>,
) {
    for cell in &v.cells {
        if cell.slot == slot_name {
            field_bindings.push(FieldBinding {
                audience: audience.to_owned(),
                view: v.name.clone(),
                field: cell.field.clone(),
            });
        }
    }
    // Section names map straight to slot names — if the section name
    // matches `slot_name` it's a section-slot binding.
    for section in &v.sections {
        if section == slot_name {
            section_bindings.push(SectionBinding {
                audience: audience.to_owned(),
                view: v.name.clone(),
            });
        }
    }
}

fn collect_from_create(
    v: &ViewCreate,
    audience: &str,
    slot_name: &str,
    bindings: &mut Vec<FieldBinding>,
) {
    for cell in &v.cells {
        if cell.slot == slot_name {
            bindings.push(FieldBinding {
                audience: audience.to_owned(),
                view: v.name.clone(),
                field: cell.field.clone(),
            });
        }
    }
}
