[package]
name = "lazuli_cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "lazuli"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
lazuli_analyzer = { path = "../lazuli_analyzer" }
lazuli_changelog = { path = "../lazuli_changelog" }
lazuli_codegen_go = { path = "../lazuli_codegen_go" }
lazuli_codegen_spec = { path = "../lazuli_codegen_spec" }
lazuli_codegen_ts = { path = "../lazuli_codegen_ts" }
lazuli_ir = { path = "../lazuli_ir" }
lazuli_lsp = { path = "../lazuli_lsp" }
lazuli_openapi = { path = "../lazuli_openapi" }
lazuli_planner = { path = "../lazuli_planner" }
lazuli_syntax = { path = "../lazuli_syntax" }
serde.workspace = true
serde_json.workspace = true
notify = "6"
tokio.workspace = true
toml = "0.8"
tower-lsp.workspace = true
