[project]
name = "marketplace-mini"
module = "github.com/lazuli-lang/example-marketplace-mini"
schema = 1

[lazuli]
runtime = "0.1.0"

[lazurite]
template = "lazurite-default"
template_version = "0.1.0"

[plugins]
"@plugin/example/marketplace-pack" = { module = "github.com/lazuli-lang/example-marketplace-pack", version = "v0.1.0" }
"@plugin/example/payment-gateway" = { module = "github.com/lazuli-lang/example-payment-gateway", version = "v0.1.0" }

[generate.go]
out = "dist/go"
gofmt = true
strict = true
emit_main = true
submodule = true

[migrations]
generated = "dist/go/migrations"
manual = "migrations"
strategy = "auto"
