//! React hook emission for `@cap.File(...)` upload flows.
//!
//! The generated hook is deliberately per-domain: it imports the concrete
//! synthesized request/confirm/clear/get-url specs from `<feature>.gen.ts`
//! and orchestrates the browser-side PUT without exposing a generic command
//! chain helper.

use std::fmt::Write;

use lazuli_ir as ir;

mod hook_writer;

use hook_writer::write_hook;

#[derive(Clone)]
struct CapFileHookSite<'a> {
    resource: &'a ir::Resource,
    field: &'a ir::Field,
    capability: &'a ir::FileCapability,
    commands: CapFileCommands,
}

#[derive(Clone)]
struct CapFileCommands {
    request: String,
    confirm: String,
    clear: String,
    get_url: String,
}

/// Emit `<feature>.react.gen.ts` for web React consumers.
///
/// Returns `None` when the feature has no complete synthesized
/// `@cap.File` command group.
pub fn emit_cap_file_hooks_ts(feature: &ir::Feature) -> Option<String> {
    let sites = collect_cap_file_hook_sites(feature);
    if sites.is_empty() {
        return None;
    }

    let mut out = String::new();
    write_header(&mut out);
    write_imports(&mut out, feature, &sites);
    write_shared_helpers(&mut out);
    for site in &sites {
        write_hook(&mut out, feature, site);
    }
    Some(out)
}

fn collect_cap_file_hook_sites<'a>(feature: &'a ir::Feature) -> Vec<CapFileHookSite<'a>> {
    let mut sites = Vec::new();
    let mut resources: Vec<&ir::Resource> = feature.resources.iter().collect();
    resources.sort_by(|a, b| a.name.cmp(&b.name));

    for resource in resources {
        let mut fields: Vec<&ir::Field> = resource.fields.iter().collect();
        fields.sort_by(|a, b| a.name.cmp(&b.name));
        for field in fields {
            let ir::TypeRef::Capability(ir::CapabilityRef::File(capability)) = &field.type_ref
            else {
                continue;
            };
            let Some(commands) = synthesized_commands_for(feature, &resource.name, &field.name)
            else {
                continue;
            };
            sites.push(CapFileHookSite {
                resource,
                field,
                capability,
                commands,
            });
        }
    }

    sites
}

fn synthesized_commands_for(
    feature: &ir::Feature,
    resource: &str,
    field: &str,
) -> Option<CapFileCommands> {
    let mut request = None;
    let mut confirm = None;
    let mut clear = None;
    let mut get_url = None;

    for command in &feature.commands {
        let Some(marker) = command.synthesized_from_cap_file.as_ref() else {
            continue;
        };
        if marker.resource != resource || marker.field != field {
            continue;
        }
        match marker.role {
            ir::AutoPhotoCommandRole::Request => request = Some(command.name.clone()),
            ir::AutoPhotoCommandRole::Confirm => confirm = Some(command.name.clone()),
            ir::AutoPhotoCommandRole::Clear => clear = Some(command.name.clone()),
            ir::AutoPhotoCommandRole::GetUrl => get_url = Some(command.name.clone()),
        }
    }

    Some(CapFileCommands {
        request: request?,
        confirm: confirm?,
        clear: clear?,
        get_url: get_url?,
    })
}

fn write_header(out: &mut String) {
    writeln!(out, "// Code generated by lazuli; DO NOT EDIT.").ok();
    writeln!(
        out,
        "// React hooks for browser-side @cap.File upload orchestration."
    )
    .ok();
    writeln!(out).ok();
}

fn write_imports(out: &mut String, feature: &ir::Feature, sites: &[CapFileHookSite<'_>]) {
    writeln!(out, "import {{ LazuliError }} from \"@lazuli/runtime\";").ok();
    // React + react-query primitives imported via @lazuli/runtime/react
    // re-exports. Pilots may host the generated file at a path that can't
    // resolve raw `react` / `@tanstack/react-query` (e.g. dist/ts-web/
    // outside the per-app node_modules walk). The runtime re-export
    // funnels them through the same path map the rest of the SDK uses.
    writeln!(
        out,
        "import {{"
    )
    .ok();
    writeln!(out, "  useCallback,").ok();
    writeln!(out, "  useState,").ok();
    writeln!(out, "  useQueryClient,").ok();
    writeln!(out, "  useLazuliCommand,").ok();
    writeln!(out, "  useLazuliQuery,").ok();
    writeln!(out, "}} from \"@lazuli/runtime/react\";").ok();

    let mut imports = Vec::new();
    for site in sites {
        imports.push(command_ident(&feature.name, &site.commands.clear));
        imports.push(command_ident(&feature.name, &site.commands.confirm));
        imports.push(command_ident(&feature.name, &site.commands.get_url));
        imports.push(command_ident(&feature.name, &site.commands.request));
    }
    imports.sort();
    imports.dedup();

    writeln!(out, "import {{").ok();
    for ident in imports {
        writeln!(out, "  {ident},").ok();
    }
    writeln!(out, "}} from \"./{}.gen\";", feature.name).ok();
    writeln!(out).ok();
}

fn write_shared_helpers(out: &mut String) {
    writeln!(
        out,
        "function lazuliFileMimeAccepted(accept: readonly string[], contentType: string): boolean {{"
    )
    .ok();
    writeln!(
        out,
        "  const [gotFamily, gotSubtype] = contentType.split(\"/\");"
    )
    .ok();
    writeln!(out, "  if (!gotFamily || !gotSubtype) return false;").ok();
    writeln!(out, "  return accept.some((entry) => {{").ok();
    writeln!(out, "    const [family, subtype] = entry.split(\"/\");").ok();
    writeln!(
        out,
        "    const familyMatches = family === \"*\" || family === gotFamily;"
    )
    .ok();
    writeln!(
        out,
        "    const subtypeMatches = subtype === \"*\" || subtype === gotSubtype;"
    )
    .ok();
    writeln!(out, "    return familyMatches && subtypeMatches;").ok();
    writeln!(out, "  }});").ok();
    writeln!(out, "}}").ok();
    writeln!(out).ok();

    writeln!(
        out,
        "function lazuliFileSizeExceeded(maxBytes: number, gotBytes: number): LazuliError {{"
    )
    .ok();
    writeln!(out, "  return new LazuliError(400, {{").ok();
    writeln!(out, "    code: \"file_size_exceeded\",").ok();
    writeln!(
        out,
        "    message: `file exceeds max size of ${{maxBytes}} bytes (got ${{gotBytes}})`,"
    )
    .ok();
    writeln!(out, "    message_key: \"file_size_exceeded\",").ok();
    writeln!(
        out,
        "    data: {{ max_bytes: maxBytes, got_bytes: gotBytes }},"
    )
    .ok();
    writeln!(out, "  }});").ok();
    writeln!(out, "}}").ok();
    writeln!(out).ok();

    writeln!(
        out,
        "function lazuliFileMimeRejected(accept: readonly string[], got: string): LazuliError {{"
    )
    .ok();
    writeln!(out, "  return new LazuliError(400, {{").ok();
    writeln!(out, "    code: \"file_mime_rejected\",").ok();
    writeln!(
        out,
        "    message: `content type \"${{got}}\" is not in accept list ${{accept.join(\", \")}}`,"
    )
    .ok();
    writeln!(out, "    message_key: \"file_mime_rejected\",").ok();
    writeln!(out, "    data: {{ got, accept: [...accept] }},").ok();
    writeln!(out, "  }});").ok();
    writeln!(out, "}}").ok();
    writeln!(out).ok();

    writeln!(
        out,
        "function lazuliUploadPutFailed(status: number, statusText: string): LazuliError {{"
    )
    .ok();
    writeln!(out, "  return new LazuliError(status, {{").ok();
    writeln!(out, "    code: \"bad_request\",").ok();
    writeln!(
        out,
        "    message: `file upload PUT failed with status ${{status}} ${{statusText}}`,"
    )
    .ok();
    writeln!(out, "    data: {{ status, status_text: statusText }},").ok();
    writeln!(out, "  }});").ok();
    writeln!(out, "}}").ok();
    writeln!(out).ok();
}

fn format_accept_array(accept: &[ir::MimeType]) -> String {
    let parts: Vec<String> = accept
        .iter()
        .map(|m| {
            format!(
                "\"{}/{}\"",
                escape_js_string(&m.family),
                escape_js_string(&m.subtype)
            )
        })
        .collect();
    format!("[{}]", parts.join(", "))
}

fn command_ident(feature: &str, command_name: &str) -> String {
    let resource_pascal = pascal_case(feature);
    let feature_lc = feature.to_ascii_lowercase();
    let mut parts = command_name.split('_');
    let verb = parts.next().unwrap_or("");
    let mut out = verb.to_ascii_lowercase();
    out.push_str(&resource_pascal);
    let mut skipped_dup = false;
    for word in parts {
        if !skipped_dup && word.eq_ignore_ascii_case(&feature_lc) {
            skipped_dup = true;
            continue;
        }
        out.push_str(&pascal_case(word));
    }
    out
}

fn file_uri_property_name(field: &str) -> String {
    let leaf = field
        .rsplit(|ch: char| !ch.is_ascii_alphanumeric())
        .find(|part| !part.is_empty())
        .unwrap_or(field);
    format!("{}Uri", lower_camel(leaf))
}

fn screaming_snake(value: &str) -> String {
    to_snake_case(value).to_ascii_uppercase()
}

fn to_snake_case(value: &str) -> String {
    let mut out = String::new();
    let mut prev_was_lower_or_digit = false;
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            if ch.is_ascii_uppercase() && prev_was_lower_or_digit && !out.ends_with('_') {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
            prev_was_lower_or_digit = ch.is_ascii_lowercase() || ch.is_ascii_digit();
        } else {
            if !out.ends_with('_') && !out.is_empty() {
                out.push('_');
            }
            prev_was_lower_or_digit = false;
        }
    }
    out.trim_matches('_').to_owned()
}

fn pascal_case(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for word in value.split(|c: char| !c.is_ascii_alphanumeric()) {
        if word.is_empty() {
            continue;
        }
        if out.is_empty() && word.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
            out.push_str("App");
        }
        if matches!(
            word.to_ascii_lowercase().as_str(),
            "id" | "url" | "uri" | "html" | "json" | "sql" | "ttl"
        ) {
            out.push_str(&word.to_ascii_uppercase());
            continue;
        }
        let mut chars = word.chars();
        if let Some(first) = chars.next() {
            out.push(first.to_ascii_uppercase());
        }
        out.push_str(chars.as_str());
    }
    out
}

fn lower_camel(value: &str) -> String {
    let pascal = pascal_case(value);
    let mut chars = pascal.chars();
    let Some(first) = chars.next() else {
        return pascal;
    };
    let mut out = first.to_ascii_lowercase().to_string();
    out.push_str(chars.as_str());
    out
}

fn escape_js_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            ch if (ch as u32) < 0x20 => {
                out.push_str(&format!("\\u{:04x}", ch as u32));
            }
            _ => out.push(ch),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn file_uri_property_uses_field_leaf() {
        assert_eq!(file_uri_property_name("profile_photo"), "photoUri");
        assert_eq!(file_uri_property_name("asset"), "assetUri");
    }
}
