//! Runtime-form emitter — produces a Go file structurally identical to
//! the hand-written `dist/go/customer/customer.gen.go`. The output
//! consumes the `lazuli.dev/runtime/lazuli` library: it declares typed
//! `Resource[T]`, `Command[I, O]`, and `Query[A, R]` values plus a single
//! `init()` block that registers them with the runtime.
//!
//! Driven by `lazuli_codegen_spec::RuntimeFeature` rather than the full
//! `lazuli_ir::Module` so the proven form is pinned today; a later cut
//! adds the `Module` -> `RuntimeFeature` mapping for full IR coverage.

use std::fmt::Write;

use lazuli_codegen_spec::{FieldKind, RuntimeFeature};

mod command;
mod init;
mod query;
mod resource;

use command::write_command;
use init::write_init;
use query::write_query;
use resource::write_resource;

/// Emit the canonical `<feature>.gen.go` for a feature. The emitted source
/// matches the layout of the hand-written runtime spike fixture: header
/// banner, resource declaration, one section per command, one section per
/// query, and a final `init()` with `lazuli.Register(...)`.
///
/// ## Examples
///
/// ```ignore
/// use lazuli_codegen_go::emit_feature_go;
/// let go_src = emit_feature_go(&runtime_feature);
/// assert!(go_src.contains("func init()"));
/// ```
pub fn emit_feature_go(feature: &RuntimeFeature) -> String {
    let needs_time = feature
        .queries
        .iter()
        .any(|q| q.cache.as_ref().is_some_and(|c| c.ttl.contains("time.")));

    let mut s = String::new();
    write_header(&mut s, feature);
    write_imports(&mut s, needs_time);
    for resource in &feature.resources {
        write_resource(&mut s, resource);
    }
    for command in &feature.commands {
        write_command(&mut s, feature, command);
    }
    for query in &feature.queries {
        write_query(&mut s, feature, query);
    }
    write_init(&mut s, feature);
    s
}

// ----------------------------------------------------------------------------
// Header / imports
// ----------------------------------------------------------------------------

fn write_header(s: &mut String, feature: &RuntimeFeature) {
    writeln!(s, "// Code generated by lazuli; DO NOT EDIT.").ok();
    writeln!(s, "//").ok();
    writeln!(
        s,
        "// Source: {} (feature `{}`)",
        feature.source_path, feature.name
    )
    .ok();
    writeln!(s, "//").ok();
    writeln!(
        s,
        "// This file is hand-written for the runtime spike. Once the runtime API"
    )
    .ok();
    writeln!(
        s,
        "// stabilises, `crates/lazuli_codegen_go` produces files exactly like this."
    )
    .ok();
    writeln!(s, "package {}", feature.name).ok();
    writeln!(s).ok();
}

fn write_imports(s: &mut String, needs_time: bool) {
    writeln!(s, "import (").ok();
    if needs_time {
        writeln!(s, "\t\"time\"").ok();
        writeln!(s).ok();
    }
    writeln!(s, "\t\"lazuli.dev/runtime/lazuli\"").ok();
    writeln!(s, ")").ok();
    writeln!(s).ok();
}

// ----------------------------------------------------------------------------
// Helpers shared across submodules. `pub(super)` so children call them
// directly without re-exporting through the public surface.
// ----------------------------------------------------------------------------

pub(super) fn write_section_banner(s: &mut String, lines: &[String]) {
    writeln!(s, "// {}", "-".repeat(76)).ok();
    for line in lines {
        writeln!(s, "// {line}").ok();
    }
    writeln!(s, "// {}", "-".repeat(76)).ok();
    writeln!(s).ok();
}

pub(super) fn write_policy(s: &mut String, indent: &str, name: &str, atoms: &[(String, String)]) {
    let atoms_lit: Vec<String> = atoms
        .iter()
        .map(|(ns, n)| format!("{{Namespace: \"{ns}\", Name: \"{n}\"}}"))
        .collect();
    writeln!(
        s,
        "{indent}Policy:    lazuli.Policy{{Name: \"{name}\", Atoms: []lazuli.PolicyAtom{{{}}}}},",
        atoms_lit.join(", ")
    )
    .ok();
}

pub(super) fn field_kind_go(kind: FieldKind) -> &'static str {
    match kind {
        FieldKind::Text | FieldKind::Email => "string",
        FieldKind::Integer => "lazuli.ID",
        FieldKind::Boolean => "bool",
    }
}

/// PascalCase that recognises canonical acronyms (`id`, `url`, `api`, ...)
/// and renders them all-caps. Mirrors the Go convention: `customer.gen.go`
/// uses `ID`, `URL`, etc. — never `Id` / `Url`.
pub(super) fn pascal_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for word in s.split(|c: char| c == '_' || c == '-') {
        if word.is_empty() {
            continue;
        }
        if is_acronym(word) {
            out.push_str(&word.to_ascii_uppercase());
            continue;
        }
        let mut chars = word.chars();
        if let Some(first) = chars.next() {
            for u in first.to_uppercase() {
                out.push(u);
            }
        }
        out.push_str(chars.as_str());
    }
    out
}

/// lowerCamelCase using the same acronym table — but the leading word is
/// always lowercased, so `id_lookup` becomes `idLookup`, not `IDLookup`.
pub(super) fn lower_camel(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut first = true;
    for word in s.split(|c: char| c == '_' || c == '-') {
        if word.is_empty() {
            continue;
        }
        if first {
            out.push_str(&word.to_ascii_lowercase());
            first = false;
            continue;
        }
        if is_acronym(word) {
            out.push_str(&word.to_ascii_uppercase());
            continue;
        }
        let mut chars = word.chars();
        if let Some(c) = chars.next() {
            for u in c.to_uppercase() {
                out.push(u);
            }
        }
        out.push_str(chars.as_str());
    }
    out
}

fn is_acronym(word: &str) -> bool {
    matches!(
        word.to_ascii_lowercase().as_str(),
        "id" | "url" | "uri" | "api" | "html" | "json" | "sql" | "ttl"
    )
}

/// `customer.create` -> `CreateCustomerInput`. Multi-word commands like
/// `update_email` slot the resource between the verb and the modifier:
/// `UpdateCustomerEmailInput`.
pub(super) fn command_input_struct_name(short_name: &str, resource_pascal: &str) -> String {
    let mut parts = short_name.split('_');
    let verb = parts.next().unwrap_or("");
    let modifier_words: Vec<&str> = parts.collect();

    let mut out = pascal_case(verb);
    out.push_str(resource_pascal);
    for w in modifier_words {
        out.push_str(&pascal_case(w));
    }
    out.push_str("Input");
    out
}

/// Command var name: lowerCamel mirror of the input struct without the
/// `Input` suffix. `create` -> `createCustomer`; `update_email` ->
/// `updateCustomerEmail`.
pub(super) fn command_var_name(
    short_name: &str,
    resource_pascal: &str,
    _resource_name: &str,
) -> String {
    let mut parts = short_name.split('_');
    let verb = parts.next().unwrap_or("");
    let modifier_words: Vec<&str> = parts.collect();

    let mut out = verb.to_ascii_lowercase();
    out.push_str(resource_pascal);
    for w in modifier_words {
        out.push_str(&pascal_case(w));
    }
    out
}

/// Build `name, type, tag` rows where each tag's `db:"..."` segment is
/// padded so the `json:` segment lines up across all fields. Each input
/// tuple is `(field name, go type, db column, json tag)`.
pub(super) fn build_db_json_rows(
    tagged: &[(String, String, String, String)],
) -> Vec<(String, String, String)> {
    let max_db_key = tagged
        .iter()
        .map(|(_, _, db, _)| db.len())
        .max()
        .unwrap_or(0);
    tagged
        .iter()
        .map(|(name, ty, db, json)| {
            let db_part = format!("db:\"{}\"", db);
            let total_db_width = "db:\"".len() + max_db_key + 1; // closing quote
            let pad = total_db_width.saturating_sub(db_part.len());
            let tag = format!("`{}{} json:\"{}\"`", db_part, " ".repeat(pad), json);
            (name.clone(), ty.clone(), tag)
        })
        .collect()
}

/// Print a struct body with `name <pad> type <pad> tag` rows whose columns
/// align to the widest entry. Output matches what `go fmt` would produce.
pub(super) fn write_aligned_struct_rows(s: &mut String, rows: &[(String, String, String)]) {
    if rows.is_empty() {
        return;
    }
    let name_width = rows.iter().map(|(n, _, _)| n.len()).max().unwrap_or(0);
    let type_width = rows.iter().map(|(_, t, _)| t.len()).max().unwrap_or(0);
    for (name, ty, tag) in rows {
        writeln!(
            s,
            "\t{name:<name_width$} {ty:<type_width$} {tag}",
            name = name,
            ty = ty,
            tag = tag
        )
        .ok();
    }
}
