//! Per-effect dispatch tests — exercise the `emit_command` /
//! `emit_input_struct` pipeline's switch on `CommandEffect` variant
//! (`Creates` / `Updates` / `Deletes` / `Returns` / `None` + cap_file
//! synth wire-up). Lifted out of `emit.rs` (wave R8-2c) so the parent
//! file stays under the ≤500-LOC gold standard.
//!
//! Coverage cluster (one test per CommandEffect axis):
//!   - `Creates` empty input → struct{} I, no Input struct
//!   - `Creates` typed input → emitted Input struct + Bindings
//!   - `Returns` → `ReturnsFromRegistry[I, O]` + handler signature comment
//!   - `None` → `Effect: nil,` (legacy no-effect path)
//!   - `None` + `synthesized_from_cap_file` → `ReturnsFromRegistry` wire-up
//!   - `Updates` → `Updates(...)` with `id` WHERE and route-slot Input field
//!   - `Deletes` → `Deletes(...)` with `id` WHERE
//!
//! Companion file: `emit_bindings_and_handlers_tests.rs` covers the
//! binding-source projection (`bare_identifier`, `enum_literal`,
//! `emits`, `invalidates`) and the handler-wrapper sentinel logic.

#![cfg(test)]

use super::test_support::{
    base_command, base_feature, emit_with_customer_fallback as emit, local_qname, typed_slot,
};
use lazuli_ir::{
    Assignment, BuiltinType, CommandEffect, CommandInput, CommandKind, CreateEffect, DeleteEffect,
    Expr, Path, PolicyRef, ReturnsEffect, RouteSlot, TypeRef, UpdateEffect,
};

#[test]
fn empty_input_creates_command_skips_input_struct_and_uses_struct_unit() {
    // `delete` style command: no input slots, Creates effect on
    // Customer. The Command value still names a type pair, so we
    // surface `struct{}` for the I parameter.
    let mut feature = base_feature("customer");
    let mut cmd = base_command("archive");
    cmd.effect = CommandEffect::Creates(CreateEffect {
        resource: local_qname("Customer"),
        from_input: false,
        assignments: Vec::new(),
    });
    feature.commands.push(cmd);

    let out = emit(&feature).expect("must emit");
    assert!(out.contains("// Code generated by lazuli; DO NOT EDIT."));
    assert!(out.contains("package customergen"));
    // No Input struct on the empty-input branch.
    assert!(!out.contains("ArchiveCustomerInput"));
    assert!(out.contains("var archiveCustomer = lazuli.Command[struct{}, Customer]{"));
}

#[test]
fn typed_input_creates_command_emits_input_struct_and_creates_bindings() {
    let mut feature = base_feature("customer");
    let mut cmd = base_command("create");
    cmd.input = CommandInput::Typed(vec![
        typed_slot("name", BuiltinType::Text, true),
        typed_slot("email", BuiltinType::SemanticEmail, true),
    ]);
    cmd.policy = PolicyRef::Atom("@role.admin".to_owned());
    cmd.rate_limit = Some(lazuli_ir::RateLimitSpec::from_default(
        "30 per hour per ip".to_owned(),
    ));
    cmd.effect = CommandEffect::Creates(CreateEffect {
        resource: local_qname("Customer"),
        from_input: false,
        assignments: vec![
            Assignment {
                field: "name".to_owned(),
                value: Expr::Path(Path::from_segments(["input", "name"])),
            },
            Assignment {
                field: "email".to_owned(),
                value: Expr::Path(Path::from_segments(["input", "email"])),
            },
        ],
    });
    feature.commands.push(cmd);

    let out = emit(&feature).expect("must emit");
    // Input struct shape.
    assert!(out.contains("type CreateCustomerInput struct {"));
    // L0 #3 §10 (D.3) — required slots now stack a `validate:"required"`
    // alongside the json tag; both pieces ship in the same backtick block.
    assert!(out.contains("json:\"name\" validate:\"required\""));
    assert!(out.contains("json:\"email\" validate:\"required\""));
    assert!(out.contains("Email lazuli.Email"));
    // Command value shape.
    assert!(out.contains("var createCustomer = lazuli.Command[CreateCustomerInput, Customer]{"));
    assert!(out.contains("Name:      \"customer.create\","));
    assert!(out.contains("Resource:  &customerResource,"));
    assert!(out.contains("lazuli.PolicyAtom{{Namespace: \"role\", Name: \"admin\"}}"));
    assert!(out.contains("RateLimit: lazuli.RateLimit{Default: \"30 per hour per ip\"},"));
    // Effect block — Creates with two FromInput bindings.
    assert!(out.contains("Effect: lazuli.Creates(&customerResource, lazuli.Bindings{"));
    assert!(out.contains("\"name\": lazuli.FromInput(\"name\"),"));
    assert!(out.contains("\"email\": lazuli.FromInput(\"email\"),"));
}

#[test]
fn returns_command_emits_returns_effect_and_handler_signature_comment() {
    let mut feature = base_feature("customer");
    let mut cmd = base_command("summary");
    cmd.input = CommandInput::Typed(vec![typed_slot("id", BuiltinType::Id, true)]);
    cmd.effect = CommandEffect::Returns(ReturnsEffect {
        return_type: TypeRef::Builtin(BuiltinType::Text),
    });
    feature.commands.push(cmd);

    let out = emit(&feature).expect("must emit");
    // Handlers live in the same Go package — no `handlers` import
    // and no qualifier on the handler value.
    assert!(!out.contains("\"lazuli/test/customer/handlers\""));
    assert!(out.contains("var summaryResult = lazuli.Command[SummaryResultInput, string]{"));
    assert!(out.contains(
        "Effect: lazuli.ReturnsFromRegistry[SummaryResultInput, string](\"customer.summary\"),"
    ));
    assert!(!out.contains("Effect: lazuli.Returns(handlers.Summary),"));
    assert!(out.contains(
        "// Wire Summary as `func(ctx *lazuli.Ctx, input SummaryResultInput) (string, error)`"
    ));
    assert!(out.contains(
        "// then register with `lazuli.RegisterFn(\"customer.summary\", Summary)` at init()."
    ));
    assert!(!out.contains("TODO(returns):"));
}

#[test]
fn no_effect_command_emits_nil_effect_without_legacy_todo() {
    let mut feature = base_feature("customer");
    feature.commands.push(base_command("summary"));

    let out = emit(&feature).expect("must emit");
    assert!(out.contains("Effect: nil,"));
    assert!(
        out.contains("// No-effect commands are pure-read legacy APIs invoked via command.Invoke.")
    );
    assert!(!out.contains("TODO(effect):"));
}

#[test]
fn cap_file_synthesised_no_effect_command_wires_returns_from_registry() {
    use lazuli_ir::{AutoPhotoCommandRole, BuiltinType, CommandInput, SynthesizedFromCapFile};
    let mut feature = base_feature("customer");
    let mut cmd = base_command("confirm_profile_photo_upload");
    cmd.input = CommandInput::Typed(vec![typed_slot("key", BuiltinType::Text, true)]);
    cmd.effect = CommandEffect::None;
    cmd.handler = None;
    cmd.synthesized_from_cap_file = Some(SynthesizedFromCapFile {
        resource: "Customer".to_owned(),
        field: "profile_photo".to_owned(),
        role: AutoPhotoCommandRole::Confirm,
    });
    feature.commands.push(cmd);

    let out = emit(&feature).expect("must emit");
    // The runtime fn lives in auto_photo.gen.go under "customer.confirm_profile_photo_upload".
    // Effect must forward to that registry key with struct{} return — without
    // the wire-up the runtime 500s with "command has no effect".
    assert!(
        out.contains(
            "Effect: lazuli.ReturnsFromRegistry[ConfirmResultProfilePhotoUploadInput, struct{}](\"customer.confirm_profile_photo_upload\"),"
        ),
        "missing ReturnsFromRegistry wire-up for cap_file confirm:\n{out}"
    );
    assert!(!out.contains("Effect: nil,"));
    assert!(out.contains(
        "// cap_file synth: handler registered by auto_photo.gen.go under \"customer.confirm_profile_photo_upload\"."
    ));
}

#[test]
fn updates_emits_updates_effect_with_id_where_clause() {
    let mut feature = base_feature("customer");
    let mut cmd = base_command("update_tier");
    cmd.kind = CommandKind::Update;
    cmd.route = vec![RouteSlot {
        name: "id".to_owned(),
        type_ref: TypeRef::Builtin(BuiltinType::Id),
        from: None,
        kind: lazuli_ir::RouteSlotKind::Plain,
    }];
    cmd.input = CommandInput::Typed(vec![typed_slot("tier", BuiltinType::Text, true)]);
    cmd.policy = PolicyRef::Local("update".to_owned());
    cmd.effect = CommandEffect::Updates(UpdateEffect {
        resource: local_qname("Customer"),
        assignments: vec![Assignment {
            field: "tier".to_owned(),
            value: Expr::Path(Path::from_segments(["input", "tier"])),
        }],
        where_clause: Vec::new(),
    });
    feature.commands.push(cmd);

    let out = emit(&feature).expect("must emit");
    assert!(
        out.contains("var updateCustomerTier = lazuli.Command[UpdateCustomerTierInput, Customer]{")
    );
    assert!(out.contains("Effect: lazuli.Updates(&customerResource,"));
    assert!(out.contains("lazuli.Bindings{\"id\": lazuli.FromInput(\"ID\")},"));
    assert!(out.contains("\"tier\": lazuli.FromInput(\"tier\"),"));
    // LAZ-route-id-codegen-go (Cell A1) — the route slot MUST land
    // on the emitted Input struct so the `FromInput("ID")` binding
    // above resolves at runtime. Route fields come first, body
    // fields after. `pascal_case("id")` hits the acronym path so
    // the Go field name is `ID`, not `Id`; the route type ref
    // `BuiltinType::Id` lowers to `lazuli.ID` via go_type_for.
    assert!(
        out.contains("type UpdateCustomerTierInput struct {"),
        "Input struct must be emitted for route + body commands:\n{out}"
    );
    assert!(
        out.contains("ID   lazuli.ID `json:\"id\" validate:\"required\"`"),
        "route id slot must surface as `ID lazuli.ID` aligned field:\n{out}"
    );
    assert!(
        out.contains("Tier string    `json:\"tier\" validate:\"required\"`"),
        "body Tier field must remain after the route Id field:\n{out}"
    );
    // Ordering invariant — route slots precede body slots.
    let id_pos = out
        .find("ID   lazuli.ID")
        .expect("ID field must be emitted");
    let tier_pos = out.find("Tier string").expect("Tier field must be emitted");
    assert!(
        id_pos < tier_pos,
        "route slots must precede body slots in the Input struct:\n{out}"
    );
    // SECURITY (POLICY-REF-UNRESOLVED): no `policies` block declares `update`
    // in this test feature, so `@policy.update` is unresolvable. The emitter
    // fails CLOSED with a deny atom rather than the former Name-only empty-atoms
    // policy (a silent bypass).
    assert!(out.contains(
        "lazuli.Policy{Name: \"@policy.update\", Atoms: []lazuli.PolicyAtom{{Namespace: \"predicate\", Name: \"deny\"}}},"
    ));
    assert!(
        !out.contains("lazuli.Policy{Name: \"@policy.update\"},"),
        "regression: unresolvable command policy must not emit Name-only (no Atoms) = bypass:\n{out}"
    );
}

#[test]
fn deletes_emits_deletes_effect_with_id_binding() {
    let mut feature = base_feature("customer");
    let mut cmd = base_command("archive");
    cmd.kind = CommandKind::Delete;
    cmd.input = CommandInput::Typed(vec![typed_slot("id", BuiltinType::Id, true)]);
    cmd.effect = CommandEffect::Deletes(DeleteEffect {
        resource: local_qname("Customer"),
        where_clause: Vec::new(),
    });
    feature.commands.push(cmd);

    let out = emit(&feature).expect("must emit");
    assert!(out.contains("var archiveCustomer = lazuli.Command[ArchiveCustomerInput, Customer]{"));
    assert!(out.contains("Effect: lazuli.Deletes(&customerResource, lazuli.Bindings{"));
    assert!(out.contains("\"id\": lazuli.FromInput(\"ID\"),"));
}

#[test]
fn deletes_command_invokes_referential_guard_before_handle() {
    // Spec 0014 BUG-2 regression — the SINGLE most important assertion this
    // primitive was missing: a `deletes <R>` command on a resource carrying a
    // `restrict on_delete` clause MUST invoke the emitted `guard<R><Rel>Refs`
    // probe BEFORE dispatching to `.Handle` (which opens the delete tx). The
    // guard FILE emitting in isolation was never enough — the delete handler
    // never called it, so the clause provided zero protection.
    let mut feature = base_feature("catalog");

    // Resource being protected: `Category`, with a guard against a live
    // `customer` referencing it via `category_id` (tenant-scoped + soft-delete
    // derived flags set so the probe is the canonical pauta shape).
    let mut category = super::test_support::simple_resource("Category");
    category.restrict_on_delete = vec![lazuli_ir::RestrictOnDelete {
        relation: "customer".to_owned(),
        fk: "category_id".to_owned(),
        extra_where: None,
        tenant_scoped: true,
        soft_delete: true,
        error_code: None,
    }];
    feature.resources.push(category);

    // The delete command, addressed by `route id: ID`.
    let mut cmd = base_command("delete_category");
    cmd.kind = CommandKind::Delete;
    cmd.route = vec![RouteSlot {
        name: "id".to_owned(),
        type_ref: TypeRef::Builtin(BuiltinType::Id),
        from: None,
        kind: lazuli_ir::RouteSlotKind::Plain,
    }];
    cmd.input = CommandInput::Empty;
    cmd.effect = CommandEffect::Deletes(DeleteEffect {
        resource: local_qname("Category"),
        where_clause: Vec::new(),
    });
    feature.commands.push(cmd);

    let out = emit(&feature).expect("must emit");

    // BUG-2 — the guard call MUST be wired into the handler, passing the live
    // pool (`lazuli.DB()` → satisfies `lazuli.DBTX`), the nil-safe tenant org
    // id, and the deleted row's id field (`input.ID`, since `pascal_case("id")`
    // hits the acronym path).
    assert!(
        out.contains(
            "if err := guardCategoryCustomerRefs(ctx, lazuli.DB(), lazuli.TenantOrgID(ctx), input.ID); err != nil {"
        ),
        "delete command must invoke the referential guard before .Handle:\n{out}"
    );

    // Ordering invariant — the guard call MUST precede the `.Handle` dispatch,
    // otherwise the row is already gone (or the tx already open) by the time
    // we probe.
    let guard_pos = out
        .find("guardCategoryCustomerRefs(")
        .expect("guard call must be emitted");
    let handle_pos = out
        .find(".Handle(ctx, input)")
        .expect("handler dispatch must be emitted");
    assert!(
        guard_pos < handle_pos,
        "guard probe must run BEFORE the handler dispatch:\n{out}"
    );
}

#[test]
fn soft_delete_updates_command_invokes_referential_guard() {
    // The canonical pauta shape — `delete_department` is `updates Department …
    // deleted_at = ctx.now` (a SOFT delete via `updates`, NOT `deletes`). The
    // guard MUST still fire: an `updates` that writes `deleted_at` is a delete
    // for referential-integrity purposes. This is the exact case the primitive
    // was built to protect (it replaces the hand-written
    // `@validator.guard_no_active_teams`).
    let mut feature = base_feature("agency");
    let mut department = super::test_support::simple_resource("Department");
    department.restrict_on_delete = vec![lazuli_ir::RestrictOnDelete {
        relation: "team".to_owned(),
        fk: "department_id".to_owned(),
        extra_where: None,
        tenant_scoped: true,
        soft_delete: true,
        error_code: None,
    }];
    feature.resources.push(department);

    let mut cmd = base_command("delete_department");
    cmd.kind = CommandKind::Update; // soft delete lowers to Update kind
    cmd.route = vec![RouteSlot {
        name: "id".to_owned(),
        type_ref: TypeRef::Builtin(BuiltinType::Id),
        from: None,
        kind: lazuli_ir::RouteSlotKind::Plain,
    }];
    cmd.input = CommandInput::Empty;
    cmd.effect = CommandEffect::Updates(UpdateEffect {
        resource: local_qname("Department"),
        assignments: vec![Assignment {
            field: "deleted_at".to_owned(),
            value: Expr::Path(Path::from_segments(["ctx", "now"])),
        }],
        where_clause: Vec::new(),
    });
    feature.commands.push(cmd);

    let out = emit(&feature).expect("must emit");
    assert!(
        out.contains(
            "if err := guardDepartmentTeamRefs(ctx, lazuli.DB(), lazuli.TenantOrgID(ctx), input.ID); err != nil {"
        ),
        "soft-delete (updates + deleted_at) command must invoke the referential guard:\n{out}"
    );
}

#[test]
fn plain_update_without_deleted_at_emits_no_guard_call() {
    // A NON-soft-delete `updates` (no `deleted_at` assignment) must NOT carry a
    // guard call — only deletes (hard or soft) trip the precondition.
    let mut feature = base_feature("agency");
    let mut department = super::test_support::simple_resource("Department");
    department.restrict_on_delete = vec![lazuli_ir::RestrictOnDelete {
        relation: "team".to_owned(),
        fk: "department_id".to_owned(),
        extra_where: None,
        tenant_scoped: true,
        soft_delete: true,
        error_code: None,
    }];
    feature.resources.push(department);

    let mut cmd = base_command("rename_department");
    cmd.kind = CommandKind::Update;
    cmd.route = vec![RouteSlot {
        name: "id".to_owned(),
        type_ref: TypeRef::Builtin(BuiltinType::Id),
        from: None,
        kind: lazuli_ir::RouteSlotKind::Plain,
    }];
    cmd.input = CommandInput::Typed(vec![typed_slot("name", BuiltinType::Text, true)]);
    cmd.effect = CommandEffect::Updates(UpdateEffect {
        resource: local_qname("Department"),
        assignments: vec![Assignment {
            field: "name".to_owned(),
            value: Expr::Path(Path::from_segments(["input", "name"])),
        }],
        where_clause: Vec::new(),
    });
    feature.commands.push(cmd);

    let out = emit(&feature).expect("must emit");
    assert!(
        !out.contains("guardDepartmentTeamRefs("),
        "a plain (non-soft-delete) update must not invoke a referential guard:\n{out}"
    );
}

#[test]
fn non_delete_command_emits_no_referential_guard_call() {
    // A `creates` command on a resource that ALSO declares a restrict clause
    // must NOT carry a guard call — the guard is a delete-only precondition.
    let mut feature = base_feature("catalog");
    let mut category = super::test_support::simple_resource("Category");
    category.restrict_on_delete = vec![lazuli_ir::RestrictOnDelete {
        relation: "customer".to_owned(),
        fk: "category_id".to_owned(),
        extra_where: None,
        tenant_scoped: true,
        soft_delete: true,
        error_code: None,
    }];
    feature.resources.push(category);

    let mut cmd = base_command("create_category");
    cmd.effect = CommandEffect::Creates(CreateEffect {
        resource: local_qname("Category"),
        from_input: false,
        assignments: Vec::new(),
    });
    feature.commands.push(cmd);

    let out = emit(&feature).expect("must emit");
    assert!(
        !out.contains("guardCategoryCustomerRefs("),
        "a creates command must not invoke a referential guard:\n{out}"
    );
}

// ---------------------------------------------------------------------
// Lifecycle initial-state auto-binding on `creates` (signup NOT-NULL bug)
// + bare `@fn.<name>` (no parens) → FromFn (signup tenant_id garbage bug)
// ---------------------------------------------------------------------

/// Build the pauta `User` lifecycle resource:
/// `lifecycle registration_step { state profile_setup initial;
///  state agency_setup; state complete terminal }`.
fn user_lifecycle_resource() -> lazuli_ir::Resource {
    use lazuli_ir::{Lifecycle, LifecycleState, LifecycleStateKind};
    let mut resource = super::test_support::simple_resource("User");
    resource.lifecycle = Some(Lifecycle {
        discriminator_field: "registration_step".to_owned(),
        generated_enum: "UserRegistrationStep".to_owned(),
        states: vec![
            LifecycleState {
                name: "profile_setup".to_owned(),
                kind: LifecycleStateKind::Initial,
                span_ref: None,
            },
            LifecycleState {
                name: "agency_setup".to_owned(),
                kind: LifecycleStateKind::Intermediate,
                span_ref: None,
            },
            LifecycleState {
                name: "complete".to_owned(),
                kind: LifecycleStateKind::Terminal,
                span_ref: None,
            },
        ],
        transitions: Vec::new(),
        invariants: Vec::new(),
        invariant_handlers: Vec::new(),
        previous_names: Vec::new(),
        span_ref: None,
    });
    resource
}

#[test]
fn creates_on_lifecycle_resource_auto_injects_initial_state_discriminator() {
    // BUG A — `creates User` that does NOT bind `registration_step` must
    // auto-inject `"registration_step": FromConst(UserRegistrationStepProfileSetup)`
    // (the initial-state const). Without it the NOT-NULL discriminator
    // column has no value at INSERT → constraint violation at runtime.
    let mut feature = base_feature("account");
    feature.resources.push(user_lifecycle_resource());

    let mut cmd = base_command("signup");
    cmd.input = CommandInput::Typed(vec![typed_slot("email", BuiltinType::Text, true)]);
    cmd.effect = CommandEffect::Creates(CreateEffect {
        resource: local_qname("User"),
        from_input: false,
        assignments: vec![Assignment {
            field: "email".to_owned(),
            value: Expr::Path(Path::from_segments(["input", "email"])),
        }],
    });
    feature.commands.push(cmd);

    let out = emit(&feature).expect("must emit");
    assert!(
        out.contains("\"registration_step\": lazuli.FromConst(UserRegistrationStepProfileSetup),"),
        "creates on a lifecycle resource must auto-inject the initial-state \
         discriminator binding:\n{out}"
    );
    // The author's explicit binding survives alongside the injected one.
    assert!(out.contains("\"email\": lazuli.FromInput(\"email\"),"));
}

#[test]
fn creates_with_explicit_discriminator_binding_is_not_overwritten() {
    // BUG A boundary — when the author DOES bind the discriminator
    // explicitly (e.g. seeding a row in a non-initial state), respect it:
    // emit exactly ONE binding, the author's, with no auto-injection.
    let mut feature = base_feature("account");
    feature.resources.push(user_lifecycle_resource());

    let mut cmd = base_command("seed_complete_user");
    cmd.effect = CommandEffect::Creates(CreateEffect {
        resource: local_qname("User"),
        from_input: false,
        assignments: vec![Assignment {
            field: "registration_step".to_owned(),
            value: Expr::Enum(lazuli_ir::EnumLiteral {
                type_name: Some(lazuli_ir::QualifiedName {
                    feature: None,
                    name: "UserRegistrationStep".to_owned(),
                }),
                variant: "complete".to_owned(),
            }),
        }],
    });
    feature.commands.push(cmd);

    let out = emit(&feature).expect("must emit");
    // Author binding present...
    assert!(
        out.contains("\"registration_step\": lazuli.FromConst(UserRegistrationStepComplete),"),
        "explicit author discriminator binding must be emitted:\n{out}"
    );
    // ...and the initial-state default was NOT also injected as a binding.
    // (The const `UserRegistrationStepProfileSetup` still legitimately
    // appears in the `lifecycle.New[...]( <initial>, ...)` machine decl —
    // we only assert it is not used as a *binding row* discriminator.)
    assert!(
        !out.contains("\"registration_step\": lazuli.FromConst(UserRegistrationStepProfileSetup),"),
        "must not auto-inject the initial state when the author bound the \
         discriminator explicitly:\n{out}"
    );
    assert_eq!(
        out.matches("\"registration_step\":").count(),
        1,
        "discriminator must be bound exactly once (no double-set):\n{out}"
    );
}

#[test]
fn creates_on_non_lifecycle_resource_is_unchanged() {
    // BUG A boundary — a `creates` on a resource WITHOUT a lifecycle must
    // emit no extra discriminator binding.
    let mut feature = base_feature("customer");
    let mut cmd = base_command("create");
    cmd.input = CommandInput::Typed(vec![typed_slot("name", BuiltinType::Text, true)]);
    cmd.effect = CommandEffect::Creates(CreateEffect {
        resource: local_qname("Customer"),
        from_input: false,
        assignments: vec![Assignment {
            field: "name".to_owned(),
            value: Expr::Path(Path::from_segments(["input", "name"])),
        }],
    });
    feature.commands.push(cmd);

    let out = emit(&feature).expect("must emit");
    assert!(out.contains("Effect: lazuli.Creates(&customerResource, lazuli.Bindings{"));
    assert!(out.contains("\"name\": lazuli.FromInput(\"name\"),"));
    // No lifecycle → no FromConst discriminator injection.
    assert!(
        !out.contains("RegistrationStep"),
        "non-lifecycle create must carry no discriminator binding:\n{out}"
    );
}

#[test]
fn bare_fn_ref_binding_emits_from_fn_not_const_string() {
    // BUG B — `tenant_id = @fn.placeholder_tenant_id` (bare, no parens)
    // must emit `lazuli.FromFn("placeholder_tenant_id", nil)`, NOT the
    // garbage `lazuli.FromConst("@fn.placeholder_tenant_id")` string.
    // The analyzer lowers the bare ref to a zero-arg FnCall; codegen's
    // FnCall arm renders FromFn with `nil` args.
    let mut feature = base_feature("account");
    feature.resources.push(user_lifecycle_resource());

    let mut cmd = base_command("signup");
    cmd.effect = CommandEffect::Creates(CreateEffect {
        resource: local_qname("User"),
        from_input: false,
        assignments: vec![Assignment {
            field: "tenant_id".to_owned(),
            value: Expr::FnCall(lazuli_ir::FnCallExpr {
                name: lazuli_ir::QualifiedName {
                    feature: None,
                    name: "placeholder_tenant_id".to_owned(),
                },
                args: Vec::new(),
            }),
        }],
    });
    feature.commands.push(cmd);

    let out = emit(&feature).expect("must emit");
    assert!(
        out.contains("\"tenant_id\": lazuli.FromFn(\"placeholder_tenant_id\", nil),"),
        "bare @fn ref must lower to a zero-arg FromFn, not a const string:\n{out}"
    );
    assert!(
        !out.contains("lazuli.FromConst(\"@fn.placeholder_tenant_id\")"),
        "the garbage const-string lowering must be gone:\n{out}"
    );
}
