[package]
name = "lazuli_codegen_ts"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
smoke = []

[dependencies]
lazuli_ir = { path = "../lazuli_ir" }
lazuli_codegen_spec = { path = "../lazuli_codegen_spec" }
serde_json.workspace = true

[dev-dependencies]
lazuli_analyzer = { path = "../lazuli_analyzer" }
lazuli_syntax = { path = "../lazuli_syntax" }
