//! Cell G1 - `Auth` kind emission. Walks the single auth block declared
//! on a feature and emits the lowered Lazuli Go auth contracts into
//! `<feature>/auth.gen.go`.
//!
//! Proposal references:
//! - Section 3.5 - Auth declaration shape.
//! - Section 11 - runtime boundary discipline. The only runtime package
//!   referenced here is `lazuli.dev/runtime/lazuli/auth`; session TTLs
//!   additionally use stdlib `time` because the current Lazuli Go
//!   `SessionsContract.TTL` field is `time.Duration`.
//!
//! Determinism: there is at most one identity/password/sessions/mfa
//! block, and OAuth providers are sorted by provider then adapter before
//! emission so `oauth: Vec<_>` order cannot perturb generated bytes.

use lazuli_ir::{
    Auth, AuthMfa, AuthOAuthProvider, AuthPassword, AuthSessions, Feature, QualifiedName,
    TheftAction,
};

use super::cross_feature::CrossFeatureIndex;
use super::imports::ImportSet;
use super::module::EmitContext;
use super::patterns::{PATTERN_AUTH_LOGIN, PATTERN_AUTH_REFRESH, emit_pattern_header};
use super::printer::GoPrinter;

/// Emit `<feature>/auth.gen.go` for a feature, or `None` when the
/// feature declares no auth block.
pub fn emit_auth_file(
    source_label: &str,
    feature: &Feature,
    module_name: &str,
    cross_index: &CrossFeatureIndex<'_>,
    emit_ctx: &EmitContext<'_>,
) -> Option<String> {
    let auth = feature.auth.as_ref()?;

    // The signature mirrors the other per-kind emitters. Auth contracts
    // carry string references rather than typed field refs, so this
    // slice does not need cross-feature type resolution today.
    let _ = (module_name, cross_index);

    let mut p = GoPrinter::new();
    let mut imports = ImportSet::new();
    imports.add("lazuli.dev/runtime/lazuli/auth");
    if has_auth_routes(auth) {
        imports.add("context");
        imports.add("lazuli.dev/runtime/lazuli");
    }
    if auth.sessions.is_some() {
        imports.add("time");
    }

    p.banner(source_label, &super::casing::gen_package_name(&feature.name));
    imports.emit(&mut p);
    p.blank();

    emit_auth(&mut p, feature, auth, emit_ctx);

    Some(p.finish())
}

fn emit_auth(p: &mut GoPrinter, feature: &Feature, auth_block: &Auth, emit_ctx: &EmitContext<'_>) {
    // Auth contract vars are PascalCase so cross-package handlers in
    // `<feature>handlers` can reference them via `<feature>gen.AuthPassword`,
    // `<feature>gen.AuthSessions`, etc. (Go exports start with an uppercase
    // first letter.)
    let feature_pascal = pascal_case(&feature.name);
    let identity_var = format!("{feature_pascal}AuthIdentity");

    write_section_banner(
        p,
        &[
            format!("Auth: {}", feature.name),
            "  auth identity/password/sessions/mfa/oauth".to_owned(),
        ],
    );

    emit_pattern_header(p, PATTERN_AUTH_LOGIN);
    let line_directive_emitted = emit_ctx.emit_line_directive(p, auth_block.span_ref);
    emit_identity(p, &identity_var, auth_block);

    if let Some(password) = &auth_block.password {
        p.blank();
        emit_password(p, &feature_pascal, &identity_var, password);
    }

    if let Some(sessions) = &auth_block.sessions {
        p.blank();
        emit_sessions(p, &feature_pascal, sessions);
    }

    let mut oauth: Vec<&AuthOAuthProvider> = auth_block.oauth.iter().collect();
    oauth.sort_by(|a, b| {
        a.provider
            .cmp(&b.provider)
            .then_with(|| a.adapter.cmp(&b.adapter))
    });
    for provider in oauth {
        p.blank();
        emit_oauth(p, &feature_pascal, provider);
    }

    if let Some(mfa) = &auth_block.mfa {
        p.blank();
        emit_mfa(p, &feature_pascal, mfa);
    }

    let routes = auth_routes(auth_block);
    if !routes.is_empty() {
        p.blank();
        emit_auth_routes(p, feature, &routes, emit_ctx);
    }
    if auth_block.sessions.is_some() {
        p.blank();
        emit_session_resolver_register(
            p,
            feature,
            &feature_pascal,
            auth_block.sessions.as_ref().unwrap(),
        );
    }
    emit_ctx.reset_line_directive(p, line_directive_emitted);
}

/// Emit an `init()` block that registers the feature's
/// `auth.sessions` contract with the runtime session resolver.
/// Wires the production session middleware to this feature's table
/// so `Authorization: Bearer <token>` and the `lazuli_session`
/// cookie populate `Ctx.User` automatically.
fn emit_session_resolver_register(
    p: &mut GoPrinter,
    feature: &Feature,
    feature_pascal: &str,
    sessions: &AuthSessions,
) {
    write_section_banner(
        p,
        &[
            format!("Auth session resolver: {}", feature.name),
            "  wires the production session middleware to this feature".to_owned(),
        ],
    );
    let pattern = if sessions.is_rotation_enabled() {
        PATTERN_AUTH_REFRESH
    } else {
        PATTERN_AUTH_LOGIN
    };
    emit_pattern_header(p, pattern);
    p.line("func init() {");
    p.indent();
    p.line(&format!(
        "auth.RegisterSessionContract({feature_pascal}AuthSessions)"
    ));
    if sessions.is_rotation_enabled() {
        p.line(&format!(
            "auth.RegisterRefreshContract({feature_pascal}AuthSessions)"
        ));
    }
    p.dedent();
    p.line("}");
}

fn emit_identity(p: &mut GoPrinter, identity_var: &str, auth_block: &Auth) {
    let field = &auth_block.identity.field;
    p.line(&format!(
        "var {identity_var} = auth.FieldRef{{Resource: \"{}\", Field: \"{}\"}}",
        escape_string(&qualified_resource_name(&field.resource)),
        escape_string(&field.field),
    ));
}

fn emit_password(
    p: &mut GoPrinter,
    feature_pascal: &str,
    identity_var: &str,
    password: &AuthPassword,
) {
    p.line(&format!(
        "var {feature_pascal}AuthPassword = auth.PasswordContract{{"
    ));
    p.indent();
    let mut rows = vec![
        ("Identity:".to_owned(), format!("{identity_var},")),
        (
            "Algorithm:".to_owned(),
            format!("{},", password_algorithm_expr(&password.algorithm)),
        ),
        (
            "HashFn:".to_owned(),
            format!("\"{}\",", escape_string(&password.hash)),
        ),
        (
            "VerifyFn:".to_owned(),
            format!("\"{}\",", escape_string(&password.verify)),
        ),
    ];
    if let Some(rate_limit) = &password.rate_limit {
        // `ir-rate-limit-env-aware` cell 1 — codegen shim: read only the
        // default literal; Cell 2 owns the env-qualified emission.
        rows.push((
            "RateLimit:".to_owned(),
            format!("\"{}\",", escape_string(&rate_limit.default)),
        ));
    }
    write_aligned_kv_rows(p, &rows);
    p.dedent();
    p.line("}");
}

fn emit_sessions(p: &mut GoPrinter, feature_pascal: &str, sessions: &AuthSessions) {
    let (ttl_expr, ttl_todo) = duration_expr(&sessions.ttl);
    p.line(&format!(
        "var {feature_pascal}AuthSessions = auth.SessionsContract{{"
    ));
    p.indent();
    let mut rows = vec![
        (
            "Resource:".to_owned(),
            format!(
                "\"{}\",",
                escape_string(&qualified_resource_name(&sessions.resource))
            ),
        ),
        ("TTL:".to_owned(), format!("{ttl_expr},")),
    ];
    let mut todos = Vec::new();
    if let Some(todo) = ttl_todo {
        todos.push(todo);
    }
    if sessions.is_rotation_enabled() {
        let (access_ttl, access_ttl_todo) =
            duration_expr_for(sessions.resolved_access_ttl(), "AuthSessions.access_ttl");
        let (refresh_ttl, refresh_ttl_todo) = duration_expr_for(
            sessions
                .resolved_refresh_ttl()
                .expect("rotation-enabled sessions must resolve refresh_ttl"),
            "AuthSessions.rotation.refresh_ttl",
        );
        let (rotation_grace, rotation_grace_todo) = duration_expr_for(
            sessions
                .resolved_rotation_grace()
                .expect("rotation-enabled sessions must resolve rotation grace"),
            "AuthSessions.rotation.grace",
        );
        rows.push(("AccessTTL:".to_owned(), format!("{access_ttl},")));
        rows.push(("RefreshTTL:".to_owned(), format!("{refresh_ttl},")));
        rows.push(("Rotation:".to_owned(), "true,".to_owned()));
        rows.push(("RotationGrace:".to_owned(), format!("{rotation_grace},")));
        rows.push((
            "TheftDetectionAction:".to_owned(),
            format!(
                "{},",
                theft_action_expr(
                    sessions
                        .resolved_theft_action()
                        .expect("rotation-enabled sessions must resolve theft action"),
                )
            ),
        ));
        rows.push(("Refresh:".to_owned(), "true,".to_owned()));
        todos.extend(
            [access_ttl_todo, refresh_ttl_todo, rotation_grace_todo]
                .into_iter()
                .flatten(),
        );
    } else {
        rows.push(("Refresh:".to_owned(), format!("{},", sessions.refresh)));
    }
    write_aligned_kv_rows(p, &rows);
    for todo in todos {
        p.line(&todo);
    }
    p.dedent();
    p.line("}");
}

fn emit_oauth(p: &mut GoPrinter, feature_pascal: &str, oauth: &AuthOAuthProvider) {
    p.line(&format!(
        "var {feature_pascal}AuthOAuth{} = auth.OAuthContract{{",
        pascal_case(&oauth.provider)
    ));
    p.indent();
    write_aligned_kv_rows(
        p,
        &[
            (
                "Provider:".to_owned(),
                format!("\"{}\",", escape_string(&oauth.provider)),
            ),
            (
                "AdapterRef:".to_owned(),
                format!("\"{}\",", escape_string(&oauth.adapter)),
            ),
        ],
    );
    p.dedent();
    p.line("}");
}

fn emit_mfa(p: &mut GoPrinter, feature_pascal: &str, mfa: &AuthMfa) {
    p.line(&format!("var {feature_pascal}AuthMfa = auth.MfaContract{{"));
    p.indent();
    let mut rows = vec![
        (
            "Method:".to_owned(),
            format!("{},", mfa_method_expr(&mfa.method)),
        ),
        (
            "EnrollFn:".to_owned(),
            format!("\"{}\",", escape_string(&mfa.enroll)),
        ),
        (
            "VerifyFn:".to_owned(),
            format!("\"{}\",", escape_string(&mfa.verify)),
        ),
    ];
    if let Some(adapter) = &mfa.adapter {
        rows.push((
            "AdapterRef:".to_owned(),
            format!("\"{}\",", escape_string(adapter)),
        ));
    }
    write_aligned_kv_rows(p, &rows);
    p.dedent();
    p.line("}");
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct AuthRoute {
    name_suffix: String,
    method: &'static str,
    path: String,
    handler: &'static str,
    verify_handler_name: bool,
}

fn has_auth_routes(auth_block: &Auth) -> bool {
    auth_block.password.is_some() || auth_block.sessions.is_some() || !auth_block.oauth.is_empty()
}

fn auth_routes(auth_block: &Auth) -> Vec<AuthRoute> {
    let mut routes = Vec::new();

    if auth_block.password.is_some() {
        routes.push(AuthRoute {
            name_suffix: "login".to_owned(),
            method: "lazuli.MethodPost",
            path: "/auth/login".to_owned(),
            handler: "auth.LoginHandler",
            verify_handler_name: false,
        });
        routes.push(AuthRoute {
            name_suffix: "signup".to_owned(),
            method: "lazuli.MethodPost",
            path: "/auth/signup".to_owned(),
            handler: "auth.SignupHandler",
            verify_handler_name: false,
        });
    }

    if auth_block.password.is_some() || auth_block.sessions.is_some() {
        routes.push(AuthRoute {
            name_suffix: "logout".to_owned(),
            method: "lazuli.MethodPost",
            path: "/auth/logout".to_owned(),
            handler: "auth.LogoutHandler",
            verify_handler_name: false,
        });
    }

    let mut oauth: Vec<&AuthOAuthProvider> = auth_block.oauth.iter().collect();
    oauth.sort_by(|a, b| {
        a.provider
            .cmp(&b.provider)
            .then_with(|| a.adapter.cmp(&b.adapter))
    });
    for provider in oauth {
        let provider_path = escape_route_segment(&provider.provider);
        routes.push(AuthRoute {
            name_suffix: format!("oauth.{}", provider.provider),
            method: "lazuli.MethodGet",
            path: format!("/auth/oauth/{provider_path}"),
            handler: "auth.OAuthHandler",
            verify_handler_name: true,
        });
        routes.push(AuthRoute {
            name_suffix: format!("oauth.{}.callback", provider.provider),
            method: "lazuli.MethodGet",
            path: format!("/auth/oauth/{provider_path}/callback"),
            handler: "auth.OAuthCallbackHandler",
            verify_handler_name: true,
        });
    }

    routes
}

fn emit_auth_routes(
    p: &mut GoPrinter,
    feature: &Feature,
    routes: &[AuthRoute],
    emit_ctx: &EmitContext<'_>,
) {
    write_section_banner(
        p,
        &[
            format!("Auth HTTP routes: {}", feature.name),
            "  canonical auth auto-mounts".to_owned(),
        ],
    );
    emit_pattern_header(p, PATTERN_AUTH_LOGIN);
    p.line("func init() {");
    p.indent();
    for route in routes {
        if route.verify_handler_name {
            p.line("// TODO(runtime): handler name verification");
        }
        p.line("lazuli.RegisterApi(&lazuli.Api[any, any]{");
        p.indent();
        write_aligned_kv_rows(
            p,
            &[
                (
                    "Name:".to_owned(),
                    format!(
                        "\"{}.auth.{}\",",
                        escape_string(&feature.name),
                        escape_string(&route.name_suffix)
                    ),
                ),
                (
                    "Feature:".to_owned(),
                    format!("\"{}\",", escape_string(&feature.name)),
                ),
                ("Method:".to_owned(), format!("{},", route.method)),
                (
                    "Path:".to_owned(),
                    format!("\"{}\",", escape_string(&route.path)),
                ),
                ("Handler:".to_owned(), format!("{},", route.handler)),
            ],
        );
        emit_ctx.emit_with_source_field(p, "auth", &route.name_suffix, None);
        p.dedent();
        p.line("})");
    }
    p.dedent();
    p.line("}");
}

fn write_aligned_kv_rows(p: &mut GoPrinter, rows: &[(String, String)]) {
    let key_width = rows.iter().map(|(key, _)| key.len()).max().unwrap_or(0);
    for (key, value) in rows {
        let pad = key_width.saturating_sub(key.len());
        p.line(&format!("{}{} {}", key, " ".repeat(pad), value));
    }
}

fn write_section_banner(p: &mut GoPrinter, lines: &[String]) {
    let rule = "-".repeat(76);
    p.line(&format!("// {rule}"));
    for line in lines {
        p.line(&format!("// {line}"));
    }
    p.line(&format!("// {rule}"));
    p.blank();
}

fn qualified_resource_name(qname: &QualifiedName) -> String {
    qname.name.clone()
}

fn password_algorithm_expr(raw: &str) -> String {
    match raw.trim().to_ascii_lowercase().as_str() {
        "" | "argon2id" => "auth.AlgoArgon2id".to_owned(),
        "bcrypt" => "auth.AlgoBcrypt".to_owned(),
        other => format!("auth.PasswordAlgorithm(\"{}\")", escape_string(other)),
    }
}

fn mfa_method_expr(raw: &str) -> String {
    match raw.trim().to_ascii_lowercase().as_str() {
        "" | "totp" => "auth.MfaMethodTOTP".to_owned(),
        other => format!("auth.MfaMethod(\"{}\")", escape_string(other)),
    }
}

fn duration_expr(raw: &str) -> (String, Option<String>) {
    duration_expr_for(raw, "AuthSessions.ttl")
}

fn duration_expr_for(raw: &str, label: &str) -> (String, Option<String>) {
    match parse_duration_literal(raw) {
        Some(expr) => (expr, None),
        None => (
            "0 * time.Second".to_owned(),
            Some(format!(
                "// TODO(auth-ttl): unsupported {label} literal \"{}\"; emit a time.Duration expression.",
                escape_string(raw),
            )),
        ),
    }
}

fn theft_action_expr(action: TheftAction) -> &'static str {
    match action {
        TheftAction::RevokeSessionFamily => "auth.TheftRevokeSessionFamily",
        TheftAction::RevokeUser => "auth.TheftRevokeUser",
    }
}

fn parse_duration_literal(raw: &str) -> Option<String> {
    let trimmed = raw.trim();
    if trimmed.is_empty() {
        return None;
    }

    let compact = trimmed.replace(' ', "");
    if let Some(parsed) = parse_number_unit(&compact) {
        return Some(parsed);
    }

    let mut parts = trimmed.split_whitespace();
    let n = parts.next()?;
    let unit = parts.next()?;
    if parts.next().is_some() {
        return None;
    }
    format_duration_unit(n, unit)
}

fn parse_number_unit(compact: &str) -> Option<String> {
    let split_at = compact
        .char_indices()
        .find_map(|(idx, ch)| (!ch.is_ascii_digit()).then_some(idx))?;
    let (n, unit) = compact.split_at(split_at);
    format_duration_unit(n, unit)
}

fn format_duration_unit(n: &str, unit: &str) -> Option<String> {
    if n.is_empty() || !n.chars().all(|ch| ch.is_ascii_digit()) {
        return None;
    }
    let value: u64 = n.parse().ok()?;
    if value == 0 {
        return Some("0".to_owned());
    }
    let unit = unit.trim().to_ascii_lowercase();
    match unit.as_str() {
        "ms" | "millisecond" | "milliseconds" => Some(scale_duration(value, "time.Millisecond")),
        "s" | "sec" | "secs" | "second" | "seconds" => Some(scale_duration(value, "time.Second")),
        "m" | "min" | "mins" | "minute" | "minutes" => Some(scale_duration(value, "time.Minute")),
        "h" | "hr" | "hrs" | "hour" | "hours" => Some(scale_duration(value, "time.Hour")),
        "d" | "day" | "days" => Some(format!("{value} * 24 * time.Hour")),
        "w" | "week" | "weeks" => Some(format!("{value} * 7 * 24 * time.Hour")),
        _ => None,
    }
}

fn scale_duration(value: u64, unit: &str) -> String {
    if value == 1 {
        unit.to_owned()
    } else {
        format!("{value} * {unit}")
    }
}

fn escape_route_segment(raw: &str) -> String {
    raw.split('/')
        .filter(|part| !part.is_empty())
        .collect::<Vec<_>>()
        .join("-")
}

fn pascal_case(s: &str) -> String {
    super::casing::pascal_case(s)
}

fn escape_string(raw: &str) -> String {
    let mut out = String::with_capacity(raw.len());
    for ch in raw.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            _ => out.push(ch),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use lazuli_ir::{
        AppManifest, AuthIdentity, Defaults, FieldRef, Module, Policies, RateLimitSpec,
    };

    fn emit(feature: &Feature) -> Option<String> {
        let module = Module {
            workspace: None,
            contracts: Vec::new(),
            app: Some(minimal_app()),
            registry: None,
            profiles: Vec::new(),
            design: None,
            rbac: None,
            features: vec![feature.clone()],
        };
        let index = CrossFeatureIndex::build(&module);
        let emit_ctx = EmitContext::no_source("customer/auth.gen.go");
        emit_auth_file("examples/x.lzi", feature, "lazuli/test", &index, &emit_ctx)
    }

    fn minimal_app() -> AppManifest {
        AppManifest {
            name: "test".to_owned(),
            title: None,
            version: None,
            lazuli_version: None,
            targets: Vec::new(),
            default_locale: None,
            default_timezone: None,
            auth_failed_redirect: None,
            not_found: None,
            error_pages: Vec::new(),
            uses: Vec::new(),
            packs: Vec::new(),
            bindings: Vec::new(),
            architecture: None,
            services: Vec::new(),
            communication: None,
            environments: Vec::new(),
            urls: Vec::new(),
            cors: None,
            headers: None,
            cookie: None,
            proxy: None,
            limits: None,
            env: Vec::new(),
            integrations: Vec::new(),
            capabilities: Vec::new(),
            runtime: Vec::new(),
            deploy: None,
            logging: None,
            tracing: None,
            observability: None,
            locale: None,
            encryption_bindings: Vec::new(),
            route_guard: None,
            actor_query: None,
            span_ref: None,
        }
    }

    fn base_feature(name: &str) -> Feature {
        Feature {
            name: name.to_owned(),
            purpose: None,
            non_goals: Vec::new(),
            context_path: None,
            defaults: Defaults {
                tenancy: None,
                timestamps: false,
                policy: None,
            },
            uses: Vec::new(),
            uses_spans: Vec::new(),
            uses_versions: Vec::new(),
            requirements: Vec::new(),
            enums: Vec::new(),
            resources: Vec::new(),
            events: Vec::new(),
            rules: Vec::new(),
            policies: Policies {
                categories: Vec::new(),
                fields: Vec::new(),
                span_ref: None,
            },
            errors: None,
            commands: Vec::new(),
            apis: Vec::new(),
            records: Vec::new(),
            queries: Vec::new(),
            resume_routers: Vec::new(),
            workflows: Vec::new(),
            jobs: Vec::new(),
            webhooks: Vec::new(),
            notifications: Vec::new(),
            event_groups: Vec::new(),
            tenant_migrations: Vec::new(),
            translation: None,
            pollers: vec![],
            auth: None,
            surfaces: Vec::new(),
            extensions: Vec::new(),
            escape_routes: Vec::new(),
            agents: Vec::new(),
            reports: Vec::new(),
            channels: Vec::new(),
            caches: Vec::new(),
            aggregates: vec![],
            mcp_servers: vec![],
            previous_names: Vec::new(),
            span_ref: None,
            synth_origins: std::collections::BTreeMap::new(),
        }
    }

    fn qname(name: &str) -> QualifiedName {
        QualifiedName {
            feature: None,
            name: name.to_owned(),
        }
    }

    fn identity(resource: &str, field: &str) -> AuthIdentity {
        AuthIdentity {
            field: FieldRef {
                resource: qname(resource),
                field: field.to_owned(),
            },
            public_contract: None,
        }
    }

    fn auth_with_identity(resource: &str, field: &str) -> Auth {
        Auth {
            identity: identity(resource, field),
            password: None,
            sessions: None,
            mfa: None,
            oauth: Vec::new(),
            span_ref: None,
        }
    }

    #[test]
    fn feature_without_auth_returns_none() {
        let feature = base_feature("customer");
        assert!(emit(&feature).is_none());
    }

    #[test]
    fn full_auth_block_emits_runtime_contracts() {
        let mut feature = base_feature("customer_auth");
        let mut auth = auth_with_identity("Customer", "email");
        auth.password = Some(AuthPassword {
            algorithm: "argon2id".to_owned(),
            hash: "@fn.hash_customer_password".to_owned(),
            verify: "@fn.verify_customer_password".to_owned(),
            rate_limit: Some(RateLimitSpec::from_default("5 per 10 minutes".to_owned())),
        });
        auth.sessions = Some(AuthSessions {
            resource: qname("CustomerSession"),
            ttl: "7 days".to_owned(),
            refresh: false,
            extra_columns: vec![],
            access_ttl: None,
            rotation: None,
        });
        auth.mfa = Some(AuthMfa {
            method: "totp".to_owned(),
            enroll: "@fn.enroll_customer_totp".to_owned(),
            verify: "@validator.verify_customer_totp".to_owned(),
            adapter: None,
        });
        auth.oauth.push(AuthOAuthProvider {
            provider: "google".to_owned(),
            adapter: "@adapter.google_oauth".to_owned(),
        });
        feature.auth = Some(auth);

        let out = emit(&feature).expect("must emit");
        assert!(out.contains("package customer_authgen"));
        assert!(out.contains("\"time\""));
        assert!(out.contains("\"lazuli.dev/runtime/lazuli\""));
        assert!(out.contains("\"lazuli.dev/runtime/lazuli/auth\""));
        assert!(out.contains(
            "var CustomerAuthAuthIdentity = auth.FieldRef{Resource: \"Customer\", Field: \"email\"}"
        ));
        assert!(out.contains("var CustomerAuthAuthPassword = auth.PasswordContract{"));
        assert!(out.contains("Identity:  CustomerAuthAuthIdentity,"));
        assert!(out.contains("Algorithm: auth.AlgoArgon2id,"));
        assert!(out.contains("HashFn:    \"@fn.hash_customer_password\","));
        assert!(out.contains("RateLimit: \"5 per 10 minutes\","));
        assert!(out.contains("var CustomerAuthAuthSessions = auth.SessionsContract{"));
        assert!(out.contains("TTL:      7 * 24 * time.Hour,"));
        assert!(out.contains("Refresh:  false,"));
        assert!(out.contains("var CustomerAuthAuthOAuthGoogle = auth.OAuthContract{"));
        assert!(out.contains("AdapterRef: \"@adapter.google_oauth\","));
        assert!(out.contains("var CustomerAuthAuthMfa = auth.MfaContract{"));
        assert!(out.contains("Method:   auth.MfaMethodTOTP,"));
        assert!(out.contains("func init() {"));
        assert!(out.contains("Name:    \"customer_auth.auth.login\","));
        assert!(out.contains("Method:  lazuli.MethodPost,"));
        assert!(out.contains("Path:    \"/auth/login\","));
        assert!(out.contains("Handler: auth.LoginHandler,"));
        assert!(out.contains("Path:    \"/auth/signup\","));
        assert!(out.contains("Handler: auth.SignupHandler,"));
        assert!(out.contains("Path:    \"/auth/logout\","));
        assert!(out.contains("Handler: auth.LogoutHandler,"));
        assert!(out.contains("Name:    \"customer_auth.auth.oauth.google\","));
        assert!(out.contains("Method:  lazuli.MethodGet,"));
        assert!(out.contains("Path:    \"/auth/oauth/google\","));
        assert!(out.contains("Handler: auth.OAuthHandler,"));
        assert!(out.contains("Path:    \"/auth/oauth/google/callback\","));
        assert!(out.contains("Handler: auth.OAuthCallbackHandler,"));
        assert!(out.contains("// TODO(runtime): handler name verification"));
        // Session resolver wire — production middleware lookup.
        assert!(out.contains("// Auth session resolver: customer_auth"));
        assert!(out.contains("auth.RegisterSessionContract(CustomerAuthAuthSessions)"));
    }

    #[test]
    fn identity_only_auth_skips_optional_contracts() {
        let mut feature = base_feature("portal");
        feature.auth = Some(auth_with_identity("User", "email"));
        let out = emit(&feature).expect("must emit");
        assert!(out.contains("var PortalAuthIdentity = auth.FieldRef"));
        assert!(!out.contains("PasswordContract"));
        assert!(!out.contains("SessionsContract"));
        assert!(!out.contains("MfaContract"));
        assert!(!out.contains("OAuthContract"));
        assert!(!out.contains("RegisterApi"));
        assert!(!out.contains("RegisterSessionContract"));
        assert!(!out.contains("\"lazuli.dev/runtime/lazuli\""));
        assert!(!out.contains("\"time\""));
    }

    #[test]
    fn oauth_providers_are_sorted_for_determinism() {
        let mut feature = base_feature("customer");
        let mut auth = auth_with_identity("Customer", "email");
        auth.oauth.push(AuthOAuthProvider {
            provider: "microsoft".to_owned(),
            adapter: "@adapter.microsoft_oauth".to_owned(),
        });
        auth.oauth.push(AuthOAuthProvider {
            provider: "google".to_owned(),
            adapter: "@adapter.google_oauth".to_owned(),
        });
        feature.auth = Some(auth);

        let a = emit(&feature).expect("must emit");
        let b = emit(&feature).expect("must emit");
        assert_eq!(a, b);
        let google_pos = a.find("AuthOAuthGoogle").expect("google contract");
        let microsoft_pos = a.find("AuthOAuthMicrosoft").expect("microsoft contract");
        assert!(google_pos < microsoft_pos);
        let google_route_pos = a
            .find("Name:    \"customer.auth.oauth.google\",")
            .expect("google route");
        let microsoft_route_pos = a
            .find("Name:    \"customer.auth.oauth.microsoft\",")
            .expect("microsoft route");
        assert!(google_route_pos < microsoft_route_pos);
        assert!(a.contains("Path:    \"/auth/oauth/google\","));
        assert!(a.contains("Path:    \"/auth/oauth/google/callback\","));
        assert!(a.contains("Path:    \"/auth/oauth/microsoft\","));
        assert!(a.contains("Path:    \"/auth/oauth/microsoft/callback\","));
    }

    #[test]
    fn sessions_only_auth_mounts_logout_route() {
        let mut feature = base_feature("portal");
        let mut auth = auth_with_identity("User", "email");
        auth.sessions = Some(AuthSessions {
            resource: qname("UserSession"),
            ttl: "1 hour".to_owned(),
            refresh: true,
            extra_columns: vec![],
            access_ttl: None,
            rotation: None,
        });
        feature.auth = Some(auth);

        let out = emit(&feature).expect("must emit");
        assert!(out.contains("Name:    \"portal.auth.logout\","));
        assert!(out.contains("Path:    \"/auth/logout\","));
        assert!(out.contains("Handler: auth.LogoutHandler,"));
        assert!(!out.contains("portal.auth.login"));
        assert!(!out.contains("portal.auth.signup"));
        // Session contract wired to the runtime resolver.
        assert!(out.contains("auth.RegisterSessionContract(PortalAuthSessions)"));
    }

    #[test]
    fn non_catalog_values_still_emit_go_valid_conversions() {
        let mut feature = base_feature("customer");
        let mut auth = auth_with_identity("Customer", "email");
        auth.password = Some(AuthPassword {
            algorithm: "scrypt".to_owned(),
            hash: "@fn.hash".to_owned(),
            verify: "@fn.verify".to_owned(),
            rate_limit: None,
        });
        auth.mfa = Some(AuthMfa {
            method: "sms".to_owned(),
            enroll: "@fn.enroll_sms".to_owned(),
            verify: "@fn.verify_sms".to_owned(),
            adapter: Some("@adapter.sms".to_owned()),
        });
        auth.sessions = Some(AuthSessions {
            resource: qname("CustomerSession"),
            ttl: "soon".to_owned(),
            refresh: true,
            extra_columns: vec![],
            access_ttl: None,
            rotation: None,
        });
        feature.auth = Some(auth);

        let out = emit(&feature).expect("must emit");
        assert!(out.contains("Algorithm: auth.PasswordAlgorithm(\"scrypt\"),"));
        assert!(out.contains("Method:     auth.MfaMethod(\"sms\"),"));
        assert!(out.contains("AdapterRef: \"@adapter.sms\","));
        assert!(out.contains("TTL:      0 * time.Second,"));
        assert!(out.contains("// TODO(auth-ttl): unsupported AuthSessions.ttl literal \"soon\""));
    }
}
