//! Cell G1 - `Auth` kind emission. Walks the single auth block declared
//! on a feature and emits the lowered Lazuli Go auth contracts into
//! `<feature>/auth.gen.go`.
//!
//! Proposal references:
//! - Section 3.5 - Auth declaration shape.
//! - Section 11 - runtime boundary discipline. The only runtime package
//!   referenced here is `lazuli.dev/runtime/lazuli/auth`; session TTLs
//!   additionally use stdlib `time` because the current Lazuli Go
//!   `SessionsContract.TTL` field is `time.Duration`.
//!
//! Determinism: there is at most one identity/password/sessions/mfa
//! block, and OAuth providers are sorted by provider then adapter before
//! emission so `oauth: Vec<_>` order cannot perturb generated bytes.

use lazuli_ir::{
    Auth, AuthMfa, AuthOAuthProvider, AuthPassword, AuthSessions, Feature, QualifiedName,
};

use super::cross_feature::CrossFeatureIndex;
use super::imports::ImportSet;
use super::printer::GoPrinter;

/// Emit `<feature>/auth.gen.go` for a feature, or `None` when the
/// feature declares no auth block.
pub fn emit_auth_file(
    source_label: &str,
    feature: &Feature,
    module_name: &str,
    cross_index: &CrossFeatureIndex<'_>,
) -> Option<String> {
    let auth = feature.auth.as_ref()?;

    // The signature mirrors the other per-kind emitters. Auth contracts
    // carry string references rather than typed field refs, so this
    // slice does not need cross-feature type resolution today.
    let _ = (module_name, cross_index);

    let mut p = GoPrinter::new();
    let mut imports = ImportSet::new();
    imports.add("lazuli.dev/runtime/lazuli/auth");
    if auth.sessions.is_some() {
        imports.add("time");
    }

    p.banner(source_label, &feature.name);
    imports.emit(&mut p);
    p.blank();

    emit_auth(&mut p, feature, auth);

    Some(p.finish())
}

fn emit_auth(p: &mut GoPrinter, feature: &Feature, auth_block: &Auth) {
    let feature_camel = lower_camel(&feature.name);
    let identity_var = format!("{feature_camel}AuthIdentity");

    write_section_banner(
        p,
        &[
            format!("Auth: {}", feature.name),
            "  auth identity/password/sessions/mfa/oauth".to_owned(),
        ],
    );

    emit_identity(p, &identity_var, auth_block);

    if let Some(password) = &auth_block.password {
        p.blank();
        emit_password(p, &feature_camel, &identity_var, password);
    }

    if let Some(sessions) = &auth_block.sessions {
        p.blank();
        emit_sessions(p, &feature_camel, sessions);
    }

    let mut oauth: Vec<&AuthOAuthProvider> = auth_block.oauth.iter().collect();
    oauth.sort_by(|a, b| {
        a.provider
            .cmp(&b.provider)
            .then_with(|| a.adapter.cmp(&b.adapter))
    });
    for provider in oauth {
        p.blank();
        emit_oauth(p, &feature_camel, provider);
    }

    if let Some(mfa) = &auth_block.mfa {
        p.blank();
        emit_mfa(p, &feature_camel, mfa);
    }
}

fn emit_identity(p: &mut GoPrinter, identity_var: &str, auth_block: &Auth) {
    let field = &auth_block.identity.field;
    p.line(&format!(
        "var {identity_var} = auth.FieldRef{{Resource: \"{}\", Field: \"{}\"}}",
        escape_string(&qualified_resource_name(&field.resource)),
        escape_string(&field.field),
    ));
}

fn emit_password(
    p: &mut GoPrinter,
    feature_camel: &str,
    identity_var: &str,
    password: &AuthPassword,
) {
    p.line(&format!(
        "var {feature_camel}AuthPassword = auth.PasswordContract{{"
    ));
    p.indent();
    let mut rows = vec![
        ("Identity:".to_owned(), format!("{identity_var},")),
        (
            "Algorithm:".to_owned(),
            format!("{},", password_algorithm_expr(&password.algorithm)),
        ),
        (
            "HashFn:".to_owned(),
            format!("\"{}\",", escape_string(&password.hash)),
        ),
        (
            "VerifyFn:".to_owned(),
            format!("\"{}\",", escape_string(&password.verify)),
        ),
    ];
    if let Some(rate_limit) = &password.rate_limit {
        rows.push((
            "RateLimit:".to_owned(),
            format!("\"{}\",", escape_string(rate_limit)),
        ));
    }
    write_aligned_kv_rows(p, &rows);
    p.dedent();
    p.line("}");
}

fn emit_sessions(p: &mut GoPrinter, feature_camel: &str, sessions: &AuthSessions) {
    let (ttl_expr, ttl_todo) = duration_expr(&sessions.ttl);
    p.line(&format!(
        "var {feature_camel}AuthSessions = auth.SessionsContract{{"
    ));
    p.indent();
    let rows = vec![
        (
            "Resource:".to_owned(),
            format!(
                "\"{}\",",
                escape_string(&qualified_resource_name(&sessions.resource))
            ),
        ),
        ("TTL:".to_owned(), format!("{ttl_expr},")),
        ("Refresh:".to_owned(), format!("{},", sessions.refresh)),
    ];
    write_aligned_kv_rows(p, &rows);
    if let Some(todo) = ttl_todo {
        p.line(&todo);
    }
    p.dedent();
    p.line("}");
}

fn emit_oauth(p: &mut GoPrinter, feature_camel: &str, oauth: &AuthOAuthProvider) {
    p.line(&format!(
        "var {feature_camel}AuthOAuth{} = auth.OAuthContract{{",
        pascal_case(&oauth.provider)
    ));
    p.indent();
    write_aligned_kv_rows(
        p,
        &[
            (
                "Provider:".to_owned(),
                format!("\"{}\",", escape_string(&oauth.provider)),
            ),
            (
                "AdapterRef:".to_owned(),
                format!("\"{}\",", escape_string(&oauth.adapter)),
            ),
        ],
    );
    p.dedent();
    p.line("}");
}

fn emit_mfa(p: &mut GoPrinter, feature_camel: &str, mfa: &AuthMfa) {
    p.line(&format!("var {feature_camel}AuthMfa = auth.MfaContract{{"));
    p.indent();
    let mut rows = vec![
        (
            "Method:".to_owned(),
            format!("{},", mfa_method_expr(&mfa.method)),
        ),
        (
            "EnrollFn:".to_owned(),
            format!("\"{}\",", escape_string(&mfa.enroll)),
        ),
        (
            "VerifyFn:".to_owned(),
            format!("\"{}\",", escape_string(&mfa.verify)),
        ),
    ];
    if let Some(adapter) = &mfa.adapter {
        rows.push((
            "AdapterRef:".to_owned(),
            format!("\"{}\",", escape_string(adapter)),
        ));
    }
    write_aligned_kv_rows(p, &rows);
    p.dedent();
    p.line("}");
}

fn write_aligned_kv_rows(p: &mut GoPrinter, rows: &[(String, String)]) {
    let key_width = rows.iter().map(|(key, _)| key.len()).max().unwrap_or(0);
    for (key, value) in rows {
        let pad = key_width.saturating_sub(key.len());
        p.line(&format!("{}{} {}", key, " ".repeat(pad), value));
    }
}

fn write_section_banner(p: &mut GoPrinter, lines: &[String]) {
    let rule = "-".repeat(76);
    p.line(&format!("// {rule}"));
    for line in lines {
        p.line(&format!("// {line}"));
    }
    p.line(&format!("// {rule}"));
    p.blank();
}

fn qualified_resource_name(qname: &QualifiedName) -> String {
    qname.name.clone()
}

fn password_algorithm_expr(raw: &str) -> String {
    match raw.trim().to_ascii_lowercase().as_str() {
        "" | "argon2id" => "auth.AlgoArgon2id".to_owned(),
        "bcrypt" => "auth.AlgoBcrypt".to_owned(),
        other => format!("auth.PasswordAlgorithm(\"{}\")", escape_string(other)),
    }
}

fn mfa_method_expr(raw: &str) -> String {
    match raw.trim().to_ascii_lowercase().as_str() {
        "" | "totp" => "auth.MfaMethodTOTP".to_owned(),
        other => format!("auth.MfaMethod(\"{}\")", escape_string(other)),
    }
}

fn duration_expr(raw: &str) -> (String, Option<String>) {
    match parse_duration_literal(raw) {
        Some(expr) => (expr, None),
        None => (
            "0 * time.Second".to_owned(),
            Some(format!(
                "// TODO(auth-ttl): unsupported AuthSessions.ttl literal \"{}\"; emit a time.Duration expression.",
                escape_string(raw)
            )),
        ),
    }
}

fn parse_duration_literal(raw: &str) -> Option<String> {
    let trimmed = raw.trim();
    if trimmed.is_empty() {
        return None;
    }

    let compact = trimmed.replace(' ', "");
    if let Some(parsed) = parse_number_unit(&compact) {
        return Some(parsed);
    }

    let mut parts = trimmed.split_whitespace();
    let n = parts.next()?;
    let unit = parts.next()?;
    if parts.next().is_some() {
        return None;
    }
    format_duration_unit(n, unit)
}

fn parse_number_unit(compact: &str) -> Option<String> {
    let split_at = compact
        .char_indices()
        .find_map(|(idx, ch)| (!ch.is_ascii_digit()).then_some(idx))?;
    let (n, unit) = compact.split_at(split_at);
    format_duration_unit(n, unit)
}

fn format_duration_unit(n: &str, unit: &str) -> Option<String> {
    if n.is_empty() || !n.chars().all(|ch| ch.is_ascii_digit()) {
        return None;
    }
    let value: u64 = n.parse().ok()?;
    if value == 0 {
        return Some("0".to_owned());
    }
    let unit = unit.trim().to_ascii_lowercase();
    match unit.as_str() {
        "ms" | "millisecond" | "milliseconds" => Some(scale_duration(value, "time.Millisecond")),
        "s" | "sec" | "secs" | "second" | "seconds" => Some(scale_duration(value, "time.Second")),
        "m" | "min" | "mins" | "minute" | "minutes" => Some(scale_duration(value, "time.Minute")),
        "h" | "hr" | "hrs" | "hour" | "hours" => Some(scale_duration(value, "time.Hour")),
        "d" | "day" | "days" => Some(format!("{value} * 24 * time.Hour")),
        "w" | "week" | "weeks" => Some(format!("{value} * 7 * 24 * time.Hour")),
        _ => None,
    }
}

fn scale_duration(value: u64, unit: &str) -> String {
    if value == 1 {
        unit.to_owned()
    } else {
        format!("{value} * {unit}")
    }
}

fn pascal_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for word in s.split(|c: char| c == '_' || c == '-') {
        if word.is_empty() {
            continue;
        }
        if is_acronym(word) {
            out.push_str(&word.to_ascii_uppercase());
            continue;
        }
        let mut chars = word.chars();
        if let Some(first) = chars.next() {
            for u in first.to_uppercase() {
                out.push(u);
            }
        }
        out.push_str(chars.as_str());
    }
    out
}

fn lower_camel(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut first = true;
    for word in s.split(|c: char| c == '_' || c == '-') {
        if word.is_empty() {
            continue;
        }
        if first {
            out.push_str(&word.to_ascii_lowercase());
            first = false;
            continue;
        }
        if is_acronym(word) {
            out.push_str(&word.to_ascii_uppercase());
            continue;
        }
        let mut chars = word.chars();
        if let Some(c) = chars.next() {
            for u in c.to_uppercase() {
                out.push(u);
            }
        }
        out.push_str(chars.as_str());
    }
    out
}

fn is_acronym(word: &str) -> bool {
    matches!(
        word.to_ascii_lowercase().as_str(),
        "id" | "url" | "uri" | "api" | "html" | "json" | "sql" | "ttl" | "uuid" | "mfa"
    )
}

fn escape_string(raw: &str) -> String {
    let mut out = String::with_capacity(raw.len());
    for ch in raw.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            _ => out.push(ch),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use lazuli_ir::{AppManifest, AuthIdentity, Defaults, FieldRef, Module, Policies};

    fn emit(feature: &Feature) -> Option<String> {
        let module = Module {
            workspace: None,
            contracts: Vec::new(),
            app: Some(minimal_app()),
            registry: None,
            profiles: Vec::new(),
            features: vec![feature.clone()],
        };
        let index = CrossFeatureIndex::build(&module);
        emit_auth_file("examples/x.lzi", feature, "lazuli/test", &index)
    }

    fn minimal_app() -> AppManifest {
        AppManifest {
            name: "test".to_owned(),
            title: None,
            version: None,
            targets: Vec::new(),
            default_locale: None,
            default_timezone: None,
            auth_failed_redirect: None,
            not_found: None,
            uses: Vec::new(),
            packs: Vec::new(),
            bindings: Vec::new(),
            architecture: None,
            services: Vec::new(),
            communication: None,
            environments: Vec::new(),
            urls: Vec::new(),
            cors: None,
            env: Vec::new(),
            integrations: Vec::new(),
            capabilities: Vec::new(),
            runtime: Vec::new(),
            deploy: None,
            logging: None,
            tracing: None,
            locale: None,
            span_ref: None,
        }
    }

    fn base_feature(name: &str) -> Feature {
        Feature {
            name: name.to_owned(),
            purpose: None,
            non_goals: Vec::new(),
            context_path: None,
            defaults: Defaults {
                tenancy: None,
                timestamps: false,
                policy: None,
            },
            uses: Vec::new(),
            requirements: Vec::new(),
            enums: Vec::new(),
            resources: Vec::new(),
            events: Vec::new(),
            rules: Vec::new(),
            policies: Policies {
                categories: Vec::new(),
                fields: Vec::new(),
                span_ref: None,
            },
            commands: Vec::new(),
            apis: Vec::new(),
            records: Vec::new(),
            queries: Vec::new(),
            workflows: Vec::new(),
            jobs: Vec::new(),
            webhooks: Vec::new(),
            notifications: Vec::new(),
            event_groups: Vec::new(),
            tenant_migrations: Vec::new(),
            translation: None,
            auth: None,
            surfaces: Vec::new(),
            extensions: Vec::new(),
            escape_routes: Vec::new(),
            agents: Vec::new(),
            previous_names: Vec::new(),
            span_ref: None,
        }
    }

    fn qname(name: &str) -> QualifiedName {
        QualifiedName {
            feature: None,
            name: name.to_owned(),
        }
    }

    fn identity(resource: &str, field: &str) -> AuthIdentity {
        AuthIdentity {
            field: FieldRef {
                resource: qname(resource),
                field: field.to_owned(),
            },
        }
    }

    fn auth_with_identity(resource: &str, field: &str) -> Auth {
        Auth {
            identity: identity(resource, field),
            password: None,
            sessions: None,
            mfa: None,
            oauth: Vec::new(),
            span_ref: None,
        }
    }

    #[test]
    fn feature_without_auth_returns_none() {
        let feature = base_feature("customer");
        assert!(emit(&feature).is_none());
    }

    #[test]
    fn full_auth_block_emits_runtime_contracts() {
        let mut feature = base_feature("customer_auth");
        let mut auth = auth_with_identity("Customer", "email");
        auth.password = Some(AuthPassword {
            algorithm: "argon2id".to_owned(),
            hash: "@fn.hash_customer_password".to_owned(),
            verify: "@fn.verify_customer_password".to_owned(),
            rate_limit: Some("5 per 10 minutes".to_owned()),
        });
        auth.sessions = Some(AuthSessions {
            resource: qname("CustomerSession"),
            ttl: "7 days".to_owned(),
            refresh: false,
        });
        auth.mfa = Some(AuthMfa {
            method: "totp".to_owned(),
            enroll: "@fn.enroll_customer_totp".to_owned(),
            verify: "@validator.verify_customer_totp".to_owned(),
            adapter: None,
        });
        auth.oauth.push(AuthOAuthProvider {
            provider: "google".to_owned(),
            adapter: "@adapter.google_oauth".to_owned(),
        });
        feature.auth = Some(auth);

        let out = emit(&feature).expect("must emit");
        assert!(out.contains("package customer_auth"));
        assert!(out.contains("\"time\""));
        assert!(out.contains("\"lazuli.dev/runtime/lazuli/auth\""));
        assert!(out.contains(
            "var customerAuthAuthIdentity = auth.FieldRef{Resource: \"Customer\", Field: \"email\"}"
        ));
        assert!(out.contains("var customerAuthAuthPassword = auth.PasswordContract{"));
        assert!(out.contains("Identity:  customerAuthAuthIdentity,"));
        assert!(out.contains("Algorithm: auth.AlgoArgon2id,"));
        assert!(out.contains("HashFn:    \"@fn.hash_customer_password\","));
        assert!(out.contains("RateLimit: \"5 per 10 minutes\","));
        assert!(out.contains("var customerAuthAuthSessions = auth.SessionsContract{"));
        assert!(out.contains("TTL:      7 * 24 * time.Hour,"));
        assert!(out.contains("Refresh:  false,"));
        assert!(out.contains("var customerAuthAuthOAuthGoogle = auth.OAuthContract{"));
        assert!(out.contains("AdapterRef: \"@adapter.google_oauth\","));
        assert!(out.contains("var customerAuthAuthMfa = auth.MfaContract{"));
        assert!(out.contains("Method:   auth.MfaMethodTOTP,"));
    }

    #[test]
    fn identity_only_auth_skips_optional_contracts() {
        let mut feature = base_feature("portal");
        feature.auth = Some(auth_with_identity("User", "email"));
        let out = emit(&feature).expect("must emit");
        assert!(out.contains("var portalAuthIdentity = auth.FieldRef"));
        assert!(!out.contains("PasswordContract"));
        assert!(!out.contains("SessionsContract"));
        assert!(!out.contains("MfaContract"));
        assert!(!out.contains("OAuthContract"));
        assert!(!out.contains("\"time\""));
    }

    #[test]
    fn oauth_providers_are_sorted_for_determinism() {
        let mut feature = base_feature("customer");
        let mut auth = auth_with_identity("Customer", "email");
        auth.oauth.push(AuthOAuthProvider {
            provider: "microsoft".to_owned(),
            adapter: "@adapter.microsoft_oauth".to_owned(),
        });
        auth.oauth.push(AuthOAuthProvider {
            provider: "google".to_owned(),
            adapter: "@adapter.google_oauth".to_owned(),
        });
        feature.auth = Some(auth);

        let a = emit(&feature).expect("must emit");
        let b = emit(&feature).expect("must emit");
        assert_eq!(a, b);
        let google_pos = a.find("AuthOAuthGoogle").expect("google contract");
        let microsoft_pos = a.find("AuthOAuthMicrosoft").expect("microsoft contract");
        assert!(google_pos < microsoft_pos);
    }

    #[test]
    fn non_catalog_values_still_emit_go_valid_conversions() {
        let mut feature = base_feature("customer");
        let mut auth = auth_with_identity("Customer", "email");
        auth.password = Some(AuthPassword {
            algorithm: "scrypt".to_owned(),
            hash: "@fn.hash".to_owned(),
            verify: "@fn.verify".to_owned(),
            rate_limit: None,
        });
        auth.mfa = Some(AuthMfa {
            method: "sms".to_owned(),
            enroll: "@fn.enroll_sms".to_owned(),
            verify: "@fn.verify_sms".to_owned(),
            adapter: Some("@adapter.sms".to_owned()),
        });
        auth.sessions = Some(AuthSessions {
            resource: qname("CustomerSession"),
            ttl: "soon".to_owned(),
            refresh: true,
        });
        feature.auth = Some(auth);

        let out = emit(&feature).expect("must emit");
        assert!(out.contains("Algorithm: auth.PasswordAlgorithm(\"scrypt\"),"));
        assert!(out.contains("Method:     auth.MfaMethod(\"sms\"),"));
        assert!(out.contains("AdapterRef: \"@adapter.sms\","));
        assert!(out.contains("TTL:      0 * time.Second,"));
        assert!(out.contains("// TODO(auth-ttl): unsupported AuthSessions.ttl literal \"soon\""));
    }
}
