//! PG.C — Plan catalog Go emitter.
//!
//! Emits `dist/go/plan/catalog.gen.go` from the analyzer-provided
//! `PlanGateEmitFacts`. Wire-thin: every plan/limit/feature is a
//! literal map entry; the runtime owns the lookup. Per-callable gate
//! preludes are intentionally NOT emitted here (handler emitters
//! would need per-feature plumbing — landed as a separate cell).
//! Authored handlers and command wiring can still call
//! `billing.CheckFeature(ctx, plan.Catalog, "...")` directly against
//! the emitted catalog.

use crate::PlanGateEmitFacts;
use lazuli_ir::{Gate, Plan, PlanCatalog, PlanLimitValue, SubscriptionAnchor};

const HEADER: &str = "// Code generated by Lazuli. DO NOT EDIT.\n// Source: PG.C plan emitter (docs/proposals/plan-and-gate-vocab.md).\n";

/// Emit the contents of `dist/go/plan/catalog.gen.go` if the package
/// has a catalog. Returns `None` when there is no plan facts entry
/// (the package does not opt in to subscription gating).
pub fn emit_plan_catalog_file(facts: &PlanGateEmitFacts) -> Option<String> {
    let catalog = facts.catalog.as_ref()?;
    let mut out = String::with_capacity(1024);
    out.push_str(HEADER);
    out.push_str("\npackage plan\n\n");
    out.push_str("import (\n");
    out.push_str("\t\"time\"\n\n");
    out.push_str("\t\"lazuli.dev/runtime/lazuli/billing\"\n");
    out.push_str(")\n\n");
    out.push_str("// Catalog is the package-wide plan catalog lowered from\n");
    out.push_str("// `plan ...` blocks in app.lzi / registry.lzi.\n");
    out.push_str("var Catalog = billing.PlanCatalog{\n");
    emit_anchor(&mut out, facts.subscription_anchor.as_ref());
    emit_plans(&mut out, catalog);
    out.push_str("}\n\n");
    emit_gate_helpers(&mut out, &facts.gates);
    Some(out)
}

fn emit_anchor(out: &mut String, anchor: Option<&SubscriptionAnchor>) {
    out.push_str("\tAnchor: billing.SubscriptionAnchor{\n");
    if let Some(a) = anchor {
        out.push_str(&format!("\t\tOwnerFeature: {:?},\n", a.feature));
        out.push_str(&format!("\t\tField:        {:?},\n", a.field));
        if let Some(axis) = &a.tenancy_axis {
            out.push_str(&format!("\t\tTenancyAxis:  {:?},\n", axis));
        }
    }
    out.push_str("\t},\n");
}

fn emit_plans(out: &mut String, catalog: &PlanCatalog) {
    out.push_str("\tPlans: map[string]billing.Plan{\n");
    for plan in &catalog.plans {
        emit_plan_entry(out, plan);
    }
    out.push_str("\t},\n");
}

fn emit_plan_entry(out: &mut String, plan: &Plan) {
    out.push_str(&format!("\t\t{:?}: {{\n", plan.name));
    out.push_str(&format!("\t\t\tName: {:?},\n", plan.name));
    if !plan.features.is_empty() {
        out.push_str("\t\t\tFeatures: billing.NewFeatureSet(");
        for (i, f) in plan.features.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(&format!("{:?}", f));
        }
        out.push_str("),\n");
    } else {
        out.push_str("\t\t\tFeatures: billing.NewFeatureSet(),\n");
    }
    if !plan.limits.is_empty() {
        out.push_str("\t\t\tLimits: map[string]billing.LimitValue{\n");
        for limit in &plan.limits {
            let rhs = match limit.value {
                PlanLimitValue::Integer(v) => format!("billing.LimitInt({})", v),
                PlanLimitValue::Unlimited => "billing.LimitUnlimited".to_owned(),
            };
            out.push_str(&format!("\t\t\t\t{:?}: {},\n", limit.name, rhs));
        }
        out.push_str("\t\t\t},\n");
    }
    if let Some(trial) = &plan.trial {
        out.push_str("\t\t\tTrial: &billing.TrialPolicy{\n");
        out.push_str(&format!(
            "\t\t\t\tDuration: {},\n",
            duration_literal(&trial.duration)
        ));
        out.push_str(&format!("\t\t\t\tThenPlan: {:?},\n", trial.then_plan));
        out.push_str("\t\t\t},\n");
    }
    out.push_str("\t\t},\n");
}

/// Translate a Lazuli duration literal (`<integer><s|m|h|d>`) into a
/// Go time.Duration expression. Integer is the multiplier; the unit
/// expands to its `time.*` constant.
fn duration_literal(literal: &str) -> String {
    let len = literal.len();
    if len < 2 {
        return "0".to_owned();
    }
    let (head, tail) = literal.split_at(len - 1);
    let unit = match tail {
        "s" => "time.Second",
        "m" => "time.Minute",
        "h" => "time.Hour",
        "d" => "24 * time.Hour",
        _ => return "0".to_owned(),
    };
    if tail == "d" {
        // `<N> * 24 * time.Hour` — parenthesise the day expansion.
        format!("{} * 24 * time.Hour", head)
    } else {
        format!("{} * {}", head, unit)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::PlanGateEmitFacts;
    use lazuli_ir::{Plan, PlanCatalog, PlanLimit, PlanLimitValue, TrialPolicy};

    fn sample_facts() -> PlanGateEmitFacts {
        let mut facts = PlanGateEmitFacts::default();
        let mut catalog = PlanCatalog::default();
        catalog.plans.push(Plan {
            name: "free".to_owned(),
            features: vec!["search".to_owned(), "view_history".to_owned()],
            limits: vec![PlanLimit {
                name: "queries_per_month".to_owned(),
                value: PlanLimitValue::Integer(100),
            }],
            trial: None,
            span_ref: None,
        });
        catalog.plans.push(Plan {
            name: "trial_pro".to_owned(),
            features: vec!["search".to_owned(), "bulk_consult".to_owned()],
            limits: vec![PlanLimit {
                name: "queries_per_month".to_owned(),
                value: PlanLimitValue::Unlimited,
            }],
            trial: Some(TrialPolicy {
                duration: "14d".to_owned(),
                then_plan: "free".to_owned(),
            }),
            span_ref: None,
        });
        catalog.feature_catalog = vec![
            "bulk_consult".to_owned(),
            "search".to_owned(),
            "view_history".to_owned(),
        ];
        catalog.limit_catalog = vec!["queries_per_month".to_owned()];
        facts.catalog = Some(catalog);
        facts
    }

    #[test]
    fn no_catalog_yields_no_file() {
        let facts = PlanGateEmitFacts::default();
        assert!(emit_plan_catalog_file(&facts).is_none());
    }

    #[test]
    fn catalog_emits_plans_features_limits_and_trial() {
        let facts = sample_facts();
        let out = emit_plan_catalog_file(&facts).expect("file emitted");
        assert!(out.contains("package plan"));
        assert!(out.contains("var Catalog = billing.PlanCatalog{"));
        assert!(out.contains("\"free\":"));
        assert!(out.contains("\"trial_pro\":"));
        assert!(out.contains("billing.NewFeatureSet(\"search\", \"view_history\")"));
        assert!(out.contains("billing.LimitInt(100)"));
        assert!(out.contains("billing.LimitUnlimited"));
        assert!(out.contains("Duration: 14 * 24 * time.Hour"));
        assert!(out.contains("ThenPlan: \"free\""));
    }

    #[test]
    fn duration_literal_translates_units() {
        assert_eq!(duration_literal("30s"), "30 * time.Second");
        assert_eq!(duration_literal("5m"), "5 * time.Minute");
        assert_eq!(duration_literal("2h"), "2 * time.Hour");
        assert_eq!(duration_literal("14d"), "14 * 24 * time.Hour");
    }

    #[test]
    fn gate_helpers_emit_gated_callables_when_present() {
        let mut facts = sample_facts();
        facts.gates.insert(
            "billing/command:create".to_owned(),
            vec![
                Gate::Quota {
                    limit: "queries_per_month".to_owned(),
                },
                Gate::Behind {
                    feature: "bulk_consult".to_owned(),
                },
            ],
        );
        let out = emit_plan_catalog_file(&facts).expect("file emitted");
        assert!(out.contains("var GatedCallables = map[string][]billing.GateRef{"));
        assert!(out.contains("\"billing/command:create\":"));
        assert!(out.contains("billing.GateQuota"));
        assert!(out.contains("billing.GateBehind"));
    }
}

fn emit_gate_helpers(
    out: &mut String,
    gates: &std::collections::BTreeMap<String, Vec<Gate>>,
) {
    // Emit a single per-callable comment listing the gates that
    // apply. The runtime helpers (`billing.CheckFeature`,
    // `billing.CheckQuota`, `billing.IncrQuota`) are called directly
    // from authored handler code; the codegen records the gates here
    // so cold-readers (and the doctor introspection layer) can see
    // every gated callable from the plan package file alone.
    if gates.is_empty() {
        return;
    }
    out.push_str("// GatedCallables enumerates every callable carrying a gate\n");
    out.push_str("// directive, keyed by `<feature>/<callable_kind>:<callable_name>`.\n");
    out.push_str("// Handler bodies invoke billing.CheckFeature / billing.CheckQuota\n");
    out.push_str("// directly against `Catalog`; this map exists for inspection /\n");
    out.push_str("// runtime debug surfacing.\n");
    out.push_str("var GatedCallables = map[string][]billing.GateRef{\n");
    for (key, gate_list) in gates {
        out.push_str(&format!("\t{:?}: {{\n", key));
        for gate in gate_list {
            match gate {
                Gate::Behind { feature } => {
                    out.push_str(&format!(
                        "\t\t{{Kind: billing.GateBehind, Name: {:?}}},\n",
                        feature
                    ));
                }
                Gate::Quota { limit } => {
                    out.push_str(&format!(
                        "\t\t{{Kind: billing.GateQuota, Name: {:?}}},\n",
                        limit
                    ));
                }
            }
        }
        out.push_str("\t},\n");
    }
    out.push_str("}\n");
}
