//! `tailwind.gen.ts` emitter — Tailwind v3 `Partial<Config>` preset whose
//! colors are wired back through CSS variables (so `data-theme="dark"` swaps
//! work without Tailwind re-parsing classes). See `docs/proposals/
//! design-tokens.md` §4.4.
//!
//! Key mappings:
//! - Single-Base color           → `name: "var(--color-name)"`.
//! - Multi-state color (no dark) → `name: { DEFAULT: "var(--color-name-base)", hover: ..., ... }`.
//! - Color with dark             → still routed via `var(--color-…)` — the
//!   dark swap lives in the CSS layer, the preset shape is identical.
//! - `radius.base`               → emitted as `DEFAULT` (Tailwind's
//!   `border-radius` default key).
//! - `motion.duration.base`      → emitted as `DEFAULT` for
//!   `transitionDuration` (same convention).

use std::fmt::Write;

use super::ir::{ColorStateKind, ColorToken, Design};

/// Emit `dist/ts-web/design/tailwind.gen.ts` for the given `Design`.
///
/// The output is a Tailwind v3 preset (`extend.colors`, `extend.spacing`,
/// …) that frontends opt into via `presets: [require('./tailwind.gen')]`
/// in their own `tailwind.config.*`.
///
/// ## Examples
///
/// ```ignore
/// use lazuli_codegen_ts::design_tailwind_v3::emit_tailwind_v3_preset;
/// use lazuli_ir::Design;
///
/// let design: Design = /* … */ unimplemented!();
/// let src = emit_tailwind_v3_preset(&design);
/// assert!(src.contains("module.exports"));
/// ```
pub fn emit_tailwind_v3_preset(design: &Design) -> String {
    let mut s = String::new();
    writeln!(s, "// Code generated by lazuli; DO NOT EDIT.").ok();
    writeln!(
        s,
        "// Source: design.lzi (design `{}`)",
        design.name
    )
    .ok();
    writeln!(s, "import type {{ Config }} from \"tailwindcss\";").ok();
    writeln!(s).ok();
    writeln!(s, "export const lazuliPreset: Partial<Config> = {{").ok();
    writeln!(
        s,
        "  darkMode: [\"class\", '[data-theme=\"dark\"]'],"
    )
    .ok();
    writeln!(s, "  theme: {{").ok();
    writeln!(s, "    extend: {{").ok();

    // colors
    writeln!(s, "      colors: {{").ok();
    for color in &design.colors {
        emit_color(&mut s, color);
    }
    // Custom tokens (9th meta-group) lower as flat var-string entries under
    // the same `colors` map. The dark variant lives in the CSS layer; the
    // preset shape stays var-backed. See
    // `docs/proposals/design-tokens-custom.md` §5.3.
    for tok in &design.custom {
        let group = kebab(&tok.name);
        let key = quote_key(&group);
        writeln!(
            s,
            "        {}: \"var(--color-{})\",",
            key, group
        )
        .ok();
    }
    writeln!(s, "      }},").ok();

    // fontFamily
    writeln!(s, "      fontFamily: {{").ok();
    for fam in &design.typography.families {
        writeln!(
            s,
            "        {}: \"var(--font-{})\",",
            quote_key(&fam.name),
            kebab(&fam.name)
        )
        .ok();
    }
    writeln!(s, "      }},").ok();

    // fontSize
    writeln!(s, "      fontSize: {{").ok();
    for entry in &design.typography.scale {
        writeln!(
            s,
            "        {}: [{}, {{ lineHeight: {} }}],",
            quote_key(&entry.name),
            ts_string(&entry.size),
            ts_string(&entry.line_height),
        )
        .ok();
    }
    writeln!(s, "      }},").ok();

    // fontWeight (Tailwind expects string values per v3 docs).
    writeln!(s, "      fontWeight: {{").ok();
    for w in &design.typography.weights {
        writeln!(s, "        {}: \"{}\",", quote_key(&w.name), w.value).ok();
    }
    writeln!(s, "      }},").ok();

    // letterSpacing
    writeln!(s, "      letterSpacing: {{").ok();
    for t in &design.typography.tracking {
        writeln!(s, "        {}: {},", quote_key(&t.name), ts_string(&t.value)).ok();
    }
    writeln!(s, "      }},").ok();

    // spacing
    writeln!(s, "      spacing: {{").ok();
    for tok in &design.spaces {
        writeln!(s, "        {}: {},", quote_key(&tok.name), ts_string(&tok.value)).ok();
    }
    writeln!(s, "      }},").ok();

    // borderRadius (radius.base → DEFAULT).
    writeln!(s, "      borderRadius: {{").ok();
    for tok in &design.radii {
        let key = if tok.name == "base" {
            "DEFAULT".to_owned()
        } else {
            quote_key(&tok.name)
        };
        writeln!(s, "        {}: {},", key, ts_string(&tok.value)).ok();
    }
    writeln!(s, "      }},").ok();

    // boxShadow
    writeln!(s, "      boxShadow: {{").ok();
    for tok in &design.shadows {
        let key = if tok.name == "base" {
            "DEFAULT".to_owned()
        } else {
            quote_key(&tok.name)
        };
        writeln!(s, "        {}: {},", key, ts_string(&tok.value)).ok();
    }
    writeln!(s, "      }},").ok();

    // transitionDuration (motion.duration.base → DEFAULT).
    writeln!(s, "      transitionDuration: {{").ok();
    for d in &design.motion.durations {
        let key = if d.name == "base" {
            "DEFAULT".to_owned()
        } else {
            quote_key(&d.name)
        };
        writeln!(s, "        {}: {},", key, ts_string(&d.value)).ok();
    }
    writeln!(s, "      }},").ok();

    // transitionTimingFunction
    writeln!(s, "      transitionTimingFunction: {{").ok();
    for e in &design.motion.easings {
        writeln!(s, "        {}: {},", quote_key(&e.name), ts_string(&e.value)).ok();
    }
    writeln!(s, "      }},").ok();

    // screens (breakpoints)
    writeln!(s, "      screens: {{").ok();
    for tok in &design.breakpoints {
        writeln!(s, "        {}: {},", quote_key(&tok.name), ts_string(&tok.value)).ok();
    }
    writeln!(s, "      }},").ok();

    // zIndex (Tailwind v3 expects string).
    writeln!(s, "      zIndex: {{").ok();
    for tok in &design.z_indices {
        writeln!(s, "        {}: \"{}\",", quote_key(&tok.name), tok.value).ok();
    }
    writeln!(s, "      }},").ok();

    writeln!(s, "    }},").ok();
    writeln!(s, "  }},").ok();
    writeln!(s, "}};").ok();
    s
}

fn emit_color(s: &mut String, color: &ColorToken) {
    let key = quote_key(&color.name);
    let single_base = color.states.len() == 1
        && color.states.first().map(|st| st.kind) == Some(ColorStateKind::Base);
    let group = kebab(&color.name);
    if single_base {
        // Flat var reference.
        writeln!(s, "        {}: \"var(--color-{})\",", key, group).ok();
        return;
    }
    writeln!(s, "        {}: {{", key).ok();
    for state in &color.states {
        let suffix = state_kind_suffix(state.kind);
        let nested_key = if state.kind == ColorStateKind::Base {
            "DEFAULT".to_owned()
        } else {
            suffix.to_owned()
        };
        writeln!(
            s,
            "          {}: \"var(--color-{}-{})\",",
            nested_key, group, suffix
        )
        .ok();
    }
    writeln!(s, "        }},").ok();
}

fn state_kind_suffix(kind: ColorStateKind) -> &'static str {
    match kind {
        ColorStateKind::Base => "base",
        ColorStateKind::Hover => "hover",
        ColorStateKind::Active => "active",
        ColorStateKind::Foreground => "foreground",
    }
}

fn kebab(s: &str) -> String {
    s.chars()
        .map(|c| if c == '_' || c == ' ' { '-' } else { c })
        .collect()
}

fn quote_key(name: &str) -> String {
    if is_safe_ident(name) {
        name.to_owned()
    } else {
        format!("\"{}\"", escape_string(name))
    }
}

fn is_safe_ident(s: &str) -> bool {
    let mut it = s.chars();
    match it.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' || c == '$' => {}
        _ => return false,
    }
    it.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
}

fn ts_string(value: &str) -> String {
    format!("\"{}\"", escape_string(value))
}

fn escape_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for c in value.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    include!("design_tailwind_v3_tests.rs");
}
