//! Mobile `tokens.ts` emitter (React Native / Expo shape) —
//! See `docs/proposals/design-tokens.md` §4.6.
//!
//! Conversions from web → RN:
//!   - `rem` values become integer `px` numbers (multiplied by `rem_base`).
//!   - `px` values strip the unit (`640px` → `640`).
//!   - `ms` durations become integer numbers (`150ms` → `150`).
//!   - `shadow` strings parse into the RN shadow-object grammar:
//!     `<offset-x> <offset-y> <blur-radius> [<spread-radius>] <color>`.
//!     Multi-layer shadows (top-level comma outside parens) emit a placeholder
//!     plus a `// TODO(design-shadow-multi-layer)` log comment — the lowering
//!     (Cell A) is expected to reject these earlier with diagnostic
//!     `DESIGN-SHADOW-MULTI-LAYER`. The emitter degrades gracefully so a
//!     single malformed shadow does not abort the rest of the file.
//!   - `breakpoint` and `z` are not emitted (RN doesn't use media queries; z
//!     is per-component runtime).
//!   - `motion.easing` cubic-bezier strings stay as strings — caller adapts
//!     to `Easing.bezier(...)` at the use site.
//!   - Font weight values emit as TS strings (Tailwind v3 + RN convention
//!     both expect numeric-looking strings).

use std::fmt::Write;

use super::ir::{ColorStateKind, ColorToken, Design, ShadowToken};

/// Emit `dist/ts-mobile/design/tokens.ts` for the given `Design`. The
/// `rem_base` parameter feeds rem→px conversion (default in `Lazurite.toml
/// [design]` is `16`).
pub fn emit_tokens_mobile_ts(design: &Design, rem_base: u32) -> String {
    let mut s = String::new();
    writeln!(s, "// Code generated by lazuli; DO NOT EDIT.").ok();
    writeln!(s, "// React Native shape — px numbers, no rem; line-heights as numbers.").ok();
    writeln!(
        s,
        "// Source: design.lzi (design `{}`); rem_base = {}",
        design.name, rem_base
    )
    .ok();
    writeln!(s).ok();
    writeln!(s, "export const tokens = {{").ok();

    // color
    writeln!(s, "  color: {{").ok();
    for color in &design.colors {
        emit_color(&mut s, color);
    }
    // Custom tokens — siblings under `color`, camelCased keys per
    // `docs/proposals/design-tokens-custom.md` §5.2.
    for tok in &design.custom {
        let key = quote_key(&kebab_to_camel(&tok.name));
        match &tok.dark {
            Some(dark) => writeln!(
                s,
                "    {}: {{ light: {}, dark: {} }},",
                key,
                ts_string(&tok.base),
                ts_string(dark),
            )
            .ok(),
            None => writeln!(s, "    {}: {},", key, ts_string(&tok.base)).ok(),
        };
    }
    writeln!(s, "  }},").ok();

    // typography
    writeln!(s, "  typography: {{").ok();
    writeln!(s, "    family: {{").ok();
    for fam in &design.typography.families {
        // RN uses the first family token only (e.g. "Inter, system-ui" → "Inter").
        let primary = fam
            .value
            .split(',')
            .next()
            .unwrap_or(&fam.value)
            .trim()
            .trim_matches('"');
        writeln!(s, "      {}: {},", quote_key(&fam.name), ts_string(primary)).ok();
    }
    writeln!(s, "    }},").ok();

    writeln!(s, "    scale: {{").ok();
    for entry in &design.typography.scale {
        let size_px = to_px(&entry.size, rem_base);
        let lh_px = to_px(&entry.line_height, rem_base);
        writeln!(
            s,
            "      {}: {{ fontSize: {}, lineHeight: {} }},",
            quote_key(&entry.name),
            size_px,
            lh_px,
        )
        .ok();
    }
    writeln!(s, "    }},").ok();

    writeln!(s, "    weight: {{").ok();
    for w in &design.typography.weights {
        writeln!(s, "      {}: \"{}\",", quote_key(&w.name), w.value).ok();
    }
    writeln!(s, "    }},").ok();

    writeln!(s, "    tracking: {{").ok();
    for t in &design.typography.tracking {
        let num = to_unitless(&t.value);
        writeln!(s, "      {}: {},", quote_key(&t.name), num).ok();
    }
    writeln!(s, "    }},").ok();
    writeln!(s, "  }},").ok();

    // space
    writeln!(s, "  space: {{").ok();
    for tok in &design.spaces {
        writeln!(s, "    {}: {},", quote_key(&tok.name), to_px(&tok.value, rem_base)).ok();
    }
    writeln!(s, "  }},").ok();

    // radius
    writeln!(s, "  radius: {{").ok();
    for tok in &design.radii {
        writeln!(s, "    {}: {},", quote_key(&tok.name), to_px(&tok.value, rem_base)).ok();
    }
    writeln!(s, "  }},").ok();

    // shadow → RN object
    writeln!(s, "  shadow: {{").ok();
    for tok in &design.shadows {
        emit_shadow(&mut s, tok);
    }
    writeln!(s, "  }},").ok();

    // motion
    writeln!(s, "  motion: {{").ok();
    writeln!(s, "    duration: {{").ok();
    for d in &design.motion.durations {
        let ms = strip_ms(&d.value);
        writeln!(s, "      {}: {},", quote_key(&d.name), ms).ok();
    }
    writeln!(s, "    }},").ok();
    writeln!(s, "    easing: {{").ok();
    for e in &design.motion.easings {
        writeln!(s, "      {}: {},", quote_key(&e.name), ts_string(&e.value)).ok();
    }
    writeln!(s, "    }},").ok();
    writeln!(s, "  }},").ok();

    // NOTE: breakpoint + z intentionally omitted (proposal §4.6).
    writeln!(s, "}} as const;").ok();
    s
}

// ---------------- color ----------------

fn emit_color(s: &mut String, color: &ColorToken) {
    let key = quote_key(&color.name);
    let has_dark = color.states.iter().any(|st| st.dark.is_some());
    let single_base = color.states.len() == 1
        && color.states.first().map(|st| st.kind) == Some(ColorStateKind::Base);

    if single_base && !has_dark {
        let val = &color.states[0].value;
        writeln!(s, "    {}: {},", key, ts_string(val)).ok();
        return;
    }

    if has_dark {
        writeln!(s, "    {}: {{", key).ok();
        for state in &color.states {
            let state_key = state_kind_key(state.kind);
            match &state.dark {
                Some(dark) => writeln!(
                    s,
                    "      {}: {{ light: {}, dark: {} }},",
                    state_key,
                    ts_string(&state.value),
                    ts_string(dark),
                )
                .ok(),
                None => writeln!(s, "      {}: {},", state_key, ts_string(&state.value)).ok(),
            };
        }
        writeln!(s, "    }},").ok();
        return;
    }

    writeln!(s, "    {}: {{", key).ok();
    for state in &color.states {
        let state_key = state_kind_key(state.kind);
        writeln!(s, "      {}: {},", state_key, ts_string(&state.value)).ok();
    }
    writeln!(s, "    }},").ok();
}

fn state_kind_key(kind: ColorStateKind) -> &'static str {
    match kind {
        ColorStateKind::Base => "base",
        ColorStateKind::Hover => "hover",
        ColorStateKind::Active => "active",
        ColorStateKind::Foreground => "foreground",
    }
}

// ---------------- shadow ----------------

/// Detect a top-level comma outside parentheses → multi-layer shadow.
fn is_multi_layer(input: &str) -> bool {
    let mut depth = 0i32;
    for c in input.chars() {
        match c {
            '(' => depth += 1,
            ')' => depth = depth.saturating_sub(1),
            ',' if depth == 0 => return true,
            _ => {}
        }
    }
    false
}

fn emit_shadow(s: &mut String, tok: &ShadowToken) {
    let key = quote_key(&tok.name);
    if is_multi_layer(&tok.value) {
        // Don't fail the whole emission — Cell A's lowering is expected to
        // reject multi-layer shadows upstream. Emit a placeholder + a TODO
        // log so the user sees something actionable.
        writeln!(
            s,
            "    // TODO(design-shadow-multi-layer): cannot map multi-layer CSS \
             box-shadow to a single RN object. Token `{}` was: {:?}.",
            tok.name, tok.value
        )
        .ok();
        writeln!(
            s,
            "    {}: {{ shadowColor: \"#000\", shadowOffset: {{ width: 0, height: 0 }}, \
             shadowOpacity: 0, shadowRadius: 0, elevation: 0 }},",
            key
        )
        .ok();
        return;
    }

    match parse_single_shadow(&tok.value) {
        Some(parsed) => {
            writeln!(s, "    {}: {{", key).ok();
            writeln!(s, "      shadowColor: {},", ts_string(&parsed.color)).ok();
            writeln!(
                s,
                "      shadowOffset: {{ width: {}, height: {} }},",
                parsed.offset_x, parsed.offset_y
            )
            .ok();
            writeln!(s, "      shadowOpacity: {},", format_opacity(parsed.opacity)).ok();
            writeln!(s, "      shadowRadius: {},", parsed.blur).ok();
            writeln!(s, "      elevation: {},", parsed.elevation).ok();
            writeln!(s, "    }},").ok();
        }
        None => {
            writeln!(
                s,
                "    // TODO(design-shadow-parse): could not parse shadow value for `{}`: {:?}.",
                tok.name, tok.value
            )
            .ok();
            writeln!(
                s,
                "    {}: {{ shadowColor: \"#000\", shadowOffset: {{ width: 0, height: 0 }}, \
                 shadowOpacity: 0, shadowRadius: 0, elevation: 0 }},",
                key
            )
            .ok();
        }
    }
}

struct ParsedShadow {
    offset_x: i32,
    offset_y: i32,
    blur: i32,
    color: String,
    opacity: f32,
    elevation: i32,
}

/// Parse the closed grammar `<offset-x> <offset-y> <blur-radius>
/// [<spread-radius>] <color>` where lengths are bare px (`1px` or `1`) and
/// color is hex / rgb / rgba / `rgb(... / α)`.
fn parse_single_shadow(input: &str) -> Option<ParsedShadow> {
    let input = input.trim();
    // Split on whitespace but keep `rgb(...)` / `rgba(...)` / `hsl(...)` as one token.
    let tokens = split_shadow_tokens(input)?;
    if tokens.len() < 4 {
        return None;
    }
    // Color is always the last token; everything before are length values.
    let color_tok = tokens.last()?.clone();
    let lens = &tokens[..tokens.len() - 1];
    if lens.len() < 3 || lens.len() > 4 {
        return None;
    }
    let offset_x = parse_length_px(&lens[0])?;
    let offset_y = parse_length_px(&lens[1])?;
    let blur = parse_length_px(&lens[2])?;
    // spread (lens[3]) intentionally ignored — RN has no spread-radius.

    let (color_hex, opacity) = parse_color(&color_tok)?;
    let elevation = approx_elevation(offset_y, blur);
    Some(ParsedShadow {
        offset_x,
        offset_y,
        blur,
        color: color_hex,
        opacity,
        elevation,
    })
}

/// Tokenize the shadow string respecting parentheses. Splits on whitespace
/// except inside `(...)`.
fn split_shadow_tokens(input: &str) -> Option<Vec<String>> {
    let mut out: Vec<String> = Vec::new();
    let mut depth = 0i32;
    let mut buf = String::new();
    for c in input.chars() {
        match c {
            '(' => {
                depth += 1;
                buf.push(c);
            }
            ')' => {
                depth = depth.checked_sub(1)?;
                buf.push(c);
            }
            ' ' | '\t' if depth == 0 => {
                if !buf.is_empty() {
                    out.push(std::mem::take(&mut buf));
                }
            }
            _ => buf.push(c),
        }
    }
    if depth != 0 {
        return None;
    }
    if !buf.is_empty() {
        out.push(buf);
    }
    Some(out)
}

fn parse_length_px(tok: &str) -> Option<i32> {
    let cleaned = tok.trim_end_matches("px");
    cleaned.parse::<i32>().ok()
}

fn parse_color(tok: &str) -> Option<(String, f32)> {
    // hex first
    if let Some(stripped) = tok.strip_prefix('#') {
        // assume 100% opacity for hex literals; RN supports #rgb/#rgba but we
        // factor the alpha into shadowOpacity in the rgb / rgba paths.
        return Some((format!("#{}", stripped), 1.0));
    }
    // rgb(...) / rgba(...) — extract color triple + optional alpha.
    let lower = tok.to_ascii_lowercase();
    if let Some(rest) = lower
        .strip_prefix("rgba(")
        .or_else(|| lower.strip_prefix("rgb("))
    {
        let body = rest.strip_suffix(')')?;
        // Body might be `r, g, b, α` (comma) or `r g b / α` (slash space).
        let (r, g, b, a) = parse_rgb_components(body)?;
        let hex = format!("#{:02x}{:02x}{:02x}", r, g, b);
        return Some((hex, a));
    }
    None
}

fn parse_rgb_components(body: &str) -> Option<(u8, u8, u8, f32)> {
    let normalized = body.replace([',', '/'], " ");
    let parts: Vec<&str> = normalized.split_whitespace().collect();
    if parts.len() < 3 {
        return None;
    }
    let r = parts[0].parse::<u8>().ok()?;
    let g = parts[1].parse::<u8>().ok()?;
    let b = parts[2].parse::<u8>().ok()?;
    let a = if parts.len() >= 4 {
        parts[3].parse::<f32>().ok()?
    } else {
        1.0
    };
    Some((r, g, b, a))
}

fn format_opacity(o: f32) -> String {
    // Trim trailing zeros, keep at least one decimal place.
    let rounded = (o * 1000.0).round() / 1000.0;
    let mut formatted = format!("{}", rounded);
    if !formatted.contains('.') {
        formatted.push_str(".0");
    }
    formatted
}

fn approx_elevation(offset_y: i32, blur: i32) -> i32 {
    // Common heuristic across token compilers: Android elevation roughly
    // matches the sum of offset-y and half the blur radius, capped at 24.
    let raw = offset_y + (blur / 2);
    raw.clamp(0, 24)
}

// ---------------- numeric helpers ----------------

/// Convert `0.25rem` → `4`, `12px` → `12`, `0` → `0`. Returns the input
/// unchanged if it can't be parsed (lets downstream typescript / tests
/// surface the malformed value).
fn to_px(value: &str, rem_base: u32) -> String {
    let trimmed = value.trim();
    if let Some(num) = trimmed.strip_suffix("rem") {
        if let Ok(parsed) = num.trim().parse::<f64>() {
            let px = (parsed * rem_base as f64).round() as i64;
            return px.to_string();
        }
    }
    if let Some(num) = trimmed.strip_suffix("px") {
        if let Ok(parsed) = num.trim().parse::<f64>() {
            return (parsed.round() as i64).to_string();
        }
    }
    if let Ok(parsed) = trimmed.parse::<f64>() {
        return (parsed.round() as i64).to_string();
    }
    // Fallback: leave as-is wrapped in a TS string so output stays valid.
    format!("\"{}\"", trimmed)
}

fn strip_ms(value: &str) -> String {
    let trimmed = value.trim();
    if let Some(num) = trimmed.strip_suffix("ms") {
        if let Ok(parsed) = num.trim().parse::<f64>() {
            return (parsed.round() as i64).to_string();
        }
    }
    if let Some(num) = trimmed.strip_suffix('s') {
        if let Ok(parsed) = num.trim().parse::<f64>() {
            return ((parsed * 1000.0).round() as i64).to_string();
        }
    }
    if let Ok(parsed) = trimmed.parse::<f64>() {
        return (parsed.round() as i64).to_string();
    }
    format!("\"{}\"", trimmed)
}

fn to_unitless(value: &str) -> String {
    let trimmed = value.trim();
    if let Some(num) = trimmed
        .strip_suffix("em")
        .or_else(|| trimmed.strip_suffix("px"))
    {
        if let Ok(parsed) = num.trim().parse::<f64>() {
            return format!("{}", parsed);
        }
    }
    if let Ok(parsed) = trimmed.parse::<f64>() {
        return format!("{}", parsed);
    }
    format!("\"{}\"", trimmed)
}

// ---------------- TS string helpers (duplicate of tokens_ts; keeping each
// emitter standalone simplifies the post-merge wire-up).

fn quote_key(name: &str) -> String {
    if is_safe_ident(name) {
        name.to_owned()
    } else {
        format!("\"{}\"", escape_string(name))
    }
}

/// Kebab → camelCase. See tokens_ts companion helper.
fn kebab_to_camel(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut upper_next = false;
    for c in name.chars() {
        if c == '-' {
            upper_next = true;
            continue;
        }
        if upper_next {
            out.extend(c.to_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    out
}

fn is_safe_ident(s: &str) -> bool {
    let mut it = s.chars();
    match it.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' || c == '$' => {}
        _ => return false,
    }
    it.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
}

fn ts_string(value: &str) -> String {
    format!("\"{}\"", escape_string(value))
}

fn escape_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for c in value.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::design::ir::{
        ColorState, ColorStateKind, ColorToken, Design, EasingToken, FamilyToken, Motion,
        ScaleToken, ShadowToken, TextScaleToken, TrackingToken, Typography, WeightToken,
    };

    fn minimal() -> Design {
        Design {
            name: "tiny".to_owned(),
            extends: None,
            colors: vec![ColorToken {
                name: "primary".to_owned(),
                states: vec![ColorState {
                    kind: ColorStateKind::Base,
                    value: "#7c3aed".to_owned(),
                    dark: None,
                }],
                span_ref: None,
            }],
            typography: Typography {
                families: vec![FamilyToken {
                    name: "sans".to_owned(),
                    value: "Inter, system-ui, sans-serif".to_owned(),
                }],
                scale: vec![TextScaleToken {
                    name: "base".to_owned(),
                    size: "1rem".to_owned(),
                    line_height: "1.5rem".to_owned(),
                }],
                weights: vec![WeightToken {
                    name: "regular".to_owned(),
                    value: 400,
                }],
                tracking: vec![],
            },
            spaces: vec![ScaleToken {
                name: "4".to_owned(),
                value: "1rem".to_owned(),
            }],
            radii: vec![],
            shadows: vec![],
            motion: Motion::default(),
            breakpoints: vec![ScaleToken {
                name: "md".to_owned(),
                value: "768px".to_owned(),
            }],
            z_indices: vec![],
            custom: vec![],
            span_ref: None,
        }
    }

    #[test]
    fn minimal_converts_rem_to_px_at_16() {
        let out = emit_tokens_mobile_ts(&minimal(), 16);
        // 1rem * 16 = 16
        assert!(out.contains("\"4\": 16,"));
        assert!(out.contains("base: { fontSize: 16, lineHeight: 24 }"));
        // Primary font uses first family only.
        assert!(out.contains("sans: \"Inter\","));
        // weight stays as string per RN convention.
        assert!(out.contains("regular: \"400\","));
        // breakpoint must NOT appear in mobile output.
        assert!(!out.contains("breakpoint:"));
        // z must NOT appear in mobile output.
        assert!(!out.contains("z: "));
    }

    #[test]
    fn rem_base_18_changes_pixel_values() {
        let out = emit_tokens_mobile_ts(&minimal(), 18);
        assert!(out.contains("\"4\": 18,"));
        assert!(out.contains("fontSize: 18"));
        assert!(out.contains("lineHeight: 27")); // 1.5rem * 18 = 27
    }

    #[test]
    fn shadow_parses_to_rn_object() {
        let mut d = minimal();
        d.shadows.push(ShadowToken {
            name: "base".to_owned(),
            value: "0 1px 3px 0 rgb(0 0 0 / 0.1)".to_owned(),
        });
        let out = emit_tokens_mobile_ts(&d, 16);
        assert!(out.contains("base: {"));
        assert!(out.contains("shadowColor: \"#000000\","));
        assert!(out.contains("shadowOffset: { width: 0, height: 1 },"));
        assert!(out.contains("shadowOpacity: 0.1,"));
        assert!(out.contains("shadowRadius: 3,"));
        assert!(out.contains("elevation: "));
    }

    #[test]
    fn dark_color_emits_light_dark_states() {
        let mut d = minimal();
        d.colors.push(ColorToken {
            name: "background".to_owned(),
            states: vec![ColorState {
                kind: ColorStateKind::Base,
                value: "#ffffff".to_owned(),
                dark: Some("#09090b".to_owned()),
            }],
            span_ref: None,
        });
        let out = emit_tokens_mobile_ts(&d, 16);
        assert!(out.contains("background: {"));
        assert!(out.contains("base: { light: \"#ffffff\", dark: \"#09090b\" },"));
    }

    #[test]
    fn empty_design_emits_skeleton_no_crash() {
        let d = Design {
            name: "void".to_owned(),
            extends: None,
            colors: vec![],
            typography: Typography::default(),
            spaces: vec![],
            radii: vec![],
            shadows: vec![],
            motion: Motion::default(),
            breakpoints: vec![],
            z_indices: vec![],
            custom: vec![],
            span_ref: None,
        };
        let out = emit_tokens_mobile_ts(&d, 16);
        assert!(out.contains("export const tokens = {"));
        assert!(out.contains("color: {"));
        assert!(out.contains("} as const;"));
    }

    #[test]
    fn multi_layer_shadow_emits_todo_comment_and_placeholder() {
        let mut d = minimal();
        d.shadows.push(ShadowToken {
            name: "elevated".to_owned(),
            value: "0 1px 2px #000, 0 4px 6px #111".to_owned(),
        });
        let out = emit_tokens_mobile_ts(&d, 16);
        assert!(out.contains("TODO(design-shadow-multi-layer)"));
        // Placeholder still emits the key so the file remains valid TS.
        assert!(out.contains("elevated: {"));
        assert!(out.contains("shadowOpacity: 0"));
    }

    #[test]
    fn duration_strips_ms() {
        let mut d = minimal();
        d.motion.durations.push(ScaleToken {
            name: "fast".to_owned(),
            value: "150ms".to_owned(),
        });
        d.motion.durations.push(ScaleToken {
            name: "slow".to_owned(),
            value: "350ms".to_owned(),
        });
        let out = emit_tokens_mobile_ts(&d, 16);
        assert!(out.contains("fast: 150,"));
        assert!(out.contains("slow: 350,"));
    }

    #[test]
    fn easing_cubic_bezier_kept_as_string() {
        let mut d = minimal();
        d.motion.easings.push(EasingToken {
            name: "out".to_owned(),
            value: "cubic-bezier(0, 0, 0.2, 1)".to_owned(),
        });
        let out = emit_tokens_mobile_ts(&d, 16);
        assert!(out.contains("out: \"cubic-bezier(0, 0, 0.2, 1)\","));
    }

    #[test]
    fn hex_shadow_color_normalizes_to_six_digit_hex() {
        let mut d = minimal();
        d.shadows.push(ShadowToken {
            name: "soft".to_owned(),
            value: "0 2px 4px #abcdef".to_owned(),
        });
        let out = emit_tokens_mobile_ts(&d, 16);
        assert!(out.contains("shadowColor: \"#abcdef\","));
        assert!(out.contains("shadowOffset: { width: 0, height: 2 },"));
        assert!(out.contains("shadowRadius: 4,"));
        // Hex without alpha → opacity 1.0.
        assert!(out.contains("shadowOpacity: 1.0,"));
    }

    #[test]
    fn px_value_in_radius_strips_unit() {
        let mut d = minimal();
        d.radii.push(ScaleToken {
            name: "full".to_owned(),
            value: "9999px".to_owned(),
        });
        let out = emit_tokens_mobile_ts(&d, 16);
        assert!(out.contains("full: 9999,"));
    }

    #[test]
    fn rgba_with_comma_syntax_parses() {
        let mut d = minimal();
        d.shadows.push(ShadowToken {
            name: "alpha".to_owned(),
            value: "0 1px 2px rgba(0, 0, 0, 0.25)".to_owned(),
        });
        let out = emit_tokens_mobile_ts(&d, 16);
        assert!(out.contains("shadowColor: \"#000000\","));
        assert!(out.contains("shadowOpacity: 0.25,"));
    }

    #[test]
    fn tracking_unit_stripped_to_number() {
        let mut d = minimal();
        d.typography.tracking.push(TrackingToken {
            name: "tight".to_owned(),
            value: "-0.025em".to_owned(),
        });
        let out = emit_tokens_mobile_ts(&d, 16);
        assert!(out.contains("tight: -0.025,"));
    }
}
