use std::collections::BTreeMap;
use std::fmt::Write;

use lazuli_ir::{AppManifest, AppRoute, Experience, Feature, Platform, PlatformSurface, ViewGuard};

use crate::GeneratedFile;
use crate::lzx::lzx_router_adapter::{RouterTarget, translate_route_path};

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum RoutesTarget {
    Web,
    Mobile,
}

impl RoutesTarget {
    fn dist_prefix(self) -> &'static str {
        match self {
            RoutesTarget::Web => "ts-web",
            RoutesTarget::Mobile => "ts-mobile",
        }
    }

    fn platform_label(self) -> &'static str {
        match self {
            RoutesTarget::Web => "web",
            RoutesTarget::Mobile => "mobile",
        }
    }

    fn platform(self) -> Platform {
        match self {
            RoutesTarget::Web => Platform::Web,
            RoutesTarget::Mobile => Platform::Mobile,
        }
    }

    fn router_target(self) -> RouterTarget {
        match self {
            RoutesTarget::Web => RouterTarget::ViteReact,
            RoutesTarget::Mobile => RouterTarget::Expo,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct RouteSpec {
    name: String,
    path: String,
    audience: String,
    component_key: String,
    route_const: String,
    /// W3 Tier 1 — when the .lzx route block declared `policy @policy.X`
    /// (plus optional `on_unauthenticated`/`on_unauthorized`), codegen
    /// emits a `beforeLoad` that calls the runtime's
    /// `tanstackBeforeLoadGuard`. None ⇒ route's `beforeLoad` falls
    /// through to `options.guards?.<key>` (consumer-supplied closure;
    /// the Wave 2 escape hatch stays available for app-bespoke logic).
    guard_emit: Option<GuardEmit>,
}

/// Resolved per-route guard payload for codegen. Atoms are decomposed
/// from `@<ns>.<name>` strings at IR-resolution time so the emitted
/// TS doesn't need a runtime lookup.
#[derive(Debug, Clone, PartialEq, Eq)]
struct GuardEmit {
    policy_name: String,
    policy_atoms: Vec<(String, String)>,
    on_unauthenticated: Option<String>,
    on_unauthorized: Option<String>,
}

pub fn emit_routes_artifacts(
    _app: Option<&AppManifest>,
    routes: &[AppRoute],
    surfaces: &[PlatformSurface],
    experiences: &[Experience],
    features: &[Feature],
    target: RoutesTarget,
) -> Vec<GeneratedFile> {
    let mut groups: BTreeMap<String, Vec<RouteSpec>> = BTreeMap::new();
    for route in routes {
        let Some(path) = route.path.as_deref() else {
            continue;
        };
        if !route_matches_target(route, surfaces, experiences, target) {
            continue;
        }
        let audience = route.audience.as_deref().unwrap_or("default").to_owned();
        groups.entry(audience.clone()).or_default().push(RouteSpec {
            name: route.name.clone(),
            path: translate_route_path(target.router_target(), path),
            audience,
            component_key: lower_camel(&route.name),
            route_const: route_const_name(&route.name),
            guard_emit: route.guard.as_ref().and_then(|g| resolve_guard_emit(g, features)),
        });
    }

    let mut files = Vec::new();
    for (audience, specs) in groups.iter_mut() {
        specs.sort_by(|a, b| a.route_const.cmp(&b.route_const));
        specs.dedup_by(|a, b| a.route_const == b.route_const);
        files.push(GeneratedFile {
            path: format!("dist/{}/{}/routes.gen.tsx", target.dist_prefix(), audience),
            contents: emit_routes_file(specs),
        });
    }
    files
}

fn route_matches_target(
    route: &AppRoute,
    surfaces: &[PlatformSurface],
    experiences: &[Experience],
    target: RoutesTarget,
) -> bool {
    if let Some(surface) = route.surface.as_deref() {
        if let Some(platform) = surface_platform_label(surface) {
            return platform == target.platform_label();
        }
    }
    let Some(surface) = matching_surface(route, surfaces, experiences, target) else {
        return target == RoutesTarget::Web;
    };
    surface.platform == target.platform()
}

fn matching_surface<'a>(
    route: &AppRoute,
    surfaces: &'a [PlatformSurface],
    _experiences: &[Experience],
    target: RoutesTarget,
) -> Option<&'a PlatformSurface> {
    let route_feature = route_target_feature(route.to.as_deref())
        .or_else(|| route.surface.as_deref().and_then(surface_feature))
        .unwrap_or_else(|| route_feature_from_name(&route.name));
    surfaces
        .iter()
        .filter(|surface| surface.platform == target.platform())
        .find(|surface| {
            route
                .surface
                .as_deref()
                .map(|label| surface_matches(surface, label))
                .unwrap_or(surface.experience == route_feature)
        })
}

fn emit_routes_file(specs: &[RouteSpec]) -> String {
    let mut s = String::new();
    s.push_str("// Code generated by lazuli; DO NOT EDIT.\n");
    // Imports flow through @lazuli/runtime so the dist file resolves
    // regardless of where it sits in the host filesystem. Pilots must
    // additionally path-map `@tanstack/react-router` + `@tanstack/react-query`
    // to their own node_modules so the lazuli-source-resolved imports and
    // the consumer's imports unify on a single physical module (otherwise
    // pnpm's per-package isolation produces different `#private` brands
    // and the router instance is not assignable to RouterProvider).
    let any_ir_guard = specs.iter().any(|s| s.guard_emit.is_some());
    s.push_str("import { createElement, type FunctionComponent, type ReactElement } from \"@lazuli/runtime/react\";\n");
    s.push_str(
        "import { Link, Outlet, createRootRouteWithContext, createRoute, createRouter, type LinkProps, type NotFoundRouteComponent, type QueryClient } from \"@lazuli/runtime/react/tanstack\";\n",
    );
    if any_ir_guard {
        // tanstackBeforeLoadGuard is the runtime helper that decomposes
        // policy → verdict and throws the configured redirect.
        s.push_str("import { tanstackBeforeLoadGuard } from \"@lazuli/runtime/react/tanstack\";\n");
    }
    s.push_str("import type { LazuliClient } from \"@lazuli/runtime\";\n\n");

    s.push_str("export const routeSpecs = [\n");
    for spec in specs {
        writeln!(s, "  {{").ok();
        writeln!(s, "    name: {},", ts_string(&spec.name)).ok();
        writeln!(s, "    path: {},", ts_string(&spec.path)).ok();
        writeln!(s, "    audience: {},", ts_string(&spec.audience)).ok();
        writeln!(s, "    component: {},", ts_string(&spec.component_key)).ok();
        writeln!(s, "  }},").ok();
    }
    s.push_str("] as const;\n\n");

    if specs.is_empty() {
        s.push_str("export type ClientComponentKey = never;\n");
    } else {
        let keys = specs
            .iter()
            .map(|spec| ts_string(&spec.component_key))
            .collect::<Vec<_>>()
            .join(" | ");
        writeln!(s, "export type ClientComponentKey = {};", keys).ok();
    }
    s.push_str("export type GeneratedRouterContext = { client: LazuliClient; queryClient: QueryClient };\n");
    s.push_str(
        "export type GeneratedRouterComponents = Record<ClientComponentKey, FunctionComponent<any>>;\n",
    );
    s.push_str("export type GeneratedRouterGuards = Partial<Record<ClientComponentKey, (params: { context: GeneratedRouterContext }) => unknown | Promise<unknown>>>;\n\n");
    s.push_str("export function createGeneratedRouter(options: {\n");
    s.push_str("  client: LazuliClient;\n");
    s.push_str("  queryClient: QueryClient;\n");
    s.push_str("  components: GeneratedRouterComponents;\n");
    s.push_str("  guards?: GeneratedRouterGuards;\n");
    s.push_str("  notFoundComponent?: NotFoundRouteComponent;\n");
    s.push_str("  defaultPreload?: \"intent\" | \"viewport\" | \"render\" | false;\n");
    s.push_str("}) {\n");
    // Root route renders Outlet so child route components actually mount.
    // Emitted as createElement(Outlet) (not JSX) so the dist file doesn't
    // need a resolvable `react/jsx-runtime` from its filesystem walk.
    // notFoundComponent is set on the rootRoute (catches __root__ errors)
    // AND wired as router-level defaultNotFoundComponent (catches mismatches
    // bubbled up from child routes) — both are required because TanStack's
    // fuzzy notFoundMode doesn't always cascade router-level default to
    // root-level errors.
    s.push_str("  const rootRoute = createRootRouteWithContext<GeneratedRouterContext>()({\n");
    s.push_str("    component: () => createElement(Outlet),\n");
    s.push_str("    notFoundComponent: options.notFoundComponent,\n");
    s.push_str("  });\n");
    for spec in specs {
        writeln!(s, "  const {} = createRoute({{", spec.route_const).ok();
        s.push_str("    getParentRoute: () => rootRoute,\n");
        writeln!(s, "    path: {},", ts_string(&spec.path)).ok();
        writeln!(
            s,
            "    component: options.components.{},",
            spec.component_key
        )
        .ok();
        emit_before_load(&mut s, spec);
        s.push_str("  });\n");
    }
    let children = specs
        .iter()
        .map(|spec| spec.route_const.as_str())
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        s,
        "  const routeTree = rootRoute.addChildren([{}] as const);",
        children
    )
    .ok();
    s.push_str("  return createRouter({\n");
    s.push_str("    routeTree,\n");
    s.push_str("    context: { client: options.client, queryClient: options.queryClient },\n");
    s.push_str("    defaultPreload: options.defaultPreload,\n");
    s.push_str("    defaultNotFoundComponent: options.notFoundComponent,\n");
    s.push_str("  });\n");
    s.push_str("}\n\n");
    s.push_str("export const AppLink = Link as <T extends LinkProps[\"to\"]>(\n");
    s.push_str("  props: LinkProps & { to: T },\n");
    s.push_str(") => ReactElement;\n");
    s
}

/// W3 Tier 1 — decide whether to emit an inline `beforeLoad` (driven
/// by the IR-resolved guard) or fall through to the Wave-2 escape
/// hatch (`options.guards?.<key>`). Both shapes can coexist: if the
/// route both declared `policy` in .lzx AND the app passes a guard by
/// key, the IR guard runs first; the consumer's guard is never
/// reached because TanStack's beforeLoad slot is single-valued.
fn emit_before_load(out: &mut String, spec: &RouteSpec) {
    let Some(guard) = &spec.guard_emit else {
        writeln!(
            out,
            "    beforeLoad: options.guards?.{},",
            spec.component_key
        )
        .ok();
        return;
    };
    let atoms_literal = guard
        .policy_atoms
        .iter()
        .map(|(ns, name)| format!("{{ namespace: {:?}, name: {:?} }}", ns, name))
        .collect::<Vec<_>>()
        .join(", ");
    let on_unauth = match guard.on_unauthenticated.as_deref() {
        Some(p) => format!("{:?}", p),
        None => "undefined".to_owned(),
    };
    let on_unauth_role = match guard.on_unauthorized.as_deref() {
        Some(p) => format!("{:?}", p),
        None => "undefined".to_owned(),
    };
    out.push_str("    beforeLoad: tanstackBeforeLoadGuard(options.client, {\n");
    out.push_str(&format!(
        "      policy: {{ name: {:?}, atoms: [{}] }},\n",
        guard.policy_name, atoms_literal
    ));
    out.push_str(&format!("      onUnauthenticated: {},\n", on_unauth));
    out.push_str(&format!("      onUnauthorized: {},\n", on_unauth_role));
    out.push_str("    }),\n");
}

/// Resolve a `ViewGuard` IR node (`policy: ["@policy.X"]` + optional
/// redirects) into the codegen-ready payload. v1 supports a single
/// policy atom reference per route — additional policies in the
/// vector are folded into the first (OR semantics). Composed policy
/// expressions go via the existing `PolicyExpr` IR path (deferred).
fn resolve_guard_emit(guard: &ViewGuard, features: &[Feature]) -> Option<GuardEmit> {
    let policy_ref = guard.policy.first()?.trim();
    if policy_ref.is_empty() {
        return None;
    }
    let atoms = resolve_policy_atoms(policy_ref, features);
    Some(GuardEmit {
        policy_name: policy_ref.to_owned(),
        policy_atoms: atoms,
        on_unauthenticated: guard.on_unauthenticated.clone(),
        on_unauthorized: guard.on_unauthorized.clone(),
    })
}

/// Decompose a policy reference into its atoms. Handles two shapes:
/// 1. Atom-form: `@<ns>.<name>` (e.g. `@role.host`) — single atom.
/// 2. Named-form: `@policy.<name>` — look up the policy by name across
///    every feature's catalog; flatten its atom strings.
fn resolve_policy_atoms(policy_ref: &str, features: &[Feature]) -> Vec<(String, String)> {
    let bare = policy_ref.strip_prefix('@').unwrap_or(policy_ref);
    let (ns, name) = match bare.split_once('.') {
        Some(parts) => parts,
        None => return Vec::new(),
    };
    if ns == "policy" {
        // Named policy — look it up in every feature's catalog.
        for feature in features {
            for category in &feature.policies.categories {
                if category.name == name {
                    return category
                        .atoms
                        .iter()
                        .filter_map(|atom| parse_atom_string(atom))
                        .collect();
                }
            }
        }
        Vec::new()
    } else {
        // Inline atom shape: `@role.host` etc.
        vec![(ns.to_owned(), name.to_owned())]
    }
}

fn parse_atom_string(s: &str) -> Option<(String, String)> {
    let bare = s.strip_prefix('@').unwrap_or(s);
    let (ns, rest) = bare.split_once('.')?;
    // Strip any trailing `(args)` parameterisation; codegen doesn't
    // forward those today (only `@mfa.required(within:15m)` carries
    // args, and route guards don't use it).
    let name = rest.split('(').next().unwrap_or(rest);
    Some((ns.to_owned(), name.to_owned()))
}

fn surface_matches(surface: &PlatformSurface, label: &str) -> bool {
    label == surface.experience
        || label == format!("{} web", surface.experience)
        || label == format!("{} mobile", surface.experience)
        || label == format!("{}.web", surface.experience)
        || label == format!("{}.mobile", surface.experience)
}

fn surface_platform_label(surface: &str) -> Option<&'static str> {
    let tail = surface.rsplit([' ', '.']).next()?;
    match tail {
        "web" => Some("web"),
        "mobile" => Some("mobile"),
        _ => None,
    }
}

fn surface_feature(surface: &str) -> Option<String> {
    surface
        .split([' ', '.'])
        .next()
        .filter(|feature| !feature.is_empty())
        .map(str::to_owned)
}

fn route_target_feature(to: Option<&str>) -> Option<String> {
    let target = to?.split('(').next()?.trim();
    let (feature, _) = target.split_once(".view.")?;
    (!feature.is_empty()).then(|| feature.to_owned())
}

fn route_feature_from_name(name: &str) -> String {
    name.split('_')
        .next()
        .filter(|part| !part.is_empty())
        .unwrap_or("app")
        .to_owned()
}

fn route_const_name(name: &str) -> String {
    format!("{}Route", lower_camel(name))
}

fn lower_camel(value: &str) -> String {
    let pascal = pascal_case(value);
    let mut chars = pascal.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().chain(chars).collect(),
        None => String::new(),
    }
}

fn pascal_case(value: &str) -> String {
    let mut out = String::new();
    for word in value.split(['_', '-', ' ']) {
        if word.is_empty() {
            continue;
        }
        let mut chars = word.chars();
        if let Some(first) = chars.next() {
            for upper in first.to_uppercase() {
                out.push(upper);
            }
        }
        out.push_str(&chars.as_str().to_ascii_lowercase());
    }
    out
}

fn ts_string(value: &str) -> String {
    format!("{:?}", value)
}
