use std::collections::BTreeSet;
use std::fmt::Write;

use lazuli_ir::{BuiltinType, CommandInput, Feature, Module, Query, TypeRef};

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum SemanticFormatter {
    Money,
    Date,
    Phone,
    BrazilianPhone,
    BrazilianCpf,
    BrazilianCnpj,
    Currency,
}

/// Emit the app-level semantic formatter re-export module.
///
/// The concrete formatter implementations live in `@lazuli/runtime/formatters`
/// so web and mobile targets share identical behavior. Codegen keeps the app
/// module tree-shake friendly by exporting only helpers whose semantic carrier
/// appears in the IR.
///
/// ## Examples
///
/// ```ignore
/// use lazuli_codegen_ts::emit_semantic_formatters_ts;
/// use lazuli_ir::Module;
///
/// let module: Module = /* … */ unimplemented!();
/// if let Some(src) = emit_semantic_formatters_ts(&module) {
///     assert!(src.contains("export"));
/// }
/// ```
pub fn emit_semantic_formatters_ts(module: &Module) -> Option<String> {
    let formatters = collect_semantic_formatters(module);
    emit_semantic_formatters_for_set(&formatters)
}

fn emit_semantic_formatters_for_set(formatters: &BTreeSet<SemanticFormatter>) -> Option<String> {
    if formatters.is_empty() {
        return None;
    }

    let mut exports: Vec<&'static str> = Vec::new();
    for formatter in formatters {
        exports.extend(formatter.exports());
    }
    exports.sort_unstable();

    let mut out = String::new();
    writeln!(out, "// Code generated by lazuli; DO NOT EDIT.").ok();
    writeln!(out, "//").ok();
    writeln!(
        out,
        "// Semantic formatter surface for @semantic.* carriers used by this app."
    )
    .ok();
    writeln!(
        out,
        "// parseXInput helpers return null on invalid input and never throw."
    )
    .ok();
    writeln!(out).ok();
    writeln!(out, "export {{").ok();
    for export in exports {
        writeln!(out, "  {export},").ok();
    }
    writeln!(out, "}} from \"@lazuli/runtime/formatters\";").ok();

    Some(out)
}

fn collect_semantic_formatters(module: &Module) -> BTreeSet<SemanticFormatter> {
    let mut out = BTreeSet::new();
    for feature in &module.features {
        collect_feature_formatters(feature, &mut out);
    }
    out
}

fn collect_feature_formatters(feature: &Feature, out: &mut BTreeSet<SemanticFormatter>) {
    for record in &feature.records {
        for field in &record.fields {
            collect_type_ref(&field.type_ref, out);
        }
    }
    for resource in &feature.resources {
        for field in &resource.fields {
            collect_type_ref(&field.type_ref, out);
        }
    }
    for event in &feature.events {
        for field in &event.payload {
            collect_type_ref(&field.type_ref, out);
        }
    }
    for command in &feature.commands {
        for route in &command.route {
            collect_type_ref(&route.type_ref, out);
        }
        if let CommandInput::Typed(slots) = &command.input {
            for slot in slots {
                collect_type_ref(&slot.type_ref, out);
            }
        }
        if let lazuli_ir::CommandEffect::Returns(effect) = &command.effect {
            collect_type_ref(&effect.return_type, out);
        }
    }
    for query in &feature.queries {
        match query {
            Query::List(q) => {
                for slot in &q.params {
                    collect_type_ref(&slot.type_ref, out);
                }
            }
            Query::Lookup(q) => {
                for slot in &q.params {
                    collect_type_ref(&slot.type_ref, out);
                }
            }
            Query::Sql(q) => {
                for slot in &q.params {
                    collect_type_ref(&slot.type_ref, out);
                }
                collect_type_ref(&q.returns, out);
            }
        }
    }
}

fn collect_type_ref(type_ref: &TypeRef, out: &mut BTreeSet<SemanticFormatter>) {
    match type_ref {
        TypeRef::Builtin(builtin) => collect_builtin(builtin, out),
        TypeRef::Many(inner) => collect_type_ref(inner, out),
        _ => {}
    }
}

fn collect_builtin(builtin: &BuiltinType, out: &mut BTreeSet<SemanticFormatter>) {
    match builtin {
        BuiltinType::Date | BuiltinType::DateTime => {
            out.insert(SemanticFormatter::Date);
        }
        BuiltinType::SemanticMoney { .. } => {
            out.insert(SemanticFormatter::Money);
        }
        BuiltinType::SemanticPhone => {
            out.insert(SemanticFormatter::Phone);
        }
        BuiltinType::SemanticCurrency => {
            out.insert(SemanticFormatter::Currency);
        }
        BuiltinType::SemanticPluginType { name, .. } => {
            if let Some(formatter) = plugin_formatter_for_name(name) {
                out.insert(formatter);
            }
        }
        _ => {}
    }
}

fn plugin_formatter_for_name(name: &str) -> Option<SemanticFormatter> {
    match name {
        "BrazilianPhone" => Some(SemanticFormatter::BrazilianPhone),
        "BrazilianCPF" => Some(SemanticFormatter::BrazilianCpf),
        "BrazilianCNPJ" => Some(SemanticFormatter::BrazilianCnpj),
        _ => None,
    }
}

impl SemanticFormatter {
    fn exports(self) -> &'static [&'static str] {
        match self {
            Self::Money => &["formatMoney", "parseMoneyInput"],
            Self::Date => &["formatDate", "parseDateInput"],
            Self::Phone => &["formatPhone", "parsePhoneInput"],
            Self::BrazilianPhone => &["formatBrazilianPhone", "parseBrazilianPhoneInput"],
            Self::BrazilianCpf => &["formatBrazilianCPF", "parseBrazilianCPFInput"],
            Self::BrazilianCnpj => &["formatBrazilianCNPJ", "parseBrazilianCNPJInput"],
            Self::Currency => &["formatCurrency", "parseCurrencyInput"],
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use lazuli_ir::{CurrencyCode, Defaults, Field, FieldConstraints, Policies, Record, Resource};

    #[test]
    fn golden_emits_selected_formatter_exports_only() {
        let mut formatters = BTreeSet::new();
        formatters.insert(SemanticFormatter::Money);
        formatters.insert(SemanticFormatter::BrazilianCpf);
        formatters.insert(SemanticFormatter::Date);

        let out = emit_semantic_formatters_for_set(&formatters).expect("emits");

        assert_eq!(
            out,
            concat!(
                "// Code generated by lazuli; DO NOT EDIT.\n",
                "//\n",
                "// Semantic formatter surface for @semantic.* carriers used by this app.\n",
                "// parseXInput helpers return null on invalid input and never throw.\n",
                "\n",
                "export {\n",
                "  formatBrazilianCPF,\n",
                "  formatDate,\n",
                "  formatMoney,\n",
                "  parseBrazilianCPFInput,\n",
                "  parseDateInput,\n",
                "  parseMoneyInput,\n",
                "} from \"@lazuli/runtime/formatters\";\n",
            )
        );
    }

    #[test]
    fn module_with_each_supported_semantic_triggers_expected_exports() {
        let module = Module {
            workspace: None,
            contracts: vec![],
            app: None,
            registry: None,
            profiles: vec![],
            design: None,
            rbac: None,
            features: vec![feature(
                "billing",
                vec![resource(
                    "Invoice",
                    vec![
                        field(
                            "total",
                            TypeRef::Builtin(BuiltinType::SemanticMoney {
                                currency: CurrencyCode::BRL,
                            }),
                        ),
                        field("issued_at", TypeRef::Builtin(BuiltinType::Date)),
                        field("paid_at", TypeRef::Builtin(BuiltinType::DateTime)),
                        field("phone", TypeRef::Builtin(BuiltinType::SemanticPhone)),
                        field("currency", TypeRef::Builtin(BuiltinType::SemanticCurrency)),
                        field("cpf", plugin_type("BrazilianCPF")),
                        field("cnpj", plugin_type("BrazilianCNPJ")),
                        field("mobile", plugin_type("BrazilianPhone")),
                    ],
                )],
                vec![record(
                    "Contact",
                    vec![field(
                        "phones",
                        TypeRef::Many(Box::new(plugin_type("BrazilianPhone"))),
                    )],
                )],
            )],
        };

        let out = emit_semantic_formatters_ts(&module).expect("emits");

        for expected in [
            "formatMoney",
            "parseMoneyInput",
            "formatDate",
            "parseDateInput",
            "formatPhone",
            "parsePhoneInput",
            "formatBrazilianPhone",
            "parseBrazilianPhoneInput",
            "formatBrazilianCPF",
            "parseBrazilianCPFInput",
            "formatBrazilianCNPJ",
            "parseBrazilianCNPJInput",
            "formatCurrency",
            "parseCurrencyInput",
        ] {
            assert!(out.contains(expected), "missing {expected} in:\n{out}");
        }
    }

    #[test]
    fn module_without_format_eligible_semantics_emits_nothing() {
        let module = Module {
            workspace: None,
            contracts: vec![],
            app: None,
            registry: None,
            profiles: vec![],
            design: None,
            rbac: None,
            features: vec![feature(
                "notes",
                vec![resource(
                    "Note",
                    vec![
                        field("title", TypeRef::Builtin(BuiltinType::Text)),
                        field("email", TypeRef::Builtin(BuiltinType::SemanticEmail)),
                    ],
                )],
                vec![],
            )],
        };

        assert!(emit_semantic_formatters_ts(&module).is_none());
    }

    fn feature(name: &str, resources: Vec<Resource>, records: Vec<Record>) -> Feature {
        Feature {
            name: name.to_owned(),
            purpose: None,
            non_goals: vec![],
            context_path: None,
            knowledge: None,
            defaults: Defaults::default(),
            uses: vec![],
            uses_spans: vec![],
            uses_versions: vec![],
            requirements: vec![],
            enums: vec![],
            resources,
            events: vec![],
            rules: vec![],
            policies: Policies::default(),
            errors: None,
            commands: vec![],
            apis: vec![],
            records,
            queries: vec![],
            resume_routers: vec![],
            workflows: vec![],
            jobs: vec![],
            webhooks: vec![],
            notifications: vec![],
            event_groups: vec![],
            tenant_migrations: vec![],
            translation: None,
            pollers: vec![],
            auth: None,
            surfaces: vec![],
            extensions: vec![],
            escape_routes: vec![],
            agents: vec![],
            reports: vec![],
            channels: vec![],
            caches: vec![],
            aggregates: vec![],
            mcp_servers: vec![],
            previous_names: vec![],
            synth_origins: std::collections::BTreeMap::new(),
            span_ref: None,
        }
    }

    fn resource(name: &str, fields: Vec<Field>) -> Resource {
        Resource {
            name: name.to_owned(),
            public_contract: None,
            tenancy: None,
            soft_delete: false,
            timestamps: None,
            fields,
            constraints: vec![],
            validate: None,
            validates: vec![],
            retention: None,
            previous_names: vec![],
            span_ref: None,
            lifecycle: None,
            invariants: vec![],
            lock: None,
            composite_key: None,
            conventions: vec![],
            lifecycle_routes: None,
            polymorphic_refs: Vec::new(),
            many_through: Vec::new(),
            restrict_on_delete: Vec::new(),
            append_only: false,
        }
    }

    fn record(name: &str, fields: Vec<Field>) -> Record {
        Record {
            name: name.to_owned(),
            public_contract: None,
            fields,
            discriminator_field: None,
            span_ref: None,
        }
    }

    fn field(name: &str, type_ref: TypeRef) -> Field {
        Field {
            name: name.to_owned(),
            type_ref,
            required: true,
            unique: false,
            slug: false,
            default: None,
            derived_from: None,
            computed_date: None,
            constraints: FieldConstraints::default(),
            full_text: false,
            previous_names: vec![],
            pii: None,
            owner_axis: None,
            cross_feature_target: None,
            span_ref: None,
        }
    }

    fn plugin_type(name: &str) -> TypeRef {
        TypeRef::Builtin(BuiltinType::SemanticPluginType {
            plugin: "@lazuli/plugin-scalars-br".to_owned(),
            name: name.to_owned(),
            carrier: Box::new(BuiltinType::Text),
            validator: format!("Validate{name}"),
            go_module: "lazuli.dev/plugin/scalars-br".to_owned(),
            ts_package: "@lazuli/plugin-scalars-br".to_owned(),
            error_code: format!("{}_invalid", name.to_lowercase()),
            message_key: String::new(),
            ts_validator: String::new(),
        })
    }
}
