//! Cell C.2 — slot interface emitter per L0 #3 §8.
//!
//! Each `cells <field> @client.<slot>` binding in a `.lzx` view
//! materialises a typed `*Props` interface that the user-authored
//! `features/<feat>/<target>/cells/<slot>.tsx` implements. The
//! generated file lives at
//! `dist/ts-<target>/<feat>/cells/<slot>.gen.ts`:
//!
//! ```typescript
//! // Code generated by lazuli; DO NOT EDIT.
//! import type { Slug } from "../slug.gen.js";
//!
//! export interface TypeBadgeProps {
//!   value: Slug["tags"];
//!   row: Slug;
//! }
//! ```
//!
//! Naming convention: a slot named `type_badge` pascal-cases to
//! `TypeBadge`, and the interface name is `<PascalSlot>Props` →
//! `TypeBadgeProps`.
//!
//! ### Multi-binding rules (§8 v0)
//!
//! A slot may be bound in multiple views (e.g. `cells tags
//! @client.type_badge` in both `slug_list` AND `slug_detail`). For v0
//! the emitter picks the FIRST encountered binding's field type as
//! authoritative and emits a comment listing the alternative binding
//! sites. A discriminated-union upgrade is reserved for a future
//! follow-up cell.
//!
//! ### Section slots
//!
//! When a slot name matches a view detail's `sections` entry (rather
//! than a `cells <field>` binding), the slot receives the whole row,
//! not a single field. The emitter then drops `value: Resource["field"]`
//! in favour of `value: void; row: <Resource>;`.
//!
//! ### Graceful missing-resource fallback
//!
//! If the slot's source query cannot be resolved to a feature
//! resource (e.g. cross-feature query whose returning resource is
//! not in this feature's `resources` list, or a `Sql` query without
//! a typed `returns`), the emitter falls back to `unknown`-typed
//! props and embeds a `// TODO` comment naming the unresolved source.
//! This keeps `tsc --noEmit` green while flagging the gap.

use std::fmt::Write;

use lazuli_codegen_spec::RuntimeFeature;

use crate::lzx_audience_slot::ir::{Surface, View, ViewCreate, ViewDetail, ViewList};
use crate::lzx_audience_slot::pascal_case;

/// Emit the `<slot>.gen.ts` file body for a given slot reference. The
/// caller pairs this with the canonical file path
/// (`dist/ts-<target>/<feat>/cells/<slot>.gen.ts`) when writing.
///
/// Walks every view in `surface` looking for `cells.field == ... &&
/// cells.slot == slot_name`. The first match wins; alternative
/// bindings are listed as a `// Also bound by:` comment block so
/// human reviewers see the divergence.
pub fn emit_slot_interface(surface: &Surface, feature: &RuntimeFeature, slot_name: &str) -> String {
    let pascal_slot = pascal_case(slot_name);
    let interface_name = format!("{pascal_slot}Props");
    let resource_pascal = pascal_case(&feature.name);

    // Walk every view to collect bindings + section matches. Track
    // bindings in source order so the FIRST encountered is the
    // authoritative type for the multi-binding case (§8 v0).
    let mut field_bindings: Vec<FieldBinding> = Vec::new();
    let mut section_bindings: Vec<SectionBinding> = Vec::new();

    for audience in &surface.audiences {
        for view in &audience.views {
            collect_bindings(
                view,
                &audience.name,
                slot_name,
                &mut field_bindings,
                &mut section_bindings,
            );
        }
    }

    // No binding at all — emit a typed-`unknown` shape with a TODO so
    // the user knows the slot file was generated but the contract is
    // unresolved. Matches the "missing source resource" graceful
    // fallback case.
    if field_bindings.is_empty() && section_bindings.is_empty() {
        return emit_unresolved_slot(slot_name, &interface_name);
    }

    // Section-only binding — slot receives the whole row.
    if field_bindings.is_empty() {
        return emit_section_slot(
            slot_name,
            &interface_name,
            &resource_pascal,
            feature,
            &section_bindings,
        );
    }

    // Cell binding present — pick the first, embed others as a comment.
    emit_cell_slot(
        slot_name,
        &interface_name,
        &resource_pascal,
        feature,
        &field_bindings,
        &section_bindings,
    )
}

// ---------------------------------------------------------------------------
// Binding collection
// ---------------------------------------------------------------------------

#[derive(Debug)]
struct FieldBinding {
    audience: String,
    view: String,
    field: String,
}

#[derive(Debug)]
struct SectionBinding {
    audience: String,
    view: String,
}

fn collect_bindings(
    view: &View,
    audience: &str,
    slot_name: &str,
    field_bindings: &mut Vec<FieldBinding>,
    section_bindings: &mut Vec<SectionBinding>,
) {
    match view {
        View::List(v) => collect_from_list(v, audience, slot_name, field_bindings),
        View::Detail(v) => {
            collect_from_detail(v, audience, slot_name, field_bindings, section_bindings)
        }
        View::Create(v) => collect_from_create(v, audience, slot_name, field_bindings),
    }
}

fn collect_from_list(
    v: &ViewList,
    audience: &str,
    slot_name: &str,
    bindings: &mut Vec<FieldBinding>,
) {
    for cell in &v.cells {
        if cell.slot == slot_name {
            bindings.push(FieldBinding {
                audience: audience.to_owned(),
                view: v.name.clone(),
                field: cell.field.clone(),
            });
        }
    }
}

fn collect_from_detail(
    v: &ViewDetail,
    audience: &str,
    slot_name: &str,
    field_bindings: &mut Vec<FieldBinding>,
    section_bindings: &mut Vec<SectionBinding>,
) {
    for cell in &v.cells {
        if cell.slot == slot_name {
            field_bindings.push(FieldBinding {
                audience: audience.to_owned(),
                view: v.name.clone(),
                field: cell.field.clone(),
            });
        }
    }
    // Section names map straight to slot names — if the section name
    // matches `slot_name` it's a section-slot binding.
    for section in &v.sections {
        if section == slot_name {
            section_bindings.push(SectionBinding {
                audience: audience.to_owned(),
                view: v.name.clone(),
            });
        }
    }
}

fn collect_from_create(
    v: &ViewCreate,
    audience: &str,
    slot_name: &str,
    bindings: &mut Vec<FieldBinding>,
) {
    for cell in &v.cells {
        if cell.slot == slot_name {
            bindings.push(FieldBinding {
                audience: audience.to_owned(),
                view: v.name.clone(),
                field: cell.field.clone(),
            });
        }
    }
}

// ---------------------------------------------------------------------------
// Emission
// ---------------------------------------------------------------------------

fn emit_cell_slot(
    slot_name: &str,
    interface_name: &str,
    resource_pascal: &str,
    feature: &RuntimeFeature,
    field_bindings: &[FieldBinding],
    section_bindings: &[SectionBinding],
) -> String {
    let primary = &field_bindings[0];
    let resource_known = feature_has_resource(feature);
    let import_module = format!("../{}.gen.js", feature.name);

    let mut s = String::new();
    writeln!(s, "// Code generated by lazuli; DO NOT EDIT.").ok();
    writeln!(s, "//").ok();
    writeln!(
        s,
        "// Slot: @client.{slot_name} — implement at \
         features/{feature}/<target>/cells/{slot_name}.tsx",
        feature = feature.name
    )
    .ok();
    writeln!(s).ok();

    if resource_known {
        writeln!(
            s,
            "import type {{ {resource_pascal} }} from \"{import_module}\";"
        )
        .ok();
        writeln!(s).ok();
    } else {
        writeln!(
            s,
            "// TODO: source resource `{resource_pascal}` is not in feature `{}`'s \
             resource list; falling back to `unknown`.",
            feature.name
        )
        .ok();
        writeln!(s).ok();
    }

    // Multi-binding comment block — listed before the interface so
    // human reviewers see the divergence above the chosen shape.
    if field_bindings.len() > 1 {
        writeln!(s, "// Bound in {} views:", field_bindings.len()).ok();
        for (idx, binding) in field_bindings.iter().enumerate() {
            let marker = if idx == 0 { "primary" } else { "also" };
            writeln!(
                s,
                "//   - {audience}/{view} field `{field}` ({marker})",
                audience = binding.audience,
                view = binding.view,
                field = binding.field,
                marker = marker
            )
            .ok();
        }
        writeln!(s, "// v0 picks the first binding's type as the slot contract;").ok();
        writeln!(
            s,
            "// alternative bindings must be cell-shape compatible at use site."
        )
        .ok();
        writeln!(s).ok();
    }

    // Section co-binding (rare but possible) — flag it so the user
    // knows the slot is overloaded between cell and section meanings.
    for section in section_bindings {
        writeln!(
            s,
            "// Also bound as section in {audience}/{view}; this emitter \
             treats the cell binding as authoritative.",
            audience = section.audience,
            view = section.view,
        )
        .ok();
    }
    if !section_bindings.is_empty() {
        writeln!(s).ok();
    }

    writeln!(s, "export interface {interface_name} {{").ok();
    if resource_known {
        writeln!(
            s,
            "  value: {resource_pascal}[\"{field}\"];",
            field = primary.field
        )
        .ok();
        writeln!(s, "  row: {resource_pascal};").ok();
    } else {
        writeln!(s, "  value: unknown;").ok();
        writeln!(s, "  row: unknown;").ok();
    }
    writeln!(s, "}}").ok();
    s
}

fn emit_section_slot(
    slot_name: &str,
    interface_name: &str,
    resource_pascal: &str,
    feature: &RuntimeFeature,
    section_bindings: &[SectionBinding],
) -> String {
    let resource_known = feature_has_resource(feature);
    let import_module = format!("../{}.gen.js", feature.name);

    let mut s = String::new();
    writeln!(s, "// Code generated by lazuli; DO NOT EDIT.").ok();
    writeln!(s, "//").ok();
    writeln!(
        s,
        "// Section slot: @client.{slot_name} — receives the whole row, not a \
         single field."
    )
    .ok();
    writeln!(
        s,
        "// Implement at features/{feature}/<target>/cells/{slot_name}.tsx",
        feature = feature.name
    )
    .ok();
    writeln!(s).ok();

    if resource_known {
        writeln!(
            s,
            "import type {{ {resource_pascal} }} from \"{import_module}\";"
        )
        .ok();
        writeln!(s).ok();
    } else {
        writeln!(
            s,
            "// TODO: source resource `{resource_pascal}` is not in feature `{}`'s \
             resource list; falling back to `unknown`.",
            feature.name
        )
        .ok();
        writeln!(s).ok();
    }

    if section_bindings.len() > 1 {
        writeln!(s, "// Bound as section in {} views:", section_bindings.len()).ok();
        for binding in section_bindings {
            writeln!(
                s,
                "//   - {audience}/{view}",
                audience = binding.audience,
                view = binding.view,
            )
            .ok();
        }
        writeln!(s).ok();
    }

    writeln!(s, "export interface {interface_name} {{").ok();
    writeln!(s, "  value: void;").ok();
    if resource_known {
        writeln!(s, "  row: {resource_pascal};").ok();
    } else {
        writeln!(s, "  row: unknown;").ok();
    }
    writeln!(s, "}}").ok();
    s
}

fn emit_unresolved_slot(slot_name: &str, interface_name: &str) -> String {
    let mut s = String::new();
    writeln!(s, "// Code generated by lazuli; DO NOT EDIT.").ok();
    writeln!(s, "//").ok();
    writeln!(
        s,
        "// TODO: slot @client.{slot_name} has no `cells` or section binding \
         in any view"
    )
    .ok();
    writeln!(
        s,
        "// of this surface. Emitted with `unknown`-typed props so the user's \
         cell.tsx"
    )
    .ok();
    writeln!(
        s,
        "// can still typecheck while the binding is wired up. Add `cells \
         <field>"
    )
    .ok();
    writeln!(
        s,
        "// @client.{slot_name}` to a view or remove the cell file."
    )
    .ok();
    writeln!(s).ok();
    writeln!(s, "export interface {interface_name} {{").ok();
    writeln!(s, "  value: unknown;").ok();
    writeln!(s, "  row: unknown;").ok();
    writeln!(s, "}}").ok();
    s
}

/// Resolve whether the feature carries at least one resource whose
/// PascalCase matches the feature name. The runtime spec emits the
/// resource interface using `pascal_case(feature.name)` as the
/// type identifier; absent a matching resource we cannot type-import.
fn feature_has_resource(feature: &RuntimeFeature) -> bool {
    let target = pascal_case(&feature.name);
    feature
        .resources
        .iter()
        .any(|r| pascal_case(&r.name) == target)
}

// ---------------------------------------------------------------------------
// Tests — Cell C.2 ships ≥6 tests covering single binding, cross-view
// consistency, section fallback, casing convention, missing resource,
// and determinism.
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    use lazuli_codegen_spec::{FieldKind, RuntimeFeature, RuntimeField, RuntimeResource, Tenancy};

    use crate::lzx_audience_slot::ir::{
        Audience, CellBinding, CommandRef, PolicyAtom, QueryKind, QueryRef, RouteParam, Surface,
        SurfaceTarget, View, ViewCreate, ViewDetail, ViewList,
    };

    // -----------------------------------------------------------------------
    // Fixtures
    // -----------------------------------------------------------------------

    fn slug_feature() -> RuntimeFeature {
        RuntimeFeature {
            name: "slug".to_owned(),
            source_path: "features/slug/slug.lzi".to_owned(),
            resources: vec![RuntimeResource {
                name: "slug".to_owned(),
                tenancy: Tenancy::Org,
                soft_delete: false,
                retention: None,
                fields: vec![
                    RuntimeField {
                        name: "key".to_owned(),
                        kind: FieldKind::Text,
                    },
                    RuntimeField {
                        name: "tags".to_owned(),
                        kind: FieldKind::Text,
                    },
                ],
            }],
            commands: vec![],
            queries: vec![],
        }
    }

    fn feature_without_matching_resource() -> RuntimeFeature {
        // Feature `widget` but no `widget` resource — only `gadget`.
        // Matches the "missing source resource" graceful fallback.
        RuntimeFeature {
            name: "widget".to_owned(),
            source_path: "features/widget/widget.lzi".to_owned(),
            resources: vec![RuntimeResource {
                name: "gadget".to_owned(),
                tenancy: Tenancy::Org,
                soft_delete: false,
                retention: None,
                fields: vec![],
            }],
            commands: vec![],
            queries: vec![],
        }
    }

    fn type_badge_cell() -> CellBinding {
        CellBinding {
            field: "tags".to_owned(),
            slot: "type_badge".to_owned(),
        }
    }

    fn slug_list_view(cells: Vec<CellBinding>) -> View {
        View::List(ViewList {
            name: "slug_list".to_owned(),
            route: Some("/slugs".to_owned()),
            source: QueryRef {
                feature: "slug".to_owned(),
                kind: QueryKind::List,
                name: "mine".to_owned(),
            },
            columns: vec!["key".to_owned(), "tags".to_owned()],
            search: vec![],
            filter: vec![],
            cells,
            actions: vec![CommandRef {
                feature: "slug".to_owned(),
                name: "create".to_owned(),
            }],
        })
    }

    fn slug_detail_view(cells: Vec<CellBinding>, sections: Vec<String>) -> View {
        View::Detail(ViewDetail {
            name: "slug_detail".to_owned(),
            route: Some("/slugs/:key".to_owned()),
            source: QueryRef {
                feature: "slug".to_owned(),
                kind: QueryKind::Lookup,
                name: "by_key".to_owned(),
            },
            route_params: vec![RouteParam {
                name: "key".to_owned(),
                type_ref: "Text".to_owned(),
            }],
            sections,
            cells,
            actions: vec![],
        })
    }

    fn slug_create_view(cells: Vec<CellBinding>) -> View {
        View::Create(ViewCreate {
            name: "slug_create".to_owned(),
            route: Some("/slugs/new".to_owned()),
            submit: CommandRef {
                feature: "slug".to_owned(),
                name: "create".to_owned(),
            },
            fields: vec!["key".to_owned(), "tags".to_owned()],
            cells,
        })
    }

    fn admin_audience_with_views(views: Vec<View>) -> Audience {
        Audience {
            name: "admin".to_owned(),
            requires: vec![PolicyAtom {
                namespace: "scope".to_owned(),
                name: "workspace_admin".to_owned(),
            }],
            views,
        }
    }

    fn surface_with_audience(audience: Audience) -> Surface {
        Surface {
            feature: "slug".to_owned(),
            target: SurfaceTarget::Web,
            audiences: vec![audience],
        }
    }

    // -----------------------------------------------------------------------
    // Tests
    // -----------------------------------------------------------------------

    /// Single binding — slot bound in one view, type derived from
    /// `Resource["field"]`.
    #[test]
    fn single_binding_emits_field_derived_type() {
        let surface = surface_with_audience(admin_audience_with_views(vec![
            slug_list_view(vec![type_badge_cell()]),
        ]));

        let output = emit_slot_interface(&surface, &slug_feature(), "type_badge");

        assert!(
            output.contains("export interface TypeBadgeProps"),
            "missing interface; got:\n{output}"
        );
        assert!(
            output.contains("value: Slug[\"tags\"];"),
            "expected `value: Slug[\"tags\"];`; got:\n{output}"
        );
        assert!(
            output.contains("row: Slug;"),
            "expected `row: Slug;`; got:\n{output}"
        );
        assert!(
            output.contains("import type { Slug } from \"../slug.gen.js\""),
            "missing typed import; got:\n{output}"
        );
    }

    /// Cross-view binding — same slot bound in `slug_list` AND
    /// `slug_detail` on the SAME field. The interface stays single
    /// and consistent; alternative bindings are noted as comments.
    #[test]
    fn cross_view_binding_emits_one_consistent_interface() {
        let surface = surface_with_audience(admin_audience_with_views(vec![
            slug_list_view(vec![type_badge_cell()]),
            slug_detail_view(vec![type_badge_cell()], vec![]),
        ]));

        let output = emit_slot_interface(&surface, &slug_feature(), "type_badge");

        // Single interface emitted (only one `export interface`).
        let export_count = output.matches("export interface ").count();
        assert_eq!(
            export_count, 1,
            "expected exactly one exported interface; got {export_count}:\n{output}"
        );

        // Both bindings flagged in the multi-binding comment block.
        assert!(
            output.contains("Bound in 2 views:"),
            "missing multi-binding header; got:\n{output}"
        );
        assert!(
            output.contains("admin/slug_list field `tags` (primary)"),
            "missing primary binding line; got:\n{output}"
        );
        assert!(
            output.contains("admin/slug_detail field `tags` (also)"),
            "missing secondary binding line; got:\n{output}"
        );

        // Primary type still wins.
        assert!(output.contains("value: Slug[\"tags\"];"));
    }

    /// Section slot — slot name matches a `sections` entry, no cell
    /// binding anywhere. Emits `value: void; row: <Resource>;`.
    #[test]
    fn section_slot_emits_void_value_with_whole_row() {
        let surface = surface_with_audience(admin_audience_with_views(vec![
            slug_detail_view(
                vec![],
                vec!["header".to_owned(), "metadata".to_owned()],
            ),
        ]));

        let output = emit_slot_interface(&surface, &slug_feature(), "header");

        assert!(
            output.contains("export interface HeaderProps"),
            "missing section interface; got:\n{output}"
        );
        assert!(
            output.contains("value: void;"),
            "section slot must emit `value: void;`; got:\n{output}"
        );
        assert!(
            output.contains("row: Slug;"),
            "section slot must still expose the whole row; got:\n{output}"
        );
        // Section emitter calls out the section-only nature so reviewers
        // don't grep `value: <type>` and miss the contract.
        assert!(
            output.contains("Section slot:"),
            "missing section-slot banner; got:\n{output}"
        );
    }

    /// Casing — slot `type_badge` (snake) pascalizes to `TypeBadge`;
    /// interface is `TypeBadgeProps`. Also verifies kebab-case slots.
    #[test]
    fn slot_name_pascal_case_with_props_suffix() {
        // snake_case slot name
        let surface_snake = surface_with_audience(admin_audience_with_views(vec![
            slug_list_view(vec![type_badge_cell()]),
        ]));
        let output_snake = emit_slot_interface(&surface_snake, &slug_feature(), "type_badge");
        assert!(output_snake.contains("export interface TypeBadgeProps"));

        // kebab-case slot name → `quick-action`
        let kebab_cell = CellBinding {
            field: "tags".to_owned(),
            slot: "quick-action".to_owned(),
        };
        let surface_kebab = surface_with_audience(admin_audience_with_views(vec![
            slug_list_view(vec![kebab_cell]),
        ]));
        let output_kebab = emit_slot_interface(&surface_kebab, &slug_feature(), "quick-action");
        assert!(
            output_kebab.contains("export interface QuickActionProps"),
            "kebab-case slot should pascalize to PascalCase; got:\n{output_kebab}"
        );
    }

    /// Missing source resource — feature has no resource whose Pascal
    /// matches the feature name. The emitter falls back to
    /// `unknown`-typed props + TODO comment instead of producing a
    /// broken `import type { Widget }` line.
    #[test]
    fn missing_source_resource_resolves_gracefully() {
        let surface = Surface {
            feature: "widget".to_owned(),
            target: SurfaceTarget::Web,
            audiences: vec![Audience {
                name: "admin".to_owned(),
                requires: vec![],
                views: vec![View::List(ViewList {
                    name: "widget_list".to_owned(),
                    route: None,
                    source: QueryRef {
                        feature: "widget".to_owned(),
                        kind: QueryKind::List,
                        name: "all".to_owned(),
                    },
                    columns: vec!["name".to_owned()],
                    search: vec![],
                    filter: vec![],
                    cells: vec![CellBinding {
                        field: "status".to_owned(),
                        slot: "badge".to_owned(),
                    }],
                    actions: vec![],
                })],
            }],
        };

        let output = emit_slot_interface(&surface, &feature_without_matching_resource(), "badge");

        assert!(
            output.contains("// TODO"),
            "missing-resource case must emit TODO comment; got:\n{output}"
        );
        assert!(
            output.contains("value: unknown;"),
            "missing-resource case must fall back to `unknown` value; got:\n{output}"
        );
        assert!(
            output.contains("row: unknown;"),
            "missing-resource case must fall back to `unknown` row; got:\n{output}"
        );
        // Don't emit a broken typed import.
        assert!(
            !output.contains("import type { Widget }"),
            "should NOT emit unresolved type import; got:\n{output}"
        );
    }

    /// Deterministic emission — same surface emits identical bytes
    /// across repeated calls, and re-ordering equivalent bindings
    /// inside the same audience yields the same primary pick
    /// (source-order discipline).
    #[test]
    fn slot_interface_emission_is_deterministic() {
        let surface = surface_with_audience(admin_audience_with_views(vec![
            slug_list_view(vec![type_badge_cell()]),
            slug_detail_view(vec![type_badge_cell()], vec![]),
        ]));
        let feature = slug_feature();

        let out_a = emit_slot_interface(&surface, &feature, "type_badge");
        let out_b = emit_slot_interface(&surface, &feature, "type_badge");
        assert_eq!(out_a, out_b);
    }

    /// Slot with no binding anywhere — emits `unknown`-typed props +
    /// TODO comment naming the slot. Locks the "unresolved slot"
    /// graceful path so generated cells/<x>.gen.ts always type-checks.
    #[test]
    fn slot_with_no_binding_emits_unresolved_fallback() {
        let surface = surface_with_audience(admin_audience_with_views(vec![
            slug_list_view(vec![]),
        ]));

        let output = emit_slot_interface(&surface, &slug_feature(), "ghost_slot");

        assert!(output.contains("export interface GhostSlotProps"));
        assert!(output.contains("// TODO"));
        assert!(output.contains("value: unknown;"));
        assert!(output.contains("row: unknown;"));
    }

    /// Create-view binding — `view create` also carries `cells <field>
    /// @client.<slot>` per §6.3. The emitter picks them up just like
    /// list/detail bindings; the resulting interface is structurally
    /// identical (no special "create" treatment — the form view's slot
    /// still receives a field value typed against the resource).
    #[test]
    fn create_view_cell_binding_emits_field_derived_type() {
        let surface = surface_with_audience(admin_audience_with_views(vec![
            slug_create_view(vec![type_badge_cell()]),
            // Detail view also binds the same field/slot — exercises
            // the multi-binding comment block so we can assert the
            // create-view binding appears alongside detail.
            slug_detail_view(vec![type_badge_cell()], vec![]),
        ]));

        let output = emit_slot_interface(&surface, &slug_feature(), "type_badge");

        assert!(
            output.contains("export interface TypeBadgeProps"),
            "create-view binding should emit the same shape as list/detail; got:\n{output}"
        );
        assert!(output.contains("value: Slug[\"tags\"];"));
        assert!(
            output.contains("admin/slug_create field `tags`"),
            "create-view binding should appear in multi-binding comment block; got:\n{output}"
        );
    }
}
