//! Emits `dist/<target>/lazurite.vite.mjs` — a portable vite-alias
//! bundle that resolves Lazuli runtime + plugin source paths via
//! `import.meta.url` rather than absolute filesystem paths. Apps
//! import this file from their vite.config and spread it into
//! `resolve.alias`, eliminating the `c:/Users/...`-style hardcodes
//! that break CI / cross-developer / cross-OS.
//!
//! The emitter takes:
//!   - `lazuli_path`: where the Lazuli source checkout lives (from
//!     `[lazuli] path = "..."` in Lazurite.toml). When `None`, the
//!     emitter assumes `@lazuli/runtime` is installed as an npm
//!     package and skips Lazuli aliases entirely.
//!   - `plugin_paths`: every active plugin's local path (from
//!     `[plugins]` + `dev.plugin_paths`). Each absolute path is
//!     converted to a path relative to the emitted file's location
//!     so the resulting mjs is portable.
//!   - `dist_dir`: where the emitted file lives, used as the anchor
//!     for the relative-path computation.
//!
//! The emitted mjs uses Node's `import.meta.url` + `fileURLToPath`
//! + `path.resolve` to compute absolute paths at vite-config-load
//! time. Vite accepts the absolute string in its `replacement` slot
//! and resolves imports against it. Apps consume the file as:
//!
//! ```js
//! // vite.config.ts
//! import { lazuliAliases } from './dist/ts-web/lazurite.vite.mjs';
//! export default defineConfig({
//!   resolve: { alias: [...lazuliAliases, ...localAliases] },
//! });
//! ```

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// One plugin entry: namespace + filesystem root + the optional
/// TS subpaths the plugin advertises (today: `<root>/src/index.ts`
/// plus any `./<sub>` entry like `react`).
#[derive(Debug, Clone)]
pub struct PluginAliasEntry {
    pub namespace: String,
    pub root: PathBuf,
    pub subpaths: Vec<String>,
}

/// `.d.mts` companion for the `lazurite.vite.mjs` bundle. Declares
/// the `lazuliAliases` export shape so consumer vite.config files
/// typecheck under `--strict`. Kept structurally minimal — every
/// entry is `{ find: string; replacement: string }` matching vite's
/// `AliasOptions` array-form.
pub fn emit_vite_aliases_dts() -> String {
    let mut s = String::new();
    s.push_str("// Code generated by lazuli; DO NOT EDIT.\n");
    s.push_str("// Type companion for lazurite.vite.mjs.\n");
    s.push_str("export declare const lazuliAliases: ReadonlyArray<{\n");
    s.push_str("  readonly find: string;\n");
    s.push_str("  readonly replacement: string;\n");
    s.push_str("}>;\n");
    s
}

/// Build the mjs source. Returns `None` when there's nothing to
/// emit (no lazuli path AND no local plugins).
pub fn emit_vite_aliases(
    lazuli_path: Option<&Path>,
    plugins: &[PluginAliasEntry],
    dist_dir: &Path,
) -> Option<String> {
    if lazuli_path.is_none() && plugins.is_empty() {
        return None;
    }
    let mut entries: Vec<(String, String)> = Vec::new();

    if let Some(root) = lazuli_path {
        let runtime_src = root.join("runtime").join("ts").join("lazuli").join("src");
        // Specific subpaths FIRST (vite array-form alias matches in
        // declaration order; the most-specific prefix must precede
        // the bare `@lazuli/runtime` mapping).
        entries.push((
            "@lazuli/runtime/react/tanstack".to_owned(),
            relative_url(dist_dir, &runtime_src.join("tanstack-adapter.ts")),
        ));
        entries.push((
            "@lazuli/runtime/react/rhf".to_owned(),
            relative_url(dist_dir, &runtime_src.join("react-rhf.ts")),
        ));
        entries.push((
            "@lazuli/runtime/react".to_owned(),
            relative_url(dist_dir, &runtime_src.join("react.web.ts")),
        ));
        entries.push((
            "@lazuli/runtime".to_owned(),
            relative_url(dist_dir, &runtime_src.join("index.ts")),
        ));
    }

    for plugin in plugins {
        let src_dir = plugin.root.join("src");
        // Subpath entries first.
        for sub in &plugin.subpaths {
            // Each subpath becomes `<namespace>/<sub>` → `<root>/src/<sub>.ts`.
            entries.push((
                format!("{}/{}", plugin.namespace, sub),
                relative_url(dist_dir, &src_dir.join(format!("{sub}.ts"))),
            ));
        }
        // Main entry last (so subpaths match first).
        entries.push((
            plugin.namespace.clone(),
            relative_url(dist_dir, &src_dir.join("index.ts")),
        ));
    }

    let mut s = String::new();
    s.push_str("// Code generated by lazuli; DO NOT EDIT.\n");
    s.push_str("// Portable vite-alias bundle. Each replacement resolves at\n");
    s.push_str("// vite-config-load time via `import.meta.url`; no absolute\n");
    s.push_str("// filesystem paths are baked in, so CI / cross-dev / cross-OS\n");
    s.push_str("// builds work identically.\n");
    s.push_str("import { fileURLToPath } from \"node:url\";\n");
    s.push_str("import { resolve } from \"node:path\";\n\n");
    s.push_str("const __here = fileURLToPath(new URL(\".\", import.meta.url));\n");
    s.push_str("const r = (p) => resolve(__here, p);\n\n");
    s.push_str("export const lazuliAliases = [\n");
    for (find, replacement) in &entries {
        s.push_str(&format!(
            "  {{ find: {:?}, replacement: r({:?}) }},\n",
            find, replacement
        ));
    }
    s.push_str("];\n");

    Some(s)
}

/// Compute a forward-slash relative path FROM `from_dir` TO
/// `to_path`. Used inside the emitted mjs as the argument to
/// `resolve(__here, ...)`. Always uses `/` separators regardless of
/// the host OS — Node's path.resolve accepts both, vite stores the
/// result as-is, and the emitted file is byte-identical on Windows
/// and Linux.
fn relative_url(from_dir: &Path, to_path: &Path) -> String {
    let rel = pathdiff(from_dir, to_path);
    rel.replace('\\', "/")
}

/// Tiny pathdiff implementation. Works on both POSIX absolute
/// paths (`/foo/bar`) and Windows drive paths (`C:/foo/bar` or
/// `C:\foo\bar`). We normalise both sides to forward-slash
/// strings and split on '/' so the drive prefix is just another
/// segment — sidesteps `Path::Components` not recognising
/// forward-slash drive prefixes on Windows.
fn pathdiff(base: &Path, target: &Path) -> String {
    let base_norm = normalize_to_segments(base);
    let target_norm = normalize_to_segments(target);
    let mut common = 0;
    while common < base_norm.len()
        && common < target_norm.len()
        && base_norm[common].eq_ignore_ascii_case(&target_norm[common])
    {
        common += 1;
    }
    let mut out = String::new();
    for _ in 0..(base_norm.len() - common) {
        if !out.is_empty() {
            out.push('/');
        }
        out.push_str("..");
    }
    for segment in &target_norm[common..] {
        if !out.is_empty() {
            out.push('/');
        }
        out.push_str(segment);
    }
    if out.is_empty() {
        out.push('.');
    }
    out
}

fn normalize_to_segments(path: &Path) -> Vec<String> {
    let raw = path.to_string_lossy().replace('\\', "/");
    // Strip Windows UNC verbatim prefix segments (`\\?\C:\...` →
    // `//?/C:/...`) so paths anchored at `c:/` and canonicalised
    // paths anchored at `\\?\C:\` compare equal. Filter empty
    // segments AFTER stripping so we don't break POSIX absolute
    // paths (`/foo/bar` → ["foo", "bar"]).
    let raw_segments: Vec<&str> = raw.split('/').filter(|s| !s.is_empty()).collect();
    // Collapse `..` (pop prior) and `.` (drop) so paths like
    // `c:/Users/lucas/hostpoint/../lazuli` normalise to
    // `c:/Users/lucas/lazuli` — otherwise the segment-by-segment
    // common-prefix walk gets fooled by the literal `..` segment.
    let mut segments: Vec<String> = Vec::with_capacity(raw_segments.len());
    for seg in raw_segments {
        if seg == "?" && segments.is_empty() {
            continue;
        }
        if seg == "." {
            continue;
        }
        if seg == ".." {
            // Only pop if the prior segment is a real directory
            // (don't pop the drive letter / root).
            if let Some(last) = segments.last() {
                if last != ".." && !last.ends_with(':') {
                    segments.pop();
                    continue;
                }
            }
        }
        segments.push(seg.to_owned());
    }
    segments
}

/// Helper to build plugin entries from the manifest's plugin map.
/// `subpaths` is a fixed convention list per plugin (the emitter
/// doesn't probe the plugin's filesystem for now — adding new
/// subpaths means updating this list OR letting the plugin's
/// manifest.toml declare them in a future field).
pub fn plugin_subpath_conventions(namespace: &str) -> Vec<String> {
    // v1 convention: known plugin → known subpaths. Future:
    // `[plugin].ts_subpaths = ["react"]` slot in the plugin's
    // manifest.toml so this list isn't hardcoded.
    match namespace {
        "@lazuli/plugin-viacep" => vec!["react".to_owned()],
        _ => Vec::new(),
    }
}

/// Helper used by tests + by orchestrators that build the
/// PluginAliasEntry list manually.
pub use plugin_subpath_conventions as default_plugin_subpaths;

// dist_dir helper export
pub fn build_plugin_entries(
    plugin_paths: &BTreeMap<String, PathBuf>,
) -> Vec<PluginAliasEntry> {
    plugin_paths
        .iter()
        .map(|(namespace, root)| PluginAliasEntry {
            namespace: namespace.clone(),
            root: root.clone(),
            subpaths: plugin_subpath_conventions(namespace),
        })
        .collect()
}
