//! Cell G1 - `Auth` kind emission. Walks the single auth block declared
//! on a feature and emits the lowered Lazuli Go auth contracts into
//! `<feature>/auth.gen.go`.
//!
//! Proposal references:
//! - Section 3.5 - Auth declaration shape.
//! - Section 11 - runtime boundary discipline. The only runtime package
//!   referenced here is `lazuli.dev/runtime/lazuli/auth`; session TTLs
//!   additionally use stdlib `time` because the current Lazuli Go
//!   `SessionsContract.TTL` field is `time.Duration`.
//!
//! Determinism: there is at most one identity/password/sessions/mfa
//! block, and OAuth providers are sorted by provider then adapter before
//! emission so `oauth: Vec<_>` order cannot perturb generated bytes.

mod contracts;
mod format;
mod routes;

use lazuli_ir::{Auth, AuthOAuthProvider, Feature};

use super::cross_feature::CrossFeatureIndex;
use super::imports::ImportSet;
use super::module::EmitContext;
use super::patterns::{PATTERN_AUTH_LOGIN, emit_pattern_header};
use super::printer::GoPrinter;

use contracts::{emit_identity, emit_mfa, emit_oauth, emit_password, emit_sessions};
use format::{pascal_case, write_section_banner};
use routes::{auth_routes, emit_auth_routes, emit_session_resolver_register, has_auth_routes};

/// Emit `<feature>/auth.gen.go` for a feature, or `None` when the
/// feature declares no auth block.
///
/// ## Examples
///
/// ```ignore
/// let go_src = emit_auth_file("auth.lzi", &feature, "demo", &cross_index, &emit_ctx);
/// ```
pub fn emit_auth_file(
    source_label: &str,
    feature: &Feature,
    module_name: &str,
    cross_index: &CrossFeatureIndex<'_>,
    emit_ctx: &EmitContext<'_>,
) -> Option<String> {
    let auth = feature.auth.as_ref()?;

    // The signature mirrors the other per-kind emitters. Auth contracts
    // carry string references rather than typed field refs, so this
    // slice does not need cross-feature type resolution today.
    let _ = (module_name, cross_index);

    let mut p = GoPrinter::new();
    let mut imports = ImportSet::new();
    imports.add("lazuli.dev/runtime/lazuli/auth");
    if has_auth_routes(auth) {
        imports.add("context");
        imports.add("lazuli.dev/runtime/lazuli");
    }
    if auth.sessions.is_some() {
        imports.add("time");
    }
    // `net/http` is pulled in only when a `auth.sessions.cookie` block
    // declares `same_site` — that is the single cookie axis lowering to an
    // `http.SameSite*Mode` constant. The other axes (name/secure/http_only/
    // domain/path) lower to plain string/bool locals and need no import,
    // so a cookie without `same_site` stays import-clean.
    if auth
        .sessions
        .as_ref()
        .and_then(|s| s.cookie.as_ref())
        .is_some_and(|c| c.same_site.is_some())
    {
        imports.add("net/http");
    }

    p.banner(
        source_label,
        &super::casing::gen_package_name(&feature.name),
    );
    imports.emit(&mut p);
    p.blank();

    emit_auth(&mut p, feature, auth, emit_ctx);

    Some(p.finish())
}

fn emit_auth(p: &mut GoPrinter, feature: &Feature, auth_block: &Auth, emit_ctx: &EmitContext<'_>) {
    // Auth contract vars are PascalCase so cross-package handlers in
    // `<feature>handlers` can reference them via `<feature>gen.AuthPassword`,
    // `<feature>gen.AuthSessions`, etc. (Go exports start with an uppercase
    // first letter.)
    let feature_pascal = pascal_case(&feature.name);
    let identity_var = format!("{feature_pascal}AuthIdentity");

    write_section_banner(
        p,
        &[
            format!("Auth: {}", feature.name),
            "  auth identity/password/sessions/mfa/oauth".to_owned(),
        ],
    );

    emit_pattern_header(p, PATTERN_AUTH_LOGIN);
    let line_directive_emitted = emit_ctx.emit_line_directive(p, auth_block.span_ref);
    emit_identity(p, &identity_var, auth_block);

    if let Some(password) = &auth_block.password {
        p.blank();
        emit_password(p, &feature_pascal, &identity_var, password);
    }

    if let Some(sessions) = &auth_block.sessions {
        p.blank();
        emit_sessions(p, &feature_pascal, sessions);
    }

    let mut oauth: Vec<&AuthOAuthProvider> = auth_block.oauth.iter().collect();
    oauth.sort_by(|a, b| {
        a.provider
            .cmp(&b.provider)
            .then_with(|| a.adapter.cmp(&b.adapter))
    });
    for provider in oauth {
        p.blank();
        emit_oauth(p, &feature_pascal, provider);
    }

    if let Some(mfa) = &auth_block.mfa {
        p.blank();
        emit_mfa(p, &feature_pascal, mfa);
    }

    let routes = auth_routes(auth_block);
    if !routes.is_empty() {
        p.blank();
        emit_auth_routes(p, feature, &routes, emit_ctx);
    }
    if let Some(sessions) = auth_block.sessions.as_ref() {
        p.blank();
        emit_session_resolver_register(p, feature, &feature_pascal, sessions);
    }
    emit_ctx.reset_line_directive(p, line_directive_emitted);
}

#[cfg(test)]
mod tests {
    use super::*;
    use lazuli_ir::{
        AppManifest, AuthIdentity, AuthMfa, AuthOAuthProvider, AuthPassword, AuthSessions,
        Defaults, FieldRef, Module, Policies, QualifiedName, SessionCookie,
    };

    fn emit(feature: &Feature) -> Option<String> {
        let module = Module {
            workspace: None,
            contracts: Vec::new(),
            app: Some(minimal_app()),
            registry: None,
            profiles: Vec::new(),
            design: None,
            rbac: None,
            features: vec![feature.clone()],
        };
        let index = CrossFeatureIndex::build(&module);
        let emit_ctx = EmitContext::no_source("customer/auth.gen.go");
        emit_auth_file("examples/x.lzi", feature, "lazuli/test", &index, &emit_ctx)
    }

    fn minimal_app() -> AppManifest {
        AppManifest {
            name: "test".to_owned(),
            title: None,
            version: None,
            lazuli_version: None,
            targets: Vec::new(),
            default_locale: None,
            default_timezone: None,
            auth_failed_redirect: None,
            not_found: None,
            error_pages: Vec::new(),
            uses: Vec::new(),
            packs: Vec::new(),
            bindings: Vec::new(),
            architecture: None,
            services: Vec::new(),
            communication: None,
            environments: Vec::new(),
            urls: Vec::new(),
            cors: None,
            headers: None,
            cookie: None,
            proxy: None,
            limits: None,
            env: Vec::new(),
            integrations: Vec::new(),
            capabilities: Vec::new(),
            runtime: Vec::new(),
            deploy: None,
            logging: None,
            tracing: None,
            observability: None,
            locale: None,
            encryption_bindings: Vec::new(),
            route_guard: None,
            actor_query: None,
            span_ref: None,
        }
    }

    fn base_feature(name: &str) -> Feature {
        Feature {
            name: name.to_owned(),
            purpose: None,
            non_goals: Vec::new(),
            context_path: None,
            knowledge: None,
            defaults: Defaults {
                tenancy: None,
                timestamps: false,
                policy: None,
            },
            uses: Vec::new(),
            uses_spans: Vec::new(),
            uses_versions: Vec::new(),
            requirements: Vec::new(),
            enums: Vec::new(),
            resources: Vec::new(),
            events: Vec::new(),
            rules: Vec::new(),
            policies: Policies {
                categories: Vec::new(),
                fields: Vec::new(),
                span_ref: None,
            },
            errors: None,
            commands: Vec::new(),
            apis: Vec::new(),
            records: Vec::new(),
            queries: Vec::new(),
            resume_routers: Vec::new(),
            workflows: Vec::new(),
            jobs: Vec::new(),
            webhooks: Vec::new(),
            notifications: Vec::new(),
            event_groups: Vec::new(),
            tenant_migrations: Vec::new(),
            translation: None,
            pollers: vec![],
            auth: None,
            surfaces: Vec::new(),
            extensions: Vec::new(),
            escape_routes: Vec::new(),
            agents: Vec::new(),
            reports: Vec::new(),
            channels: Vec::new(),
            caches: Vec::new(),
            aggregates: vec![],
            mcp_servers: vec![],
            previous_names: Vec::new(),
            span_ref: None,
            synth_origins: std::collections::BTreeMap::new(),
        }
    }

    fn qname(name: &str) -> QualifiedName {
        QualifiedName {
            feature: None,
            name: name.to_owned(),
        }
    }

    fn identity(resource: &str, field: &str) -> AuthIdentity {
        AuthIdentity {
            field: FieldRef {
                resource: qname(resource),
                field: field.to_owned(),
            },
            public_contract: None,
        }
    }

    fn auth_with_identity(resource: &str, field: &str) -> Auth {
        Auth {
            identity: identity(resource, field),
            password: None,
            sessions: None,
            mfa: None,
            oauth: Vec::new(),
            span_ref: None,
        }
    }

    #[test]
    fn feature_without_auth_returns_none() {
        let feature = base_feature("customer");
        assert!(emit(&feature).is_none());
    }

    #[test]
    fn full_auth_block_emits_runtime_contracts() {
        let mut feature = base_feature("customer_auth");
        let mut auth = auth_with_identity("Customer", "email");
        auth.password = Some(AuthPassword {
            algorithm: "argon2id".to_owned(),
            hash: "@fn.hash_customer_password".to_owned(),
            verify: "@fn.verify_customer_password".to_owned(),
            rate_limit: Some(lazuli_ir::RateLimitSpec::from_default(
                "5 per 10 minutes".to_owned(),
            )),
        });
        auth.sessions = Some(AuthSessions {
            resource: qname("CustomerSession"),
            ttl: "7 days".to_owned(),
            refresh: false,
            extra_columns: vec![],
            access_ttl: None,
            rotation: None,
            cookie: None,
        });
        auth.mfa = Some(AuthMfa {
            method: "totp".to_owned(),
            enroll: "@fn.enroll_customer_totp".to_owned(),
            verify: "@validator.verify_customer_totp".to_owned(),
            adapter: None,
        });
        auth.oauth.push(AuthOAuthProvider {
            provider: "google".to_owned(),
            adapter: "@adapter.google_oauth".to_owned(),
        });
        feature.auth = Some(auth);

        let out = emit(&feature).expect("must emit");
        assert!(out.contains("package customer_authgen"));
        assert!(out.contains("\"time\""));
        assert!(out.contains("\"lazuli.dev/runtime/lazuli\""));
        assert!(out.contains("\"lazuli.dev/runtime/lazuli/auth\""));
        assert!(out.contains(
            "var CustomerAuthAuthIdentity = auth.FieldRef{Resource: \"Customer\", Field: \"email\"}"
        ));
        assert!(out.contains("var CustomerAuthAuthPassword = auth.PasswordContract{"));
        assert!(out.contains("Identity:  CustomerAuthAuthIdentity,"));
        assert!(out.contains("Algorithm: auth.AlgoArgon2id,"));
        assert!(out.contains("HashFn:    \"@fn.hash_customer_password\","));
        assert!(out.contains("RateLimit: \"5 per 10 minutes\","));
        assert!(out.contains("var CustomerAuthAuthSessions = auth.SessionsContract{"));
        assert!(out.contains("TTL:      7 * 24 * time.Hour,"));
        assert!(out.contains("Refresh:  false,"));
        assert!(out.contains("var CustomerAuthAuthOAuthGoogle = auth.OAuthContract{"));
        assert!(out.contains("AdapterRef: \"@adapter.google_oauth\","));
        assert!(out.contains("var CustomerAuthAuthMfa = auth.MfaContract{"));
        assert!(out.contains("Method:   auth.MfaMethodTOTP,"));
        assert!(out.contains("func init() {"));
        assert!(out.contains("Name:    \"customer_auth.auth.login\","));
        assert!(out.contains("Method:  lazuli.MethodPost,"));
        assert!(out.contains("Path:    \"/auth/login\","));
        assert!(out.contains("Handler: auth.LoginHandler,"));
        assert!(out.contains("Path:    \"/auth/signup\","));
        assert!(out.contains("Handler: auth.SignupHandler,"));
        assert!(out.contains("Path:    \"/auth/logout\","));
        assert!(out.contains("Handler: auth.LogoutHandler,"));
        assert!(out.contains("Name:    \"customer_auth.auth.oauth.google\","));
        assert!(out.contains("Method:  lazuli.MethodGet,"));
        assert!(out.contains("Path:    \"/auth/oauth/google\","));
        assert!(out.contains("Handler: auth.OAuthHandler,"));
        assert!(out.contains("Path:    \"/auth/oauth/google/callback\","));
        assert!(out.contains("Handler: auth.OAuthCallbackHandler,"));
        assert!(out.contains("// TODO(runtime): handler name verification"));
        // Session resolver wire — production middleware lookup.
        assert!(out.contains("// Auth session resolver: customer_auth"));
        assert!(out.contains("auth.RegisterSessionContract(CustomerAuthAuthSessions)"));
    }

    #[test]
    fn identity_only_auth_skips_optional_contracts() {
        let mut feature = base_feature("portal");
        feature.auth = Some(auth_with_identity("User", "email"));
        let out = emit(&feature).expect("must emit");
        assert!(out.contains("var PortalAuthIdentity = auth.FieldRef"));
        assert!(!out.contains("PasswordContract"));
        assert!(!out.contains("SessionsContract"));
        assert!(!out.contains("MfaContract"));
        assert!(!out.contains("OAuthContract"));
        assert!(!out.contains("RegisterApi"));
        assert!(!out.contains("RegisterSessionContract"));
        assert!(!out.contains("\"lazuli.dev/runtime/lazuli\""));
        assert!(!out.contains("\"time\""));
    }

    #[test]
    fn oauth_providers_are_sorted_for_determinism() {
        let mut feature = base_feature("customer");
        let mut auth = auth_with_identity("Customer", "email");
        auth.oauth.push(AuthOAuthProvider {
            provider: "microsoft".to_owned(),
            adapter: "@adapter.microsoft_oauth".to_owned(),
        });
        auth.oauth.push(AuthOAuthProvider {
            provider: "google".to_owned(),
            adapter: "@adapter.google_oauth".to_owned(),
        });
        feature.auth = Some(auth);

        let a = emit(&feature).expect("must emit");
        let b = emit(&feature).expect("must emit");
        assert_eq!(a, b);
        let google_pos = a.find("AuthOAuthGoogle").expect("google contract");
        let microsoft_pos = a.find("AuthOAuthMicrosoft").expect("microsoft contract");
        assert!(google_pos < microsoft_pos);
        let google_route_pos = a
            .find("Name:    \"customer.auth.oauth.google\",")
            .expect("google route");
        let microsoft_route_pos = a
            .find("Name:    \"customer.auth.oauth.microsoft\",")
            .expect("microsoft route");
        assert!(google_route_pos < microsoft_route_pos);
        assert!(a.contains("Path:    \"/auth/oauth/google\","));
        assert!(a.contains("Path:    \"/auth/oauth/google/callback\","));
        assert!(a.contains("Path:    \"/auth/oauth/microsoft\","));
        assert!(a.contains("Path:    \"/auth/oauth/microsoft/callback\","));
    }

    #[test]
    fn sessions_only_auth_mounts_logout_route() {
        let mut feature = base_feature("portal");
        let mut auth = auth_with_identity("User", "email");
        auth.sessions = Some(AuthSessions {
            resource: qname("UserSession"),
            ttl: "1 hour".to_owned(),
            refresh: true,
            extra_columns: vec![],
            access_ttl: None,
            rotation: None,
            cookie: None,
        });
        feature.auth = Some(auth);

        let out = emit(&feature).expect("must emit");
        assert!(out.contains("Name:    \"portal.auth.logout\","));
        assert!(out.contains("Path:    \"/auth/logout\","));
        assert!(out.contains("Handler: auth.LogoutHandler,"));
        assert!(!out.contains("portal.auth.login"));
        assert!(!out.contains("portal.auth.signup"));
        // Session contract wired to the runtime resolver.
        assert!(out.contains("auth.RegisterSessionContract(PortalAuthSessions)"));
    }

    #[test]
    fn non_catalog_values_still_emit_go_valid_conversions() {
        let mut feature = base_feature("customer");
        let mut auth = auth_with_identity("Customer", "email");
        auth.password = Some(AuthPassword {
            algorithm: "scrypt".to_owned(),
            hash: "@fn.hash".to_owned(),
            verify: "@fn.verify".to_owned(),
            rate_limit: None,
        });
        auth.mfa = Some(AuthMfa {
            method: "sms".to_owned(),
            enroll: "@fn.enroll_sms".to_owned(),
            verify: "@fn.verify_sms".to_owned(),
            adapter: Some("@adapter.sms".to_owned()),
        });
        auth.sessions = Some(AuthSessions {
            resource: qname("CustomerSession"),
            ttl: "soon".to_owned(),
            refresh: true,
            extra_columns: vec![],
            access_ttl: None,
            rotation: None,
            cookie: None,
        });
        feature.auth = Some(auth);

        let out = emit(&feature).expect("must emit");
        assert!(out.contains("Algorithm: auth.PasswordAlgorithm(\"scrypt\"),"));
        assert!(out.contains("Method:     auth.MfaMethod(\"sms\"),"));
        assert!(out.contains("AdapterRef: \"@adapter.sms\","));
        assert!(out.contains("TTL:      0 * time.Second,"));
        assert!(out.contains("// TODO(auth-ttl): unsupported AuthSessions.ttl literal \"soon\""));
    }

    // Cookie-emission cases live in a sibling file to keep this module
    // under the 500-LOC Rails budget. `include!` pastes them into this
    // `mod tests` body so they share the helpers + `SessionCookie` import.
    include!("cookie_tests.rs");
}
