//! End-to-end test for `emit_api_file`. Kept as a sibling so it stays at
//! the `emitter::api::feature_emit_tests::*` path, in parity with the
//! `emitter::webhook::feature_emit_tests::*` shape next door.

#![cfg(test)]

use super::*;
use lazuli_ir::{
    Api, BuiltinType, Defaults, HttpMethod, Module, PathRef, Policies, PolicyRef, RateLimitSpec,
    TypeRef,
};

fn feature_with_api() -> Feature {
    Feature {
        name: "catalog".to_owned(),
        purpose: None,
        non_goals: Vec::new(),
        context_path: None,
        knowledge: None,
        defaults: Defaults {
            tenancy: None,
            timestamps: false,
            policy: None,
            rate_limit: None,
            audit: None,
        },
        uses: Vec::new(),
        uses_spans: Vec::new(),
        uses_versions: Vec::new(),
        requirements: Vec::new(),
        enums: Vec::new(),
        resources: Vec::new(),
        events: Vec::new(),
        rules: Vec::new(),
        policies: Policies {
            categories: Vec::new(),
            fields: Vec::new(),
            span_ref: None,
        },
        errors: None,
        commands: Vec::new(),
        apis: vec![Api {
            name: "list_products".to_owned(),
            method: HttpMethod::Get,
            path: "/api/products/{category_id}".to_owned(),
            policy: PolicyRef::Local("read".to_owned()),
            policy_expr: None,
            policy_when_denied: None,
            rate_limit: Some(RateLimitSpec::from_default(
                "30 per minute per user".to_owned(),
            )),
            output: TypeRef::Many(Box::new(TypeRef::Builtin(BuiltinType::Text))),
            handler: PathRef::authored("./api/list_products.go"),
            locale_negotiate: None,
            deprecated: None,
            span_ref: None,
        }],
        records: Vec::new(),
        queries: Vec::new(),
        resume_routers: Vec::new(),
        workflows: Vec::new(),
        jobs: Vec::new(),
        webhooks: Vec::new(),
        notifications: Vec::new(),
        event_groups: Vec::new(),
        tenant_migrations: Vec::new(),
        translation: None,
        pollers: vec![],
        auth: None,
        surfaces: Vec::new(),
        extensions: Vec::new(),
        escape_routes: Vec::new(),
        agents: Vec::new(),
        reports: Vec::new(),
        channels: Vec::new(),
        caches: Vec::new(),
        aggregates: vec![],
        mcp_servers: vec![],
        previous_names: Vec::new(),
        span_ref: None,
        synth_origins: std::collections::BTreeMap::new(),
    }
}

#[test]
fn feature_emit_api_file_outputs_package_and_endpoint_contract() {
    let feature = feature_with_api();
    let module = Module {
        workspace: None,
        contracts: Vec::new(),
        app: None,
        registry: None,
        profiles: Vec::new(),
        design: None,
        rbac: None,
        features: vec![feature],
    };
    let cross_index = CrossFeatureIndex::build(&module);
    let emit_ctx = EmitContext::no_source("catalog/api.gen.go");

    let out = emit_api_file(
        "features/catalog/catalog.lzi",
        &module.features[0],
        "lazuli/test",
        &cross_index,
        &emit_ctx,
    )
    .expect("feature with one API must emit api.gen.go");

    assert!(!out.is_empty());
    assert!(out.contains("// Code generated by lazuli; DO NOT EDIT."));
    assert!(out.contains("package cataloggen"));
    assert!(out.contains("type ListProductsApiArgs struct {"));
    assert!(out.contains("CategoryID lazuli.ID `json:\"category_id\"`"));
    assert!(out.contains("var listProductsApi = lazuli.Api[ListProductsApiArgs, []string]{"));
    assert!(out.contains("Method:    lazuli.MethodGet,"));
    assert!(out.contains("RateLimit: lazuli.RateLimit{Default: \"30 per minute per user\"},"));
}
