//! Sub-file of the inline LSP test suite — see `mod.rs` for the
//! shared preamble and helpers. Tests are grouped by line-range
//! buckets only; each bucket is ≤ 500 LOC so `clippy` and
//! `rust-analyzer` stay responsive.
#![allow(unused_imports)]
use super::*;

#[test]
fn canonical_warns_for_incomplete_crypto_contracts() {
    let source = r#"
feature auth
  purpose "Auth"

  domain
    resource Session
      legacy_secret: @cap.Secret required
      refresh_token_hash: @cap.Hashed required
      api_key: @cap.Encrypted required
      reset_token: @cap.Token(ttl:1h,single_use:true) required
"#;

    let diagnostics = diagnostics_for(source);
    let messages: Vec<_> = diagnostics
        .iter()
        .map(|diagnostic| diagnostic.message.as_str())
        .collect();

    assert!(
        messages
            .iter()
            .any(|message| { message.contains("`@cap.Secret` is legacy") })
    );
    assert!(
        messages
            .iter()
            .any(|message| { message.contains("`@cap.Hashed` should declare `algorithm:<name>`") })
    );
    assert!(
        messages.iter().any(|message| {
            message.contains("`@cap.Encrypted` should declare `key:@key.<scope>`")
        })
    );
    assert!(
        messages
            .iter()
            .any(|message| { message.contains("`@cap.Token` should declare `store:hashed`") })
    );
}

#[test]
fn canonical_warns_for_invalid_crypto_capability_arguments() {
    let source = r#"
feature auth
  purpose "Auth"

  domain
    resource Session
      refresh_token_hash: @cap.Hashed(algorithm:md5,pepper:true) required
      api_key: @cap.Encrypted(key:tenant) required
      private_note: @cap.E2ee(key:tenant) optional
      reset_token: @cap.Token(ttl:"one hour",single_use:yes,store:plain) required
"#;

    let diagnostics = diagnostics_for(source);
    let messages: Vec<_> = diagnostics
        .iter()
        .map(|diagnostic| diagnostic.message.as_str())
        .collect();

    assert!(messages.iter().any(|message| {
        message.contains("canonical v0 hash algorithms are `argon2id` or `bcrypt`")
    }));
    assert!(messages.iter().any(|message| {
        message.contains("@cap.Hashed only accepts canonical arguments: algorithm")
    }));
    assert!(messages.iter().any(|message| {
        message.contains("encryption capability keys should use `key:@key.<scope>`")
    }));
    assert!(
        messages
            .iter()
            .any(|message| { message.contains("`@cap.Token` ttl should use `ttl:<duration>`") })
    );
    assert!(messages.iter().any(|message| {
        message.contains("`@cap.Token` single_use should be `true` or `false`")
    }));
    assert!(messages.iter().any(|message| {
        message.contains("`@cap.Token` store should be `hashed` in canonical v0")
    }));
}

#[test]
fn canonical_warns_for_authored_summary() {
    let source = r#"
feature customer
  purpose "Customers"

  summary
    resources: Customer
"#;

    let diagnostics = diagnostics_for(source);

    assert!(diagnostics.iter().any(|diagnostic| {
        diagnostic
            .message
            .contains("`summary` is generated by `lazuli inspect --expand=summary`")
    }));
}

#[test]
fn canonical_warns_for_env_reference_without_schema() {
    let source = r#"
feature integration
  purpose "Integration"

  webhook inbound
    path "/webhooks/inbound"
    verify hmac sha256
      secret env.INBOUND_WEBHOOK_SECRET
      header "X-Signature"
    idempotency by payload.id
"#;

    let diagnostics = diagnostics_for(source);

    assert!(diagnostics.iter().any(|diagnostic| {
        diagnostic
            .message
            .contains("environment reference `env.INBOUND_WEBHOOK_SECRET`")
    }));
}

#[test]
fn canonical_accepts_declared_env_reference() {
    let source = r#"
env
  group webhooks
    server INBOUND_WEBHOOK_SECRET: Secret required in production
  group public_clients
    client PUBLIC_APP_URL: Url required
    mobile EXPO_PUBLIC_API_URL: Url required

feature integration
  purpose "Integration"

  webhook inbound
    path "/webhooks/inbound"
    verify hmac sha256
      secret env.INBOUND_WEBHOOK_SECRET
      header "X-Signature"
    idempotency by payload.id
"#;

    let diagnostics = diagnostics_for(source);

    assert!(!diagnostics.iter().any(|diagnostic| {
        diagnostic
            .message
            .contains("environment reference `env.INBOUND_WEBHOOK_SECRET`")
    }));
}

#[test]
fn canonical_warns_for_incomplete_api_contract() {
    let source = r#"
feature customer
  purpose "Customers"

  api stream_summary
    method POST
    path "/api/customers/:id/summary"
    output stream Text
    policy @policy.read
"#;

    let diagnostics = diagnostics_for(source);
    let messages: Vec<_> = diagnostics
        .iter()
        .map(|diagnostic| diagnostic.message.as_str())
        .collect();

    assert!(messages.iter().any(|message| message.contains("handler")));
    assert!(
        messages
            .iter()
            .any(|message| { message.contains("api path parameter `id` should be declared") })
    );
}

#[test]
fn canonical_warns_for_incomplete_cache_contract() {
    let source = r#"
feature customer
  purpose "Customers"

  domain
    resource Customer

    query.list list
      cache
        key customer.list(params)
"#;

    let diagnostics = diagnostics_for(source);

    assert!(diagnostics.iter().any(|diagnostic| {
        diagnostic
            .message
            .contains("query cache contracts should declare ttl")
    }));
}

#[test]
fn canonical_warns_for_invalid_error_contract() {
    let source = r#"
feature customer
  purpose "Customers"

  errors
    default leak
    expose client 4xx stack

  command archive
    policy @policy.update
    rate_limit "30 per minute per user"
    error CustomerGone status 900 expose stack
    deletes Customer
"#;

    let diagnostics = diagnostics_for(source);
    let messages: Vec<_> = diagnostics
        .iter()
        .map(|diagnostic| diagnostic.message.as_str())
        .collect();

    assert!(
        messages
            .iter()
            .any(|message| { message.contains("feature error defaults use `default hide`") })
    );
    assert!(
        messages
            .iter()
            .any(|message| { message.contains("error exposure uses `expose client") })
    );
    assert!(
        messages
            .iter()
            .any(|message| message.contains("HTTP status code from 100 to 599"))
    );
}

#[test]
fn lzx_accepts_experience_and_platform_surface_layers() {
    let experience = r#"
experience customer
  imports customer

  view list
    source customer.query.list
    action create -> customer.command.create
"#;

    let surface = r#"
surface customer web
  uses experience customer

  audience admin
    view list Table
      columns name, email, tier
"#;

    assert!(diagnostics_for(experience).is_empty());
    assert!(diagnostics_for(surface).is_empty());
}

#[test]
fn lzx_warns_for_untyped_top_level_route_params() {
    let source = r#"
route customer_detail
  path "/customers/:id"
  to customer.view.detail(id: route.id)
  surface customer web
  audience admin
"#;

    let diagnostics = diagnostics_for(source);

    assert!(diagnostics.iter().any(|diagnostic| {
        diagnostic
            .message
            .contains("route path parameter `id` should be declared")
    }));
}

#[test]
fn lzx_accepts_typed_top_level_routes() {
    let source = r#"
app AcmeCRM
  title "Acme CRM"
  targets
    backend go
    web react
  uses customer

route customer_detail
  path "/customers/:id"
  route id: Customer.ID
  to customer.view.detail(id: route.id)
  surface customer web
  audience admin
"#;

    assert!(diagnostics_for(source).is_empty());
}

#[test]
fn derived_field_accepts_expression() {
    let source = r#"
feature customer
  domain
    resource Customer
      score: Integer = 0
      is_high_value: Boolean derived from score > 80
"#;
    assert!(diagnostics_for(source).is_empty());
}

#[test]
fn derived_field_rejects_default_or_requiredness() {
    let bad_default = r#"
feature customer
  domain
    resource Customer
      tier: Text derived from compute_tier(score) = "bronze"
"#;
    let diagnostics = diagnostics_for(bad_default);
    assert!(
        diagnostics
            .iter()
            .any(|d| d.message.contains("must not declare `default`"))
    );

    let bad_required = r#"
feature customer
  domain
    resource Customer
      tier: Text required derived from compute_tier(score)
"#;
    let diagnostics = diagnostics_for(bad_required);
    assert!(
        diagnostics
            .iter()
            .any(|d| d.message.contains("must not declare `required`"))
    );
}

#[test]
fn derived_field_requires_expression() {
    let source = r#"
feature customer
  domain
    resource Customer
      tier: Text derived from
"#;
    let diagnostics = diagnostics_for(source);
    assert!(
        diagnostics
            .iter()
            .any(|d| d.message.contains("requires an expression"))
    );
}

#[test]
fn has_many_accepts_canonical_collections() {
    let source = r#"
feature customer
  domain
    resource Customer
      has_many notes: CustomerNote inverse customer
      has_many tags: CustomerTag
"#;
    assert!(diagnostics_for(source).is_empty());
}

#[test]
fn has_many_rejects_unexpected_tail_or_missing_inverse_field() {
    let bad_tail = r#"
feature customer
  domain
    resource Customer
      has_many notes: CustomerNote required
"#;
    assert!(
        diagnostics_for(bad_tail)
            .iter()
            .any(|d| d.message.contains("Only `inverse <field>` is allowed"))
    );

    let bad_inverse = r#"
feature customer
  domain
    resource Customer
      has_many notes: CustomerNote inverse
"#;
    assert!(
        diagnostics_for(bad_inverse)
            .iter()
            .any(|d| d.message.contains("`inverse` requires a field name"))
    );
}

#[test]
fn agent_accepts_canonical_declaration() {
    let source = r#"
feature customer
  policies
    read: @scope.same_org

  agent summarize_customer
    input
      customer_id: ID required
    context customer.query.by_id(id: input.customer_id)
    policy @policy.read
    rate_limit "20 per hour per user"
    output stream Text
    model @llm.default
    prompt "./prompts/summarize_customer.md"
"#;
    let diagnostics = diagnostics_for(source);
    assert!(
        diagnostics.is_empty(),
        "expected no diagnostics, got: {:#?}",
        diagnostics
            .iter()
            .map(|d| (d.message.clone(), d.code.clone()))
            .collect::<Vec<_>>()
    );
}

#[test]
fn agent_rejects_missing_required_children() {
    let source = r#"
feature customer
  agent summarize_customer
    input
      prompt: Text required
"#;
    let diagnostics = diagnostics_for(source);
    let messages: Vec<_> = diagnostics.iter().map(|d| d.message.as_str()).collect();
    assert!(
        messages
            .iter()
            .any(|m| m.contains("`policy @policy.<name>`"))
    );
    assert!(
        messages
            .iter()
            .any(|m| m.contains("`output [stream] <Type>`"))
    );
    assert!(messages.iter().any(|m| m.contains("`model @llm.<name>`")));
    assert!(messages.iter().any(|m| m.contains("prompt")));
}

