//! Higher-level wiring tests — determinism, feature entry-point integration,
//! gate annotations (PG.C.2), and per-branch emit-binding dispatch tables.

use super::super::*;
use super::{base_feature, base_webhook, emit, hmac_verify, module_with_feature};
use lazuli_ir::{BackoffStrategy, RetryPolicy};

#[test]
fn deterministic_across_runs_and_sorts_by_name() {
    let mut feature = base_feature("payments");
    let mut zebra = base_webhook("zebra");
    zebra.structured_verify = Some(hmac_verify());
    let mut alpha = base_webhook("alpha");
    alpha.structured_verify = Some(hmac_verify());
    feature.webhooks.push(zebra);
    feature.webhooks.push(alpha);

    let a = emit(&feature).expect("must emit");
    let b = emit(&feature).expect("must emit");
    assert_eq!(a, b);

    let alpha_pos = a.find("Webhook: payments.alpha").expect("alpha banner");
    let zebra_pos = a.find("Webhook: payments.zebra").expect("zebra banner");
    assert!(alpha_pos < zebra_pos);
}

#[test]
fn feature_emit_entry_point_emits_representative_webhook_file() {
    let mut feature = base_feature("payments");
    let mut webhook = base_webhook("mercadopago_callback");
    webhook.route = "/webhooks/mercadopago".to_owned();
    webhook.structured_verify = Some(hmac_verify());
    webhook.retry = Some(RetryPolicy {
        count: 3,
        backoff: BackoffStrategy::Fixed,
    });
    feature.webhooks.push(webhook);

    let out = emit(&feature).expect("feature with webhook must emit webhook.gen.go");
    assert!(!out.is_empty());
    assert!(out.contains("// Code generated by lazuli; DO NOT EDIT."));
    assert!(out.contains("package paymentsgen"));
    assert!(out.contains("\"lazuli.dev/runtime/lazuli/webhooks\""));
    assert!(out.contains("\"lazuli.dev/runtime/lazuli/jobs\""));
    assert!(out.contains("var MercadopagoCallbackWebhook = webhooks.WebhookContract{"));
    assert!(out.contains("Route:       \"/webhooks/mercadopago\","));
    assert!(out.contains("HandlerPath: \"./webhooks/mercadopago_callback.go\","));
    assert!(out.contains("Retry:       &jobs.RetryPolicy{Count: 3, Backoff: jobs.BackoffFixed},"));
}

#[test]
fn gated_webhook_emits_real_prelude_field_and_billing_imports() {
    // PG.C.2 — gated webhooks lift the wave-4 comment
    // annotation into a real `Prelude: []billing.GateRef{...}`
    // field on the WebhookContract; the receiver consults it
    // via the runner billing registers at init.
    let mut feature = base_feature("billing");
    let mut webhook = base_webhook("payment_callback");
    webhook.route = "/webhooks/payment".to_owned();
    webhook.structured_verify = Some(hmac_verify());
    feature.webhooks.push(webhook);

    let mut gates: std::collections::BTreeMap<String, Vec<lazuli_ir::Gate>> =
        std::collections::BTreeMap::new();
    gates.insert(
        "billing/webhook:payment_callback".to_owned(),
        vec![
            lazuli_ir::Gate::Behind {
                feature: "payment_webhooks".to_owned(),
            },
            lazuli_ir::Gate::Quota {
                limit: "webhooks_per_month".to_owned(),
            },
        ],
    );
    let module = module_with_feature(feature);
    let index = CrossFeatureIndex::build(&module);
    let emit_ctx =
        EmitContext::for_feature(None, "billing-app", "billing", "billing/webhook.gen.go")
            .with_gates(Some(&gates));
    let out = emit_webhook_file(
        "examples/billing.lzi",
        &module.features[0],
        "billing-app",
        &index,
        &emit_ctx,
    )
    .expect("must emit");

    assert!(
        out.contains("\"lazuli.dev/runtime/lazuli/billing\""),
        "billing import missing:\n{out}"
    );
    assert!(
        out.contains("\"billing-app/plan\""),
        "plan import missing:\n{out}"
    );
    assert!(
        out.contains("Prelude: []billing.GateRef{"),
        "Prelude field missing:\n{out}"
    );
    assert!(
        out.contains("{Kind: billing.GateBehind, Name: \"payment_webhooks\"},"),
        "behind-gate row missing:\n{out}"
    );
    assert!(
        out.contains("{Kind: billing.GateQuota, Name: \"webhooks_per_month\"},"),
        "quota-gate row missing:\n{out}"
    );
}

#[test]
fn ungated_webhook_emits_no_prelude_or_billing_import() {
    let mut feature = base_feature("payments");
    let mut webhook = base_webhook("callback");
    webhook.structured_verify = Some(hmac_verify());
    feature.webhooks.push(webhook);
    let out = emit(&feature).expect("must emit");
    assert!(!out.contains("Prelude:"), "no Prelude when no gates");
    assert!(
        !out.contains("\"lazuli.dev/runtime/lazuli/billing\""),
        "no billing import when no gates"
    );
}

/// B5 framework gap 2 — flat `emits` list (no `when` predicates)
/// leaves the legacy `Emits []string{...}` shape on the contract
/// and does NOT emit a `EmitBindings:` slot.
#[test]
fn flat_emits_keeps_legacy_string_slice_shape() {
    let mut feature = base_feature("payments");
    let mut webhook = base_webhook("mp_payment");
    webhook.structured_verify = Some(hmac_verify());
    webhook.emits = vec!["charge_confirmed".to_owned(), "charge_failed".to_owned()];
    // emit_predicates intentionally empty — flat shape.
    feature.webhooks.push(webhook);
    let out = emit(&feature).expect("must emit");
    assert!(
        out.contains("Emits:"),
        "flat emits must still emit the string slice"
    );
    assert!(!out.contains("EmitBindings:"));
}

/// B5 framework gap 2 — per-branch `emits ... when <predicate>`
/// writes an `EmitBindings` dispatch table on the contract.
#[test]
fn per_branch_emits_emits_dispatch_table_on_contract() {
    let mut feature = base_feature("payments");
    let mut webhook = base_webhook("mp_payment");
    webhook.structured_verify = Some(hmac_verify());
    webhook.emits = vec![
        "charge_confirmed".to_owned(),
        "charge_failed".to_owned(),
        "mp_status_received".to_owned(),
    ];
    webhook.emit_predicates = vec![
        Some(lazuli_ir::EmitPredicate {
            raw: "payload.status = \"approved\"".to_owned(),
            kind: lazuli_ir::EmitPredicateKind::Equals {
                path: "payload.status".to_owned(),
                literal: "approved".to_owned(),
            },
            span_ref: None,
        }),
        Some(lazuli_ir::EmitPredicate {
            raw: "payload.status in (\"rejected\", \"cancelled\")".to_owned(),
            kind: lazuli_ir::EmitPredicateKind::In {
                path: "payload.status".to_owned(),
                literals: vec!["rejected".to_owned(), "cancelled".to_owned()],
            },
            span_ref: None,
        }),
        None,
    ];
    feature.webhooks.push(webhook);
    let out = emit(&feature).expect("must emit");
    assert!(out.contains("Emits:"));
    assert!(
        out.contains("EmitBindings:"),
        "dispatch table missing:\n{}",
        out
    );
    assert!(out.contains("webhooks.EmitPredicateEquals"));
    assert!(out.contains("Path: \"payload.status\""));
    assert!(out.contains("Literal: \"approved\""));
    assert!(out.contains("webhooks.EmitPredicateIn"));
    assert!(out.contains("Literals: []string{\"rejected\", \"cancelled\"}"));
    assert!(out.contains("webhooks.EmitPredicateNone"));
    assert!(out.contains("Event: \"mp_status_received\""));
}
