//! Registry `ALL` section 9/11 (SPEC-19 split; concatenated in `registry::ALL`).
#![allow(clippy::all, unused_imports)]

use super::super::builders::*;
use super::super::facets::*;
use crate::{CapabilitySpec, Context, DiagnosticFacet, SemanticToken, Sigil, Surface};

pub(crate) const ROWS: &[CapabilitySpec] = &[
    lzx(
        "columns",
        Context::SurfaceView,
        SECTION,
        "List column projection.",
    ),
    lzx(
        "fields",
        Context::SurfaceView,
        SECTION,
        "Form/detail field block.",
    ),
    lzx(
        "sections",
        Context::SurfaceView,
        SECTION,
        "Detail section block.",
    ),
    lzx(
        "cells",
        Context::SurfaceView,
        SECTION,
        "Cell renderer block.",
    ),
    lzx("route", Context::SurfaceView, STMT, "View route."),
    lzx(
        "actions",
        Context::SurfaceView,
        SECTION,
        "View action block.",
    ),
    lzx("action", Context::SurfaceView, STMT, "View action."),
    lzx("filter", Context::SurfaceView, STMT, "List filter."),
    lzx(
        "filters",
        Context::SurfaceView,
        SECTION,
        "List filter block.",
    ),
    lzx("search", Context::SurfaceView, STMT, "List search."),
    lzx(
        "drawer",
        Context::SurfaceView,
        SECTION,
        "Detail drawer block.",
    ),
    lzx("sort", Context::SurfaceView, STMT, "List sort."),
    lzx(
        "selection",
        Context::SurfaceView,
        STMT,
        "Row selection mode.",
    ),
    lzx(
        "bulk_actions",
        Context::SurfaceView,
        SECTION,
        "Bulk-action block.",
    ),
    lzx(
        "settings",
        Context::SurfaceView,
        SECTION,
        "View settings block.",
    ),
    lzx(
        "persist",
        Context::SurfaceView,
        STMT,
        "Filter/sort persistence.",
    ),
    lzx(
        "flash",
        Context::SurfaceView,
        STMT,
        "Flash message on success.",
    ),
    lzx("replace", Context::SurfaceView, STMT, "Replace navigation."),
    lzx(
        "redirect",
        Context::SurfaceView,
        STMT,
        "Redirect on success.",
    ),
    lzx(
        "back",
        Context::SurfaceView,
        STMT,
        "Navigate back on success.",
    ),
    lzx("tabs", Context::SurfaceView, SECTION, "Tabbed view block."),
    lzx("tab", Context::SurfaceView, STMT, "A single tab."),
    lzx(
        "tab_group",
        Context::SurfaceView,
        SECTION,
        "Tab-group block.",
    ),
    lzx(
        "wizard",
        Context::SurfaceView,
        SECTION,
        "Wizard view block.",
    ),
    lzx(
        "wizard_steps",
        Context::SurfaceView,
        SECTION,
        "Wizard-steps block.",
    ),
    lzx("step", Context::SurfaceView, STMT, "A wizard step."),
    lzx(
        "view_mode",
        Context::SurfaceView,
        STMT,
        "View display mode.",
    ),
    lzx(
        "date_range",
        Context::SurfaceView,
        STMT,
        "Date-range filter primitive.",
    ),
    lzx(
        "repeatable",
        Context::SurfaceView,
        STMT,
        "Repeatable input group.",
    ),
    lzx("lazy", Context::SurfaceView, STMT, "Lazy-load marker."),
    lzx("prerender", Context::SurfaceView, STMT, "Prerender marker."),
    lzx(
        "loader",
        Context::SurfaceView,
        STMT,
        "Data loader reference.",
    ),
    lzx(
        "opens",
        Context::SurfaceView,
        STMT,
        "Drawer/modal open trigger.",
    ),
    lzx("lanes", Context::SurfaceView, STMT, "Board lanes."),
    lzx("icon", Context::SurfaceView, STMT, "Action/tab icon."),
    lzx("hint", Context::SurfaceView, STMT, "Field hint text."),
    lzx(
        "error_view",
        Context::SurfaceView,
        STMT,
        "Error-state view.",
    ),
    lzx(
        "error_redact",
        Context::SurfaceView,
        STMT,
        "Error redaction.",
    ),
    lzx(
        "pending_view",
        Context::SurfaceView,
        STMT,
        "Pending/loading view.",
    ),
    lzx(
        "on_change",
        Context::SurfaceView,
        STMT,
        "On-change handler.",
    ),
    lzx("mutate", Context::SurfaceView, STMT, "Optimistic mutation."),
    lzx(
        "requires_lifecycle",
        Context::SurfaceView,
        STMT,
        "Lifecycle-state gate for the view/route.",
    ),
    lzx(
        "requires_lifecycle_in",
        Context::SurfaceView,
        STMT,
        "Lifecycle-state-set gate.",
    ),
    lzx(
        "on_lifecycle_pending",
        Context::SurfaceView,
        STMT,
        "Pending-lifecycle handler.",
    ),
    lzx(
        "resume",
        Context::SurfaceView,
        STMT,
        "Resume-from-pending reference.",
    ),
    lzx(
        "view.inline_table",
        Context::SurfaceView,
        STMT,
        "Inline-table view primitive (W6).",
    ),
    lzx(
        "view.board",
        Context::SurfaceView,
        STMT,
        "Board view primitive (W6).",
    ),
    lzx(
        "detail",
        Context::SurfaceView,
        DECL,
        "`view detail` projection kind.",
    ),
    lzx(
        "create",
        Context::SurfaceView,
        DECL,
        "`view create` projection kind.",
    ),
    // route / view guards (.lzx app + feature route blocks)
    lzx(
        "on_unauthenticated",
        Context::SurfaceView,
        STMT,
        "Guard: action when unauthenticated.",
    ),
    lzx(
        "on_unauthorized",
        Context::SurfaceView,
        STMT,
        "Guard: action when unauthorized.",
    ),
    lzx(
        "role_mismatch",
        Context::SurfaceView,
        STMT,
        "Route guard: per-role mismatch redirect.",
    ),
    lzx(
        "default_policy",
        Context::SurfaceView,
        STMT,
        "Default route policy.",
    ),
    lzx(
        "default_unauthenticated_redirect",
        Context::SurfaceView,
        STMT,
        "Default unauthenticated redirect.",
    ),
    lzx(
        "default_unauthorized_redirect",
        Context::SurfaceView,
        STMT,
        "Default unauthorized redirect.",
    ),
    // extends / anchor / slot extensibility
    lzx(
        "extends",
        Context::Extends,
        DECL,
        "Extends a sibling feature's anchor.",
    ),
    lzx(
        "anchor",
        Context::Extends,
        STMT,
        "Declares an extensibility anchor.",
    ),
    lzx(
        "extensible_by",
        Context::Extends,
        STMT,
        "Declares this view extensible by siblings.",
    ),
    lzx("slot", Context::Extends, STMT, "Extension slot position."),
    lzx(
        "platforms",
        Context::Extends,
        STMT,
        "Target platforms for the extension.",
    ),
];
