//! Per-API contract shape tests — output types (cap.File / storage.FileRef),
//! inferred path args, method constants, cross-feature outputs, deprecation
//! literals.

use super::super::*;
use super::{
    base_feature, emit, emit_from_module, make_file_capability, module_with_features, simple_api,
    simple_record,
};
use lazuli_ir::{
    BuiltinType, CapabilityRef, FileSizeLiteral, FileVisibility, HttpMethod, PathRef, PolicyRef,
    QualifiedName, RateLimitSpec, TypeRef,
};

#[test]
fn canonical_file_api_emits_real_type_storage_and_register_placeholder() {
    let mut feature = base_feature("customer");
    let mut api = simple_api(
        "customer_export",
        HttpMethod::Get,
        "/api/customers/export",
        TypeRef::Builtin(BuiltinType::CapFile),
    );
    api.policy = PolicyRef::Local("global_read".to_owned());
    api.rate_limit = Some(RateLimitSpec::from_default(
        "10 per hour per user".to_owned(),
    ));
    api.handler = PathRef::authored("./api/export_customers.go");
    feature.apis.push(api);

    let out = emit(&feature).expect("must emit");
    assert!(out.contains("// Code generated by lazuli; DO NOT EDIT."));
    assert!(out.contains("package customergen"));
    assert!(out.contains("\"lazuli.dev/runtime/lazuli\""));
    assert!(out.contains("\"lazuli.dev/runtime/lazuli/storage\""));
    assert!(!out.contains("\"lazuli/test/customer/api\""));
    assert!(out.contains("type CustomerExportApiArgs struct{}"));
    assert!(
        out.contains("var customerExportApi = lazuli.Api[CustomerExportApiArgs, storage.FileRef]{")
    );
    assert!(!out.contains("var customerExportApi = struct {"));
    assert!(!out.contains("TODO(runtime):"));
    // Codegen now emits a `func init()` that registers the typed
    // API value. The previous inert `TODO` comment never registered
    // anything (review bug #1, 2026-05-15).
    assert!(out.contains("func init() { lazuli.RegisterApi(&customerExportApi) }"));
    // W3 API bridge: the `Handler` field is now wired via the fn
    // registry — no hand-wiring needed, no "Wire ... in your application
    // code" TODO, no ValidateApiHandlers nudge. Convention/file handler
    // (`./api/export_customers.go`) → registry key `<feature>.<api name>`.
    assert!(out.contains(
        "Handler:   lazuli.HandlerFromRegistry[CustomerExportApiArgs, storage.FileRef](\"customer.customer_export\"),"
    ));
    assert!(
        !out.contains("// Wire customerExportApi.Handler in your application code"),
        "the hand-wiring TODO must be gone now that codegen bridges the handler"
    );
    assert!(
        !out.contains("ValidateApiHandlers"),
        "no ValidateApiHandlers nudge once the handler is auto-wired"
    );
    assert!(
        !out.contains("// TODO(extension-points)"),
        "legacy TODO comment must be gone"
    );
    assert!(out.contains("Method:    lazuli.MethodGet,"));
    // SECURITY (POLICY-REF-UNRESOLVED): this feature declares no `policies`
    // block, so `@policy.global_read` resolves to no category. The emitter
    // fails CLOSED with an explicit deny atom rather than the former Name-only
    // empty-atoms policy (which shipped the endpoint effectively unguarded).
    assert!(out.contains(
        "Policy:    lazuli.Policy{Name: \"@policy.global_read\", Atoms: []lazuli.PolicyAtom{{Namespace: \"predicate\", Name: \"deny\"}}},"
    ));
    assert!(
        !out.contains("Policy:    lazuli.Policy{Name: \"@policy.global_read\"},"),
        "regression: unresolvable api policy must not emit Name-only (no Atoms) = bypass"
    );
    assert!(out.contains("RateLimit: lazuli.RateLimit{Default: \"10 per hour per user\"},"));
    // Generated Api value now wires Handler via the registry bridge
    // (no extension-point hand-wiring).
    assert!(out.contains("Handler:   lazuli.HandlerFromRegistry["));
}

#[test]
fn typed_cap_file_api_output_uses_storage_file_ref() {
    let mut feature = base_feature("customer");
    feature.apis.push(simple_api(
        "customer_export",
        HttpMethod::Get,
        "/api/customers/export",
        TypeRef::Capability(CapabilityRef::File(make_file_capability(
            FileSizeLiteral::Mb(100),
            vec![("text", "csv")],
            Some(FileVisibility::Signed),
            Some("1h"),
        ))),
    ));

    let out = emit(&feature).expect("must emit");
    assert!(out.contains("\"lazuli.dev/runtime/lazuli/storage\""));
    assert!(
        out.contains("var customerExportApi = lazuli.Api[CustomerExportApiArgs, storage.FileRef]{")
    );
    assert!(!out.contains("_cap_File"));
}

#[test]
fn cap_file_literal_api_output_uses_storage_file_ref() {
    let mut feature = base_feature("customer");
    feature.apis.push(simple_api(
        "customer_export",
        HttpMethod::Get,
        "/api/customers/export",
        TypeRef::UserDefined(QualifiedName {
            feature: None,
            name: "@cap.File(max_size:100mb,accept:text/csv,visibility:signed,signed_ttl:1h)"
                .to_owned(),
        }),
    ));

    let out = emit(&feature).expect("must emit");
    assert!(out.contains("\"lazuli.dev/runtime/lazuli/storage\""));
    assert!(
        out.contains("var customerExportApi = lazuli.Api[CustomerExportApiArgs, storage.FileRef]{")
    );
    assert!(!out.contains("_cap_File"));
}

#[test]
fn path_params_emit_inferred_args_and_method_constant() {
    let mut feature = base_feature("customer");
    feature.records.push(simple_record("CustomerSummary"));
    let mut api = simple_api(
        "customer_summary",
        HttpMethod::Get,
        "/api/customer/{id}/summary",
        TypeRef::UserDefined(QualifiedName {
            feature: None,
            name: "CustomerSummary".to_owned(),
        }),
    );
    api.rate_limit = Some(RateLimitSpec::from_default(
        "60 per minute per user".to_owned(),
    ));
    feature.apis.push(api);

    let out = emit(&feature).expect("must emit");
    assert!(out.contains("type CustomerSummaryApiArgs struct {"));
    assert!(out.contains("ID lazuli.ID `json:\"id\"`"));
    assert!(out.contains("// TODO(ir): Api path parameters have no typed IR slots"));
    assert!(out.contains(
        r#"var customerSummaryApi = lazuli.Api[CustomerSummaryApiArgs, CustomerSummary]{
	Name:      "customer.customer_summary",
	Feature:   "customer",
	Method:    lazuli.MethodGet,
	Path:      "/api/customer/{id}/summary",
	Policy:    lazuli.Policy{Name: "@policy.read", Atoms: []lazuli.PolicyAtom{{Namespace: "predicate", Name: "deny"}}},
	RateLimit: lazuli.RateLimit{Default: "60 per minute per user"},
	Handler:   lazuli.HandlerFromRegistry[CustomerSummaryApiArgs, CustomerSummary]("customer.customer_summary"),
}

//lazuli:pattern api_register v1
func init() { lazuli.RegisterApi(&customerSummaryApi) }"#
    ));
    assert!(!out.contains("TODO(runtime):"));
    // Handler now wired via the registry bridge; the value is
    // registered via init() AND mounts at runtime.
    assert!(out.contains("Handler:   lazuli.HandlerFromRegistry["));
    assert!(!out.contains("// Wire customerSummaryApi.Handler"));
}

#[test]
fn api_output_resource_resolves_full_struct_not_id_collapse() {
    // Regression: `api me` with `output User` (a resource) must resolve to
    // the full `User` struct on BOTH the Api generic and the handler
    // bridge generic — NOT the FK collapse `lazuli.ID`. The collapse made
    // the bridge's `HandlerFromRegistry[MeApiArgs, lazuli.ID]` reject the
    // registered `@fn.me` handler (which returns `User`) at dispatch → 500
    // instead of 200. Mirrors the command `Returns` return-axis resolver.
    use super::simple_resource;
    let mut feature = base_feature("account");
    feature.resources.push(simple_resource("User"));
    let mut api = simple_api(
        "me",
        HttpMethod::Get,
        "/me",
        TypeRef::UserDefined(QualifiedName {
            feature: None,
            name: "User".to_owned(),
        }),
    );
    api.handler = PathRef::authored("@fn.me");
    feature.apis.push(api);

    let out = emit(&feature).expect("must emit");
    assert!(
        out.contains("var meApi = lazuli.Api[MeApiArgs, User]{"),
        "api output resource must resolve to full struct, not lazuli.ID:\n{out}"
    );
    assert!(
        !out.contains("lazuli.Api[MeApiArgs, lazuli.ID]"),
        "regression: resource output collapsed to FK id:\n{out}"
    );
    assert!(
        out.contains(
            "Handler: lazuli.HandlerFromRegistry[MeApiArgs, User](\"account.me\"),"
        ),
        "handler bridge must use the @fn name + full struct O:\n{out}"
    );
}

#[test]
fn method_consts_cover_runtime_catalog() {
    // Drive every HTTP verb end-to-end through the emitter; each must
    // reference its own runtime catalog constant on the contract row
    // and must not leak any other verb's constant into the same output.
    let all_consts = [
        "lazuli.MethodGet",
        "lazuli.MethodPost",
        "lazuli.MethodPut",
        "lazuli.MethodPatch",
        "lazuli.MethodDelete",
    ];
    for (method, expected) in [
        (HttpMethod::Get, "lazuli.MethodGet"),
        (HttpMethod::Post, "lazuli.MethodPost"),
        (HttpMethod::Put, "lazuli.MethodPut"),
        (HttpMethod::Patch, "lazuli.MethodPatch"),
        (HttpMethod::Delete, "lazuli.MethodDelete"),
    ] {
        let mut feature = base_feature("customer");
        feature.records.push(simple_record("Customer"));
        feature.apis.push(simple_api(
            "endpoint",
            method,
            "/api/endpoint",
            TypeRef::UserDefined(QualifiedName {
                feature: None,
                name: "Customer".to_owned(),
            }),
        ));
        let out = emit(&feature).expect("must emit");
        assert!(
            out.contains(&format!("{expected},")),
            "expected `{expected},` in output:\n{out}"
        );
        for other in all_consts.iter().filter(|c| **c != expected) {
            assert!(
                !out.contains(&format!("{other},")),
                "verb {expected:?} leaked unrelated constant {other:?}:\n{out}"
            );
        }
    }
}

#[test]
fn cross_feature_output_emits_qualified_type_and_import() {
    let mut customer = base_feature("customer");
    customer.apis.push(simple_api(
        "owner_profile",
        HttpMethod::Post,
        "/api/customer/{owner_id}/profile",
        TypeRef::UserDefined(QualifiedName {
            feature: None,
            name: "UserProfile".to_owned(),
        }),
    ));

    let mut org = base_feature("org");
    org.records.push(simple_record("UserProfile"));

    let module = module_with_features(vec![customer, org]);
    let out = emit_from_module(&module, 0).expect("must emit");
    assert!(out.contains("\"lazuli/test/org\""));
    assert!(
        out.contains("var ownerProfileApi = lazuli.Api[OwnerProfileApiArgs, orggen.UserProfile]{")
    );
    assert!(out.contains("Method:  lazuli.MethodPost,"));
    assert!(out.contains("OwnerID lazuli.ID `json:\"owner_id\"`"));
}

#[test]
fn deprecated_api_emits_deprecation_literal() {
    let mut feature = base_feature("customer");
    feature.records.push(simple_record("Customer"));
    let mut api = simple_api(
        "legacy_export",
        HttpMethod::Get,
        "/api/customers/export-v1",
        TypeRef::Many(Box::new(TypeRef::UserDefined(QualifiedName {
            feature: None,
            name: "Customer".to_owned(),
        }))),
    );
    api.deprecated = Some(lazuli_ir::Deprecation {
        since: Some("2026-04-01".to_owned()),
        replacement: Some(lazuli_ir::DeprecationReplacement::LocalApi(
            "export_v2".to_owned(),
        )),
        sunset: Some("2026-09-30".to_owned()),
    });
    feature.apis.push(api);

    let out = emit(&feature).expect("must emit");
    assert!(out.contains(
        "Deprecation: &lazuli.Deprecation{Since: \"2026-04-01\", Replacement: \"customer.api.export_v2\", Sunset: \"2026-09-30\"},"
    ));
}
