//! `query.compose` W2 — analyzer lowering for the declarative composite read.
//!
//! Lifts a parsed [`syntax::ComposeQueryDecl`] onto the resolved
//! [`ir::ComposeQuery`] that Go codegen (W5) consumes — the W2→W5 contract.
//! See `docs/proposals/ir-composite-read-primitive-2026-05-29.md` §5.
//!
//! ## What W2 resolves (vs. defers to doctor/W3)
//!
//! * Root + FK-path JOIN edges, projection sources, and the closed-catalog
//!   subselects are resolved against the IN-FEATURE relation graph here.
//! * Cross-feature roots / FK hops that leave the feature are TRUSTED at
//!   lowering and validated by doctor with Module context — the same
//!   deferral the owner-scope synth uses (`conventions/owner_scope.rs`).
//! * Structurally-detectable malformations surface as clean
//!   [`AnalyzeError`]s (never panics), giving the W3 doctor codes
//!   (`COMPOSE-JOIN-PATH-001` / `-PROJECTION-SOURCE-001` /
//!   `-SUBSELECT-RELATION-001`) their data.
//!
//! ## Scope inheritance (the verifiability-critical part)
//!
//! The tenant + soft-delete predicate is GENERATED by codegen from
//! `effective_tenancy` on the root, exactly like [`ir::ListQuery`]. The
//! analyzer records the ORIGIN ([`ir::ComposeScopeOrigin`]) so inspect (W6)
//! and doctor (W3) can prove the predicate is present without reading a
//! handler — `Inherited` by default (secure), `Overridden` only when the
//! author wrote `scope override` (§5.2 / §5.3).
//!
//! Predicate / order / key clause lifting lives in the sibling
//! [`super::compose_predicates`] module.

use lazuli_ir as ir;
use lazuli_syntax as syntax;

use crate::expr::{lower_policy_atom, lower_policy_expr};
use crate::helpers::{pascal_to_snake, span_of};
use crate::{AnalyzeError, lower_public_contract, type_ref_from_text};

use super::compose_predicates::{
    lower_compose_scope_lines, lower_order_lines, lower_subselect_preds, parse_key_clause,
};
use super::{lower_command_input_to_typed, lower_query_filter_lines};

/// `query.compose` W2 — lower a parsed [`syntax::ComposeQueryDecl`] into the
/// resolved [`ir::ComposeQuery`] that Go codegen (W5) consumes.
///
/// ## What "resolved" means (the W2→W5 contract)
///
/// W1 produced the typed-but-unresolved AST. W2 produces the IR that codegen
/// can lower to one SELECT *without re-deciding anything*:
///
/// * `root` — `from <Resource>` lifted to a [`ir::TypeRef`]. Resolved against
///   `resources` (the in-feature relation graph) when present.
/// * `joins[]` — each `join <fk.path>` carries the resolved [`ir::FkPath`] +
///   the alias (defaulted to the last path segment when omitted) + nullability
///   (`optional` ⇒ LEFT JOIN). The FIRST path segment is checked against the
///   root resource's FK fields; an unresolved segment is a clean
///   [`AnalyzeError::ComposeJoinPathUnresolved`] (W3 `COMPOSE-JOIN-PATH-001`
///   data), never a panic. Cross-feature roots/segments are trusted here and
///   validated by doctor with Module context (mirrors the owner-scope synth).
/// * `projections[]` — each `<field> = <source>` resolved to a closed
///   [`ir::ProjectionSource`]. `<alias>.<col>` must name a declared join
///   alias; a bare subselect ref must name a declared subselect — otherwise a
///   clean [`AnalyzeError::ComposeProjectionSourceUnresolved`].
/// * `subselects[]` — each closed-catalog kind mapped to [`ir::SubselectKind`]
///   with its resource [`ir::TypeRef`], the resolved `related_by`
///   [`ir::FkPath`] (required — missing is
///   [`AnalyzeError::ComposeSubselectMissingRelation`]), and the lowered
///   `where`/`filter` predicates + `order`.
/// * `scope_origin` — stamped [`ir::ComposeScopeOrigin::Inherited`] by default
///   (tenant + soft-delete inherited exactly like [`ir::ListQuery`]) or
///   `Overridden` when the author wrote `scope override`. This is the
///   load-bearing verifiability artifact: codegen GENERATES the tenant
///   predicate from `effective_tenancy`, so a dropped predicate is
///   structurally impossible for the absorbed shapes (§5.2 / §5.3).
/// * `returns` — the generated record name (`<Compose>Row` default).
///
/// Author-written composes set `owner_scope_sql: None`, exactly like an
/// author-written `query.list`/`query.lookup` (`query.rs` List/Lookup arms);
/// the actor-axis (`@owner_axis`) chain is the convention-synth concern.
pub(crate) fn lower_compose_decl(
    compose: &syntax::ComposeQueryDecl,
    resources: &[ir::Resource],
) -> Result<ir::ComposeQuery, AnalyzeError> {
    let root = type_ref_from_text(&compose.root);
    // In-feature root resource (if resolvable here). Absent ⇒ cross-feature
    // or not-yet-declared root; FK-path resolution is then deferred to doctor.
    let root_resource = resource_for_type(resources, &root);

    // --- joins --------------------------------------------------------------
    // Resolve each join's FK path, default the alias, capture nullability.
    // Track the declared aliases so projection sources can be validated.
    let mut joins = Vec::with_capacity(compose.joins.len());
    let mut join_aliases: Vec<String> = Vec::new();
    for join in &compose.joins {
        let segments = split_fk_path(&join.path);
        // FK-path resolution against the relation graph. The path is rooted
        // at the source resource's snake name (`chat.counterpart` from
        // `Chat`); segments after the root are FK fields walked hop-by-hop.
        // Only enforced when the root is in-feature; cross-feature roots /
        // hops leaving the feature are trusted (doctor validates with Module
        // context — mirrors the owner-scope synth's deferral).
        if let Some(root_res) = root_resource {
            resolve_fk_path(
                &compose.name,
                &join.path,
                &segments,
                root_res,
                resources,
            )?;
        }
        let alias = join
            .alias
            .clone()
            .or_else(|| segments.last().cloned())
            .unwrap_or_default();
        join_aliases.push(alias.clone());
        joins.push(ir::ComposeJoin {
            path: ir::FkPath::from_segments(segments),
            alias,
            nullable: join.nullable,
        });
    }

    // --- subselects (resolved first so projections can reference them) ------
    let mut subselects = Vec::with_capacity(compose.subselects.len());
    let mut subselect_names: Vec<String> = Vec::new();
    for sub in &compose.subselects {
        let related_by = sub.related_by.as_deref().map(str::trim).unwrap_or("");
        if related_by.is_empty() {
            return Err(AnalyzeError::ComposeSubselectMissingRelation {
                query: compose.name.clone(),
                name: sub.name.clone(),
            });
        }
        subselect_names.push(sub.name.clone());
        subselects.push(ir::ComposeSubselect {
            name: sub.name.clone(),
            kind: lower_subselect_kind(&sub.kind, sub.negate),
            related_by: ir::FkPath::from_segments(split_fk_path(related_by)),
            where_pred: lower_subselect_preds(&sub.where_pred),
            filter_pred: lower_subselect_preds(&sub.filter_pred),
            order: lower_order_lines(&sub.order),
        });
    }

    // --- projections --------------------------------------------------------
    let mut projections = Vec::with_capacity(compose.projections.len());
    for proj in &compose.projections {
        let source = resolve_projection_source(
            &compose.name,
            proj,
            &join_aliases,
            &subselect_names,
        )?;
        projections.push(ir::ComposeProjection {
            name: proj.name.clone(),
            source,
        });
    }

    // --- scope inheritance (the verifiability-critical part) ----------------
    // The tenant + soft-delete predicate is GENERATED by codegen from
    // `effective_tenancy` on the root, exactly like `query.list`. The
    // analyzer's job is to record the ORIGIN so inspect (W6) and doctor (W3)
    // can prove the predicate is present without reading a handler. The
    // default is `Inherited` (secure); `scope override` flips it to
    // `Overridden` (explicit, doctor-gated opt-out).
    let scope_origin = if compose.scope_override {
        ir::ComposeScopeOrigin::Overridden
    } else {
        ir::ComposeScopeOrigin::Inherited
    };

    // Local safety `scope` predicates layered atop the inherited scope.
    let scope = lower_compose_scope_lines(&compose.scope_lines);

    // `key` ⇒ single-row read (§3.2 #6). Lower the `<path> = <expr>` clause.
    let key = compose.key.as_deref().and_then(parse_key_clause);

    // `returns <Type>` — default `<Compose>Row` when omitted.
    let returns_text = compose
        .returns
        .clone()
        .unwrap_or_else(|| default_compose_record_name(&compose.name));

    Ok(ir::ComposeQuery {
        name: compose.name.clone(),
        public_contract: lower_public_contract(&compose.public_contract),
        root,
        params: compose
            .params
            .iter()
            .map(lower_command_input_to_typed)
            .collect::<Result<Vec<_>, _>>()?,
        joins,
        projections,
        subselects,
        filters: lower_query_filter_lines(&compose.filters),
        key,
        scope,
        scope_override: compose.scope_override,
        order: lower_order_lines(&compose.order),
        paginate: compose.paginate,
        policy: compose
            .policy
            .as_deref()
            .map(lower_policy_atom)
            .unwrap_or(ir::PolicyRef::None),
        policy_expr: compose.policy_expr.as_ref().map(lower_policy_expr),
        policy_when_denied: None,
        returns: type_ref_from_text(&returns_text),
        scope_origin,
        // Author-written queries default to tenant-only owner-scope; the
        // `@owner_axis` actor-chain is the convention-synth concern (mirrors
        // the List/Lookup arms). `None` here.
        owner_scope_sql: None,
        previous_names: Vec::new(),
        span_ref: Some(span_of(compose.span)),
    })
}

/// Default generated-record name for a `query.compose` with no `returns`:
/// `<PascalName>Row` (e.g. `chat_inbox` → `ChatInboxRow`), matching §3.1.
fn default_compose_record_name(query_name: &str) -> String {
    let pascal: String = query_name
        .split('_')
        .filter(|seg| !seg.is_empty())
        .map(|seg| {
            let mut chars = seg.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect();
    format!("{pascal}Row")
}

/// Split a dotted FK path (`host.user`) into its lowercase segments,
/// trimming whitespace and dropping empty segments defensively.
fn split_fk_path(path: &str) -> Vec<String> {
    path.split('.')
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(str::to_owned)
        .collect()
}

/// Find the in-feature [`ir::Resource`] a [`ir::TypeRef`] points at, when the
/// ref is a same-feature `UserDefined` name. Cross-feature refs (carrying a
/// `feature` segment) and builtins return `None` — resolution is deferred to
/// doctor, which has the Module graph.
fn resource_for_type<'a>(
    resources: &'a [ir::Resource],
    type_ref: &ir::TypeRef,
) -> Option<&'a ir::Resource> {
    let ir::TypeRef::UserDefined(qname) = type_ref else {
        return None;
    };
    if qname.feature.is_some() {
        return None;
    }
    resources.iter().find(|r| r.name == qname.name)
}

/// Resolve an FK path (`chat.counterpart.user`) against the relation graph,
/// hop by hop. The path is ROOTED at the source resource's snake name
/// (segment[0]); every segment after that is an FK field walked from the
/// current resource onto its target.
///
/// Resolution is enforced only for in-feature hops — the join-path closure
/// lever (§3.2 #2). An FK field is one whose type is another resource
/// (`TypeRef::UserDefined`) or an `ID` field bearing a GAP-12
/// `cross_feature_target`. A segment that names no such field on the current
/// in-feature resource is a clean [`AnalyzeError::ComposeJoinPathUnresolved`]
/// (W3 `COMPOSE-JOIN-PATH-001` data). When a hop's target leaves the feature
/// (not found in `resources`), the walk stops and trusts the remainder —
/// doctor validates cross-feature hops with Module context.
fn resolve_fk_path(
    query_name: &str,
    raw_path: &str,
    segments: &[String],
    root: &ir::Resource,
    resources: &[ir::Resource],
) -> Result<(), AnalyzeError> {
    // segment[0] is the source-resource anchor (the snake-cased root name).
    // If it doesn't match the root, the path is anchored elsewhere — trust
    // it and let doctor resolve (defensive; the parser shapes the anchor).
    let Some((anchor, hops)) = segments.split_first() else {
        return Ok(());
    };
    if *anchor != pascal_to_snake(&root.name) {
        return Ok(());
    }
    let mut current: &ir::Resource = root;
    for hop in hops {
        let Some(target_name) = fk_target_resource_name(current, hop) else {
            // No FK field named `hop` on the current in-feature resource.
            return Err(AnalyzeError::ComposeJoinPathUnresolved {
                query: query_name.to_owned(),
                path: raw_path.to_owned(),
                segment: hop.clone(),
                on_resource: current.name.clone(),
            });
        };
        // Walk to the target resource if it lives in-feature; otherwise the
        // hop leaves the feature — stop walking and trust the remainder.
        match resources.iter().find(|r| r.name == target_name) {
            Some(next) => current = next,
            None => return Ok(()),
        }
    }
    Ok(())
}

/// The FK target resource name for `field_name` on `resource`, when that
/// field is a relation edge: a `UserDefined` typed field (returns the
/// referenced resource name) or an `ID` field bearing a GAP-12
/// `cross_feature_target` (returns the annotated target resource). `None`
/// when the field is absent or not a relation.
fn fk_target_resource_name(resource: &ir::Resource, field_name: &str) -> Option<String> {
    let field = resource.fields.iter().find(|f| f.name == field_name)?;
    if let ir::TypeRef::UserDefined(qname) = &field.type_ref {
        return Some(qname.name.clone());
    }
    field
        .cross_feature_target
        .as_ref()
        .map(|t| t.resource.clone())
}

/// Resolve a projection's source against the declared join aliases +
/// subselect names. `self.<col>` always resolves (root column existence is a
/// doctor concern — `COMPOSE-PROJECTION-SOURCE-001` validates it with the
/// resource's full field set). `<alias>.<col>` requires a declared alias; a
/// bare subselect ref requires a declared subselect.
fn resolve_projection_source(
    query_name: &str,
    proj: &syntax::ComposeProjectionDecl,
    join_aliases: &[String],
    subselect_names: &[String],
) -> Result<ir::ProjectionSource, AnalyzeError> {
    match &proj.source {
        syntax::ComposeProjectionSourceDecl::SelfColumn(col) => {
            Ok(ir::ProjectionSource::SelfCol(col.clone()))
        }
        syntax::ComposeProjectionSourceDecl::Joined { alias, column } => {
            if !join_aliases.iter().any(|a| a == alias) {
                return Err(AnalyzeError::ComposeProjectionSourceUnresolved {
                    query: query_name.to_owned(),
                    field: proj.name.clone(),
                    source_text: format!("{alias}.{column}"),
                    kind: "join alias".to_owned(),
                });
            }
            Ok(ir::ProjectionSource::Joined(alias.clone(), column.clone()))
        }
        syntax::ComposeProjectionSourceDecl::Subselect(name) => {
            if !subselect_names.iter().any(|s| s == name) {
                return Err(AnalyzeError::ComposeProjectionSourceUnresolved {
                    query: query_name.to_owned(),
                    field: proj.name.clone(),
                    source_text: name.clone(),
                    kind: "subselect".to_owned(),
                });
            }
            Ok(ir::ProjectionSource::Subselect(name.clone()))
        }
    }
}

/// Map a parsed closed-catalog subselect kind onto the resolved
/// [`ir::SubselectKind`], lifting each `<Resource>` reference to a
/// [`ir::TypeRef`]. `negate` only takes effect on `exists` (NOT EXISTS
/// anti-join); the parser already rejects `negate` on other kinds.
fn lower_subselect_kind(kind: &syntax::ComposeSubselectKindDecl, negate: bool) -> ir::SubselectKind {
    match kind {
        syntax::ComposeSubselectKindDecl::Count { resource } => {
            ir::SubselectKind::Count(type_ref_from_text(resource))
        }
        syntax::ComposeSubselectKindDecl::Exists { resource } => ir::SubselectKind::Exists {
            resource: type_ref_from_text(resource),
            negate,
        },
        syntax::ComposeSubselectKindDecl::Latest { column, resource } => {
            ir::SubselectKind::Latest {
                column: column.clone(),
                resource: type_ref_from_text(resource),
            }
        }
        syntax::ComposeSubselectKindDecl::Aggregate {
            func,
            column,
            resource,
        } => ir::SubselectKind::Aggregate {
            func: lower_agg_fn(*func),
            column: column.clone(),
            resource: type_ref_from_text(resource),
        },
    }
}

/// Map the closed 5-member aggregate-function catalog onto [`ir::AggFn`].
fn lower_agg_fn(func: syntax::ComposeAggFnDecl) -> ir::AggFn {
    match func {
        syntax::ComposeAggFnDecl::Sum => ir::AggFn::Sum,
        syntax::ComposeAggFnDecl::Avg => ir::AggFn::Avg,
        syntax::ComposeAggFnDecl::Min => ir::AggFn::Min,
        syntax::ComposeAggFnDecl::Max => ir::AggFn::Max,
        syntax::ComposeAggFnDecl::CountDistinct => ir::AggFn::CountDistinct,
    }
}
