//! Real-world diagnostic-emission snapshot.
//!
//! Walks every `.lzi` / `.lzx` file under `examples/` (skipping
//! `node_modules`, `anti-patterns`, and `generated`), runs
//! `lazuli_lsp::diagnostics_for_source` on each, aggregates diagnostic
//! codes by frequency, and writes the report to
//! `editors/vscode/tests/grammar/sanity-sweep.txt`.
//!
//! This is a SNAPSHOT of the diagnostic surface today (2026-05-15).
//! Reviewers comparing future diffs against `sanity-sweep.txt` can
//! eyeball whether a new lint or a refactor accidentally moved real
//! example files from clean -> noisy.
//!
//! Marked `#[ignore]` so it's opt-in: it writes a file, which would
//! be surprising in a default `cargo test` run. To regenerate:
//!
//!   cargo test -p lazuli_lsp --test sanity_sweep -- --ignored
//!
//! The committed `sanity-sweep.txt` is the source of truth between
//! regenerations.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use lazuli_lsp::diagnostics_for_source;
use tower_lsp::lsp_types::NumberOrString;

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf()
}

fn collect_lazuli_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let name = entry.file_name();
        let name_str = name.to_string_lossy();
        if path.is_dir() {
            // Skip noise.
            if matches!(
                name_str.as_ref(),
                "node_modules" | "anti-patterns" | "generated" | "target" | ".git" | "worktrees"
            ) {
                continue;
            }
            collect_lazuli_files(&path, out);
        } else if path.is_file() {
            let ext = path.extension().and_then(|s| s.to_str()).unwrap_or("");
            if matches!(ext, "lzi" | "lzx") {
                out.push(path);
            }
        }
    }
}

#[test]
#[ignore]
fn regenerate_sanity_sweep() {
    let root = repo_root();
    let mut files = Vec::new();
    collect_lazuli_files(&root.join("examples"), &mut files);
    files.sort();

    let mut code_counts: BTreeMap<String, usize> = BTreeMap::new();
    let mut file_counts: BTreeMap<String, usize> = BTreeMap::new();
    let mut total_diagnostics: usize = 0;
    let mut files_with_diagnostics: usize = 0;

    let mut per_file: Vec<(String, usize, BTreeMap<String, usize>)> = Vec::new();

    for path in &files {
        let source = match fs::read_to_string(path) {
            Ok(s) => s,
            Err(_) => continue,
        };
        let diagnostics = diagnostics_for_source(&source);
        if !diagnostics.is_empty() {
            files_with_diagnostics += 1;
        }
        total_diagnostics += diagnostics.len();

        let mut here: BTreeMap<String, usize> = BTreeMap::new();
        for d in &diagnostics {
            let code = match d.code.as_ref() {
                Some(NumberOrString::String(s)) => s.clone(),
                Some(NumberOrString::Number(n)) => n.to_string(),
                None => "<no-code>".to_string(),
            };
            *code_counts.entry(code.clone()).or_default() += 1;
            *here.entry(code).or_default() += 1;
        }
        if !diagnostics.is_empty() {
            let rel = path
                .strip_prefix(&root)
                .unwrap_or(path)
                .to_string_lossy()
                .replace('\\', "/");
            *file_counts.entry(rel.clone()).or_default() += diagnostics.len();
            per_file.push((rel, diagnostics.len(), here));
        }
    }

    let mut by_freq: Vec<(&String, &usize)> = code_counts.iter().collect();
    by_freq.sort_by(|a, b| b.1.cmp(a.1).then_with(|| a.0.cmp(b.0)));

    let mut by_file_freq: Vec<(&String, &usize)> = file_counts.iter().collect();
    by_file_freq.sort_by(|a, b| b.1.cmp(a.1).then_with(|| a.0.cmp(b.0)));

    let mut out = String::new();
    out.push_str("# Lazuli LSP diagnostic sanity sweep\n");
    out.push_str("# Generated by `cargo test -p lazuli_lsp --test sanity_sweep -- --ignored`.\n");
    out.push_str("# Scope: every .lzi/.lzx under examples/ (skips node_modules / anti-patterns /\n");
    out.push_str("# generated / target / .git / worktrees). Each file passed through\n");
    out.push_str("# `lazuli_lsp::diagnostics_for_source` (Strict security profile).\n");
    out.push_str("#\n");
    out.push_str("# Use the diff between regenerations to spot:\n");
    out.push_str("#   - New lints firing on existing example files (expected when adding rules).\n");
    out.push_str("#   - Refactors that silenced an existing diagnostic (good or regression?).\n");
    out.push_str("#   - Examples that drifted from clean to noisy (cleanup target).\n");
    out.push_str("\n");
    out.push_str(&format!("files scanned: {}\n", files.len()));
    out.push_str(&format!("files with diagnostics: {}\n", files_with_diagnostics));
    out.push_str(&format!("total diagnostics: {}\n", total_diagnostics));
    out.push_str(&format!("unique diagnostic codes: {}\n", code_counts.len()));
    out.push_str("\n");
    out.push_str("## diagnostic codes by frequency (top 25)\n");
    for (code, count) in by_freq.iter().take(25) {
        out.push_str(&format!("{:>6}  {}\n", count, code));
    }
    if by_freq.len() > 25 {
        out.push_str(&format!(
            "  ...  ({} more codes; see full table below)\n",
            by_freq.len() - 25
        ));
    }
    out.push_str("\n");
    out.push_str("## all diagnostic codes (alphabetical)\n");
    let mut alpha: Vec<(&String, &usize)> = code_counts.iter().collect();
    alpha.sort();
    for (code, count) in alpha {
        out.push_str(&format!("{:>6}  {}\n", count, code));
    }
    out.push_str("\n");
    out.push_str("## noisiest files (top 25)\n");
    for (file, count) in by_file_freq.iter().take(25) {
        out.push_str(&format!("{:>6}  {}\n", count, file));
    }
    out.push_str("\n");
    out.push_str("## per-file breakdown\n");
    for (file, total, codes) in &per_file {
        out.push_str(&format!("\n{}  ({} total)\n", file, total));
        let mut codes_sorted: Vec<(&String, &usize)> = codes.iter().collect();
        codes_sorted.sort_by(|a, b| b.1.cmp(a.1).then_with(|| a.0.cmp(b.0)));
        for (code, count) in codes_sorted {
            out.push_str(&format!("    {:>4}  {}\n", count, code));
        }
    }

    let dest = root.join("editors/vscode/tests/grammar/sanity-sweep.txt");
    fs::write(&dest, out).unwrap_or_else(|err| panic!("write {dest:?}: {err}"));
    eprintln!("wrote {}", dest.display());
}
