//! Per-feature React-hook emission for `lazuli generate ts`.
//!
//! Emits `dist/ts-<target>/<feature>/<feature>.react.gen.ts` — a thin
//! wrapper layer that pairs every command/query exported from
//! `<feature>.gen.ts` with a `useXxx` hook. Two flavours:
//!
//! - `useLazuliQuery(spec, args?, options?)` for `defineQuery` specs
//!   (and pure-read commands lowered to defineQuery by Wave 0
//!   ir-returns-list-2026-05-22 §2.2).
//! - `useLazuliCommand(spec, options?)` for `defineCommand` specs.
//!
//! Deprecated-alias generation: when a command/query was renamed
//! (`previously_named`) the hook for the new name re-exports a
//! `const oldName = newName` alias guarded by `@deprecated` so the
//! callsite migration is incremental.
//!
//! Identifier-shape rules live in `mod.rs` (`command_ident`,
//! `query_ident`, `pick_query_resource_ts`, `pluralize_snake`, …).
//! This module is wiring only — it composes hook bodies from those
//! identifier shapes plus the prelude imports from `@lazuli/runtime/react`.

use std::collections::BTreeSet;
use std::fmt::Write as _;

use crate::casing::pascal_case;

use super::{
    command_ident, command_is_pure_read, command_sdk_slots, pick_query_resource_ts, query_args,
    query_ident,
};

pub(crate) fn emit_feature_react_hooks_ts(
    feature: &lazuli_ir::Feature,
    module: &lazuli_ir::Module,
) -> String {
    let mut s = String::new();
    let has_query_hooks =
        !feature.queries.is_empty() || feature.commands.iter().any(command_is_pure_read);
    let has_command_hooks = feature
        .commands
        .iter()
        .any(|command| !command_is_pure_read(command));
    writeln!(s, "// Code generated by lazuli; DO NOT EDIT.").ok();
    writeln!(s).ok();
    writeln!(s, "import {{").ok();
    if has_command_hooks {
        writeln!(s, "  useLazuliCommand,").ok();
    }
    if has_query_hooks {
        writeln!(s, "  useLazuliQuery,").ok();
    }
    if has_command_hooks {
        writeln!(s, "  type UseLazuliCommandOptions,").ok();
    }
    if has_query_hooks {
        writeln!(s, "  type UseLazuliQueryOptions,").ok();
    }
    writeln!(s, "}} from \"@lazuli/runtime/react\";").ok();
    writeln!(s).ok();

    let specs = feature_react_hook_specs(feature);
    if !specs.is_empty() {
        writeln!(s, "import {{").ok();
        for spec in specs {
            writeln!(s, "  {spec},").ok();
        }
        writeln!(s, "}} from \"./{}.gen.js\";", feature.name).ok();
        writeln!(s).ok();
    }

    if has_command_hooks {
        writeln!(
            s,
            "type CommandInput<TSpec> = TSpec extends {{ readonly _input?: infer Input }} ? Input : never;"
        )
        .ok();
        writeln!(
            s,
            "type CommandOutput<TSpec> = TSpec extends {{ readonly _output?: infer Output }} ? Output : never;"
        )
        .ok();
        writeln!(
            s,
            "type CommandOptions<TSpec> = UseLazuliCommandOptions<CommandInput<TSpec>, CommandOutput<TSpec>>;"
        )
        .ok();
    }
    if has_query_hooks {
        writeln!(
            s,
            "type QueryArgs<TSpec> = TSpec extends {{ readonly _args?: infer Args }} ? Args : never;"
        )
        .ok();
        writeln!(
            s,
            "type QueryResult<TSpec> = TSpec extends {{ readonly _result?: infer Result }} ? Result : never;"
        )
        .ok();
        writeln!(
            s,
            "type QueryOptions<TSpec> = UseLazuliQueryOptions<QueryResult<TSpec>>;"
        )
        .ok();
    }
    writeln!(s).ok();

    let mut used_hook_names = collect_canonical_react_hook_names(feature);
    let mut pure_read_commands: Vec<&lazuli_ir::Command> = feature
        .commands
        .iter()
        .filter(|command| command_is_pure_read(command))
        .collect();
    pure_read_commands.sort_by(|a, b| a.name.cmp(&b.name));

    let mut queries: Vec<&lazuli_ir::Query> = feature.queries.iter().collect();
    queries.sort_by(|a, b| a.name().cmp(b.name()));

    if !pure_read_commands.is_empty() || !queries.is_empty() {
        writeln!(s, "// Queries").ok();
        for command in pure_read_commands {
            let spec_ident = command_ident(&feature.name, &command.name);
            let hook_name = react_hook_name_for_spec(&spec_ident);
            let has_args = !command_sdk_slots(feature, command, module).is_empty();
            write_react_query_hook(&mut s, &hook_name, &spec_ident, has_args);
            let aliases = command
                .previous_names
                .iter()
                .map(|name| react_hook_name_for_spec(&command_ident(&feature.name, name)))
                .collect::<Vec<_>>();
            write_deprecated_react_hook_aliases(&mut s, &mut used_hook_names, &hook_name, aliases);
        }
        for query in queries {
            let kind = react_query_kind(query);
            let resource_pascal =
                pick_query_resource_ts(feature, query.name()).unwrap_or_else(|| {
                    feature
                        .resources
                        .first()
                        .map(|r| pascal_case(&r.name))
                        .unwrap_or_else(|| pascal_case(&feature.name))
                });
            let spec_ident = query_ident(&feature.name, &resource_pascal, kind, query.name());
            let hook_name = react_hook_name_for_spec(&spec_ident);
            let has_args = !query_args(feature, query, module).is_empty();
            write_react_query_hook(&mut s, &hook_name, &spec_ident, has_args);
            let aliases = query_hook_aliases(feature, query);
            write_deprecated_react_hook_aliases(&mut s, &mut used_hook_names, &hook_name, aliases);
        }
    }

    let mut commands: Vec<&lazuli_ir::Command> = feature
        .commands
        .iter()
        .filter(|command| !command_is_pure_read(command))
        .collect();
    commands.sort_by(|a, b| a.name.cmp(&b.name));
    if !commands.is_empty() {
        writeln!(s, "// Commands").ok();
        for command in commands {
            let spec_ident = command_ident(&feature.name, &command.name);
            let hook_name = react_hook_name_for_spec(&spec_ident);
            write_react_command_hook(&mut s, &hook_name, &spec_ident);
            let aliases = command
                .previous_names
                .iter()
                .map(|name| react_hook_name_for_spec(&command_ident(&feature.name, name)))
                .collect::<Vec<_>>();
            write_deprecated_react_hook_aliases(&mut s, &mut used_hook_names, &hook_name, aliases);
        }
    }

    s
}

fn feature_react_hook_specs(feature: &lazuli_ir::Feature) -> BTreeSet<String> {
    let mut specs = BTreeSet::new();
    for command in &feature.commands {
        specs.insert(command_ident(&feature.name, &command.name));
    }
    for query in &feature.queries {
        let resource_pascal = pick_query_resource_ts(feature, query.name()).unwrap_or_else(|| {
            feature
                .resources
                .first()
                .map(|r| pascal_case(&r.name))
                .unwrap_or_else(|| pascal_case(&feature.name))
        });
        specs.insert(query_ident(
            &feature.name,
            &resource_pascal,
            react_query_kind(query),
            query.name(),
        ));
    }
    specs
}

fn collect_canonical_react_hook_names(feature: &lazuli_ir::Feature) -> BTreeSet<String> {
    feature_react_hook_specs(feature)
        .into_iter()
        .map(|spec| react_hook_name_for_spec(&spec))
        .collect()
}

fn write_react_query_hook(s: &mut String, hook_name: &str, spec_ident: &str, has_args: bool) {
    if has_args {
        writeln!(
            s,
            "export function {hook_name}(\n  args: QueryArgs<typeof {spec_ident}>,\n  options: QueryOptions<typeof {spec_ident}> = {{}},\n) {{"
        )
        .ok();
        writeln!(s, "  return useLazuliQuery({spec_ident}, args, options);").ok();
    } else {
        writeln!(
            s,
            "export function {hook_name}(\n  options: QueryOptions<typeof {spec_ident}> = {{}},\n) {{"
        )
        .ok();
        writeln!(s, "  return useLazuliQuery({spec_ident}, {{}}, options);").ok();
    }
    writeln!(s, "}}").ok();
    writeln!(s).ok();
}

fn write_react_command_hook(s: &mut String, hook_name: &str, spec_ident: &str) {
    writeln!(
        s,
        "export function {hook_name}(\n  options: CommandOptions<typeof {spec_ident}> = {{}},\n) {{"
    )
    .ok();
    writeln!(s, "  return useLazuliCommand({spec_ident}, options);").ok();
    writeln!(s, "}}").ok();
    writeln!(s).ok();
}

fn write_deprecated_react_hook_aliases(
    s: &mut String,
    used_hook_names: &mut BTreeSet<String>,
    canonical: &str,
    aliases: Vec<String>,
) {
    for alias in aliases {
        if alias == canonical || !used_hook_names.insert(alias.clone()) {
            continue;
        }
        writeln!(s, "/** @deprecated Use `{canonical}` instead. */").ok();
        writeln!(s, "export const {alias} = {canonical};").ok();
        writeln!(s).ok();
    }
}

fn query_hook_aliases(feature: &lazuli_ir::Feature, query: &lazuli_ir::Query) -> Vec<String> {
    let kind = react_query_kind(query);
    let resource_pascal = pick_query_resource_ts(feature, query.name()).unwrap_or_else(|| {
        feature
            .resources
            .first()
            .map(|r| pascal_case(&r.name))
            .unwrap_or_else(|| pascal_case(&feature.name))
    });
    let mut aliases = query_previous_names(query)
        .iter()
        .map(|name| {
            react_hook_name_for_spec(&query_ident(&feature.name, &resource_pascal, kind, name))
        })
        .collect::<Vec<_>>();

    // Compatibility with the runtime-spike React template: lookup
    // queries without an authored `lookup_` prefix used to expose
    // `use<Resource><ShortName>` (for example `useCustomerByID`).
    // The canonical SDK name is now `useLookup<Resource>By<ShortName>`.
    if kind == lazuli_ir::QueryKind::Lookup && !query.name().starts_with("lookup_") {
        aliases.push(react_hook_name_for_spec(&format!(
            "{}{}",
            lazuli_codegen_ts::lower_camel_export(&feature.name),
            pascal_case(query.name())
        )));
    }

    aliases
}

fn query_previous_names(query: &lazuli_ir::Query) -> &[String] {
    match query {
        lazuli_ir::Query::List(query) => &query.previous_names,
        lazuli_ir::Query::Lookup(query) => &query.previous_names,
        lazuli_ir::Query::Sql(query) => &query.previous_names,
        // query.compose: W2/W3 — previous_names accessor is real.
        lazuli_ir::Query::Compose(query) => &query.previous_names,
    }
}

fn react_query_kind(query: &lazuli_ir::Query) -> lazuli_ir::QueryKind {
    match query {
        lazuli_ir::Query::List(_) => lazuli_ir::QueryKind::List,
        lazuli_ir::Query::Lookup(_) => lazuli_ir::QueryKind::Lookup,
        lazuli_ir::Query::Sql(_) => lazuli_ir::QueryKind::Sql,
        // query.compose: W4/W6 — `QueryKind` (a surface/inspect enum) has no
        // `Compose` arm yet; that lands with the LSP/inspect cells. A compose
        // read is SELECT-shaped, so map to `Sql` until then to keep TS hook
        // generation panic-free for features that mix compose with others.
        lazuli_ir::Query::Compose(_) => lazuli_ir::QueryKind::Sql,
    }
}

fn react_hook_name_for_spec(spec_ident: &str) -> String {
    format!("use{}", pascal_case(spec_ident))
}
