// Code generated by lazuli; DO NOT EDIT.
// React hooks for browser-side @cap.File upload orchestration.

import { useCallback, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { LazuliError } from "@lazuli/runtime";
import { useLazuliCommand, useLazuliQuery } from "@lazuli/runtime/react";
import {
  clearHostProfilePhoto,
  confirmHostProfilePhotoUpload,
  getHostProfilePhotoURL,
  requestHostProfilePhotoUpload,
} from "./host.gen";

function lazuliFileMimeAccepted(accept: readonly string[], contentType: string): boolean {
  const [gotFamily, gotSubtype] = contentType.split("/");
  if (!gotFamily || !gotSubtype) return false;
  return accept.some((entry) => {
    const [family, subtype] = entry.split("/");
    const familyMatches = family === "*" || family === gotFamily;
    const subtypeMatches = subtype === "*" || subtype === gotSubtype;
    return familyMatches && subtypeMatches;
  });
}

function lazuliFileSizeExceeded(maxBytes: number, gotBytes: number): LazuliError {
  return new LazuliError(400, {
    code: "file_size_exceeded",
    message: `file exceeds max size of ${maxBytes} bytes (got ${gotBytes})`,
    message_key: "file_size_exceeded",
    data: { max_bytes: maxBytes, got_bytes: gotBytes },
  });
}

function lazuliFileMimeRejected(accept: readonly string[], got: string): LazuliError {
  return new LazuliError(400, {
    code: "file_mime_rejected",
    message: `content type "${got}" is not in accept list ${accept.join(", ")}`,
    message_key: "file_mime_rejected",
    data: { got, accept: [...accept] },
  });
}

function lazuliUploadPutFailed(status: number, statusText: string): LazuliError {
  return new LazuliError(status, {
    code: "bad_request",
    message: `file upload PUT failed with status ${status} ${statusText}`,
    data: { status, status_text: statusText },
  });
}

const HOST_PROFILE_PHOTO_UPLOAD_ACCEPT = ["image/jpeg", "image/png"] as const;
const HOST_PROFILE_PHOTO_UPLOAD_DEFAULT_INVALIDATES = ["host.lookup_my_host"] as const;

export type HostProfilePhotoUploadOptions = {
  /** Override default invalidation; defaults to the field's lookup_my query. */
  invalidates?: string[];
  onSuccess?: () => void;
  onError?: (err: unknown) => void;
};

export type HostProfilePhotoUploadResult = {
  photoUri: string | null;
  isUploading: boolean;
  error: unknown;
  uploadFile: (file: File) => Promise<void>;
  removeFile: () => Promise<void>;
};

export function useHostProfilePhotoUpload(opts: HostProfilePhotoUploadOptions = {}): HostProfilePhotoUploadResult {
  const queryClient = useQueryClient();
  const [putInFlight, setPutInFlight] = useState(false);
  const [localError, setLocalError] = useState<unknown>(null);
  const invalidates = opts.invalidates ?? HOST_PROFILE_PHOTO_UPLOAD_DEFAULT_INVALIDATES;
  const onSuccess = opts.onSuccess;
  const onError = opts.onError;

  const requestUpload = useLazuliCommand(requestHostProfilePhotoUpload);
  const confirmUpload = useLazuliCommand(confirmHostProfilePhotoUpload);
  const clearUpload = useLazuliCommand(clearHostProfilePhoto);
  const displayUrl = useLazuliQuery(getHostProfilePhotoURL, {});

  const invalidateUploadTargets = useCallback(async () => {
    await Promise.all([
      ...invalidates.map((name) => queryClient.invalidateQueries({ queryKey: ["lazuli", name] })),
      queryClient.invalidateQueries({ queryKey: ["lazuli", getHostProfilePhotoURL.name] }),
    ]);
  }, [invalidates, queryClient]);

  const uploadFile = useCallback(async (file: File) => {
    const contentType = file.type || "application/octet-stream";
    try {
      setLocalError(null);
      if (file.size > 5242880) {
        throw lazuliFileSizeExceeded(5242880, file.size);
      }
      if (!lazuliFileMimeAccepted(HOST_PROFILE_PHOTO_UPLOAD_ACCEPT, contentType)) {
        throw lazuliFileMimeRejected(HOST_PROFILE_PHOTO_UPLOAD_ACCEPT, contentType);
      }
      const upload = await requestUpload.mutateAsync({ contentType, sizeBytes: file.size });
      const headers: Record<string, string> = {};
      if (upload.headersContentType) {
        headers["Content-Type"] = upload.headersContentType;
      }
      setPutInFlight(true);
      try {
        const put = await fetch(upload.url, {
          method: upload.method || "PUT",
          headers,
          body: file,
        });
        if (!put.ok) {
          throw lazuliUploadPutFailed(put.status, put.statusText);
        }
      } finally {
        setPutInFlight(false);
      }
      await confirmUpload.mutateAsync({ key: upload.key });
      await invalidateUploadTargets();
      await displayUrl.refetch();
      onSuccess?.();
    } catch (err) {
      setLocalError(err);
      onError?.(err);
      throw err;
    }
  }, [confirmUpload, displayUrl, invalidateUploadTargets, onError, onSuccess, requestUpload]);

  const removeFile = useCallback(async () => {
    try {
      setLocalError(null);
      await clearUpload.mutateAsync({});
      await invalidateUploadTargets();
      await displayUrl.refetch();
      onSuccess?.();
    } catch (err) {
      setLocalError(err);
      onError?.(err);
      throw err;
    }
  }, [clearUpload, displayUrl, invalidateUploadTargets, onError, onSuccess]);

  const error = localError ?? requestUpload.error ?? confirmUpload.error ?? clearUpload.error ?? displayUrl.error ?? null;
  const isUploading = requestUpload.isPending || confirmUpload.isPending || clearUpload.isPending || putInFlight;

  return {
    photoUri: displayUrl.data?.url ?? null,
    isUploading,
    error,
    uploadFile,
    removeFile,
  };
}

