[package]
name = "lazuli_lsp"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
lazuli_analyzer = { path = "../lazuli_analyzer" }
lazuli_doctor = { path = "../lazuli_doctor" }
lazuli_ir = { path = "../lazuli_ir" }
lazuli_keywords = { path = "../lazuli_keywords" }
lazuli_syntax = { path = "../lazuli_syntax" }
tokio.workspace = true
tower-lsp.workspace = true

[dev-dependencies]
serde_json.workspace = true
