//! Reachability gate: every NON-EMPTY generated `#kw-*` repository group in
//! the VS Code grammar MUST be transitively reachable from the top-level
//! `patterns` array.
//!
//! # Why this exists
//!
//! The `#kw-*` keyword-alternation rules are GENERATED by
//! `cargo xtask gen-tmlanguage` from `lazuli_keywords::ALL`, but the wiring
//! (which structural `begin/end` block `include`s which generated rule) is
//! hand-written. The freshness gate (`tmlanguage_fresh.rs`) only checks that
//! the generated section is byte-identical to the registry projection — it
//! says NOTHING about whether each generated rule is actually referenced.
//!
//! A generated `#kw-foo` group that is emitted into `repository` but never
//! `#include`d from any pattern reachable from `patterns` is **orphaned**: its
//! keywords never match at runtime, so they render with no color. This is
//! silent — the grammar is valid JSON, the parity gate passes, and the bug
//! only shows up as "this keyword has no syntax highlighting" in the editor.
//!
//! This test makes orphaning impossible: it BFS-walks every `"include":"#x"`
//! edge from the top-level `patterns` through `repository`, collects the
//! reachable repository keys, then asserts every NON-EMPTY `kw-*` group is in
//! the reachable set. On failure it lists the unreachable group names.
//!
//! Empty groups (an alternation with no literals, `^\s+()\b`) are vacuously OK
//! — a registry context can legitimately have zero rows of a given
//! sigil-shape — so they are excluded from the assertion.

use std::collections::{HashSet, VecDeque};
use std::path::PathBuf;

use serde_json::Value;

/// Path to the committed grammar, relative to the workspace root.
const GRAMMAR_REL: &str = "editors/vscode/syntaxes/lazuli.tmLanguage.json";

fn workspace_root() -> PathBuf {
    // CARGO_MANIFEST_DIR is .../tools/xtask; climb two levels to the root.
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.pop(); // xtask
    p.pop(); // tools
    p
}

/// Collect every `"include": "#name"` reference found anywhere inside `node`
/// (recursively), stripping the leading `#`. Self-references and external
/// (`$self`-style or non-`#`) includes are ignored.
fn collect_includes(node: &Value, out: &mut Vec<String>) {
    match node {
        Value::Array(items) => {
            for item in items {
                collect_includes(item, out);
            }
        }
        Value::Object(map) => {
            for (key, value) in map {
                if key == "include" {
                    if let Value::String(s) = value
                        && let Some(name) = s.strip_prefix('#')
                    {
                        out.push(name.to_string());
                    }
                } else {
                    collect_includes(value, out);
                }
            }
        }
        _ => {}
    }
}

/// Whether a `kw-*` repository rule has at least one keyword literal in its
/// alternation. A generated rule's `match` is `^\s+(<lit>|<lit>|...)\b`; an
/// empty group serializes as `^\s+()\b` (nothing between the parens). We treat
/// "contains a lowercase-ident or `_` character inside the alternation parens"
/// as non-empty, which is robust to the longest-first ordering.
fn is_non_empty_kw_rule(rule: &Value) -> bool {
    let Some(m) = rule.get("match").and_then(Value::as_str) else {
        return false;
    };
    // Find the alternation body between the first '(' and the matching close
    // before the trailing `\b`. Cheap heuristic: any ident char after a '('.
    let Some(open) = m.find('(') else {
        return false;
    };
    let body = &m[open + 1..];
    body.chars()
        .take_while(|&c| c != ')')
        .any(|c| c.is_ascii_lowercase() || c.is_ascii_uppercase() || c == '_')
}

#[test]
fn every_nonempty_kw_group_is_reachable() {
    let grammar_path = workspace_root().join(GRAMMAR_REL);
    let raw = std::fs::read_to_string(&grammar_path)
        .unwrap_or_else(|e| panic!("reading {}: {e}", grammar_path.display()));
    let grammar: Value = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("parsing {} as JSON: {e}", grammar_path.display()));

    let repository = grammar
        .get("repository")
        .and_then(Value::as_object)
        .unwrap_or_else(|| panic!("grammar has no `repository` object"));

    // BFS seed: every include reachable from the top-level `patterns` array.
    let mut seen: HashSet<String> = HashSet::new();
    let mut queue: VecDeque<String> = VecDeque::new();
    if let Some(patterns) = grammar.get("patterns") {
        let mut seeds = Vec::new();
        collect_includes(patterns, &mut seeds);
        for s in seeds {
            if seen.insert(s.clone()) {
                queue.push_back(s);
            }
        }
    }

    // BFS through repository following every include edge.
    while let Some(key) = queue.pop_front() {
        let Some(rule) = repository.get(&key) else {
            continue;
        };
        let mut children = Vec::new();
        collect_includes(rule, &mut children);
        for child in children {
            if seen.insert(child.clone()) {
                queue.push_back(child);
            }
        }
    }

    // Every NON-EMPTY `kw-*` group (excluding the `_kw_generated_*` sentinels)
    // must be in the reachable set.
    let mut orphans: Vec<String> = repository
        .iter()
        .filter(|(k, _)| k.starts_with("kw-"))
        .filter(|(_, v)| is_non_empty_kw_rule(v))
        .filter(|(k, _)| !seen.contains(k.as_str()))
        .map(|(k, _)| k.clone())
        .collect();
    orphans.sort();

    assert!(
        orphans.is_empty(),
        "{} non-empty generated `#kw-*` group(s) are ORPHANED — emitted into \
         `repository` but never `#include`d from any pattern reachable from the \
         top-level `patterns`. Their keywords render with NO color. Wire each \
         into the semantically correct block's `patterns` (or the top-level \
         `patterns` for single-line decl contexts):\n  {}",
        orphans.len(),
        orphans.join("\n  ")
    );
}
