//! Rich Markdown hovers for the canonical-kind keywords:
//! `command`, `query.list`, `query.lookup`, `query.sql`, `query.view`,
//! `api`, `policy`, `effect`.

pub(super) fn rich_canonical_kind_hover(keyword: &str) -> Option<String> {
    match keyword {
        "command" => Some(
            [
                "**`command`** — write operation on an aggregate. Lazuli owns the contract; the runtime emits a typed handler that runs effects, emits events, and invalidates queries.",
                "",
                "**Required children**",
                "- `policy @policy.<name>` — feature-local authorization category.",
                "- An effect line — exactly one of `creates`/`updates`/`deletes`, or a non-mutating `returns <Record>` shape.",
                "",
                "**Optional children**",
                "- `input` / short-form `input name, email` — submitted fields.",
                "- `route <name>: <Type>` — URL/context slots.",
                "- `rate_limit \"<N> per <window> per <axis>\"` — required when the policy includes `@scope.public` or the command mutates state.",
                "- `audit` / `audit <field>+` / `audit none` — audit-log contract.",
                "- `emits <event> [from creates|updates|deletes]` — domain event publication.",
                "- `invalidates query.<name>` — cache fan-out.",
                "- `approval` — conditional human sign-off block.",
                "- `validate @validator.<name>` — blocking validator.",
                "",
                "**Example**",
                "```lazuli",
                "command create",
                "  input",
                "    name: Text required",
                "  policy @policy.create",
                "  rate_limit \"30 per hour per ip\"",
                "  creates Customer",
                "    name = input.name",
                "  emits customer_created from creates",
                "```",
                "",
                "See [quickref.md §Minimal Feature](docs/quickref.md) and [invariants.md §Security And Crypto](docs/invariants.md).",
                "",
                "**Inspect**: `lazuli inspect <file> --expand=commands` projects this declaration's typed IR slice (route + input + policy + audit + approval + invalidates + external_calls + rate_limit + timeout/retry/idempotency).",
            ]
            .join("\n"),
        ),
        "query.list" => Some(
            [
                "**`query.list`** — generated collection query. Defaults to `order created_at desc`; simple equality filters derive language-managed indexes.",
                "",
                "**Required children**",
                "- None at the syntax level — a bare `query.list <name>` is valid.",
                "",
                "**Optional children**",
                "- `params` — typed read arguments.",
                "- `filters` — equality / `when params.*` filter rows; derives indexes.",
                "- `search params.<name> over <field>...` with `mode contains|prefix|exact` — text matching (does not derive indexes).",
                "- `order <field> asc|desc` — override the `created_at desc` default.",
                "- `paginate <positive-int>` — generated default page size, not a hard maximum.",
                "- `cache key <expr> ttl <duration>` (+ optional `tags`, `namespace`).",
                "- `scope override` (+ `reason`) — cross-tenant / admin queries.",
                "- `policy @policy.<name>` — explicit category (required under `scope override`).",
                "- `modifier @query_modifier.<name>` — query-modifier extension.",
                "",
                "**Example**",
                "```lazuli",
                "query.list list",
                "  params",
                "    status: CustomerStatus optional",
                "  filters",
                "    status when params.status",
                "  paginate 50",
                "```",
                "",
                "See [quickref.md §Queries](docs/quickref.md) and [invariants.md §Queries And Relations](docs/invariants.md).",
                "",
                "**Inspect**: `lazuli inspect <file> --expand=queries` projects every lifted query (List / Lookup / Sql) with its full v0 child coverage.",
            ]
            .join("\n"),
        ),
        "query.lookup" => Some(
            [
                "**`query.lookup`** — generated single-record query. Single-key form sugars to `query.lookup <name> by <field>: <Type>`; composite/reshaped lookups use a `params`/`key` body.",
                "",
                "**Required slots**",
                "- A key spec — either `by <field>: <Type>` (single-key sugar) or a `params`/`key` body for composite lookups.",
                "",
                "**Optional children**",
                "- `params` — composite-key arguments (when `by` shorthand is not used).",
                "- `key` — explicit key composition for composite lookups.",
                "- `policy @policy.<name>` — explicit category.",
                "- `cache key <expr> ttl <duration>`.",
                "- `scope override` (+ `reason`) — cross-tenant lookups.",
                "",
                "**Example**",
                "```lazuli",
                "query.lookup by_id by id: ID",
                "",
                "query.lookup by_email by email: @semantic.Email",
                "```",
                "",
                "See [quickref.md §Queries](docs/quickref.md) and [invariants.md §Queries And Relations](docs/invariants.md).",
                "",
                "**Inspect**: `lazuli inspect <file> --expand=queries` includes Lookup queries alongside List/Sql.",
            ]
            .join("\n"),
        ),
        "query.sql" => Some(
            [
                "**`query.sql`** — SQL-backed query wrapper. The result type must resolve to a `record`, resource, or registered contract before codegen; Lazuli does not infer result shape from SQL text.",
                "",
                "**Required children**",
                "- `returns <Type>` or `returns <Type>[]` — must resolve to a `record`, resource, or contract.",
                "- `sql \"./queries/<name>.sql\"` — relative path to the SQL file.",
                "",
                "**Optional children**",
                "- `params` — typed query arguments referenced inside the SQL file.",
                "- `scope` — tenancy or filter scope applied at codegen.",
                "- `policy @policy.<name>` — explicit category.",
                "- `cache key <expr> ttl <duration>`.",
                "",
                "**Example**",
                "```lazuli",
                "query.sql lifetime_value",
                "  returns CustomerLtv[]",
                "  scope",
                "    org = ctx.user.org",
                "  sql \"./queries/customer_lifetime_value.sql\"",
                "```",
                "",
                "See [quickref.md §Queries](docs/quickref.md) and [invariants.md §Queries And Relations](docs/invariants.md).",
                "",
                "**Inspect**: `lazuli inspect <file> --expand=queries` includes Sql queries alongside List/Lookup.",
            ]
            .join("\n"),
        ),
        "query.view" => Some(
            [
                "**`query.view`** — typed SQL-backed screen-read projection. Use it for denormalized reads whose row shape is declared as a local `record`.",
                "",
                "**Required children**",
                "- `returns list of <Record>` or `returns <Record>` — typed row shape for the generated SDK.",
                "- `source @file.<name>.sql` — SQL file under the feature `queries/` directory.",
                "",
                "**Optional children**",
                "- `policy @policy.<name>` — explicit category.",
                "- `params` — typed query arguments bound to SQL placeholders in source order.",
                "- `scope` — tenancy or filter scope applied at codegen.",
                "",
                "**Example**",
                "```lazuli",
                "query.view host_home_view",
                "  policy @policy.host_only",
                "  returns list of HostHomeRow",
                "  source @file.host_home_view.sql",
                "  params",
                "    user_id: ID required",
                "```",
                "",
                "See [quickref.md §Queries](docs/quickref.md) and [invariants.md §Queries And Relations](docs/invariants.md).",
            ]
            .join("\n"),
        ),
        "api" => Some(
            [
                "**`api`** — custom typed HTTP endpoint outside `command`/`query`/`webhook` semantics. Use it when the handler does meaningful work beyond translating HTTP to a single dispatch; otherwise prefer `expose http` on an `agent` or a generated command/query.",
                "",
                "**Required children**",
                "- `method <GET|POST|PUT|PATCH|DELETE>` — HTTP verb.",
                "- `path \"<url>\"` — concrete URL path; `:slot` placeholders bind via `route`.",
                "- `output <Type>` — response shape (record, resource, or `@cap.File(...)`).",
                "- `policy @policy.<name>` — authorization category.",
                "- `handler @fn.<name>` or `handler \"./path.go\"` — handler reference.",
                "",
                "**Optional children**",
                "- `input <Type>` — request body shape.",
                "- `route <name>: <Type>` — one per `:slot` placeholder.",
                "- `rate_limit \"<N> per <window> per <axis>\"` — per-call throttle (required when policy includes `@scope.public`).",
                "- `audit` / `audit <field>+` / `audit none`.",
                "",
                "**Example**",
                "```lazuli",
                "api me",
                "  method GET",
                "  path \"/me\"",
                "  output User",
                "  policy @policy.authenticated",
                "  handler @fn.me",
                "```",
                "",
                "See [quickref.md §Security Checklist](docs/quickref.md) and [invariants.md §Security And Crypto](docs/invariants.md).",
                "",
                "**Inspect**: `lazuli inspect <file> --expand=apis` (or `--expand=api`) projects every lifted Api with method + path + output + policy + handler + locale_negotiate.",
            ]
            .join("\n"),
        ),
        "policy" => Some(
            [
                "**`policy`** — feature-local authorization category reference on a `command`/`query`/`api`/`webhook`/`job`. The category resolves against the same feature's `policies` block unless feature-qualified.",
                "",
                "**Forms**",
                "- `policy @policy.<name>` — single category from the feature `policies` dictionary.",
                "- `policy @policy.<feature>.<name>` — cross-feature category (rarely needed).",
                "- On `policies` entry lines (atom decomposition): `<category>: <atom>[, <atom>]+` where each atom is `@role.*`, `@scope.*`, or `@actor.*`.",
                "- Predicate combinators inside categories: comma = OR, `and` = AND, parentheses for grouping (canonical closed predicate language).",
                "",
                "**Rules**",
                "- Commands declare `policy` explicitly — there is no implicit `creates -> @policy.create`.",
                "- Direct atoms (`@role.*`, `@scope.*`, `@actor.*`) belong in `policies` entries, not on individual command lines. Jobs / webhooks / escape routes may use atoms directly where appropriate.",
                "",
                "**Example**",
                "```lazuli",
                "policies",
                "  create: @role.admin, @role.sales",
                "  read: @scope.same_org",
                "",
                "command reassign",
                "  policy @policy.update",
                "```",
                "",
                "See [quickref.md §Policy Vocabulary](docs/quickref.md) and [invariants.md §Policies](docs/invariants.md).",
            ]
            .join("\n"),
        ),
        "effect" => Some(
            [
                "**`effect`** — write effect on a `command`. The closed catalog is `creates` / `updates` / `deletes` / `returns`. Exactly one mutating effect per command; `returns` is non-mutating.",
                "",
                "**Closed catalog**",
                "- `creates <Resource>` — new row; body assigns input/derived values to fields.",
                "- `updates <Resource>` — mutates the loaded `target`; body assigns changed fields.",
                "- `deletes <Resource>` — removes the loaded `target`. Soft-delete is automatic when the resource declares `soft_delete`.",
                "- `returns <Record>` — non-mutating command (no row write); the handler returns a typed record.",
                "",
                "**Rules**",
                "- One mutating effect per command. Multi-effect commands are rejected.",
                "- `target` is loaded before `updates`/`deletes` (explicit `target query.by_id(...)` or sugar when route/lookup match).",
                "- Event derivation works with effects: `emits <event> from creates|updates|deletes` maps the effect's bindings into the event payload by name.",
                "",
                "**Example**",
                "```lazuli",
                "command create",
                "  policy @policy.create",
                "  creates Customer",
                "    name = input.name",
                "    email = input.email",
                "  emits customer_created from creates",
                "```",
                "",
                "See [quickref.md §Canonical Sugar Table](docs/quickref.md) and [invariants.md §Source And Derived Views](docs/invariants.md).",
            ]
            .join("\n"),
        ),
        _ => None,
    }
}
