//! Rich Markdown hovers for the IR Error-Vocab keywords: `errors`,
//! `when_denied`, `message_key`. See
//! `docs/proposals/ir-error-messages-vocab.md` §7.2.

pub(super) fn rich_error_vocab_hover(keyword: &str) -> Option<String> {
    match keyword {
        "errors" => Some(
            [
                "**`errors`** — feature-level error contract. Combines (1) wire exposure rules and (2) typed per-code message overrides.",
                "",
                "**Children**",
                "- `default hide` | `default expose` — wire-envelope default for `message`/`data`/`message_key`. `hide` is the secure default.",
                "- `expose client 4xx <fields>` — comma-separated closed catalog: `message`, `code`, `data`, `message_key`.",
                "- `expose client 5xx <fields>` — comma-separated closed catalog: `code`, `data`. (`message` deliberately excluded — 5xx text is framework-internal.)",
                "- `<code> message @translation.<key>` — per-code typed override. Closed catalog of 12 codes: `policy_denied`, `validation_failed`, `tenant_mismatch`, `not_found`, `rate_limited`, `bad_request`, `method_not_allowed`, `integration_error`, `unique_violation`, `foreign_key_violation`, `not_null_violation`, `check_violation`.",
                "",
                "**Resolution chain** (proposal §2.E)",
                "1. `command.policy_when_denied` — per-command override.",
                "2. `policies.<category>.when_denied` — per-policy default.",
                "3. `feature.errors.<code> message` — per-feature catch-all (this block).",
                "4. Runtime built-in PT-BR / en-US catalog — framework floor.",
                "",
                "**Example**",
                "```lazuli",
                "feature account",
                "  errors",
                "    default hide",
                "    expose client 4xx message, code, message_key",
                "    expose client 5xx code",
                "    policy_denied      message @translation.account_signin_required",
                "    validation_failed  message @translation.account_invalid_input",
                "```",
                "",
                "Doctor: `ERR-VOCAB-001`/`002`/`003`, `ERR-VOCAB-CODE-UNKNOWN`, `ERR-VOCAB-EXPOSE-UNKNOWN`, `ERR-VOCAB-EXPOSE-5XX-MESSAGE`.",
            ]
            .join("\n"),
        ),
        "when_denied" => Some(
            [
                "**`when_denied`** — typed override for the `policy_denied` error message rendered to the wire. Two attachment sites:",
                "",
                "- Under a `command.policy` line — per-command override (resolution-chain step 1).",
                "- Under a `policies.<category>:` line — per-policy default (resolution-chain step 2).",
                "",
                "**Shape**",
                "- `when_denied @translation.<key>` — references a key declared in the surrounding feature's `translation` block.",
                "",
                "**Resolution chain** (proposal §2.E)",
                "1. `command.policy_when_denied` (this site, on a `command.policy` line).",
                "2. `policies.<category>.when_denied` (this site, on a `policies` entry).",
                "3. `feature.errors.policy_denied message`.",
                "4. Runtime built-in localized message.",
                "",
                "**Example**",
                "```lazuli",
                "feature account",
                "  policies",
                "    authenticated: @scope.authenticated",
                "      when_denied @translation.must_be_signed_in",
                "",
                "  command choose_role",
                "    policy @policy.authenticated",
                "      when_denied @translation.choose_role_signin_required",
                "```",
                "",
                "Doctor: `ERR-VOCAB-001` (warn, no override anywhere), `ERR-VOCAB-002` (error, key unresolved), `ERR-VOCAB-WHEN-DENIED-NO-POLICY` (error, attached to a command without a `policy`).",
            ]
            .join("\n"),
        ),
        "message_key" => Some(
            [
                "**`message_key`** — opt-in 4xx wire-envelope field exposing the resolved `@translation.<key>` token alongside `message`. Lets clients with offline catalogs (native mobile apps, kiosks) localize independently from the server-rendered string.",
                "",
                "**Shape**",
                "- Listed inside `expose client 4xx <fields>` in a feature's `errors` block.",
                "- Always namespaced on the wire: `<feature>.<key>` (e.g. `account.choose_role_signin_required`).",
                "",
                "**Example**",
                "```lazuli",
                "feature account",
                "  errors",
                "    expose client 4xx message, code, message_key",
                "    policy_denied message @translation.account_signin_required",
                "```",
                "",
                "Wire payload:",
                "```json",
                "{",
                "  \"code\": \"policy_denied\",",
                "  \"message\": \"Para escolher seu papel, entre na sua conta primeiro.\",",
                "  \"message_key\": \"account.account_signin_required\"",
                "}",
                "```",
                "",
                "Closed-catalog field — alternatives (`message`, `code`, `data`) live under the same parent. Doctor: `ERR-VOCAB-EXPOSE-UNKNOWN` rejects unknown fields.",
            ]
            .join("\n"),
        ),
        _ => None,
    }
}
