//! Rich Markdown hovers for the security-shape keywords: `audit`,
//! `rate_limit`, and `error_page`.

pub(super) fn rich_security_hover(keyword: &str) -> Option<String> {
    match keyword {
        "audit" => Some(
            [
                "**`audit`** — declares an operation as audited so generated audit-log codegen has a typed contract instead of relying on event-name conventions. Surfaces in `lazuli inspect --expand=security`.",
                "",
                "**Forms**",
                "- `audit` — emit the default audit fields (`actor`, `tenant`, `target.id`, `ctx.now`).",
                "- `audit <field>, <field>, ...` — explicit field list. Each entry resolves against the command's binding namespaces (`input.*`, `route.*`, `target.*`, `ctx.*`, `payload.*`, etc.).",
                "- `audit none` — opt out of audit-log generation. Doctor records the opt-out so security review can see it.",
                "",
                "**Optional child**",
                "- `emit_to <stream>` — direct audit emission to a specific stream (e.g. `audit_log`).",
                "",
                "**Rules**",
                "- Valid on `command`, `query.*`, `job`, `webhook`, and `report` (and `api` via `policy` linkage).",
                "- Audit declarations do not replace `emits`; events and audits are different contracts.",
                "",
                "**Example**",
                "```lazuli",
                "command reassign",
                "  policy @policy.update",
                "  audit actor, target.id, input.owner_id",
                "    emit_to audit_log",
                "  updates Customer",
                "    owner = resolved_owner",
                "```",
                "",
                "See [invariants.md §Source And Derived Views](docs/invariants.md) (audit fields paragraph) and [quickref.md §Security Checklist](docs/quickref.md).",
            ]
            .join("\n"),
        ),
        "rate_limit" => Some(
            [
                "**`rate_limit`** — per-call throttle on a `command`, `api`, `agent.expose http`, or `auth password`. Distinct from `notification.throttle` (which keys on recipient/channel axes).",
                "",
                "**Grammar**",
                "- `rate_limit \"<N> per <window> per <axis>\"`",
                "- `<N>` — positive integer.",
                "- `<window>` — duration string (`second`, `minute`, `hour`, `day`, or `<N> <unit>` like `\"5 10 minutes\"` for explicit count).",
                "- `<axis>` — closed catalog: `ip`, `user`, `org`, `tenant`.",
                "- `rate_limit none` (with `reason \"...\"`) — explicit opt-out; required when the strict security profile demands a decision.",
                "",
                "**When required**",
                "- Commands that mutate state.",
                "- Commands / APIs whose effective policy includes `@scope.public`.",
                "- `auth password` flows.",
                "",
                "**Example**",
                "```lazuli",
                "command create",
                "  policy @policy.create",
                "  rate_limit \"30 per hour per ip\"",
                "  creates Customer",
                "```",
                "",
                "See [quickref.md §Security Checklist](docs/quickref.md) and [invariants.md §Security And Crypto](docs/invariants.md).",
            ]
            .join("\n"),
        ),
        "error_page" => Some(
            [
                "**`error_page`** — declares a custom app-level HTTP error page once so every generated surface can share the same status response contract.",
                "",
                "**Header**",
                "- `error_page <status>` — closed catalog: `400`, `401`, `403`, `404`, `405`, `410`, `422`, `429`, `500`, `502`, `503`, `504`.",
                "",
                "**Required children**",
                "- `template \"./views/<status>.tmpl\"` — relative template path.",
                "",
                "**Optional children**",
                "- `audience <name>` — route audience that can see this page, commonly `public`.",
                "",
                "**Example**",
                "```lazuli",
                "app MyApp",
                "  error_page 404",
                "    template \"./views/404.tmpl\"",
                "    audience public",
                "```",
                "",
                "Doctor: `error-page-contract`, `error-page-template-missing`, `error-page-duplicate`.",
            ]
            .join("\n"),
        ),
        _ => None,
    }
}
