//! Feature-vocabulary diagnostics — bare-shape checks that live at the
//! intersection of source lexicon and IR vocabulary.
//!
//! Four producers in one file because they all walk top-level
//! `feature` / `non_goals` / `defaults` / `policies` lines looking for
//! lexical mismatches against the closed catalog:
//!
//! - `summary-generated` — `summary` is generated by `lazuli inspect`;
//!   authors must not author it in canonical source.
//! - `non-goals-shape` — `non_goals` entries must be either bare quoted
//!   strings (flat shape) or grouped under `delegated_to` /
//!   `out_of_scope` (partitioned shape).
//! - `defaults-policy-for` — `defaults` blocks should use `policy_for
//!   <kinds>: <atom>`, not the deprecated `policy <atom>` form.
//! - `namespace-catalog` — every `@...` reference must use one of the
//!   allowed reference namespaces (`@role`, `@scope`, `@actor`, …); the
//!   set is kept in registry-parity with `lazuli_keywords` `@`-decorators
//!   by `registry_decorator_namespaces_are_allowed_references`.
//!
//! `namespace_references` + `is_allowed_reference_namespace` are
//! pub(crate) so the policy / lazurite_manifest aggregators can reuse
//! the namespace scanner.

use tower_lsp::lsp_types::{Diagnostic, DiagnosticSeverity};

use crate::{leading_spaces, simple_canonical_diagnostic};

pub(crate) fn generated_summary_diagnostics(source: &str) -> Vec<Diagnostic> {
    let mut diagnostics = Vec::new();

    for (line_index, line) in source.lines().enumerate() {
        let trimmed = line.trim_start();
        if leading_spaces(line) == 2 && trimmed == "summary" {
            diagnostics.push(simple_canonical_diagnostic(
                line_index,
                line,
                DiagnosticSeverity::WARNING,
                "summary-generated",
                "`summary` is generated by `lazuli inspect --expand=summary`; do not author it in canonical source.",
            ));
        }
    }

    diagnostics
}

pub(crate) fn non_goals_shape_diagnostics(source: &str) -> Vec<Diagnostic> {
    let mut diagnostics = Vec::new();
    let mut in_non_goals = false;

    for (line_index, line) in source.lines().enumerate() {
        let trimmed = line.trim_start();

        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        if leading_spaces(line) == 2 {
            in_non_goals = trimmed == "non_goals";
            continue;
        }

        if !in_non_goals {
            continue;
        }

        if leading_spaces(line) == 4 {
            if matches!(trimmed, "delegated_to" | "out_of_scope") {
                continue;
            }
            // Iron-hand context vocabulary — the flat quoted-string
            // form is the preferred canonical shape for new features
            // (see `docs/canonical-semantics.md#feature-context-vocabulary`).
            // Partitioned `delegated_to` / `out_of_scope` blocks stay
            // valid for the existing fixture but are no longer the only
            // shape worth surfacing. Only flag bareword `key: value`
            // entries that match neither the flat shape nor the
            // partitioned shape.
            if trimmed.starts_with('"') {
                continue;
            }

            diagnostics.push(simple_canonical_diagnostic(
                line_index,
                line,
                DiagnosticSeverity::WARNING,
                "non-goals-shape",
                "`non_goals` entries must be either bare quoted strings (flat shape) or grouped under `delegated_to` / `out_of_scope` (partitioned shape). See docs/canonical-semantics.md#feature-context-vocabulary.",
            ));
        }
    }

    diagnostics
}

pub(crate) fn defaults_policy_syntax_diagnostics(source: &str) -> Vec<Diagnostic> {
    let mut diagnostics = Vec::new();
    let mut in_defaults = false;

    for (line_index, line) in source.lines().enumerate() {
        let trimmed = line.trim_start();

        if leading_spaces(line) == 2 {
            in_defaults = trimmed == "defaults";
            continue;
        }

        if !in_defaults || leading_spaces(line) != 4 || trimmed.is_empty() {
            continue;
        }

        if trimmed.starts_with("policy ") {
            diagnostics.push(simple_canonical_diagnostic(
                line_index,
                line,
                DiagnosticSeverity::WARNING,
                "defaults-policy-for",
                "feature-level policy defaults should use `policy_for jobs, webhooks: @actor.system` so the fallback scope is explicit.",
            ));
        }
    }

    diagnostics
}

pub(crate) fn namespace_reference_diagnostics(source: &str) -> Vec<Diagnostic> {
    let mut diagnostics = Vec::new();
    // SPEC-01: the allow-list message derives from the single source
    // (`lazuli_keywords::REFERENCE_NAMESPACES`) instead of a hand-kept copy.
    let allowed = lazuli_keywords::REFERENCE_NAMESPACES
        .iter()
        .map(|n| format!("`@{n}`"))
        .collect::<Vec<_>>()
        .join(", ");

    for (line_index, line) in source.lines().enumerate() {
        // skip comment lines — an `@info.x` in a comment is documentation,
        // not an IR ref. Likewise skip the `@doctor.allow(...)` waiver node: its
        // CODE arg (e.g. `@info.record_column_jsonb`) and reason prose are opaque
        // diagnostic text, not IR namespace references (spec 0028 Gap A). The
        // `doctor` head itself is allowed; this also covers an `@<ns>` token
        // carried inside the code/reason.
        let trimmed = line.trim_start();
        if trimmed.starts_with('#')
            || lazuli_syntax::doctor_allow::line_is_doctor_allow_node(trimmed)
        {
            continue;
        }
        for namespace in namespace_references(line) {
            if !is_allowed_reference_namespace(namespace) {
                diagnostics.push(simple_canonical_diagnostic(
                    line_index,
                    line,
                    DiagnosticSeverity::WARNING,
                    "namespace-catalog",
                    &format!("unknown `@...` namespace. Allowed namespaces: {allowed}."),
                ));
                break;
            }
        }
    }

    diagnostics
}

/// VOCAB-SCALAR-ALIAS-001 — a field/slot type written with a non-canonical
/// scalar alias (`Int`/`Bool`/`Float`/`String`/`Id`/`Json`). The analyzer still
/// resolves these, but silently — this surfaces them with the canonical fix so
/// the alias never reaches the IR unannounced (`lazuli fmt` normalizes them).
pub(crate) fn scalar_alias_diagnostics(source: &str) -> Vec<Diagnostic> {
    let mut diagnostics = Vec::new();
    for (line_index, line) in source.lines().enumerate() {
        let trimmed = line.trim_start();
        // A scalar alias appearing inside a waiver reason (e.g. a code like
        // `...: Int ...` quoted in prose) is not an authored type position
        // (spec 0028 Gap A).
        if trimmed.starts_with('#')
            || lazuli_syntax::doctor_allow::line_is_doctor_allow_node(trimmed)
        {
            continue;
        }
        if let Some(alias) = type_position_alias(line) {
            let canonical = lazuli_keywords::canonical_scalar(alias).unwrap_or(alias);
            diagnostics.push(simple_canonical_diagnostic(
                line_index,
                line,
                DiagnosticSeverity::WARNING,
                "scalar-alias",
                &format!(
                    "non-canonical scalar `{alias}` — use `{canonical}` (the closed \
                     catalog spelling; `lazuli fmt` normalizes it). VOCAB-SCALAR-ALIAS-001."
                ),
            ));
        }
    }
    diagnostics
}

/// The first scalar alias appearing in a type position (`<name>: <Alias>`) on
/// the line, if any. Walks each `:` and checks the following bare word.
fn type_position_alias(line: &str) -> Option<&'static str> {
    let mut start = 0;
    while let Some(rel) = line[start..].find(':') {
        let colon = start + rel;
        let after = line[colon + 1..].trim_start();
        let word: String = after
            .chars()
            .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
            .collect();
        for &(alias, _) in lazuli_keywords::SCALAR_ALIASES {
            if word == alias {
                return Some(alias);
            }
        }
        start = colon + 1;
    }
    None
}

pub(crate) fn namespace_references(line: &str) -> Vec<&str> {
    // Mask the spans inside double-quoted string literals so e.g.
    // `requires customer.email = "ada@example.com"` does not surface
    // `@example` as a stray namespace. The scan walks the original byte
    // slice; the mask just decides which `@` positions are eligible.
    let bytes = line.as_bytes();
    let mut in_quote = false;
    let mut quote_ranges: Vec<(usize, usize)> = Vec::new();
    let mut quote_start = 0;
    for (i, b) in bytes.iter().enumerate() {
        if *b == b'"' {
            if in_quote {
                quote_ranges.push((quote_start, i + 1));
                in_quote = false;
            } else {
                quote_start = i;
                in_quote = true;
            }
        }
    }
    let in_string = |pos: usize| {
        quote_ranges
            .iter()
            .any(|(start, end)| pos >= *start && pos < *end)
    };

    let mut namespaces = Vec::new();
    let mut cursor = 0;

    while cursor < line.len() {
        let Some(rel) = line[cursor..].find('@') else {
            break;
        };
        let at_pos = cursor + rel;
        if in_string(at_pos) {
            cursor = at_pos + 1;
            continue;
        }
        let after_at = &line[at_pos + 1..];
        let Some(dot) = after_at.find('.') else {
            cursor = at_pos + 1;
            continue;
        };

        let namespace = &after_at[..dot];
        if !namespace.is_empty()
            && namespace
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
        {
            namespaces.push(namespace);
        }

        cursor = at_pos + 1 + dot + 1;
    }

    namespaces
}

pub(crate) fn is_allowed_reference_namespace(namespace: &str) -> bool {
    // SPEC-01: the closed catalog is single-sourced in `lazuli_keywords`
    // (`REFERENCE_NAMESPACES`) and gated against the registry's `@`-decorator
    // rows. The LSP and the doctor (`refs.rs`) derive from it so they cannot
    // drift apart (they previously did: LSP=23, doctor=18).
    lazuli_keywords::is_reference_namespace(namespace)
}

#[cfg(test)]
mod alias_tests {
    use super::*;

    #[test]
    fn flags_scalar_alias_in_type_position() {
        let d = scalar_alias_diagnostics("resource R\n  count: Int required\n  ok: Bool\n");
        assert_eq!(d.len(), 2, "expected Int + Bool flagged");
        assert!(
            d[0].message.contains("Integer"),
            "message was: {}",
            d[0].message
        );
    }

    #[test]
    fn ignores_canonical_types_and_comments() {
        let src = "resource R\n  count: Integer\n  # note: Int in a comment is fine\n";
        assert!(scalar_alias_diagnostics(src).is_empty());
    }

    #[test]
    fn doctor_allow_node_emits_no_namespace_catalog_warning() {
        // Spec 0028 regression: the sanctioned `@doctor.allow(...)` waiver node
        // must NOT self-inflict a `namespace-catalog` warning. The scanner
        // splits the head into namespace `doctor` + target `allow`; `doctor` is
        // now in REFERENCE_NAMESPACES, so the warning is suppressed.
        use tower_lsp::lsp_types::NumberOrString;
        let src =
            "@doctor.allow(LZI-FILE-SIZE-001, reason: \"generated\")\nfeature billing\n";
        let d = namespace_reference_diagnostics(src);
        let is_catalog = |diag: &Diagnostic| {
            matches!(&diag.code, Some(NumberOrString::String(s)) if s == "namespace-catalog")
        };
        assert!(
            !d.iter().any(is_catalog),
            "@doctor.allow should not emit a namespace-catalog warning, got: {:?}",
            d.iter().map(|x| &x.message).collect::<Vec<_>>()
        );
    }

    #[test]
    fn doctor_allow_node_with_at_info_code_arg_emits_no_namespace_catalog_warning() {
        // Spec 0028 Gap A: a CODE arg like `@info.record_column_jsonb` (namespace
        // `info` is NOT a reference namespace) must NOT self-inflict a
        // namespace-catalog warning when carried inside the waiver node.
        use tower_lsp::lsp_types::NumberOrString;
        let src =
            "@doctor.allow(@info.record_column_jsonb, reason: \"jsonb column ok\")\nfeature billing\n";
        let d = namespace_reference_diagnostics(src);
        let is_catalog = |diag: &Diagnostic| {
            matches!(&diag.code, Some(NumberOrString::String(s)) if s == "namespace-catalog")
        };
        assert!(
            !d.iter().any(is_catalog),
            "an @info.* CODE arg inside @doctor.allow must not warn, got: {:?}",
            d.iter().map(|x| &x.message).collect::<Vec<_>>()
        );
    }

    #[test]
    fn unknown_namespace_still_warns() {
        // Guard the fix doesn't over-suppress: a genuinely unknown namespace
        // still surfaces the catalog warning.
        use tower_lsp::lsp_types::NumberOrString;
        let d = namespace_reference_diagnostics("  requires @bogus.thing\n");
        let is_catalog = |diag: &Diagnostic| {
            matches!(&diag.code, Some(NumberOrString::String(s)) if s == "namespace-catalog")
        };
        assert!(
            d.iter().any(is_catalog),
            "unknown @bogus namespace must still warn"
        );
    }
}
