//! Feature-vocabulary diagnostics — bare-shape checks that live at the
//! intersection of source lexicon and IR vocabulary.
//!
//! Four producers in one file because they all walk top-level
//! `feature` / `non_goals` / `defaults` / `policies` lines looking for
//! lexical mismatches against the closed catalog:
//!
//! - `summary-generated` — `summary` is generated by `lazuli inspect`;
//!   authors must not author it in canonical source.
//! - `non-goals-shape` — `non_goals` entries must be either bare quoted
//!   strings (flat shape) or grouped under `delegated_to` /
//!   `out_of_scope` (partitioned shape).
//! - `defaults-policy-for` — `defaults` blocks should use `policy_for
//!   <kinds>: <atom>`, not the deprecated `policy <atom>` form.
//! - `namespace-catalog` — every `@...` reference must use one of the
//!   17 allowed namespaces (`@role`, `@scope`, `@actor`, …).
//!
//! `namespace_references` + `is_allowed_reference_namespace` are
//! pub(crate) so the policy / lazurite_manifest aggregators can reuse
//! the namespace scanner.

use tower_lsp::lsp_types::{Diagnostic, DiagnosticSeverity};

use crate::{leading_spaces, simple_canonical_diagnostic};

pub(crate) fn generated_summary_diagnostics(source: &str) -> Vec<Diagnostic> {
    let mut diagnostics = Vec::new();

    for (line_index, line) in source.lines().enumerate() {
        let trimmed = line.trim_start();
        if leading_spaces(line) == 2 && trimmed == "summary" {
            diagnostics.push(simple_canonical_diagnostic(
                line_index,
                line,
                DiagnosticSeverity::WARNING,
                "summary-generated",
                "`summary` is generated by `lazuli inspect --expand=summary`; do not author it in canonical source.",
            ));
        }
    }

    diagnostics
}

pub(crate) fn non_goals_shape_diagnostics(source: &str) -> Vec<Diagnostic> {
    let mut diagnostics = Vec::new();
    let mut in_non_goals = false;

    for (line_index, line) in source.lines().enumerate() {
        let trimmed = line.trim_start();

        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        if leading_spaces(line) == 2 {
            in_non_goals = trimmed == "non_goals";
            continue;
        }

        if !in_non_goals {
            continue;
        }

        if leading_spaces(line) == 4 {
            if matches!(trimmed, "delegated_to" | "out_of_scope") {
                continue;
            }
            // Iron-hand context vocabulary — the flat quoted-string
            // form is the preferred canonical shape for new features
            // (see `docs/canonical-semantics.md#feature-context-vocabulary`).
            // Partitioned `delegated_to` / `out_of_scope` blocks stay
            // valid for the existing fixture but are no longer the only
            // shape worth surfacing. Only flag bareword `key: value`
            // entries that match neither the flat shape nor the
            // partitioned shape.
            if trimmed.starts_with('"') {
                continue;
            }

            diagnostics.push(simple_canonical_diagnostic(
                line_index,
                line,
                DiagnosticSeverity::WARNING,
                "non-goals-shape",
                "`non_goals` entries must be either bare quoted strings (flat shape) or grouped under `delegated_to` / `out_of_scope` (partitioned shape). See docs/canonical-semantics.md#feature-context-vocabulary.",
            ));
        }
    }

    diagnostics
}

pub(crate) fn defaults_policy_syntax_diagnostics(source: &str) -> Vec<Diagnostic> {
    let mut diagnostics = Vec::new();
    let mut in_defaults = false;

    for (line_index, line) in source.lines().enumerate() {
        let trimmed = line.trim_start();

        if leading_spaces(line) == 2 {
            in_defaults = trimmed == "defaults";
            continue;
        }

        if !in_defaults || leading_spaces(line) != 4 || trimmed.is_empty() {
            continue;
        }

        if trimmed.starts_with("policy ") {
            diagnostics.push(simple_canonical_diagnostic(
                line_index,
                line,
                DiagnosticSeverity::WARNING,
                "defaults-policy-for",
                "feature-level policy defaults should use `policy_for jobs, webhooks: @actor.system` so the fallback scope is explicit.",
            ));
        }
    }

    diagnostics
}

pub(crate) fn namespace_reference_diagnostics(source: &str) -> Vec<Diagnostic> {
    let mut diagnostics = Vec::new();

    for (line_index, line) in source.lines().enumerate() {
        // 2026-05-27 — skip comment lines. The rule looks for typed
        // `@<ns>.<x>` refs that the IR will resolve at lower time;
        // those have semantic meaning. Comments (including the
        // canonical `# doctor:allow @info.<code>` opt-out) carry rule
        // CODES as documentation, not as IR refs, so an `@info.x` in
        // a comment is documentation, not a real namespace ref.
        if line.trim_start().starts_with('#') {
            continue;
        }
        for namespace in namespace_references(line) {
            if !is_allowed_reference_namespace(namespace) {
                diagnostics.push(simple_canonical_diagnostic(
                    line_index,
                    line,
                    DiagnosticSeverity::WARNING,
                    "namespace-catalog",
                    "unknown `@...` namespace. Allowed namespaces are `@role`, `@scope`, `@actor`, `@policy`, `@semantic`, `@cap`, `@pii`, `@key`, `@fn`, `@hook`, `@validator`, `@adapter`, `@client`, `@query_modifier`, `@anchor`, `@llm`, `@tool`, `@trace`, `@translation`, and `@feature`.",
                ));
                break;
            }
        }
    }

    diagnostics
}

pub(crate) fn namespace_references(line: &str) -> Vec<&str> {
    // Mask the spans inside double-quoted string literals so e.g.
    // `requires customer.email = "ada@example.com"` does not surface
    // `@example` as a stray namespace. The scan walks the original byte
    // slice; the mask just decides which `@` positions are eligible.
    let bytes = line.as_bytes();
    let mut in_quote = false;
    let mut quote_ranges: Vec<(usize, usize)> = Vec::new();
    let mut quote_start = 0;
    for (i, b) in bytes.iter().enumerate() {
        if *b == b'"' {
            if in_quote {
                quote_ranges.push((quote_start, i + 1));
                in_quote = false;
            } else {
                quote_start = i;
                in_quote = true;
            }
        }
    }
    let in_string = |pos: usize| {
        quote_ranges
            .iter()
            .any(|(start, end)| pos >= *start && pos < *end)
    };

    let mut namespaces = Vec::new();
    let mut cursor = 0;

    while cursor < line.len() {
        let Some(rel) = line[cursor..].find('@') else {
            break;
        };
        let at_pos = cursor + rel;
        if in_string(at_pos) {
            cursor = at_pos + 1;
            continue;
        }
        let after_at = &line[at_pos + 1..];
        let Some(dot) = after_at.find('.') else {
            cursor = at_pos + 1;
            continue;
        };

        let namespace = &after_at[..dot];
        if !namespace.is_empty()
            && namespace
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
        {
            namespaces.push(namespace);
        }

        cursor = at_pos + 1 + dot + 1;
    }

    namespaces
}

pub(crate) fn is_allowed_reference_namespace(namespace: &str) -> bool {
    matches!(
        namespace,
        "role"
            | "scope"
            | "actor"
            | "policy"
            | "semantic"
            | "cap"
            | "pii"
            | "key"
            | "fn"
            | "hook"
            | "validator"
            | "adapter"
            | "client"
            | "query_modifier"
            | "anchor"
            | "llm"
            | "tool"
            // Observability bucket cycle row 35 — reference-only namespace
            // for `trigger @trace.<name>` on subscriber jobs. Reserved
            // names live in `lazuli_ir::built_in_trace_events()`; LSP
            // checks resolution in `trigger_trace_unknown_diagnostics`.
            | "trace"
            // i18n bucket cycle row 54 — reference-only namespace for
            // `rule message @translation.<key>` (and post-pilot surface
            // labels). Keys are declared in feature `translation` blocks;
            // doctor's `rule_message_ref_unresolved` validates resolution.
            | "translation"
            // GAP-12 / GAP-AUDIT-01 — cross-feature reference namespace for
            // `@feature.<feature>.<Resource>` on `target` (effect-target
            // resolution) and `audit ... materialize @feature.x.OperationLog`.
            // Resolves to a resource declared in a sibling feature block.
            | "feature"
    )
}
