#[test]
fn empty_feature_returns_none() {
    let feature = base_feature("customer");
    assert!(emit(&feature).is_none());
}

#[test]
fn single_resource_emits_struct_and_resource_value() {
    let mut feature = base_feature("customer");
    let resource = simple_resource(
        "customer",
        vec![
            simple_field("name", BuiltinType::Text, true),
            simple_field("email", BuiltinType::SemanticEmail, true),
        ],
    );
    feature.resources.push(resource);
    let out = emit(&feature).expect("must emit");

    assert!(out.contains("// Code generated by lazuli; DO NOT EDIT."));
    assert!(out.contains("package customergen"));
    assert!(out.contains("import (\n\t\"lazuli.dev/runtime/lazuli\"\n)"));
    assert!(out.contains("type Customer struct {"));
    assert!(out.contains("ID    lazuli.ID"));
    assert!(out.contains("Name  string"));
    assert!(out.contains("Email lazuli.Email"));
    assert!(out.contains("var customerResource = lazuli.Resource[Customer]{"));
    assert!(out.contains("Name:    \"customer\","));
    assert!(out.contains("Feature: \"customer\","));
    // No SoftDelete here, so key column pads to `Tenancy:` width (8).
    assert!(out.contains("Tenancy: lazuli.TenancyNone,"));
    // No retention block.
    assert!(!out.contains("RetentionSpec"));
    // No soft-delete row.
    assert!(!out.contains("DeletedAt"));
}

#[test]
fn semantic_plugin_type_field_emits_validate_tag() {
    // B3 + GAP-R2 — `@semantic.BrazilianCPF` lowers to
    // `SemanticPluginType { plugin: "@lazuli/plugin-scalars-br", name:
    // "BrazilianCPF", carrier: Text, validator: "ValidateCPF" }`.
    // The emitted struct field must carry the `string` carrier Go type
    // plus a `validate:"…"` tag whose body merges the plugin dispatch key
    // `scalars-br.ValidateCPF` with the field's `required` flag.
    // See `docs/proposals/semantic-types-plugin-locales.md` §Codegen.
    let mut feature = base_feature("host");
    let plugin_field = Field {
        name: "cpf".to_owned(),
        type_ref: TypeRef::Builtin(BuiltinType::SemanticPluginType {
            plugin: "@lazuli/plugin-scalars-br".to_owned(),
            name: "BrazilianCPF".to_owned(),
            carrier: Box::new(BuiltinType::Text),
            validator: "ValidateCPF".to_owned(),
            go_module: "lazuli.dev/plugin/scalars-br".to_owned(),
            ts_package: "@lazuli/plugin-scalars-br".to_owned(),
            error_code: "cpf_invalid".to_owned(),
            message_key: String::new(),
            ts_validator: String::new(),
        }),
        required: true,
        unique: false,
        slug: false,
        default: None,
        derived_from: None,
        computed_date: None,
        constraints: lazuli_ir::FieldConstraints::default(),
        full_text: false,
        previous_names: Vec::new(),
        pii: None,
        owner_axis: None,
        cross_feature_target: None,
        span_ref: None,
    };
    feature
        .resources
        .push(simple_resource("Host", vec![plugin_field]));
    let out = emit(&feature).expect("must emit");

    // Carrier is `Text` → Go `string`.
    assert!(out.contains("Cpf string"));
    // Validate tag merges the plugin short name + validator function with
    // the `required` flag (GAP-R2: constraints + plugin key share the tag).
    assert!(
        out.contains("validate:\"scalars-br.ValidateCPF,required\""),
        "expected merged validate tag, got: {out}"
    );
    // db + json tags preserved alongside validate.
    assert!(out.contains("db:\"cpf\""));
    assert!(out.contains("json:\"cpf\""));
}

#[test]
fn record_emits_struct_without_resource_value() {
    let mut feature = base_feature("customer");
    feature.records.push(Record {
        name: "CustomerLtv".to_owned(),
        public_contract: None,
        fields: vec![
            simple_field("customer_id", BuiltinType::Id, true),
            simple_field(
                "amount",
                BuiltinType::SemanticMoney {
                    currency: lazuli_ir::CurrencyCode::BRL,
                },
                true,
            ),
        ],
        discriminator_field: None,
        span_ref: None,
    });
    let out = emit(&feature).expect("must emit");
    assert!(out.contains("type CustomerLtv struct {"));
    assert!(!out.contains("lazuli.Resource"));
    assert!(out.contains("CustomerID lazuli.ID"));
    assert!(out.contains("Amount     lazuli.Money"));
}

#[test]
fn record_field_emits_semantic_and_constraint_validate_tags_and_validate_method() {
    // GAP-R2 — a `record Installment { days: Integer (min 1 max 36),
    // percentage: @semantic.Percentage }` used as a `Many<Installment>`
    // JSONB value-object must carry per-field validation on the nested
    // struct:
    //   - `percentage` resolves to the W1 `lazuli.Percentage` carrier whose
    //     UnmarshalJSON enforces 0..=100 (no validate-tag keyword needed).
    //   - `days` carries its `min`/`max` constraints as a `validate:"…"` tag.
    // Plus the record gets a `Validate()` method delegating to
    // `lazuli.ValidateValue` for the explicit (construction-time) path.
    let mut feature = base_feature("billing");
    let mut days = simple_field("days", BuiltinType::Integer, true);
    days.constraints = lazuli_ir::FieldConstraints {
        min: Some(1),
        max: Some(36),
        ..lazuli_ir::FieldConstraints::default()
    };
    feature.records.push(Record {
        name: "Installment".to_owned(),
        public_contract: None,
        fields: vec![
            days,
            simple_field("percentage", BuiltinType::SemanticPercentage, true),
        ],
        discriminator_field: None,
        span_ref: None,
    });
    let out = emit(&feature).expect("must emit");

    // Nested struct shape: typed carrier for the percentage field.
    assert!(out.contains("type Installment struct {"));
    assert!(
        out.contains("Percentage lazuli.Percentage"),
        "expected Percentage carrier on the nested record field; got:\n{out}"
    );
    // `days` carries its min/max + required as a go-playground validator tag.
    assert!(
        out.contains("validate:\"required,min=1,max=36\""),
        "expected merged constraint validate tag on the record field; got:\n{out}"
    );
    // The record exposes a Validate() method wired to the runtime walker.
    assert!(
        out.contains("func (m Installment) Validate() error {"),
        "expected record Validate() method; got:\n{out}"
    );
    assert!(
        out.contains("return lazuli.ValidateValue(m)"),
        "expected Validate() to delegate to lazuli.ValidateValue; got:\n{out}"
    );
}

#[test]
fn many_record_field_on_resource_emits_jsonb_slice_with_typed_element() {
    // GAP-R2 — a resource field `installments: Many<Installment>` lowers the
    // Go field to `[]Installment` (a JSONB document at the DDL layer). The
    // element type is the typed record struct, so `json.Unmarshal` of the
    // command input fires each element's `Percentage.UnmarshalJSON` carrier.
    let mut feature = base_feature("billing");
    feature.records.push(Record {
        name: "Installment".to_owned(),
        public_contract: None,
        fields: vec![
            simple_field("days", BuiltinType::Integer, true),
            simple_field("percentage", BuiltinType::SemanticPercentage, true),
        ],
        discriminator_field: None,
        span_ref: None,
    });
    let resource = simple_resource(
        "plan",
        vec![Field {
            name: "installments".to_owned(),
            type_ref: TypeRef::Many(Box::new(TypeRef::UserDefined(lazuli_ir::QualifiedName {
                feature: None,
                name: "Installment".to_owned(),
            }))),
            required: true,
            unique: false,
            slug: false,
            default: None,
            derived_from: None,
            computed_date: None,
            constraints: lazuli_ir::FieldConstraints::default(),
            full_text: false,
            previous_names: Vec::new(),
            pii: None,
            owner_axis: None,
            cross_feature_target: None,
            span_ref: None,
        }],
    );
    feature.resources.push(resource);
    let out = emit(&feature).expect("must emit");

    assert!(
        out.contains("Installments []Installment"),
        "expected typed slice element for Many<Record>; got:\n{out}"
    );
    // The nested record's percentage field keeps the typed carrier.
    assert!(out.contains("Percentage lazuli.Percentage"));
}

#[test]
fn cap_file_field_registers_storage_import() {
    let mut feature = base_feature("docs");
    let resource = simple_resource(
        "document",
        vec![Field {
            name: "blob".to_owned(),
            type_ref: TypeRef::Builtin(BuiltinType::CapFile),
            required: true,
            unique: false,
            slug: false,
            default: None,
            derived_from: None,
            computed_date: None,
            constraints: lazuli_ir::FieldConstraints::default(),
            full_text: false,
            previous_names: Vec::new(),
            pii: None,
            owner_axis: None,
            cross_feature_target: None,
            span_ref: None,
        }],
    );
    feature.resources.push(resource);
    let out = emit(&feature).expect("must emit");
    assert!(out.contains("\"lazuli.dev/runtime/lazuli/storage\""));
    assert!(out.contains("Blob storage.FileRef"));
}

#[test]
fn geopoint_field_emits_postgis_import_and_geo_tag() {
    let mut feature = base_feature("places");
    let resource = simple_resource(
        "place",
        vec![simple_field(
            "location",
            BuiltinType::SemanticGeoPoint,
            true,
        )],
    );
    feature.resources.push(resource);
    let out = emit(&feature).expect("must emit");
    assert!(out.contains("\"github.com/cridenour/go-postgis\""));
    assert!(out.contains("Location postgis.Point"));
    // The geo column tag must carry the PostGIS type modifier so
    // pgx scans + DDL stay aligned (proposal §3.1 / §9.1).
    assert!(
        out.contains("db:\"location,type:geography(point,4326)\""),
        "expected geo type modifier in db tag, output was:\n{out}"
    );
}

#[test]
fn soft_delete_adds_deleted_at_pointer_with_omitempty() {
    let mut feature = base_feature("customer");
    let mut resource = simple_resource(
        "customer",
        vec![simple_field("name", BuiltinType::Text, true)],
    );
    resource.soft_delete = true;
    feature.resources.push(resource);
    let out = emit(&feature).expect("must emit");
    assert!(out.contains("DeletedAt *lazuli.Time"));
    assert!(out.contains("json:\"deleted_at,omitempty\""));
    // With soft_delete, `SoftDelete:` (11 chars) is the widest key
    // so it occupies the column verbatim without padding.
    assert!(out.contains("SoftDelete: true,"));
    // Bare `soft_delete` (no actor form) emits NO deleted_by surface.
    assert!(!out.contains("DeletedBy"));
    assert!(!out.contains("SoftDeleteActor"));
}

#[test]
fn soft_delete_by_adds_deleted_by_actor_column() {
    // Spec 0015 — `soft_delete by` projects a nullable `deleted_by`
    // (`*lazuli.ID`) struct field alongside `DeletedAt`, plus the
    // `SoftDeleteActor: true` flag on the `Resource[T]` value that
    // drives the runtime's `"deleted_by" = $actor` SET clause.
    let mut feature = base_feature("customer");
    let mut resource = simple_resource(
        "customer",
        vec![simple_field("name", BuiltinType::Text, true)],
    );
    resource.soft_delete = true;
    resource.soft_delete_actor = true;
    feature.resources.push(resource);
    let out = emit(&feature).expect("must emit");
    // Both soft-delete columns present, both nullable + omitempty.
    assert!(out.contains("DeletedAt *lazuli.Time"));
    assert!(out.contains("DeletedBy *lazuli.ID"));
    assert!(out.contains("json:\"deleted_by,omitempty\""));
    // Resource[T] value carries both flags.
    assert!(out.contains("SoftDelete:"));
    assert!(out.contains("SoftDeleteActor: true,"));
}

#[test]
fn retention_spec_lifts_window_and_action() {
    let mut feature = base_feature("customer");
    let mut resource = simple_resource(
        "customer",
        vec![simple_field("name", BuiltinType::Text, true)],
    );
    resource.retention = Some(RetentionSpec {
        duration: "7y".to_owned(),
        action: RetentionAction::Anonymize,
    });
    feature.resources.push(resource);
    let out = emit(&feature).expect("must emit");
    assert!(out.contains("Retention: &lazuli.RetentionSpec{"));
    assert!(out.contains("Window: lazuli.Duration(\"7y\"),"));
    assert!(out.contains("Then:   lazuli.Anonymize,"));
}

#[test]
fn tenancy_org_emits_orgid_field_and_constant() {
    let mut feature = base_feature("customer");
    let mut resource = simple_resource(
        "customer",
        vec![simple_field("name", BuiltinType::Text, true)],
    );
    resource.tenancy = Some(Tenancy::Org);
    feature.resources.push(resource);
    let out = emit(&feature).expect("must emit");
    assert!(out.contains("OrgID lazuli.ID"));
    assert!(out.contains("Tenancy: lazuli.TenancyOrg,"));
}

#[test]
fn feature_default_timestamps_lift_created_updated_at() {
    let mut feature = base_feature("customer");
    feature.defaults.timestamps = true;
    let resource = simple_resource(
        "customer",
        vec![simple_field("name", BuiltinType::Text, true)],
    );
    feature.resources.push(resource);
    let out = emit(&feature).expect("must emit");
    assert!(out.contains("CreatedAt lazuli.Time"));
    assert!(out.contains("UpdatedAt lazuli.Time"));
}

#[test]
fn resource_timestamps_override_feature_default() {
    let mut feature = base_feature("customer");
    feature.defaults.timestamps = true;
    let mut resource = simple_resource(
        "customer",
        vec![simple_field("name", BuiltinType::Text, true)],
    );
    // Explicit opt-out on the resource side beats the feature default.
    resource.timestamps = Some(false);
    feature.resources.push(resource);
    let out = emit(&feature).expect("must emit");
    assert!(!out.contains("CreatedAt"));
    assert!(!out.contains("UpdatedAt"));
}

#[test]
fn optional_field_emits_pointer_and_omitempty() {
    let mut feature = base_feature("customer");
    let resource = simple_resource(
        "customer",
        vec![simple_field("name", BuiltinType::Text, false)],
    );
    feature.resources.push(resource);
    let out = emit(&feature).expect("must emit");
    assert!(out.contains("Name *string"));
    assert!(out.contains("json:\"name,omitempty\""));
}

#[test]
fn derived_field_renders_as_comment_only() {
    let mut feature = base_feature("customer");
    let mut field = simple_field("is_high_value", BuiltinType::Boolean, true);
    field.derived_from = Some("score > 80".to_owned());
    let resource = simple_resource("customer", vec![field]);
    feature.resources.push(resource);
    let out = emit(&feature).expect("must emit");
    assert!(out.contains("// IsHighValue is derived"));
    // Not a real struct field.
    assert!(!out.contains("IsHighValue bool"));
}

#[test]
fn computed_date_field_emits_addate_helper_with_field_offset() {
    use lazuli_ir::{ComputedDate, ComputedDateBase, ComputedDateOffset};
    let mut feature = base_feature("campaign");
    let mut due = simple_field("due_date", BuiltinType::Date, true);
    due.computed_date = Some(ComputedDate {
        base: ComputedDateBase::Field("campaign_start".to_owned()),
        offset: ComputedDateOffset::Field("offset_days".to_owned()),
    });
    let resource = simple_resource(
        "campaign",
        vec![
            simple_field("campaign_start", BuiltinType::Date, true),
            simple_field("offset_days", BuiltinType::Integer, true),
            due,
        ],
    );
    feature.resources.push(resource);
    let out = emit(&feature).expect("must emit");

    // The computed_date column is a REAL struct field (Go computes it at
    // write time; it round-trips back from the stored DATE column).
    assert!(out.contains("DueDate"));
    // The stdlib `time` import is registered for the helper.
    assert!(out.contains("\"time\""));
    // The `Compute<Field>` helper emits the wire-thin `AddDate` arithmetic.
    assert!(out.contains("func (m *Campaign) ComputeDueDate() {"));
    assert!(out.contains("time.Parse(\"2006-01-02\", string(m.CampaignStart))"));
    assert!(
        out.contains("base.AddDate(0, 0, int(m.OffsetDays))"),
        "expected AddDate emission; got:\n{out}"
    );
}
