// Code generated by lazuli; DO NOT EDIT.
// source: features/account/account.lzi:42

package account_gen

import (
	"time"

	"lazuli.dev/runtime/lazuli"
	"lazuli.dev/runtime/lazuli/auth"
)

// IssueUserSession is the tenant-aware wrapper around
// auth.IssueSession. Codegen-emitted; do not call auth.IssueSession
// directly for tenant-scoped session resources — doctor enforces
// AUTH-SESSION-CALLSITE-001.
//
// Extra columns (IR declaration order): org_id
func IssueUserSession(
	ctx *lazuli.Ctx,
	userID lazuli.ID,
	orgID lazuli.ID, // tenant axis from defaults.tenancy
) (string, time.Time, error) {
	token, tokenHash, expiresAt, err := auth.MintSessionToken(ctx, UserSessionContract)
	if err != nil {
		return "", time.Time{}, err
	}

	// Per-resource INSERT writes every NOT NULL column.
	sql := `INSERT INTO "user_session"
              (org_id, user_id, token_hash, expires_at)
            VALUES ($1, $2, $3, $4)`
	if _, err := auth.SessionDB().Exec(ctx.Context(), sql, orgID, userID, tokenHash, expiresAt); err != nil {
		return "", time.Time{}, err
	}
	return token, expiresAt, nil
}

// ResolveUserSession is the tenant-aware wrapper. Populates
// ctx.User and ctx.Tenant from the session row.
func ResolveUserSession(
	ctx *lazuli.Ctx,
	token string,
) (lazuli.ID, lazuli.ID, error) { // (userID, orgID, error)
	tokenHash, err := auth.HashSessionToken(token)
	if err != nil {
		return 0, 0, err
	}

	sql := `SELECT user_id, org_id, expires_at FROM "user_session"
            WHERE token_hash = $1 LIMIT 1`
	var userID, orgID lazuli.ID
	var expiresAt time.Time
	err = auth.SessionDB().QueryRow(ctx.Context(), sql, tokenHash).Scan(&userID, &orgID, &expiresAt)
	if err != nil {
		return 0, 0, auth.MapSessionResolveError(err)
	}
	if !expiresAt.After(time.Now()) {
		return 0, 0, auth.ErrSessionExpired
	}
	ctx.User = userID
	ctx.Tenant = orgID
	return userID, orgID, nil
}

// InvalidateUserSession remains generic — no tenant axis matters
// on delete-by-token, but we emit a per-resource wrapper for
// vocabulary consistency.
func InvalidateUserSession(ctx *lazuli.Ctx, token string) error {
	return auth.InvalidateSessionByToken(ctx, UserSessionContract, token)
}

// UserSessionContract is the lowered SessionsContract for this
// resource. Retained for adapter-level introspection (tests, doctor).
var UserSessionContract = auth.SessionsContract{
	Resource: "user_session",
	TTL:      "7 days",
	Refresh:  false,
}
