//! Rich Markdown hover for the closed-catalog DSL kinds the LSP knows
//! best. Each entry renders a one-line summary, required-children
//! bullets, optional-children bullets, a worked example, and a doc
//! anchor link. Markdown intentionally uses only the conservative
//! subset (headings via `**bold**`, bullet lists, fenced code blocks,
//! inline `[label](path)` links) so VS Code and Helix both render it
//! the same way; we don't use VS Code-only renderer features.
//!
//! Falls back to `keyword_description` (one-liner) when no rich
//! template exists, so adding a kind here is strictly additive and
//! cannot regress unrelated hover output.
//!
//! The canonical kinds covered today: `command`, `query.list`,
//! `query.lookup`, `query.sql`, `query.view`, `api`, `policy`,
//! `effect`, `audit`, `rate_limit`, `error_page`, `errors`,
//! `when_denied`, `message_key`, `conventions`, `@owner_axis`.

pub fn rich_keyword_hover(keyword: &str) -> Option<String> {
    match keyword {
        "command" => Some(
            [
                "**`command`** — write operation on an aggregate. Lazuli owns the contract; the runtime emits a typed handler that runs effects, emits events, and invalidates queries.",
                "",
                "**Required children**",
                "- `policy @policy.<name>` — feature-local authorization category.",
                "- An effect line — exactly one of `creates`/`updates`/`deletes`, or a non-mutating `returns <Record>` shape.",
                "",
                "**Optional children**",
                "- `input` / short-form `input name, email` — submitted fields.",
                "- `route <name>: <Type>` — URL/context slots.",
                "- `rate_limit \"<N> per <window> per <axis>\"` — required when the policy includes `@scope.public` or the command mutates state.",
                "- `audit` / `audit <field>+` / `audit none` — audit-log contract.",
                "- `emits <event> [from creates|updates|deletes]` — domain event publication.",
                "- `invalidates query.<name>` — cache fan-out.",
                "- `approval` — conditional human sign-off block.",
                "- `validate @validator.<name>` — blocking validator.",
                "",
                "**Example**",
                "```lazuli",
                "command create",
                "  input",
                "    name: Text required",
                "  policy @policy.create",
                "  rate_limit \"30 per hour per ip\"",
                "  creates Customer",
                "    name = input.name",
                "  emits customer_created from creates",
                "```",
                "",
                "See [quickref.md §Minimal Feature](docs/quickref.md) and [invariants.md §Security And Crypto](docs/invariants.md).",
                "",
                "**Inspect**: `lazuli inspect <file> --expand=commands` projects this declaration's typed IR slice (route + input + policy + audit + approval + invalidates + external_calls + rate_limit + timeout/retry/idempotency).",
            ]
            .join("\n"),
        ),
        "query.list" => Some(
            [
                "**`query.list`** — generated collection query. Defaults to `order created_at desc`; simple equality filters derive language-managed indexes.",
                "",
                "**Required children**",
                "- None at the syntax level — a bare `query.list <name>` is valid.",
                "",
                "**Optional children**",
                "- `params` — typed read arguments.",
                "- `filters` — equality / `when params.*` filter rows; derives indexes.",
                "- `search params.<name> over <field>...` with `mode contains|prefix|exact` — text matching (does not derive indexes).",
                "- `order <field> asc|desc` — override the `created_at desc` default.",
                "- `paginate <positive-int>` — generated default page size, not a hard maximum.",
                "- `cache key <expr> ttl <duration>` (+ optional `tags`, `namespace`).",
                "- `scope override` (+ `reason`) — cross-tenant / admin queries.",
                "- `policy @policy.<name>` — explicit category (required under `scope override`).",
                "- `modifier @query_modifier.<name>` — query-modifier extension.",
                "",
                "**Example**",
                "```lazuli",
                "query.list list",
                "  params",
                "    status: CustomerStatus optional",
                "  filters",
                "    status when params.status",
                "  paginate 50",
                "```",
                "",
                "See [quickref.md §Queries](docs/quickref.md) and [invariants.md §Queries And Relations](docs/invariants.md).",
                "",
                "**Inspect**: `lazuli inspect <file> --expand=queries` projects every lifted query (List / Lookup / Sql) with its full v0 child coverage.",
            ]
            .join("\n"),
        ),
        "query.lookup" => Some(
            [
                "**`query.lookup`** — generated single-record query. Single-key form sugars to `query.lookup <name> by <field>: <Type>`; composite/reshaped lookups use a `params`/`key` body.",
                "",
                "**Required slots**",
                "- A key spec — either `by <field>: <Type>` (single-key sugar) or a `params`/`key` body for composite lookups.",
                "",
                "**Optional children**",
                "- `params` — composite-key arguments (when `by` shorthand is not used).",
                "- `key` — explicit key composition for composite lookups.",
                "- `policy @policy.<name>` — explicit category.",
                "- `cache key <expr> ttl <duration>`.",
                "- `scope override` (+ `reason`) — cross-tenant lookups.",
                "",
                "**Example**",
                "```lazuli",
                "query.lookup by_id by id: ID",
                "",
                "query.lookup by_email by email: @semantic.Email",
                "```",
                "",
                "See [quickref.md §Queries](docs/quickref.md) and [invariants.md §Queries And Relations](docs/invariants.md).",
                "",
                "**Inspect**: `lazuli inspect <file> --expand=queries` includes Lookup queries alongside List/Sql.",
            ]
            .join("\n"),
        ),
        "query.sql" => Some(
            [
                "**`query.sql`** — SQL-backed query wrapper. The result type must resolve to a `record`, resource, or registered contract before codegen; Lazuli does not infer result shape from SQL text.",
                "",
                "**Required children**",
                "- `returns <Type>` or `returns <Type>[]` — must resolve to a `record`, resource, or contract.",
                "- `sql \"./queries/<name>.sql\"` — relative path to the SQL file.",
                "",
                "**Optional children**",
                "- `params` — typed query arguments referenced inside the SQL file.",
                "- `scope` — tenancy or filter scope applied at codegen.",
                "- `policy @policy.<name>` — explicit category.",
                "- `cache key <expr> ttl <duration>`.",
                "",
                "**Example**",
                "```lazuli",
                "query.sql lifetime_value",
                "  returns CustomerLtv[]",
                "  scope",
                "    org = ctx.user.org",
                "  sql \"./queries/customer_lifetime_value.sql\"",
                "```",
                "",
                "See [quickref.md §Queries](docs/quickref.md) and [invariants.md §Queries And Relations](docs/invariants.md).",
                "",
                "**Inspect**: `lazuli inspect <file> --expand=queries` includes Sql queries alongside List/Lookup.",
            ]
            .join("\n"),
        ),
        "query.view" => Some(
            [
                "**`query.view`** — typed SQL-backed screen-read projection. Use it for denormalized reads whose row shape is declared as a local `record`.",
                "",
                "**Required children**",
                "- `returns list of <Record>` or `returns <Record>` — typed row shape for the generated SDK.",
                "- `source @file.<name>.sql` — SQL file under the feature `queries/` directory.",
                "",
                "**Optional children**",
                "- `policy @policy.<name>` — explicit category.",
                "- `params` — typed query arguments bound to SQL placeholders in source order.",
                "- `scope` — tenancy or filter scope applied at codegen.",
                "",
                "**Example**",
                "```lazuli",
                "query.view host_home_view",
                "  policy @policy.host_only",
                "  returns list of HostHomeRow",
                "  source @file.host_home_view.sql",
                "  params",
                "    user_id: ID required",
                "```",
                "",
                "See [quickref.md §Queries](docs/quickref.md) and [invariants.md §Queries And Relations](docs/invariants.md).",
            ]
            .join("\n"),
        ),
        "api" => Some(
            [
                "**`api`** — custom typed HTTP endpoint outside `command`/`query`/`webhook` semantics. Use it when the handler does meaningful work beyond translating HTTP to a single dispatch; otherwise prefer `expose http` on an `agent` or a generated command/query.",
                "",
                "**Required children**",
                "- `method <GET|POST|PUT|PATCH|DELETE>` — HTTP verb.",
                "- `path \"<url>\"` — concrete URL path; `:slot` placeholders bind via `route`.",
                "- `output <Type>` — response shape (record, resource, or `@cap.File(...)`).",
                "- `policy @policy.<name>` — authorization category.",
                "- `handler @fn.<name>` or `handler \"./path.go\"` — handler reference.",
                "",
                "**Optional children**",
                "- `input <Type>` — request body shape.",
                "- `route <name>: <Type>` — one per `:slot` placeholder.",
                "- `rate_limit \"<N> per <window> per <axis>\"` — per-call throttle (required when policy includes `@scope.public`).",
                "- `audit` / `audit <field>+` / `audit none`.",
                "",
                "**Example**",
                "```lazuli",
                "api me",
                "  method GET",
                "  path \"/me\"",
                "  output User",
                "  policy @policy.authenticated",
                "  handler @fn.me",
                "```",
                "",
                "See [quickref.md §Security Checklist](docs/quickref.md) and [invariants.md §Security And Crypto](docs/invariants.md).",
                "",
                "**Inspect**: `lazuli inspect <file> --expand=apis` (or `--expand=api`) projects every lifted Api with method + path + output + policy + handler + locale_negotiate.",
            ]
            .join("\n"),
        ),
        "policy" => Some(
            [
                "**`policy`** — feature-local authorization category reference on a `command`/`query`/`api`/`webhook`/`job`. The category resolves against the same feature's `policies` block unless feature-qualified.",
                "",
                "**Forms**",
                "- `policy @policy.<name>` — single category from the feature `policies` dictionary.",
                "- `policy @policy.<feature>.<name>` — cross-feature category (rarely needed).",
                "- On `policies` entry lines (atom decomposition): `<category>: <atom>[, <atom>]+` where each atom is `@role.*`, `@scope.*`, or `@actor.*`.",
                "- Predicate combinators inside categories: comma = OR, `and` = AND, parentheses for grouping (canonical closed predicate language).",
                "",
                "**Rules**",
                "- Commands declare `policy` explicitly — there is no implicit `creates -> @policy.create`.",
                "- Direct atoms (`@role.*`, `@scope.*`, `@actor.*`) belong in `policies` entries, not on individual command lines. Jobs / webhooks / escape routes may use atoms directly where appropriate.",
                "",
                "**Example**",
                "```lazuli",
                "policies",
                "  create: @role.admin, @role.sales",
                "  read: @scope.same_org",
                "",
                "command reassign",
                "  policy @policy.update",
                "```",
                "",
                "See [quickref.md §Policy Vocabulary](docs/quickref.md) and [invariants.md §Policies](docs/invariants.md).",
            ]
            .join("\n"),
        ),
        "effect" => Some(
            [
                "**`effect`** — write effect on a `command`. The closed catalog is `creates` / `updates` / `deletes` / `returns`. Exactly one mutating effect per command; `returns` is non-mutating.",
                "",
                "**Closed catalog**",
                "- `creates <Resource>` — new row; body assigns input/derived values to fields.",
                "- `updates <Resource>` — mutates the loaded `target`; body assigns changed fields.",
                "- `deletes <Resource>` — removes the loaded `target`. Soft-delete is automatic when the resource declares `soft_delete`.",
                "- `returns <Record>` — non-mutating command (no row write); the handler returns a typed record.",
                "",
                "**Rules**",
                "- One mutating effect per command. Multi-effect commands are rejected.",
                "- `target` is loaded before `updates`/`deletes` (explicit `target query.by_id(...)` or sugar when route/lookup match).",
                "- Event derivation works with effects: `emits <event> from creates|updates|deletes` maps the effect's bindings into the event payload by name.",
                "",
                "**Example**",
                "```lazuli",
                "command create",
                "  policy @policy.create",
                "  creates Customer",
                "    name = input.name",
                "    email = input.email",
                "  emits customer_created from creates",
                "```",
                "",
                "See [quickref.md §Canonical Sugar Table](docs/quickref.md) and [invariants.md §Source And Derived Views](docs/invariants.md).",
            ]
            .join("\n"),
        ),
        "audit" => Some(
            [
                "**`audit`** — declares an operation as audited so generated audit-log codegen has a typed contract instead of relying on event-name conventions. Surfaces in `lazuli inspect --expand=security`.",
                "",
                "**Forms**",
                "- `audit` — emit the default audit fields (`actor`, `tenant`, `target.id`, `ctx.now`).",
                "- `audit <field>, <field>, ...` — explicit field list. Each entry resolves against the command's binding namespaces (`input.*`, `route.*`, `target.*`, `ctx.*`, `payload.*`, etc.).",
                "- `audit none` — opt out of audit-log generation. Doctor records the opt-out so security review can see it.",
                "",
                "**Optional child**",
                "- `emit_to <stream>` — direct audit emission to a specific stream (e.g. `audit_log`).",
                "",
                "**Rules**",
                "- Valid on `command`, `query.*`, `job`, `webhook`, and `report` (and `api` via `policy` linkage).",
                "- Audit declarations do not replace `emits`; events and audits are different contracts.",
                "",
                "**Example**",
                "```lazuli",
                "command reassign",
                "  policy @policy.update",
                "  audit actor, target.id, input.owner_id",
                "    emit_to audit_log",
                "  updates Customer",
                "    owner = resolved_owner",
                "```",
                "",
                "See [invariants.md §Source And Derived Views](docs/invariants.md) (audit fields paragraph) and [quickref.md §Security Checklist](docs/quickref.md).",
            ]
            .join("\n"),
        ),
        "rate_limit" => Some(
            [
                "**`rate_limit`** — per-call throttle on a `command`, `api`, `agent.expose http`, or `auth password`. Distinct from `notification.throttle` (which keys on recipient/channel axes).",
                "",
                "**Grammar**",
                "- `rate_limit \"<N> per <window> per <axis>\"`",
                "- `<N>` — positive integer.",
                "- `<window>` — duration string (`second`, `minute`, `hour`, `day`, or `<N> <unit>` like `\"5 10 minutes\"` for explicit count).",
                "- `<axis>` — closed catalog: `ip`, `user`, `org`, `tenant`.",
                "- `rate_limit none` (with `reason \"...\"`) — explicit opt-out; required when the strict security profile demands a decision.",
                "",
                "**When required**",
                "- Commands that mutate state.",
                "- Commands / APIs whose effective policy includes `@scope.public`.",
                "- `auth password` flows.",
                "",
                "**Example**",
                "```lazuli",
                "command create",
                "  policy @policy.create",
                "  rate_limit \"30 per hour per ip\"",
                "  creates Customer",
                "```",
                "",
                "See [quickref.md §Security Checklist](docs/quickref.md) and [invariants.md §Security And Crypto](docs/invariants.md).",
            ]
            .join("\n"),
        ),
        "error_page" => Some(
            [
                "**`error_page`** — declares a custom app-level HTTP error page once so every generated surface can share the same status response contract.",
                "",
                "**Header**",
                "- `error_page <status>` — closed catalog: `400`, `401`, `403`, `404`, `405`, `410`, `422`, `429`, `500`, `502`, `503`, `504`.",
                "",
                "**Required children**",
                "- `template \"./views/<status>.tmpl\"` — relative template path.",
                "",
                "**Optional children**",
                "- `audience <name>` — route audience that can see this page, commonly `public`.",
                "",
                "**Example**",
                "```lazuli",
                "app MyApp",
                "  error_page 404",
                "    template \"./views/404.tmpl\"",
                "    audience public",
                "```",
                "",
                "Doctor: `error-page-contract`, `error-page-template-missing`, `error-page-duplicate`.",
            ]
            .join("\n"),
        ),
        // IR Error-Vocab — see `docs/proposals/ir-error-messages-vocab.md`
        // §7.2. Rich-Markdown hovers for `errors` (feature-level block
        // keyword), `when_denied` (per-command + per-policy override),
        // `message_key` (wire-envelope opt-in field). The 8 closed-catalog
        // error codes get a separate **resolved-text** hover wired in the
        // dispatch above this function (see `hover` handler) because the
        // resolved text depends on the active document content, not just
        // the keyword name.
        "errors" => Some(
            [
                "**`errors`** — feature-level error contract. Combines (1) wire exposure rules and (2) typed per-code message overrides.",
                "",
                "**Children**",
                "- `default hide` | `default expose` — wire-envelope default for `message`/`data`/`message_key`. `hide` is the secure default.",
                "- `expose client 4xx <fields>` — comma-separated closed catalog: `message`, `code`, `data`, `message_key`.",
                "- `expose client 5xx <fields>` — comma-separated closed catalog: `code`, `data`. (`message` deliberately excluded — 5xx text is framework-internal.)",
                "- `<code> message @translation.<key>` — per-code typed override. Closed catalog of 12 codes: `policy_denied`, `validation_failed`, `tenant_mismatch`, `not_found`, `rate_limited`, `bad_request`, `method_not_allowed`, `integration_error`, `unique_violation`, `foreign_key_violation`, `not_null_violation`, `check_violation`.",
                "",
                "**Resolution chain** (proposal §2.E)",
                "1. `command.policy_when_denied` — per-command override.",
                "2. `policies.<category>.when_denied` — per-policy default.",
                "3. `feature.errors.<code> message` — per-feature catch-all (this block).",
                "4. Runtime built-in PT-BR / en-US catalog — framework floor.",
                "",
                "**Example**",
                "```lazuli",
                "feature account",
                "  errors",
                "    default hide",
                "    expose client 4xx message, code, message_key",
                "    expose client 5xx code",
                "    policy_denied      message @translation.account_signin_required",
                "    validation_failed  message @translation.account_invalid_input",
                "```",
                "",
                "Doctor: `ERR-VOCAB-001`/`002`/`003`, `ERR-VOCAB-CODE-UNKNOWN`, `ERR-VOCAB-EXPOSE-UNKNOWN`, `ERR-VOCAB-EXPOSE-5XX-MESSAGE`.",
            ]
            .join("\n"),
        ),
        "when_denied" => Some(
            [
                "**`when_denied`** — typed override for the `policy_denied` error message rendered to the wire. Two attachment sites:",
                "",
                "- Under a `command.policy` line — per-command override (resolution-chain step 1).",
                "- Under a `policies.<category>:` line — per-policy default (resolution-chain step 2).",
                "",
                "**Shape**",
                "- `when_denied @translation.<key>` — references a key declared in the surrounding feature's `translation` block.",
                "",
                "**Resolution chain** (proposal §2.E)",
                "1. `command.policy_when_denied` (this site, on a `command.policy` line).",
                "2. `policies.<category>.when_denied` (this site, on a `policies` entry).",
                "3. `feature.errors.policy_denied message`.",
                "4. Runtime built-in localized message.",
                "",
                "**Example**",
                "```lazuli",
                "feature account",
                "  policies",
                "    authenticated: @scope.authenticated",
                "      when_denied @translation.must_be_signed_in",
                "",
                "  command choose_role",
                "    policy @policy.authenticated",
                "      when_denied @translation.choose_role_signin_required",
                "```",
                "",
                "Doctor: `ERR-VOCAB-001` (warn, no override anywhere), `ERR-VOCAB-002` (error, key unresolved), `ERR-VOCAB-WHEN-DENIED-NO-POLICY` (error, attached to a command without a `policy`).",
            ]
            .join("\n"),
        ),
        "message_key" => Some(
            [
                "**`message_key`** — opt-in 4xx wire-envelope field exposing the resolved `@translation.<key>` token alongside `message`. Lets clients with offline catalogs (native mobile apps, kiosks) localize independently from the server-rendered string.",
                "",
                "**Shape**",
                "- Listed inside `expose client 4xx <fields>` in a feature's `errors` block.",
                "- Always namespaced on the wire: `<feature>.<key>` (e.g. `account.choose_role_signin_required`).",
                "",
                "**Example**",
                "```lazuli",
                "feature account",
                "  errors",
                "    expose client 4xx message, code, message_key",
                "    policy_denied message @translation.account_signin_required",
                "```",
                "",
                "Wire payload:",
                "```json",
                "{",
                "  \"code\": \"policy_denied\",",
                "  \"message\": \"Para escolher seu papel, entre na sua conta primeiro.\",",
                "  \"message_key\": \"account.account_signin_required\"",
                "}",
                "```",
                "",
                "Closed-catalog field — alternatives (`message`, `code`, `data`) live under the same parent. Doctor: `ERR-VOCAB-EXPOSE-UNKNOWN` rejects unknown fields.",
            ]
            .join("\n"),
        ),
        // `docs/proposals/ir-resource-conventions-crud.md` §4.4 + the
        // `docs/proposals/ir-resource-conventions-me.md` §4.4 — rich
        // hover for the resource-level `conventions [..]` opt-in. Body
        // begins with the verbatim one-liner from the proposal so the
        // hover surface, the docstring on `Resource.conventions`, and
        // the doctor diagnostic share phrasing. Cells C4 + M3.
        "conventions" => Some(
            [
                "**`conventions`** — Resource-level conventions opt-in: `conventions [<name1>, <name2>, ...]`. Each entry references a closed-catalog convention bundle that auto-synthesizes commands/queries during lowering. Today's catalog: `crud`, `me`. See `docs/proposals/ir-resource-conventions-crud.md` and `docs/proposals/ir-resource-conventions-me.md`.",
                "",
                "**Closed catalog**",
                "- `crud` — auto-synthesizes the 5 canonical CRUD shapes (`create_<r>`, `update_<r>`, `delete_<r>`, `lookup_<r>`, `list_<r>s`).",
                "- `me` — auto-synthesizes one `lookup_my_<r>` query keyed by the active actor (`ctx.User.ID` / `ctx.User.OrgID`), per `ir-resource-conventions-me.md` §5.",
                "",
                "**Example**",
                "```lazuli",
                "resource Customer",
                "  email: @semantic.Email required unique",
                "  name: Text required",
                "  conventions [crud, me]",
                "```",
                "",
                "**Authoring rules**",
                "- Empty list (`conventions []`) is a parse error — omit the slot instead.",
                "- An author-written `command <name>` overrides the synth for that name; the remaining synth entries still emit (per §6 RULE-VOCAB-02).",
                "- Unknown identifiers fail at parse time with doctor code `conventions_unknown`.",
                "",
                "**Inspect**: `lazuli inspect features` annotates each opted-in resource with `(conventions: <bundle>)` and each synthesized command/query with `[conv:<bundle>]`.",
            ]
            .join("\n"),
        ),
        // `docs/proposals/ir-resource-conventions-owner-scope.md` §7.5 +
        // §11.3 — rich Markdown hover for the `@owner_axis(through: <col>)`
        // FK annotation. Body opens with the verbatim one-liner from
        // §11.3 (also surfaced as the `keyword_description` fallback) so
        // the hover surface, the doctor diagnostic phrasing, and the
        // docstring on `Field.owner_axis` all agree. Cell O3.
        "@owner_axis" | "owner_axis" => Some(
            [
                "**`@owner_axis`** — Field-level annotation: `@owner_axis(through: <column>)`. Marks the field as the FK that anchors the resource's ownership chain. The crud / me synth passes use this to emit ownership-restricted WHERE clauses (the row's owner is resolved through the chain to `ctx.User.ID` rather than just the tenant). See `docs/proposals/ir-resource-conventions-owner-scope.md` §7.",
                "",
                "**Required parameter**",
                "- `through: <column>` — column on the FK target resource that holds the actor key. Typically `user` (the User-typed column on the target).",
                "",
                "**Example**",
                "```lazuli",
                "resource Property",
                "  org: Org required",
                "  host: Host required @owner_axis(through: user)",
                "  name: Text required",
                "  conventions [crud]",
                "```",
                "",
                "**Lowered SQL** (for `delete_property` under `conventions [crud]`):",
                "```sql",
                "DELETE FROM \"property\"",
                "WHERE id = $1",
                "  AND org_id = $2",
                "  AND host IN (SELECT id FROM \"host\" WHERE \"user\" = $3)",
                "```",
                "",
                "**Authoring rules**",
                "- Only valid on FK fields (the type must reference another resource). Doctor code `owner_axis_on_non_fk` fires otherwise.",
                "- The `through:` column must exist on the FK target resource. Doctor code `owner_axis_unknown_through` fires otherwise.",
                "- Redundant with `user: User required unique` on the same resource. Doctor code `owner_axis_collides_with_unique_user` warns when both are present.",
                "",
                "**Inspect**: `lazuli inspect features` adds `, owner-scope` to the resource's `(conventions: ...)` annotation and `, owner-scope` to each synth-origin command/query's `[conv:<bundle>]` tag.",
            ]
            .join("\n"),
        ),
        _ => None,
    }
}
