// ── tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    /// Mirror of the pilot incident `User` struct — just enough fields
    /// to exercise NOT NULL detection across pointer (`*string`) and
    /// value (`string`, `lazuli.Time`) types.
    const USER_RESOURCE_GEN_GO: &str = r#"// Code generated by lazuli; DO NOT EDIT.
package accountgen

import "github.com/lazuli/runtime/lazuli"

type User struct {
    ID                   lazuli.ID        `db:"id"                    json:"id"`
    OrgID                lazuli.ID        `db:"org_id"                json:"org_id"`
    Org                  lazuli.ID        `db:"org"                   json:"org"`
    Email                lazuli.Email     `db:"email"                 json:"email"`
    Phone                *string          `db:"phone"                 json:"phone,omitempty"`
    Name                 string           `db:"name"                  json:"name"`
    Role                 *string          `db:"role"                  json:"role,omitempty"`
    RegistrationStep     string           `db:"registration_step"     json:"registration_step"`
    IsEmailVerified      bool             `db:"is_email_verified"     json:"is_email_verified"`
    IsPhoneVerified      bool             `db:"is_phone_verified"     json:"is_phone_verified"`
    PasswordHash         string           `db:"password_hash"         json:"-"`
    MfaEnabled           bool             `db:"mfa_enabled"           json:"mfa_enabled"`
    NotificationsEnabled bool             `db:"notifications_enabled" json:"notifications_enabled"`
    CreatedAt            lazuli.Time      `db:"created_at"            json:"created_at"`
    UpdatedAt            lazuli.Time      `db:"updated_at"            json:"updated_at"`
}
"#;

    /// Set up a temp workspace with `dist/go/account/resource.gen.go`
    /// + a handler file under `features/account/handlers/<name>.go`,
    /// and run the rule.
    fn run_against(handler_source: &str, file_name: &str) -> (TempDir, Vec<Finding>) {
        let tmp = TempDir::new().unwrap();
        let root = tmp.path();
        // Codegen artifact.
        let dist = root.join("dist").join("go").join("account");
        fs::create_dir_all(&dist).unwrap();
        fs::write(dist.join("resource.gen.go"), USER_RESOURCE_GEN_GO).unwrap();
        // Handler.
        let handlers = root.join("features").join("account").join("handlers");
        fs::create_dir_all(&handlers).unwrap();
        let handler_path = handlers.join(file_name);
        fs::write(&handler_path, handler_source).unwrap();
        let is_test = file_name.ends_with("_test.go");
        let handlers_list = vec![GoHandlerSourceFile {
            feature_name: "account".to_owned(),
            bucket: "handlers".to_owned(),
            relative_path: PathBuf::from(format!("features/account/handlers/{file_name}")),
            absolute_path: handler_path,
            source: handler_source.to_owned(),
            loc_count: handler_source.lines().count(),
            is_test,
        }];
        let findings = check(&handlers_list, root);
        (tmp, findings)
    }

    /// Pilot incident replay: a `register_with_google.go` INSERT that
    /// omits an *author-declared* NOT NULL column (`password_hash`).
    /// The rule MUST fire with `password_hash` named. (The synthesized
    /// `id` / `created_at` / `updated_at` are deliberately also omitted
    /// here and MUST NOT appear in the missing set — Postgres supplies
    /// them.)
    #[test]
    fn pilot_incident_replay_fires() {
        let src = r#"package handlers

import "context"

func RegisterWithGoogle(ctx context.Context) error {
    _, err := db.Exec(ctx,
        `INSERT INTO "user" (
           org_id, org, email, name,
           registration_step, is_email_verified, is_phone_verified,
           mfa_enabled, notifications_enabled
         ) VALUES ($1, $1, $2, $3, 'role_pending', $4, false, false, true)`,
        orgID, email, name, verified,
    )
    return err
}
"#;
        let (_tmp, findings) = run_against(src, "register_with_google.go");
        assert_eq!(findings.len(), 1, "got: {findings:#?}");
        match &findings[0].kind {
            FindingKind::Missing { missing } => {
                assert!(
                    missing.contains(&"password_hash".to_owned()),
                    "expected password_hash in missing list, got {missing:?}",
                );
                // Synthesized columns must never leak into the drift set.
                assert!(
                    !missing.contains(&"id".to_owned()),
                    "id (BIGSERIAL identity) must not be flagged, got {missing:?}",
                );
                assert!(
                    !missing.contains(&"created_at".to_owned())
                        && !missing.contains(&"updated_at".to_owned()),
                    "timestamps (DEFAULT NOW()) must not be flagged, got {missing:?}",
                );
            }
            other => panic!("expected Missing, got {other:?}"),
        }
        assert_eq!(findings[0].table, "user");
        assert_eq!(findings[0].resource.as_deref(), Some("User"));
        assert!(findings[0].message().contains("password_hash"));
        assert!(findings[0].message().contains("NOT NULL"));
    }

    /// REGRESSION (W4, pauta false-positive class): a handler INSERT
    /// that omits `id` (BIGSERIAL identity PK) and the timestamps but
    /// enumerates every author-declared NOT NULL column MUST be clean.
    /// Postgres auto-generates the serial PK and defaults the
    /// timestamps; this is the canonical correct INSERT shape and the
    /// rule fired on it before the synthesized-column exclusion.
    #[test]
    fn serial_pk_and_timestamps_omitted_does_not_fire() {
        let src = r#"package handlers

func Insert() {
    _, _ = db.Exec(ctx, `INSERT INTO "user" (
        org_id, org, email, name,
        registration_step, is_email_verified, is_phone_verified,
        password_hash, mfa_enabled, notifications_enabled
    ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)`)
}
"#;
        let (_tmp, findings) = run_against(src, "insert_user.go");
        assert!(
            findings.is_empty(),
            "omitting serial id + DEFAULT-NOW timestamps must NOT fire; got: {findings:#?}",
        );
    }

    /// CONTROL: same shape as the regression test but additionally
    /// omits a real author-declared NOT NULL column (`email`). The rule
    /// MUST still fire — and name only the author column, not the
    /// synthesized ones that are also absent.
    #[test]
    fn real_required_column_omitted_still_fires() {
        let src = r#"package handlers

func Insert() {
    _, _ = db.Exec(ctx, `INSERT INTO "user" (
        org_id, org, name,
        registration_step, is_email_verified, is_phone_verified,
        password_hash, mfa_enabled, notifications_enabled
    ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`)
}
"#;
        let (_tmp, findings) = run_against(src, "insert_user.go");
        assert_eq!(findings.len(), 1, "got: {findings:#?}");
        match &findings[0].kind {
            FindingKind::Missing { missing } => {
                assert_eq!(
                    missing,
                    &vec!["email".to_owned()],
                    "expected exactly [email] (no synthesized columns), got {missing:?}",
                );
            }
            other => panic!("expected Missing, got {other:?}"),
        }
    }

    /// CONTROL: a handler that references a non-existent column
    /// (`nonexistent_col`) while omitting the real required `email`
    /// still fires the drift for the genuinely-missing author column.
    /// (v0.1 does not separately validate that referenced columns
    /// exist — but it must keep catching the omitted-required class even
    /// when junk columns are present.)
    #[test]
    fn nonexistent_column_reference_still_catches_real_drift() {
        let src = r#"package handlers

func Insert() {
    _, _ = db.Exec(ctx, `INSERT INTO "user" (
        org_id, org, name, nonexistent_col,
        registration_step, is_email_verified, is_phone_verified,
        password_hash, mfa_enabled, notifications_enabled
    ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)`)
}
"#;
        let (_tmp, findings) = run_against(src, "insert_user.go");
        assert_eq!(findings.len(), 1, "got: {findings:#?}");
        match &findings[0].kind {
            FindingKind::Missing { missing } => {
                assert!(
                    missing.contains(&"email".to_owned()),
                    "expected email (real omitted required col), got {missing:?}",
                );
            }
            other => panic!("expected Missing, got {other:?}"),
        }
    }

    /// Happy path — INSERT enumerates every NOT NULL column. No finding.
    #[test]
    fn happy_path_no_finding() {
        let src = r#"package handlers

func Insert() {
    _, _ = db.Exec(ctx, `INSERT INTO "user" (
        id, org_id, org, email, name,
        registration_step, is_email_verified, is_phone_verified,
        password_hash, mfa_enabled, notifications_enabled,
        created_at, updated_at
    ) VALUES (DEFAULT, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)`)
}
"#;
        let (_tmp, findings) = run_against(src, "insert_user.go");
        assert!(
            findings.is_empty(),
            "got unexpected findings: {findings:#?}"
        );
    }

    /// String-concatenated SQL (`"INSERT INTO " + tableName + ...`):
    /// the raw-string walker never sees the full statement. v0.1
    /// emits an `SqlUnreadable` finding for any backtick raw string
    /// containing just `INSERT INTO ` with no parenthesised column
    /// list — so authors who concatenated half the SQL into one
    /// fragment still get told the rule can't validate.
    #[test]
    fn concatenated_sql_emits_unreadable() {
        let src = r#"package handlers

func Insert() {
    _, _ = db.Exec(ctx, `INSERT INTO `+table+` (id, email) VALUES ($1, $2)`)
}
"#;
        let (_tmp, findings) = run_against(src, "concat.go");
        // The first raw string is "INSERT INTO " — no table, no
        // column list → Unreadable.
        assert!(
            findings
                .iter()
                .any(|f| matches!(f.kind, FindingKind::SqlUnreadable { .. })),
            "expected SqlUnreadable finding, got: {findings:#?}",
        );
        // And NOT a Missing finding (no false positive on the
        // concatenated form — the catalog can't resolve a partial
        // table name).
        assert!(
            !findings
                .iter()
                .any(|f| matches!(f.kind, FindingKind::Missing { .. })),
            "did not expect Missing finding on concatenated SQL, got: {findings:#?}",
        );
    }

    /// `INSERT INTO "stripe_webhook_log"` — not a Lazuli resource.
    /// Rule short-circuits silently (no finding, no panic).
    #[test]
    fn non_lazuli_table_silent() {
        let src = r#"package handlers

func Log() {
    _, _ = db.Exec(ctx, `INSERT INTO "stripe_webhook_log" (id, payload) VALUES ($1, $2)`)
}
"#;
        let (_tmp, findings) = run_against(src, "log.go");
        assert!(findings.is_empty(), "got: {findings:#?}");
    }

    /// `dist/go/` does not exist (initial codegen not yet run). Every
    /// table fails to resolve → no findings, no panic.
    #[test]
    fn no_codegen_artifact_silent() {
        let tmp = TempDir::new().unwrap();
        let root = tmp.path();
        let handlers = root.join("features").join("account").join("handlers");
        fs::create_dir_all(&handlers).unwrap();
        let src = r#"package handlers
func Insert() {
    _, _ = db.Exec(ctx, `INSERT INTO "user" (id) VALUES ($1)`)
}
"#;
        let handler_path = handlers.join("insert.go");
        fs::write(&handler_path, src).unwrap();
        let handlers_list = vec![GoHandlerSourceFile {
            feature_name: "account".to_owned(),
            bucket: "handlers".to_owned(),
            relative_path: PathBuf::from("features/account/handlers/insert.go"),
            absolute_path: handler_path,
            source: src.to_owned(),
            loc_count: src.lines().count(),
            is_test: false,
        }];
        let findings = check(&handlers_list, root);
        assert!(findings.is_empty(), "got: {findings:#?}");
    }

    /// `// doctor:allow HANDLER-SQL-COLUMN-DRIFT-001` on the line
    /// above the INSERT silences the finding.
    #[test]
    fn allow_comment_silences() {
        let src = r#"package handlers

func Insert() {
    // doctor:allow HANDLER-SQL-COLUMN-DRIFT-001 — reason "trigger fills updated_at"
    _, _ = db.Exec(ctx, `INSERT INTO "user" (
        id, org_id, org, email, name, registration_step,
        is_email_verified, is_phone_verified, password_hash,
        mfa_enabled, notifications_enabled, created_at
    ) VALUES (DEFAULT, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)`)
}
"#;
        let (_tmp, findings) = run_against(src, "insert_user.go");
        assert!(
            findings.is_empty(),
            "allow comment should silence; got: {findings:#?}"
        );
    }

    /// UPDATE statements (v0.1 deferred) MUST NOT false-positive.
    /// The parser sees the statement, classifies it as `Update`, and
    /// emits no finding.
    #[test]
    fn negative_update_does_not_false_positive() {
        let src = r#"package handlers

func Touch() {
    _, _ = db.Exec(ctx, `UPDATE "user" SET name = $1, updated_at = NOW() WHERE id = $2`)
}
"#;
        let (_tmp, findings) = run_against(src, "touch.go");
        assert!(
            findings.is_empty(),
            "UPDATE must not fire in v0.1; got: {findings:#?}"
        );
    }

    /// `*_test.go` files are skipped — Go test convention uses
    /// arbitrary SQL fixtures.
    #[test]
    fn test_file_skipped() {
        let src = r#"package handlers

func TestInsert(t *testing.T) {
    _, _ = db.Exec(ctx, `INSERT INTO "user" (id) VALUES ($1)`)
}
"#;
        let (_tmp, findings) = run_against(src, "register_with_google_test.go");
        assert!(
            findings.is_empty(),
            "test files must be silent; got: {findings:#?}"
        );
    }

    // ── fine-grained parser tests ───────────────────────────────────────────

    #[test]
    fn parse_insert_header_quoted_table() {
        let (table, cols) = parse_insert_header(r#" "user" (id, email, name)"#).unwrap();
        assert_eq!(table, "user");
        assert_eq!(cols, vec!["id", "email", "name"]);
    }

    #[test]
    fn parse_insert_header_unquoted_table() {
        let (table, cols) = parse_insert_header(" user (id, email)").unwrap();
        assert_eq!(table, "user");
        assert_eq!(cols, vec!["id", "email"]);
    }

    #[test]
    fn parse_insert_header_no_column_list_returns_none() {
        // `INSERT INTO "user" VALUES (...)` — no column list. v0.1
        // can't validate this shape, so the parser returns None and
        // the caller skips silently.
        assert!(parse_insert_header(r#" "user" VALUES ($1, $2)"#).is_none());
    }

    #[test]
    fn parse_db_tag_handles_omitempty() {
        assert_eq!(
            extract_db_tag("db:\"phone,omitempty\" json:\"phone\""),
            Some("phone".into())
        );
    }

    #[test]
    fn parse_db_tag_skips_dash() {
        assert!(extract_db_tag("db:\"-\"").is_none());
    }

    #[test]
    fn lower_snake_basic() {
        assert_eq!(lower_snake("User"), "user");
        assert_eq!(lower_snake("OrgInvitation"), "org_invitation");
        assert_eq!(lower_snake("HTTPServer"), "httpserver");
    }

    #[test]
    fn resource_catalog_skips_pointer_fields() {
        let parsed = parse_resource_structs(USER_RESOURCE_GEN_GO);
        assert_eq!(parsed.len(), 1);
        assert_eq!(parsed[0].resource_name, "User");
        assert!(
            parsed[0]
                .required_columns
                .contains(&"updated_at".to_owned())
        );
        assert!(
            parsed[0]
                .required_columns
                .contains(&"created_at".to_owned())
        );
        // Pointer-typed fields (Phone, Role) are NOT in the required
        // set — they're nullable.
        assert!(!parsed[0].required_columns.contains(&"phone".to_owned()));
        assert!(!parsed[0].required_columns.contains(&"role".to_owned()));
    }
}
