//! Tests for the feature-level `emit_events_file` entry point with
//! a standalone (non-grouped) typed event. Split out of `mod.rs` to
//! keep production under the 500 LOC budget.

use super::*;
use crate::emitter::cross_feature::CrossFeatureIndex;
use lazuli_ir::{
    BuiltinType, Defaults, Event, EventField, EventKind, Feature, Module, OutboxMode, Policies,
    TypeRef,
};

fn feature_with_standalone_event() -> Feature {
    Feature {
        name: "customer".to_owned(),
        purpose: None,
        non_goals: Vec::new(),
        context_path: None,
        knowledge: None,
        defaults: Defaults {
            tenancy: None,
            timestamps: false,
            policy: None,
            rate_limit: None,
            audit: None,
        },
        uses: Vec::new(),
        uses_spans: Vec::new(),
        uses_versions: Vec::new(),
        requirements: Vec::new(),
        enums: Vec::new(),
        resources: Vec::new(),
        events: vec![Event {
            name: "customer_signed_up".to_owned(),
            kind: EventKind::Domain,
            payload: vec![
                EventField {
                    name: "customer_id".to_owned(),
                    type_ref: TypeRef::Builtin(BuiltinType::Id),
                    optional: false,
                },
                EventField {
                    name: "email".to_owned(),
                    type_ref: TypeRef::Builtin(BuiltinType::SemanticEmail),
                    optional: false,
                },
            ],
            payload_none: false,
            level: None,
            outbox: OutboxMode::None,
            previous_names: Vec::new(),
            span_ref: None,
        }],
        rules: Vec::new(),
        policies: Policies {
            categories: Vec::new(),
            fields: Vec::new(),
            span_ref: None,
        },
        errors: None,
        commands: Vec::new(),
        apis: Vec::new(),
        records: Vec::new(),
        queries: Vec::new(),
        resume_routers: Vec::new(),
        workflows: Vec::new(),
        jobs: Vec::new(),
        webhooks: Vec::new(),
        notifications: Vec::new(),
        event_groups: Vec::new(),
        tenant_migrations: Vec::new(),
        translation: None,
        pollers: vec![],
        auth: None,
        surfaces: Vec::new(),
        extensions: Vec::new(),
        escape_routes: Vec::new(),
        agents: Vec::new(),
        reports: Vec::new(),
        channels: Vec::new(),
        caches: Vec::new(),
        aggregates: vec![],
        mcp_servers: vec![],
        previous_names: Vec::new(),
        span_ref: None,
        synth_origins: std::collections::BTreeMap::new(),
    }
}

fn module_with_feature(feature: Feature) -> Module {
    Module {
        workspace: None,
        contracts: Vec::new(),
        app: None,
        registry: None,
        profiles: Vec::new(),
        design: None,
        rbac: None,
        doctor_allows: Vec::new(),
        features: vec![feature],
    }
}

#[test]
fn feature_emit_entry_point_emits_standalone_event_payload() {
    let feature = feature_with_standalone_event();
    let module = module_with_feature(feature.clone());
    let cross_index = CrossFeatureIndex::build(&module);

    let out = emit_events_file(
        "features/customer/customer.lzi",
        &feature,
        "lazuli/test",
        &cross_index,
    )
    .expect("feature with a standalone event must emit events.gen.go");

    assert!(!out.is_empty());
    assert!(out.contains("// Code generated by lazuli; DO NOT EDIT."));
    assert!(out.contains("package customergen"));
    assert!(out.contains("type CustomerSignedUpPayload struct {"));
    assert!(out.contains("CustomerID lazuli.ID    `json:\"customer_id\"`"));
    assert!(out.contains("Email      lazuli.Email `json:\"email\"`"));
}

/// EVENT_GROUP-HOIST — after the analyzer hoists an `event_group`
/// variant into `Feature.events`, the events emitter must still produce
/// the variant payload struct EXACTLY ONCE (from the group/variant
/// path), not a second time via the standalone-event loop. A duplicate
/// would emit the struct twice with doubled fields and break `go build`.
#[test]
fn hoisted_group_variant_payload_struct_emitted_once() {
    use lazuli_ir::{EventGroup, EventVariant, EventVariantKind};

    let variant_fields = vec![EventField {
        name: "amount".to_owned(),
        type_ref: TypeRef::Builtin(BuiltinType::Id),
        optional: false,
    }];
    let mut feature = feature_with_standalone_event();
    // Drop the unrelated standalone event so the assertion is precise.
    feature.events = vec![Event {
        // The analyzer hoists the variant under the group-prefixed name.
        name: "charge_confirmed".to_owned(),
        kind: EventKind::Domain,
        payload: variant_fields.clone(),
        payload_none: false,
        level: None,
        outbox: OutboxMode::None,
        previous_names: Vec::new(),
        span_ref: None,
    }];
    feature.event_groups = vec![EventGroup {
        pattern: "charge_*".to_owned(),
        on_resource: Some("Charge".to_owned()),
        raw_payload: vec![],
        raw_audit: None,
        events: vec!["confirmed".to_owned()],
        events_outbox: vec![],
        variants: vec![EventVariant {
            name: "confirmed".to_owned(),
            kind: EventVariantKind::Committed,
            outbox: OutboxMode::None,
            fields: variant_fields,
            span_ref: None,
        }],
        span_ref: None,
    }];

    let module = module_with_feature(feature.clone());
    let cross_index = CrossFeatureIndex::build(&module);
    let out = emit_events_file(
        "features/billing/billing.lzi",
        &feature,
        "lazuli/test",
        &cross_index,
    )
    .expect("feature with an event group must emit events.gen.go");

    let struct_decls = out.matches("type ChargeConfirmedPayload struct {").count();
    assert_eq!(
        struct_decls, 1,
        "hoisted variant payload struct must be emitted exactly once, not duplicated \
         via the standalone-event path:\n{out}"
    );
    // And the single struct must carry the field exactly once.
    assert_eq!(
        out.matches("Amount").count(),
        1,
        "payload field must not be duplicated:\n{out}"
    );
}
