[package]
name = "lazuli_codegen_go"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
smoke = []

[dependencies]
lazuli_ir = { path = "../lazuli_ir" }
lazuli_codegen_spec = { path = "../lazuli_codegen_spec" }

[dev-dependencies]
lazuli_analyzer = { path = "../lazuli_analyzer" }
lazuli_syntax = { path = "../lazuli_syntax" }
