// Code generated by lazuli; DO NOT EDIT.
import { createElement, type FunctionComponent, type ReactElement } from "@lazuli/runtime/react";
import { Link, Outlet, createRootRouteWithContext, createRoute, createRouter, type LinkProps, type NotFoundRouteComponent, type QueryClient } from "@lazuli/runtime/react/tanstack";
import type { LazuliClient } from "@lazuli/runtime";

export const routeSpecs = [
  {
    name: "host_booking_detail",
    path: "/host/bookings/$booking_id",
    audience: "host",
    component: "hostBookingDetail",
  },
  {
    name: "host_home",
    path: "/host",
    audience: "host",
    component: "hostHome",
  },
] as const;

export type ClientComponentKey = "hostBookingDetail" | "hostHome";
export type GeneratedRouterContext = { client: LazuliClient; queryClient: QueryClient };
export type GeneratedRouterComponents = Record<ClientComponentKey, FunctionComponent<any>>;
export type GeneratedRouterGuards = Partial<Record<ClientComponentKey, (params: { context: GeneratedRouterContext }) => unknown | Promise<unknown>>>;

export function createGeneratedRouter(options: {
  client: LazuliClient;
  queryClient: QueryClient;
  components: GeneratedRouterComponents;
  guards?: GeneratedRouterGuards;
  notFoundComponent?: NotFoundRouteComponent;
  defaultPreload?: "intent" | "viewport" | "render" | false;
}) {
  const rootRoute = createRootRouteWithContext<GeneratedRouterContext>()({
    component: () => createElement(Outlet),
  });
  const hostBookingDetailRoute = createRoute({
    getParentRoute: () => rootRoute,
    path: "/host/bookings/$booking_id",
    component: options.components.hostBookingDetail,
    beforeLoad: options.guards?.hostBookingDetail,
  });
  const hostHomeRoute = createRoute({
    getParentRoute: () => rootRoute,
    path: "/host",
    component: options.components.hostHome,
    beforeLoad: options.guards?.hostHome,
  });
  const routeTree = rootRoute.addChildren([hostBookingDetailRoute, hostHomeRoute] as const);
  return createRouter({
    routeTree,
    context: { client: options.client, queryClient: options.queryClient },
    defaultPreload: options.defaultPreload,
    defaultNotFoundComponent: options.notFoundComponent,
  });
}

export const AppLink = Link as <T extends LinkProps["to"]>(
  props: LinkProps & { to: T },
) => ReactElement;
