//! `.lzx` view-kind emitters — compile-time MVVM hooks per
//! `docs/proposals/lzx-integration-codegen.md` §6.
//!
//! Three view kinds each emit a single `<view>.gen.ts` to:
//!
//! ```text
//! dist/ts-<target>/<feat>/views/<audience>/<view-name>.gen.ts
//! ```
//!
//! Per L0 #1 §4 file canon. `<target>` is `ts-web` or `ts-mobile`
//! depending on the surface's `SurfaceTarget`; `<feat>`, `<audience>`,
//! `<view-name>` come straight off the IR — kebab-case and snake_case
//! are preserved verbatim in the path, then pascal-cased for hook
//! identifiers.
//!
//! Module layout:
//!
//! - `ir` — the canonical `.lzx` IR stub. The real types land in
//!   `lazuli_ir` via a separate cell; until that arrives this module
//!   owns the contract end-to-end so the emitters can be exercised
//!   under `cargo test -p lazuli_codegen_ts`.
//! - `lzx_view_list` / `lzx_view_detail` / `lzx_view_create` — the
//!   three per-kind emitters. Each is independent and shares only the
//!   helpers in this file (banner, qualified imports, identifier
//!   casing, file paths).
//! - `lzx_router_adapter` — the per-target `useParams` import switch
//!   for `view detail`.
//! - `emit_surface_views` — top-level walker. Orchestrator wires this
//!   into `generate()` post-merge.

#[path = "../lzx_router_adapter.rs"]
pub mod lzx_router_adapter;

#[path = "../lzx_aux/mod.rs"]
pub mod lzx_aux;

#[path = "../lzx_filters.rs"]
pub mod lzx_filters;

#[path = "../lzx_search.rs"]
pub mod lzx_search;

#[path = "../lzx_view_list/mod.rs"]
pub mod lzx_view_list;

#[path = "../lzx_view_detail.rs"]
pub mod lzx_view_detail;

#[path = "../lzx_view_create.rs"]
pub mod lzx_view_create;

mod casing;
mod formatting;
mod idents;
mod paths;

pub(crate) use casing::{lower_camel, pascal_case, pascal_tokens};
pub(crate) use formatting::{
    escape_ts_string, format_cells_literal, format_on_success_options, format_string_array,
};
pub(crate) use idents::{command_action_key, command_ident, query_ident, strip_verb_prefix};
pub(crate) use paths::{audience_view_pascal, view_file_path, view_hook_name, view_spec_const};

use crate::{GeneratedFile, pluralize};
use lzx_router_adapter::RouterTarget;

// ---------------------------------------------------------------------------
// Canonical IR stub — replaced by `lazuli_ir` once the `.lzx` parser cell
// lands. The shapes match the spec in the L0 #3 cell-B brief verbatim.
// ---------------------------------------------------------------------------

pub mod ir {
    //! Canonical .lzx IR types — re-exported from lazuli_ir.
    //! (Original stubs replaced after Cell A.1+A.2+A.3 landed in 235d7a7.)
    pub use lazuli_ir::{
        Surface, SurfaceTarget, Audience, View, ViewList, ViewDetail, ViewCreate,
        QueryRef, QueryKind, CommandRef, CellBinding, RouteParam, PolicyAtom,
        ListRender, SearchDecl, SearchMode, SearchField, BindingRef, FilterDecl, FilterCardinality,
        DrawerSubView, DrawerTrigger, DrawerRouteBinding, DrawerBindingSource,
        SortDecl, SortDir, SelectionDecl, SelectionMode, SettingDecl,
        SettingValueSpace, SettingPersistence, OnSuccessSpec, FlashSpec,
        InvalidatesSpec, TranslationKeyRef, QualifiedName,
    };
}

pub use ir::*;

// ---------------------------------------------------------------------------
// Shared emitter helpers — used by all three view-kind emitters.
// ---------------------------------------------------------------------------

/// Emit the canonical `// Code generated …` banner that every `.gen.ts`
/// file shares.
pub(crate) fn banner() -> &'static str {
    "// Code generated by lazuli; DO NOT EDIT.\n"
}

// ---------------------------------------------------------------------------
// Top-level walker — orchestrator wires this into `generate()` post-merge.
// ---------------------------------------------------------------------------

/// Walk a `Surface` and emit one `<view>.gen.ts` per (audience, view)
/// tuple. The `router_target` parameter feeds the per-target
/// `useParams` import for `view detail` hooks (per §6.2 table); list
/// and create views ignore it. `app_name` is the project name from
/// `Lazurite.toml [project] name` — used as the localStorage namespace
/// prefix for `settings ... persist local` so two apps don't collide
/// on the same view name (proposal §3.7). Empty string falls back to
/// the feature name.
///
/// ## Examples
///
/// ```ignore
/// use lazuli_codegen_ts::lzx::emit_surface_views;
/// use lazuli_codegen_ts::lzx::lzx_router_adapter::RouterTarget;
/// use lazuli_ir::Surface;
///
/// let surface: Surface = /* … */ unimplemented!();
/// let files = emit_surface_views(&surface, RouterTarget::ViteReact, "hostpoint");
/// assert!(files.iter().all(|f| f.path.ends_with(".gen.ts")));
/// ```
pub fn emit_surface_views(
    surface: &Surface,
    router_target: RouterTarget,
    app_name: &str,
) -> Vec<GeneratedFile> {
    let mut files = Vec::new();
    for audience in &surface.audiences {
        for view in &audience.views {
            let (view_name, contents) = match view {
                View::List(v) => (
                    v.name.clone(),
                    lzx_view_list::emit_view_list(surface, audience, v, app_name),
                ),
                View::Detail(v) => (
                    v.name.clone(),
                    lzx_view_detail::emit_view_detail(surface, audience, v, router_target),
                ),
                View::Create(v) => (
                    v.name.clone(),
                    lzx_view_create::emit_view_create(surface, audience, v),
                ),
            };
            files.push(GeneratedFile {
                path: view_file_path(surface.target, &surface.feature, &audience.name, &view_name),
                contents,
            });
        }
    }
    files
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
pub(crate) mod test_fixtures;

#[cfg(test)]
mod tests {
    use super::*;
    use lzx_router_adapter::RouterTarget;

    #[test]
    fn emit_surface_views_matches_proposal_section_13() {
        // Walks the §13.1 `slug.web.lzx` fixture and asserts the four
        // emitted files land at the right paths with the right
        // top-level identifiers.
        let surface = test_fixtures::slug_web_surface();
        let files = emit_surface_views(&surface, RouterTarget::ViteReact, "");

        // Four (audience, view) tuples: admin × {list, detail, create}
        // plus public × list.
        assert_eq!(files.len(), 4, "expected 4 files, got {:?}",
            files.iter().map(|f| f.path.as_str()).collect::<Vec<_>>());

        let paths: Vec<&str> = files.iter().map(|f| f.path.as_str()).collect();
        assert!(paths.contains(&"dist/ts-web/slug/views/admin/slug_list.gen.ts"));
        assert!(paths.contains(&"dist/ts-web/slug/views/admin/slug_detail.gen.ts"));
        assert!(paths.contains(&"dist/ts-web/slug/views/admin/slug_create.gen.ts"));
        assert!(paths.contains(&"dist/ts-web/slug/views/public/public_slug_list.gen.ts"));

        // Spot-check each emitted file carries its hook + spec const.
        let by_path = |p: &str| files.iter().find(|f| f.path == p).expect("path present");

        let list_file = by_path("dist/ts-web/slug/views/admin/slug_list.gen.ts");
        assert!(list_file.contents.contains("export const adminSlugListView"));
        assert!(list_file.contents.contains("export function useAdminSlugListView"));
        assert!(list_file.contents.contains("listMineSlugs"));

        let detail_file = by_path("dist/ts-web/slug/views/admin/slug_detail.gen.ts");
        assert!(detail_file.contents.contains("export const adminSlugDetailView"));
        assert!(detail_file.contents.contains("export function useAdminSlugDetailView"));
        assert!(detail_file.contents.contains("@tanstack/react-router"));
        assert!(detail_file.contents.contains("AdminSlugDetailSections"));

        let create_file = by_path("dist/ts-web/slug/views/admin/slug_create.gen.ts");
        assert!(create_file.contents.contains("export const adminSlugCreateView"));
        assert!(create_file.contents.contains("export function useAdminSlugCreateView"));
        assert!(create_file.contents.contains("zodResolver"));

        let public_file = by_path("dist/ts-web/slug/views/public/public_slug_list.gen.ts");
        assert!(public_file.contents.contains("export const publicPublicSlugListView"));
        assert!(public_file.contents.contains("export function usePublicPublicSlugListView"));
    }

    #[test]
    fn emit_surface_views_switches_router_target_for_detail() {
        let surface = test_fixtures::slug_web_surface();

        let vite_files = emit_surface_views(&surface, RouterTarget::ViteReact, "");
        let nextjs_files = emit_surface_views(&surface, RouterTarget::NextJs, "");

        let vite_detail = vite_files
            .iter()
            .find(|f| f.path.ends_with("slug_detail.gen.ts"))
            .unwrap();
        let nextjs_detail = nextjs_files
            .iter()
            .find(|f| f.path.ends_with("slug_detail.gen.ts"))
            .unwrap();

        assert!(vite_detail.contents.contains("@tanstack/react-router"));
        assert!(!vite_detail.contents.contains("next/navigation"));
        assert!(nextjs_detail.contents.contains("next/navigation"));
        assert!(!nextjs_detail.contents.contains("@tanstack/react-router"));
    }

}
