//! `.lzx` view-kind emitters — compile-time MVVM hooks per
//! `docs/proposals/lzx-integration-codegen.md` §6.
//!
//! Three view kinds each emit a single `<view>.gen.ts` to:
//!
//! ```text
//! dist/ts-<target>/<feat>/views/<audience>/<view-name>.gen.ts
//! ```
//!
//! Per L0 #1 §4 file canon. `<target>` is `ts-web` or `ts-mobile`
//! depending on the surface's `SurfaceTarget`; `<feat>`, `<audience>`,
//! `<view-name>` come straight off the IR — kebab-case and snake_case
//! are preserved verbatim in the path, then pascal-cased for hook
//! identifiers.
//!
//! Module layout:
//!
//! - `ir` — the canonical `.lzx` IR stub. The real types land in
//!   `lazuli_ir` via a separate cell; until that arrives this module
//!   owns the contract end-to-end so the emitters can be exercised
//!   under `cargo test -p lazuli_codegen_ts`.
//! - `lzx_view_list` / `lzx_view_detail` / `lzx_view_create` — the
//!   three per-kind emitters. Each is independent and shares only the
//!   helpers in this file (banner, qualified imports, identifier
//!   casing, file paths).
//! - `lzx_router_adapter` — the per-target `useParams` import switch
//!   for `view detail`.
//! - `emit_surface_views` — top-level walker. Orchestrator wires this
//!   into `generate()` post-merge.

#[path = "../lzx_router_adapter.rs"]
pub mod lzx_router_adapter;

#[path = "../lzx_aux.rs"]
pub mod lzx_aux;

#[path = "../lzx_filters.rs"]
pub mod lzx_filters;

#[path = "../lzx_search.rs"]
pub mod lzx_search;

#[path = "../lzx_view_list/mod.rs"]
pub mod lzx_view_list;

#[path = "../lzx_view_detail.rs"]
pub mod lzx_view_detail;

#[path = "../lzx_view_create.rs"]
pub mod lzx_view_create;

mod casing;
mod idents;
mod paths;

pub(crate) use casing::{lower_camel, pascal_case, pascal_tokens};
pub(crate) use idents::{command_action_key, command_ident, query_ident, strip_verb_prefix};
pub(crate) use paths::{audience_view_pascal, view_file_path, view_hook_name, view_spec_const};

use crate::{GeneratedFile, pluralize};
use lzx_router_adapter::RouterTarget;

// ---------------------------------------------------------------------------
// Canonical IR stub — replaced by `lazuli_ir` once the `.lzx` parser cell
// lands. The shapes match the spec in the L0 #3 cell-B brief verbatim.
// ---------------------------------------------------------------------------

pub mod ir {
    //! Canonical .lzx IR types — re-exported from lazuli_ir.
    //! (Original stubs replaced after Cell A.1+A.2+A.3 landed in 235d7a7.)
    pub use lazuli_ir::{
        Surface, SurfaceTarget, Audience, View, ViewList, ViewDetail, ViewCreate,
        QueryRef, QueryKind, CommandRef, CellBinding, RouteParam, PolicyAtom,
        ListRender, SearchDecl, SearchMode, SearchField, BindingRef, FilterDecl, FilterCardinality,
        DrawerSubView, DrawerTrigger, DrawerRouteBinding, DrawerBindingSource,
        SortDecl, SortDir, SelectionDecl, SelectionMode, SettingDecl,
        SettingValueSpace, SettingPersistence, OnSuccessSpec, FlashSpec,
        InvalidatesSpec, TranslationKeyRef, QualifiedName,
    };
}

pub use ir::*;

// ---------------------------------------------------------------------------
// Shared emitter helpers — used by all three view-kind emitters.
// ---------------------------------------------------------------------------

/// Emit the canonical `// Code generated …` banner that every `.gen.ts`
/// file shares.
pub(crate) fn banner() -> &'static str {
    "// Code generated by lazuli; DO NOT EDIT.\n"
}

/// Format the `cells` literal for the spec const — a TS object literal
/// like `{ tags: "@client.type_badge" as const }`. Empty input emits an
/// empty object so the spec field is always present.
pub(crate) fn format_cells_literal(cells: &[CellBinding]) -> String {
    if cells.is_empty() {
        return "{}".to_owned();
    }
    let parts: Vec<String> = cells
        .iter()
        .map(|c| format!("{}: \"@client.{}\" as const", c.field, c.slot))
        .collect();
    format!("{{ {} }}", parts.join(", "))
}

/// Format a `["a", "b", "c"]` string literal array with each entry
/// quoted. Used for `columns` / `search` / `filter` / `fields`.
pub(crate) fn format_string_array(items: &[String]) -> String {
    if items.is_empty() {
        return "[]".to_owned();
    }
    let parts: Vec<String> = items.iter().map(|s| format!("\"{}\"", s)).collect();
    format!("[{}]", parts.join(", "))
}

pub(crate) fn format_on_success_options(spec: &OnSuccessSpec, host_feature: &str) -> String {
    let mut parts: Vec<String> = Vec::new();
    if spec.back {
        parts.push("back: true".to_owned());
    }
    if let Some(redirect) = &spec.redirect {
        parts.push(format!("redirect: \"{}\"", escape_ts_string(redirect)));
    }
    if let Some(flash) = &spec.flash {
        parts.push(format!(
            "flash: {{ kind: \"{}\", messageKey: \"{}\" }}",
            escape_ts_string(&flash.kind),
            escape_ts_string(&flash.message_key.key)
        ));
    }
    if !spec.invalidates.is_empty() {
        parts.push(format!(
            "invalidates: {}",
            format_string_array(&on_success_invalidates(spec, host_feature))
        ));
    }
    if spec.replace {
        parts.push("replace: true".to_owned());
    }
    format!("{{ {} }}", parts.join(", "))
}

fn on_success_invalidates(spec: &OnSuccessSpec, host_feature: &str) -> Vec<String> {
    spec.invalidates
        .iter()
        .map(|invalidates| {
            let feature = invalidates
                .query
                .feature
                .as_deref()
                .unwrap_or(host_feature);
            format!("{}.{}", feature, invalidates.query.name)
        })
        .collect()
}

pub(crate) fn escape_ts_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

// ---------------------------------------------------------------------------
// Top-level walker — orchestrator wires this into `generate()` post-merge.
// ---------------------------------------------------------------------------

/// Walk a `Surface` and emit one `<view>.gen.ts` per (audience, view)
/// tuple. The `router_target` parameter feeds the per-target
/// `useParams` import for `view detail` hooks (per §6.2 table); list
/// and create views ignore it. `app_name` is the project name from
/// `Lazurite.toml [project] name` — used as the localStorage namespace
/// prefix for `settings ... persist local` so two apps don't collide
/// on the same view name (proposal §3.7). Empty string falls back to
/// the feature name.
pub fn emit_surface_views(
    surface: &Surface,
    router_target: RouterTarget,
    app_name: &str,
) -> Vec<GeneratedFile> {
    let mut files = Vec::new();
    for audience in &surface.audiences {
        for view in &audience.views {
            let (view_name, contents) = match view {
                View::List(v) => (
                    v.name.clone(),
                    lzx_view_list::emit_view_list(surface, audience, v, app_name),
                ),
                View::Detail(v) => (
                    v.name.clone(),
                    lzx_view_detail::emit_view_detail(surface, audience, v, router_target),
                ),
                View::Create(v) => (
                    v.name.clone(),
                    lzx_view_create::emit_view_create(surface, audience, v),
                ),
            };
            files.push(GeneratedFile {
                path: view_file_path(surface.target, &surface.feature, &audience.name, &view_name),
                contents,
            });
        }
    }
    files
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
pub(crate) mod test_fixtures {
    //! Test fixtures shared between `lzx.rs` and the per-view emitter
    //! test modules. Encodes the L0 #3 §13.1 `slug.web.lzx` example
    //! verbatim.
    use super::ir::*;

    pub fn type_badge_cell() -> CellBinding {
        CellBinding {
            field: "tags".to_owned(),
            slot: "type_badge".to_owned(),
        }
    }

    pub fn slug_list_view() -> ViewList {
        ViewList {
            name: "slug_list".to_owned(),
            route: Some("/slugs".to_owned()),
            source: QueryRef {
                feature: "slug".to_owned(),
                kind: QueryKind::List,
                name: "mine".to_owned(),
            },
            render: ListRender::Table {
                columns: vec![
                    "key".to_owned(),
                    "title".to_owned(),
                    "tags".to_owned(),
                    "created_at".to_owned(),
                ],
            },
            search: Some(SearchDecl {
                mode: SearchMode::Columns {
                    columns: vec!["key".to_owned(), "title".to_owned()],
                },
                fields: vec![],
                free_text_target: None,
                span_ref: None,
            }),
            filter: vec![FilterDecl {
                name: "tags".to_owned(),
                type_ref: String::new(),
                cardinality: FilterCardinality::Single,
                url_sync: false,
                span_ref: None,
            }],
            cells: vec![type_badge_cell()],
            actions: vec![
                CommandRef {
                    feature: "slug".to_owned(),
                    name: "create".to_owned(),
                },
                CommandRef {
                    feature: "slug".to_owned(),
                    name: "update".to_owned(),
                },
                CommandRef {
                    feature: "slug".to_owned(),
                    name: "delete".to_owned(),
                },
            ],
            drawer: None,
            sort: None,
            selection: None,
            settings: vec![],
            redacted_fields: Vec::new(),
            span_ref: None,
        }
    }

    pub fn slug_detail_view() -> ViewDetail {
        ViewDetail {
            name: "slug_detail".to_owned(),
            route: Some("/slugs/:key".to_owned()),
            source: QueryRef {
                feature: "slug".to_owned(),
                kind: QueryKind::Lookup,
                name: "by_key".to_owned(),
            },
            route_params: vec![RouteParam {
                name: "key".to_owned(),
                type_ref: "Text".to_owned(),
            }],
            sections: vec![
                "header".to_owned(),
                "metadata".to_owned(),
                "related_items".to_owned(),
            ],
            cells: vec![type_badge_cell()],
            actions: vec![
                CommandRef {
                    feature: "slug".to_owned(),
                    name: "update".to_owned(),
                },
                CommandRef {
                    feature: "slug".to_owned(),
                    name: "delete".to_owned(),
                },
            ],
            redacted_fields: Vec::new(),
            span_ref: None,
        }
    }

    pub fn slug_create_view() -> ViewCreate {
        ViewCreate {
            name: "slug_create".to_owned(),
            route: Some("/slugs/new".to_owned()),
            submit: CommandRef {
                feature: "slug".to_owned(),
                name: "create".to_owned(),
            },
            on_success: None,
            fields: vec![
                "key".to_owned(),
                "title".to_owned(),
                "description".to_owned(),
                "tags".to_owned(),
            ],
            cells: vec![type_badge_cell()],
            redacted_fields: Vec::new(),
            span_ref: None,
        }
    }

    pub fn public_slug_list_view() -> ViewList {
        ViewList {
            name: "public_slug_list".to_owned(),
            route: Some("/browse".to_owned()),
            source: QueryRef {
                feature: "slug".to_owned(),
                kind: QueryKind::List,
                name: "mine".to_owned(),
            },
            render: ListRender::Table {
                columns: vec!["key".to_owned(), "title".to_owned()],
            },
            search: Some(SearchDecl {
                mode: SearchMode::Columns {
                    columns: vec!["key".to_owned(), "title".to_owned()],
                },
                fields: vec![],
                free_text_target: None,
                span_ref: None,
            }),
            filter: vec![],
            cells: vec![],
            actions: vec![],
            drawer: None,
            sort: None,
            selection: None,
            settings: vec![],
            redacted_fields: Vec::new(),
            span_ref: None,
        }
    }

    pub fn admin_audience() -> Audience {
        Audience {
            name: "admin".to_owned(),
            requires: vec![PolicyAtom {
                namespace: "scope".to_owned(),
                name: "workspace_admin".to_owned(),
                args: None,
            }],
            views: vec![
                View::List(slug_list_view()),
                View::Detail(slug_detail_view()),
                View::Create(slug_create_view()),
            ],
            span_ref: None,
        }
    }

    pub fn public_audience() -> Audience {
        Audience {
            name: "public".to_owned(),
            requires: vec![PolicyAtom {
                namespace: "scope".to_owned(),
                name: "workspace_member".to_owned(),
                args: None,
            }],
            views: vec![View::List(public_slug_list_view())],
            span_ref: None,
        }
    }

    pub fn slug_web_surface() -> Surface {
        Surface {
            feature: "slug".to_owned(),
            target: SurfaceTarget::Web,
            audiences: vec![admin_audience(), public_audience()],
            span_ref: None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use lzx_router_adapter::RouterTarget;

    #[test]
    fn emit_surface_views_matches_proposal_section_13() {
        // Walks the §13.1 `slug.web.lzx` fixture and asserts the four
        // emitted files land at the right paths with the right
        // top-level identifiers.
        let surface = test_fixtures::slug_web_surface();
        let files = emit_surface_views(&surface, RouterTarget::ViteReact, "");

        // Four (audience, view) tuples: admin × {list, detail, create}
        // plus public × list.
        assert_eq!(files.len(), 4, "expected 4 files, got {:?}",
            files.iter().map(|f| f.path.as_str()).collect::<Vec<_>>());

        let paths: Vec<&str> = files.iter().map(|f| f.path.as_str()).collect();
        assert!(paths.contains(&"dist/ts-web/slug/views/admin/slug_list.gen.ts"));
        assert!(paths.contains(&"dist/ts-web/slug/views/admin/slug_detail.gen.ts"));
        assert!(paths.contains(&"dist/ts-web/slug/views/admin/slug_create.gen.ts"));
        assert!(paths.contains(&"dist/ts-web/slug/views/public/public_slug_list.gen.ts"));

        // Spot-check each emitted file carries its hook + spec const.
        let by_path = |p: &str| files.iter().find(|f| f.path == p).expect("path present");

        let list_file = by_path("dist/ts-web/slug/views/admin/slug_list.gen.ts");
        assert!(list_file.contents.contains("export const adminSlugListView"));
        assert!(list_file.contents.contains("export function useAdminSlugListView"));
        assert!(list_file.contents.contains("listMineSlugs"));

        let detail_file = by_path("dist/ts-web/slug/views/admin/slug_detail.gen.ts");
        assert!(detail_file.contents.contains("export const adminSlugDetailView"));
        assert!(detail_file.contents.contains("export function useAdminSlugDetailView"));
        assert!(detail_file.contents.contains("@tanstack/react-router"));
        assert!(detail_file.contents.contains("AdminSlugDetailSections"));

        let create_file = by_path("dist/ts-web/slug/views/admin/slug_create.gen.ts");
        assert!(create_file.contents.contains("export const adminSlugCreateView"));
        assert!(create_file.contents.contains("export function useAdminSlugCreateView"));
        assert!(create_file.contents.contains("zodResolver"));

        let public_file = by_path("dist/ts-web/slug/views/public/public_slug_list.gen.ts");
        assert!(public_file.contents.contains("export const publicPublicSlugListView"));
        assert!(public_file.contents.contains("export function usePublicPublicSlugListView"));
    }

    #[test]
    fn emit_surface_views_switches_router_target_for_detail() {
        let surface = test_fixtures::slug_web_surface();

        let vite_files = emit_surface_views(&surface, RouterTarget::ViteReact, "");
        let nextjs_files = emit_surface_views(&surface, RouterTarget::NextJs, "");

        let vite_detail = vite_files
            .iter()
            .find(|f| f.path.ends_with("slug_detail.gen.ts"))
            .unwrap();
        let nextjs_detail = nextjs_files
            .iter()
            .find(|f| f.path.ends_with("slug_detail.gen.ts"))
            .unwrap();

        assert!(vite_detail.contents.contains("@tanstack/react-router"));
        assert!(!vite_detail.contents.contains("next/navigation"));
        assert!(nextjs_detail.contents.contains("next/navigation"));
        assert!(!nextjs_detail.contents.contains("@tanstack/react-router"));
    }

    #[test]
    fn format_cells_literal_handles_empty_and_populated() {
        assert_eq!(format_cells_literal(&[]), "{}");
        let cells = vec![CellBinding {
            field: "tags".to_owned(),
            slot: "type_badge".to_owned(),
        }];
        assert_eq!(
            format_cells_literal(&cells),
            "{ tags: \"@client.type_badge\" as const }"
        );
    }

    #[test]
    fn format_string_array_handles_empty_and_populated() {
        assert_eq!(format_string_array(&[]), "[]");
        let items = vec!["a".to_owned(), "b".to_owned(), "c".to_owned()];
        assert_eq!(format_string_array(&items), "[\"a\", \"b\", \"c\"]");
    }
}
