// Code generated by lazuli; DO NOT EDIT.
//lazuli:pattern pattern_lifecycle_gate_metadata v1
import { isLazuliError, type LazuliClient } from "@lazuli/runtime";
import { withLifecycleGate, withRouteGuard, type RouteGuardSpec } from "@lazuli/runtime/react";
import { HostHomeScreen } from "./components/HostHomeScreen.js";
import { HostOnboardingBasicDetailsScreen } from "./components/HostOnboardingBasicDetailsScreen.js";
import { HostOnboardingIntermediationScreen } from "./components/HostOnboardingIntermediationScreen.js";
import { lookupHostByMyHost } from "./host.gen.js";
import type { HostLifecycleState } from "./host.gen.js";

// Generated from resume host_onboarding (host surface).
export function hostOnboardingResume(state: HostLifecycleState | null): string {
  switch (state) {
    case null: return "/onboarding/host/intermediation";
    case "intermediation_terms_pending": return "/onboarding/host/intermediation";
    case "basic_details_pending": return "/onboarding/host/basic-details";
    case "complete": return "/host";
    default: { const _exhaustive: never = state; return "/onboarding/host/intermediation"; }
  }
}

export async function hostOnboardingEvaluateGate(
  client: LazuliClient,
  expectedState: HostLifecycleState,
  expectedSubstep?: string,
): Promise<{ verdict: "pass" } | { verdict: "redirect"; to: string }> {
  void expectedSubstep;
  try {
    const row = await client.runQuery(lookupHostByMyHost, {});
    if (row === null || row === undefined) {
      return { verdict: "redirect", to: hostOnboardingResume(null) };
    }
    const state = row.lifecycleState as HostLifecycleState;
    if (state === expectedState) return { verdict: "pass" };
    return { verdict: "redirect", to: hostOnboardingResume(state) };
  } catch (err) {
    if (isLazuliError(err) && err.status === 404) {
      return { verdict: "redirect", to: hostOnboardingResume(null) };
    }
    if (isLazuliError(err) && err.status >= 500) {
      return { verdict: "pass" };
    }
    throw err;
  }
}

export const hostHomeRoute = {
  path: "/host",
  component: HostHomeScreen,
  policy: {
    name: "@policy.host_only",
    atoms: [
      { namespace: "scope", name: "authenticated" },
      { namespace: "role", name: "host" },
    ],
  },
  onUnauthenticated: "/sign-in",
  onUnauthorized: "/explore",
} as const satisfies RouteGuardSpec<typeof HostHomeScreen>;

export const HostHomeScreenGuarded = withRouteGuard(
  withLifecycleGate(
    HostHomeScreen,
    {
      resource: "Host",
      state: "complete",
      resume: "host_onboarding",
    },
    hostOnboardingEvaluateGate,
  ),
  hostHomeRoute,
);

export const hostOnboardingBasicDetailsRoute = {
  path: "/onboarding/host/basic-details",
  component: HostOnboardingBasicDetailsScreen,
  policy: {
    name: "@policy.host_only",
    atoms: [
      { namespace: "scope", name: "authenticated" },
      { namespace: "role", name: "host" },
    ],
  },
  onUnauthenticated: "/sign-in",
  onUnauthorized: "/explore",
} as const satisfies RouteGuardSpec<typeof HostOnboardingBasicDetailsScreen>;

export const HostOnboardingBasicDetailsScreenGuarded = withRouteGuard(
  withLifecycleGate(
    HostOnboardingBasicDetailsScreen,
    {
      resource: "Host",
      state: "basic_details_pending",
      resume: "host_onboarding",
    },
    hostOnboardingEvaluateGate,
  ),
  hostOnboardingBasicDetailsRoute,
);

export const hostOnboardingIntermediationRoute = {
  path: "/onboarding/host/intermediation",
  component: HostOnboardingIntermediationScreen,
  policy: {
    name: "@policy.host_only",
    atoms: [
      { namespace: "scope", name: "authenticated" },
      { namespace: "role", name: "host" },
    ],
  },
  onUnauthenticated: "/sign-in",
  onUnauthorized: "/explore",
} as const satisfies RouteGuardSpec<typeof HostOnboardingIntermediationScreen>;

export const HostOnboardingIntermediationScreenGuarded = withRouteGuard(
  withLifecycleGate(
    HostOnboardingIntermediationScreen,
    {
      resource: "Host",
      state: "intermediation_terms_pending",
      resume: "host_onboarding",
    },
    hostOnboardingEvaluateGate,
  ),
  hostOnboardingIntermediationRoute,
);

