use std::fmt::Write;

/// One backend command projected for the API-policy harness.
///
/// Only the policy string is consulted at emission time — public
/// commands are dropped, every other policy collapses to "must be 403
/// when called anonymously". The detailed policy AST stays in the Go
/// emitter; this struct is the boundary shim into Playwright.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Command {
    /// Feature name (e.g. `"account"`).
    pub feature: String,
    /// Command name (e.g. `"disable"`).
    pub name: String,
    /// Raw policy ref as written in the IR — only `@policy.public` is
    /// special-cased; everything else is treated as protected.
    pub policy: String,
}

/// Emit the Playwright spec that asserts every protected command
/// returns `403 policy_denied` when called anonymously.
///
/// Public commands are intentionally absent from the generated spec —
/// they have their own positive-path tests elsewhere. The output is a
/// complete, ready-to-write `.spec.ts` file including the file banner
/// and the `test.describe` wrapper.
///
/// ## Examples
///
/// ```
/// use lazuli_codegen_ts::playwright::api_policy::{emit_playwright_api_policy, Command};
/// let cmds = vec![Command {
///     feature: "account".to_owned(),
///     name: "disable".to_owned(),
///     policy: "@policy.authenticated".to_owned(),
/// }];
/// let spec = emit_playwright_api_policy(&cmds);
/// assert!(spec.contains("account.disable"));
/// ```
pub fn emit_playwright_api_policy(commands: &[Command]) -> String {
    let mut out = String::new();

    writeln!(
        out,
        "// AUTO-GENERATED by `lazuli generate playwright --target=api-policy`. DO NOT EDIT."
    )
    .ok();
    writeln!(out, "import {{ expect, test }} from '@playwright/test';").ok();
    writeln!(out).ok();
    writeln!(
        out,
        "const apiURL = process.env.APP_API_URL ?? 'http://localhost:8080';"
    )
    .ok();
    writeln!(out).ok();
    writeln!(
        out,
        "const protectedCommands: ReadonlyArray<{{ name: string; expectStatus: number }}> = ["
    )
    .ok();
    for command in commands {
        if command.policy == "@policy.public" {
            continue;
        }
        writeln!(
            out,
            "  {{ name: '{}', expectStatus: 403 }},",
            escape_ts_single_quoted(&format!("{}.{}", command.feature, command.name))
        )
        .ok();
    }
    writeln!(out, "];").ok();
    writeln!(out).ok();
    writeln!(
        out,
        "test.describe('Backend command policy enforcement (generated)', () => {{"
    )
    .ok();
    writeln!(out, "  for (const cmd of protectedCommands) {{").ok();
    writeln!(
        out,
        "    test(`POST ${{cmd.name}} -> ${{cmd.expectStatus}} (anonymous)`, async ({{ request }}) => {{"
    )
    .ok();
    writeln!(
        out,
        "      const res = await request.post(`${{apiURL}}/api/v1/c/${{cmd.name}}`, {{ data: {{}} }});"
    )
    .ok();
    writeln!(out, "      expect(res.status()).toBe(cmd.expectStatus);").ok();
    writeln!(out, "      if (cmd.expectStatus === 403) {{").ok();
    writeln!(out, "        const body = await res.json();").ok();
    writeln!(out, "        expect(body.code).toBe('policy_denied');").ok();
    writeln!(out, "      }}").ok();
    writeln!(out, "    }});").ok();
    writeln!(out, "  }}").ok();
    writeln!(out, "}});").ok();

    out
}

fn escape_ts_single_quoted(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '\'' => out.push_str("\\'"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emit_playwright_api_policy_skips_public_commands() {
        let commands = vec![
            Command {
                feature: "account".to_owned(),
                name: "register".to_owned(),
                policy: "@policy.public".to_owned(),
            },
            Command {
                feature: "account".to_owned(),
                name: "disable".to_owned(),
                policy: "@policy.authenticated".to_owned(),
            },
        ];

        let out = emit_playwright_api_policy(&commands);

        assert!(out.contains("{ name: 'account.disable', expectStatus: 403 },"));
        assert!(!out.contains("account.register"));
    }
}
