//! `tokens.ts` emitter — typed `const tokens = {...} as const` + per-group
//! type aliases. See `docs/proposals/design-tokens.md` §4.2.
//!
//! Color shape detection (§4.2 lines 332-345 of the proposal):
//! - Single `Base` state, no `dark` →   `success: "#16a34a"`.
//! - Multi-state, no `dark` anywhere →  `primary: { base: "...", hover: "...", ... }`.
//! - Any `dark` set on any state →      `background: { base: { light: "#fff", dark: "#000" }, muted: ... }`.
//!
//! The detection is per-token-local (one `ColorToken` is one of the three
//! shapes), so a catalog can mix shapes freely — e.g. `primary` multi-state
//! and `success` single-flat coexist.

use std::fmt::Write;

use super::ir::{ColorStateKind, ColorToken, Design};

/// Emit `dist/ts-web/design/tokens.ts` for the given `Design` catalog.
///
/// Renders a typed `tokens` object plus per-axis sub-exports
/// (`colors`, `spacing`, `typography`, …) so frontend code can import
/// either the whole catalog or a single axis without pulling in the
/// rest.
///
/// ## Examples
///
/// ```ignore
/// use lazuli_codegen_ts::design_tokens_ts::emit_tokens_ts;
/// use lazuli_ir::Design;
///
/// let design: Design = /* … */ unimplemented!();
/// let src = emit_tokens_ts(&design);
/// assert!(src.contains("export"));
/// ```
pub fn emit_tokens_ts(design: &Design) -> String {
    let mut s = String::new();
    writeln!(s, "// Code generated by lazuli; DO NOT EDIT.").ok();
    writeln!(s, "// Source: design.lzi (design `{}`)", design.name).ok();
    writeln!(s).ok();
    writeln!(s, "export const tokens = {{").ok();

    // color
    writeln!(s, "  color: {{").ok();
    for color in &design.colors {
        emit_color(&mut s, color);
    }
    // Custom tokens lower as siblings under `tokens.color`, with
    // `{ base, dark? }` shape per `docs/proposals/design-tokens-custom.md` §5.2.
    // Names are camelCased so they remain legal JS identifiers (e.g.
    // `chat-bubble-mine` → `chatBubbleMine`).
    for tok in &design.custom {
        let key = quote_key(&kebab_to_camel(&tok.name));
        match &tok.dark {
            Some(dark) => writeln!(
                s,
                "    {}: {{ base: {}, dark: {} }},",
                key,
                ts_string(&tok.base),
                ts_string(dark),
            )
            .ok(),
            None => writeln!(s, "    {}: {{ base: {} }},", key, ts_string(&tok.base),).ok(),
        };
    }
    writeln!(s, "  }},").ok();

    // typography
    writeln!(s, "  typography: {{").ok();
    writeln!(s, "    family: {{").ok();
    for fam in &design.typography.families {
        writeln!(
            s,
            "      {}: {},",
            quote_key(&fam.name),
            ts_string(&fam.value)
        )
        .ok();
    }
    writeln!(s, "    }},").ok();

    writeln!(s, "    scale: {{").ok();
    for entry in &design.typography.scale {
        writeln!(
            s,
            "      {}: {{ size: {}, lineHeight: {} }},",
            quote_key(&entry.name),
            ts_string(&entry.size),
            ts_string(&entry.line_height),
        )
        .ok();
    }
    writeln!(s, "    }},").ok();

    writeln!(s, "    weight: {{").ok();
    for w in &design.typography.weights {
        writeln!(s, "      {}: {},", quote_key(&w.name), w.value).ok();
    }
    writeln!(s, "    }},").ok();

    writeln!(s, "    tracking: {{").ok();
    for t in &design.typography.tracking {
        writeln!(s, "      {}: {},", quote_key(&t.name), ts_string(&t.value)).ok();
    }
    writeln!(s, "    }},").ok();
    writeln!(s, "  }},").ok();

    // space
    writeln!(s, "  space: {{").ok();
    for tok in &design.spaces {
        writeln!(
            s,
            "    {}: {},",
            quote_key(&tok.name),
            ts_string(&tok.value)
        )
        .ok();
    }
    writeln!(s, "  }},").ok();

    // radius
    writeln!(s, "  radius: {{").ok();
    for tok in &design.radii {
        writeln!(
            s,
            "    {}: {},",
            quote_key(&tok.name),
            ts_string(&tok.value)
        )
        .ok();
    }
    writeln!(s, "  }},").ok();

    // shadow
    writeln!(s, "  shadow: {{").ok();
    for tok in &design.shadows {
        writeln!(
            s,
            "    {}: {},",
            quote_key(&tok.name),
            ts_string(&tok.value)
        )
        .ok();
    }
    writeln!(s, "  }},").ok();

    // motion
    writeln!(s, "  motion: {{").ok();
    writeln!(s, "    duration: {{").ok();
    for d in &design.motion.durations {
        writeln!(s, "      {}: {},", quote_key(&d.name), ts_string(&d.value)).ok();
    }
    writeln!(s, "    }},").ok();
    writeln!(s, "    easing: {{").ok();
    for e in &design.motion.easings {
        writeln!(s, "      {}: {},", quote_key(&e.name), ts_string(&e.value)).ok();
    }
    writeln!(s, "    }},").ok();
    writeln!(s, "  }},").ok();

    // breakpoint
    writeln!(s, "  breakpoint: {{").ok();
    for tok in &design.breakpoints {
        writeln!(
            s,
            "    {}: {},",
            quote_key(&tok.name),
            ts_string(&tok.value)
        )
        .ok();
    }
    writeln!(s, "  }},").ok();

    // z
    writeln!(s, "  z: {{").ok();
    for tok in &design.z_indices {
        writeln!(s, "    {}: {},", quote_key(&tok.name), tok.value).ok();
    }
    writeln!(s, "  }},").ok();

    writeln!(s, "}} as const;").ok();
    writeln!(s).ok();

    // type aliases
    writeln!(s, "export type ColorToken = keyof typeof tokens.color;").ok();
    writeln!(s, "export type SpaceToken = keyof typeof tokens.space;").ok();
    writeln!(s, "export type RadiusToken = keyof typeof tokens.radius;").ok();
    writeln!(s, "export type ShadowToken = keyof typeof tokens.shadow;").ok();
    writeln!(
        s,
        "export type FontFamilyToken = keyof typeof tokens.typography.family;"
    )
    .ok();
    writeln!(
        s,
        "export type FontWeightToken = keyof typeof tokens.typography.weight;"
    )
    .ok();
    writeln!(
        s,
        "export type TextScaleToken = keyof typeof tokens.typography.scale;"
    )
    .ok();
    writeln!(
        s,
        "export type TrackingToken = keyof typeof tokens.typography.tracking;"
    )
    .ok();
    writeln!(
        s,
        "export type MotionDurationToken = keyof typeof tokens.motion.duration;"
    )
    .ok();
    writeln!(
        s,
        "export type MotionEasingToken = keyof typeof tokens.motion.easing;"
    )
    .ok();
    writeln!(
        s,
        "export type BreakpointToken = keyof typeof tokens.breakpoint;"
    )
    .ok();
    writeln!(s, "export type ZToken = keyof typeof tokens.z;").ok();
    s
}

fn emit_color(s: &mut String, color: &ColorToken) {
    let key = quote_key(&color.name);
    let has_dark = color.states.iter().any(|st| st.dark.is_some());
    let single_base = color.states.len() == 1
        && color.states.first().map(|st| st.kind) == Some(ColorStateKind::Base);

    if single_base && !has_dark {
        // Single hex shape.
        let val = &color.states[0].value;
        writeln!(s, "    {}: {},", key, ts_string(val)).ok();
        return;
    }

    if has_dark {
        // Multi-state with dark — each state becomes { light, dark }.
        writeln!(s, "    {}: {{", key).ok();
        for state in &color.states {
            let state_key = state_kind_key(state.kind);
            match &state.dark {
                Some(dark) => writeln!(
                    s,
                    "      {}: {{ light: {}, dark: {} }},",
                    state_key,
                    ts_string(&state.value),
                    ts_string(dark),
                )
                .ok(),
                None => writeln!(s, "      {}: {},", state_key, ts_string(&state.value)).ok(),
            };
        }
        writeln!(s, "    }},").ok();
        return;
    }

    // Multi-state, no dark — flat per-state map.
    writeln!(s, "    {}: {{", key).ok();
    for state in &color.states {
        let state_key = state_kind_key(state.kind);
        writeln!(s, "      {}: {},", state_key, ts_string(&state.value)).ok();
    }
    writeln!(s, "    }},").ok();
}

fn state_kind_key(kind: ColorStateKind) -> &'static str {
    match kind {
        ColorStateKind::Base => "base",
        ColorStateKind::Hover => "hover",
        ColorStateKind::Active => "active",
        ColorStateKind::Foreground => "foreground",
    }
}

/// Quote a key only when it isn't a legal unquoted JS/TS identifier (starts
/// with a digit, contains punctuation, etc.). Authored names like `"2xl"`,
/// `"3xl"`, `"16"` reach us as strings and must stay quoted.
fn quote_key(name: &str) -> String {
    if is_safe_ident(name) {
        name.to_owned()
    } else {
        format!("\"{}\"", escape_string(name))
    }
}

/// Convert kebab-case identifier (`chat-bubble-mine`) to camelCase
/// (`chatBubbleMine`). Single-segment names (`chat`) pass through unchanged.
/// Used by the `custom` token lowering — kebab is the lexer-visible form
/// (Tailwind utility class compat); camelCase is the JS object-key form.
fn kebab_to_camel(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut upper_next = false;
    for c in name.chars() {
        if c == '-' {
            upper_next = true;
            continue;
        }
        if upper_next {
            out.extend(c.to_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    out
}

fn is_safe_ident(s: &str) -> bool {
    let mut it = s.chars();
    match it.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' || c == '$' => {}
        _ => return false,
    }
    it.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
}

fn ts_string(value: &str) -> String {
    format!("\"{}\"", escape_string(value))
}

fn escape_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for c in value.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests;
