use super::*;
use lazuli_ir::{AppManifest, Defaults, Module, Path, PathRef, Policies, TenantMigrationTarget};

fn base_feature(name: &str) -> Feature {
    Feature {
        name: name.to_owned(),
        purpose: None,
        non_goals: Vec::new(),
        context_path: None,
        knowledge: None,
        defaults: Defaults {
            tenancy: None,
            timestamps: false,
            policy: None,
            rate_limit: None,
            audit: None,
        },
        uses: Vec::new(),
        uses_spans: Vec::new(),
        uses_versions: Vec::new(),
        requirements: Vec::new(),
        enums: Vec::new(),
        resources: Vec::new(),
        events: Vec::new(),
        rules: Vec::new(),
        policies: Policies {
            categories: Vec::new(),
            fields: Vec::new(),
            span_ref: None,
        },
        errors: None,
        commands: Vec::new(),
        apis: Vec::new(),
        records: Vec::new(),
        queries: Vec::new(),
        resume_routers: Vec::new(),
        workflows: Vec::new(),
        jobs: Vec::new(),
        webhooks: Vec::new(),
        notifications: Vec::new(),
        event_groups: Vec::new(),
        tenant_migrations: Vec::new(),
        translation: None,
        pollers: vec![],
        auth: None,
        surfaces: Vec::new(),
        extensions: Vec::new(),
        escape_routes: Vec::new(),
        agents: Vec::new(),
        reports: Vec::new(),
        channels: Vec::new(),
        caches: Vec::new(),
        aggregates: vec![],
        mcp_servers: vec![],
        previous_names: Vec::new(),
        span_ref: None,
        synth_origins: std::collections::BTreeMap::new(),
    }
}

fn minimal_app() -> AppManifest {
    AppManifest {
        name: "test".to_owned(),
        title: None,
        version: None,
        lazuli_version: None,
        targets: Vec::new(),
        default_locale: None,
        default_timezone: None,
        auth_failed_redirect: None,
        not_found: None,
        error_pages: Vec::new(),
        uses: Vec::new(),
        packs: Vec::new(),
        bindings: Vec::new(),
        architecture: None,
        services: Vec::new(),
        communication: None,
        environments: Vec::new(),
        urls: Vec::new(),
        cors: None,
        headers: None,
        cookie: None,
        proxy: None,
        limits: None,
        env: Vec::new(),
        integrations: Vec::new(),
        capabilities: Vec::new(),
        runtime: Vec::new(),
        deploy: None,
        logging: None,
        tracing: None,
        observability: None,
        locale: None,
        encryption_bindings: Vec::new(),
        route_guard: None,
        actor_query: None,
        span_ref: None,
    }
}

fn module_with_feature(feature: Feature) -> Module {
    Module {
        workspace: None,
        contracts: Vec::new(),
        app: Some(minimal_app()),
        registry: None,
        profiles: Vec::new(),
        design: None,
        rbac: None,
        features: vec![feature],
    }
}

fn emit(feature: Feature) -> Option<String> {
    let module = module_with_feature(feature);
    let index = CrossFeatureIndex::build(&module);
    emit_migration_file("examples/x.lzi", &module.features[0], "lazuli/test", &index)
}

fn migration(name: &str) -> TenantMigration {
    TenantMigration {
        name: name.to_owned(),
        target: TenantMigrationTarget {
            operation: None,
            axis: "org".to_owned(),
        },
        idempotency: IdempotencyKey {
            by: Path::from_segments(["tenant", "org_id"]),
        },
        retry: Some(RetryPolicy {
            count: 3,
            backoff: BackoffStrategy::Exponential,
        }),
        timeout: Some("5m".to_owned()),
        handler: PathRef::authored(format!("./migrations/{name}.go")),
        previous_names: Vec::new(),
        span_ref: None,
    }
}

#[test]
fn empty_feature_returns_none() {
    let feature = base_feature("customer");
    assert!(emit(feature).is_none());
}

#[test]
fn canonical_migration_emits_contract_value() {
    let mut feature = base_feature("customer");
    feature
        .tenant_migrations
        .push(migration("backfill_customer_score"));

    let out = emit(feature).expect("must emit");
    assert!(out.contains("// Code generated by lazuli; DO NOT EDIT."));
    assert!(out.contains("package customergen"));
    assert!(out.contains("\"time\""));
    assert!(out.contains("\"lazuli.dev/runtime/lazuli/migrations\""));
    assert!(out.contains(
        "var customerBackfillCustomerScoreMigration = migrations.TenantMigrationContract{"
    ));
    assert!(out.contains("Feature:     \"customer\","));
    assert!(out.contains("Name:        \"backfill_customer_score\","));
    assert!(out.contains("Target:      migrations.TenantMigrationTarget{Axis: \"org\"},"));
    assert!(out.contains("Idempotency: migrations.IdempotencyKeySpec{Path: \"tenant.org_id\"},"));
    assert!(out.contains(
        "Retry:       &migrations.RetryPolicy{Count: 3, Backoff: migrations.BackoffExponential},"
    ));
    assert!(out.contains("Timeout:     5 * time.Minute,"));
    assert!(out.contains("HandlerPath: \"./migrations/backfill_customer_score.go\","));
    assert!(out.contains(
        "// TODO(runtime): TenantMigrationContract has no per-migration PreHook/PostHook fields."
    ));
}

#[test]
fn feature_emit() {
    let mut feature = base_feature("billing");
    feature.tenant_migrations.push(migration("seed_orgs"));

    let out = emit_migration_file(
        "features/billing/billing.lzi",
        &feature,
        "lazuli/test",
        &CrossFeatureIndex::build(&module_with_feature(feature.clone())),
    )
    .expect("feature with tenant_migrations must emit migration file");

    assert!(!out.is_empty());
    assert!(out.contains("// Code generated by lazuli; DO NOT EDIT."));
    assert!(out.contains("package billinggen"));
    assert!(out.contains("var billingSeedOrgsMigration = migrations.TenantMigrationContract{"));
    assert!(out.contains("Name:        \"seed_orgs\","));
    assert!(out.contains("HandlerPath: \"./migrations/seed_orgs.go\","));
}

#[test]
fn fixed_retry_and_missing_timeout_are_omitted_cleanly() {
    let mut feature = base_feature("customer");
    let mut item = migration("seed_orgs");
    item.retry = Some(RetryPolicy {
        count: 1,
        backoff: BackoffStrategy::Fixed,
    });
    item.timeout = None;
    feature.tenant_migrations.push(item);

    let out = emit(feature).expect("must emit");
    assert!(!out.contains("\"time\""));
    assert!(out.contains(
        "Retry:       &migrations.RetryPolicy{Count: 1, Backoff: migrations.BackoffFixed},"
    ));
    assert!(!out.contains("Timeout:"));
}

#[test]
fn invalid_timeout_emits_runtime_todo_and_stays_deterministic() {
    let mut feature = base_feature("customer");
    let mut zebra = migration("zebra");
    zebra.timeout = Some("1 day".to_owned());
    let alpha = migration("alpha");
    feature.tenant_migrations.push(zebra);
    feature.tenant_migrations.push(alpha);

    let out = emit(feature.clone()).expect("must emit");
    let again = emit(feature).expect("must emit");
    assert_eq!(out, again);
    assert!(out.contains("// TODO(runtime): TenantMigrationContract.Timeout is time.Duration; cannot preserve authored duration \"1 day\" without a parser helper."));
    let alpha_pos = out.find("TenantMigration: customer.alpha").expect("alpha");
    let zebra_pos = out.find("TenantMigration: customer.zebra").expect("zebra");
    assert!(alpha_pos < zebra_pos);
}
