//! Smoke test for `generate_v1` (cell E1). Constructs a minimal IR
//! `Module` by hand (one feature, no kinds), runs the emitter, and
//! verifies the structural invariants the proposal locks in:
//!
//! 1. At least one feature `.gen.go` plus the root `go.mod`.
//! 2. `go.mod` carries the resolved module path and the
//!    `require lazuli.dev/runtime/lazuli <version>` line.
//! 3. Each `.gen.go` opens with the Code Connect-style banner
//!    (`// Code generated by lazuli; DO NOT EDIT.`) and a
//!    matching `package <feature_name>` directive.
//!
//! Hand-rolled IR (not via the analyzer) keeps the test
//! deliberately decoupled from grammar-side drift.

use std::collections::BTreeMap;

use lazuli_analyzer::source_map::SourceMapResolver;
use lazuli_codegen_go::{
    generate_v1, generate_v1_with_manifest, generate_v1_with_manifest_and_source, GoEmitOptions,
    GoSourceContext, LazuriteDev, LazuriteGenerateGo, LazuriteManifest, LazuritePlugin,
    LAZULI_GO_VERSION,
};
use lazuli_ir::{
    AppLocale, AppLogging, AppManifest, AppTracing, Assignment, BuiltinType, Command,
    CommandEffect, CommandInput, CommandKind, CreateEffect, Defaults, EnumDecl, EnumVariant, Expr,
    Feature, Field, FieldConstraints, Module, Path, Policies, PolicyRef, QualifiedName, Resource,
    SourceMap, SpanRef, StorageValue, TypeRef, TypedSlot,
};

fn empty_feature(name: &str) -> Feature {
    Feature {
        name: name.to_owned(),
        purpose: None,
        non_goals: Vec::new(),
        context_path: None,
        defaults: Defaults {
            tenancy: None,
            timestamps: false,
            policy: None,
        },
        uses: Vec::new(),
        uses_spans: Vec::new(),
        uses_versions: Vec::new(),
        requirements: Vec::new(),
        enums: Vec::new(),
        resources: Vec::new(),
        events: Vec::new(),
        rules: Vec::new(),
        policies: Policies {
            categories: Vec::new(),
            fields: Vec::new(),
            span_ref: None,
        },
        commands: Vec::new(),
        apis: Vec::new(),
        records: Vec::new(),
        queries: Vec::new(),
        workflows: Vec::new(),
        jobs: Vec::new(),
        webhooks: Vec::new(),
        notifications: Vec::new(),
        event_groups: Vec::new(),
        tenant_migrations: Vec::new(),
        translation: None,
        pollers: vec![],
        auth: None,
        surfaces: Vec::new(),
        extensions: Vec::new(),
        escape_routes: Vec::new(),
        agents: Vec::new(),
        reports: Vec::new(),
        channels: Vec::new(),
            caches: Vec::new(),
        aggregates: vec![],
            mcp_servers: vec![],
        previous_names: Vec::new(),
        span_ref: None,
    }
}

fn minimal_app_manifest(name: &str) -> AppManifest {
    // `AppManifest` has no `Default` impl (the bucket-observability
    // cycle dropped `Eq` derive so `f64` sample-rate fields can
    // coexist). Build the whole shape explicitly.
    AppManifest {
        name: name.to_owned(),
        title: None,
        version: None,
        lazuli_version: None,
        targets: Vec::new(),
        default_locale: None,
        default_timezone: None,
        auth_failed_redirect: None,
        not_found: None,
        error_pages: Vec::new(),
        uses: Vec::new(),
        packs: Vec::new(),
        bindings: Vec::new(),
        architecture: None,
        services: Vec::new(),
        communication: None,
        environments: Vec::new(),
        urls: Vec::new(),
        cors: None,
        headers: None,
        cookie: None,
        proxy: None,
        limits: None,
        env: Vec::new(),
        integrations: Vec::new(),
        capabilities: Vec::new(),
        runtime: Vec::new(),
        deploy: None,
        logging: None,
        tracing: None,
        observability: None,
        locale: None,
        encryption_bindings: Vec::new(),
        span_ref: None,
    }
}

fn minimal_module(app_name: &str, feature_name: &str) -> Module {
    Module {
        workspace: None,
        contracts: Vec::new(),
        app: Some(minimal_app_manifest(app_name)),
        registry: None,
        profiles: Vec::new(),
        design: None,
        rbac: None,
        features: vec![empty_feature(feature_name)],
    }
}

fn empty_command(name: &str, span_ref: Option<SpanRef>) -> Command {
    Command {
        name: name.to_owned(),
        public_contract: None,
        kind: CommandKind::Create,
        route: Vec::new(),
        input: CommandInput::Empty,
        target: None,
        lets: Vec::new(),
        effect: CommandEffect::None,
        policy: PolicyRef::None,
        policy_expr: None,
        emits: Vec::new(),
        rate_limit: None,
        audit: None,
        approval: None,
        invalidates: Vec::new(),
        external_calls: Vec::new(),
        timeout: None,
        retry: None,
        idempotency: None,
        write_window: None,
        deprecated: None,
        handler: None,
        tests: None,
        previous_names: Vec::new(),
        span_ref,
    }
}

fn source_map_context<'a>(
    source_map: &'a SourceMap,
    feature_file_ids: &'a BTreeMap<String, lazuli_ir::FileId>,
) -> GoSourceContext<'a> {
    GoSourceContext {
        source_map,
        feature_file_ids,
    }
}

fn command_gen_contents(files: &[lazuli_codegen_go::GeneratedFile], feature: &str) -> String {
    files
        .iter()
        .find(|file| file.path == format!("{feature}/command.gen.go"))
        .expect("expected command.gen.go")
        .contents
        .clone()
}

fn lazurite_manifest(
    plugins: Vec<(&str, &str)>,
    generate_go: Option<LazuriteGenerateGo>,
    plugin_paths: Vec<(&str, &str)>,
) -> LazuriteManifest {
    LazuriteManifest {
        project_module: "github.com/acme/test-app".to_owned(),
        plugins: plugins
            .into_iter()
            .map(|(plugin_ref, module)| {
                (
                    plugin_ref.to_owned(),
                    LazuritePlugin {
                        module: Some(module.to_owned()),
                        version: Some("v0.1.0".to_owned()),
                        path: None,
                    },
                )
            })
            .collect::<BTreeMap<_, _>>(),
        generate_go,
        dev: Some(LazuriteDev {
            plugin_paths: plugin_paths
                .into_iter()
                .map(|(plugin_ref, path)| (plugin_ref.to_owned(), path.to_owned()))
                .collect::<BTreeMap<_, _>>(),
        }),
    }
}

#[test]
fn emit_command_with_span_emits_line_directive() {
    let mut module = minimal_module("marketplace", "foo");
    let source = format!("{}command create\n", "\n".repeat(41));
    let span = SpanRef { start: 41, end: 55 };
    module.features[0]
        .commands
        .push(empty_command("create", Some(span)));

    let source_map = SourceMap {
        files: vec![SourceMap::build_source_file(7, "features/foo.lzi", &source)],
    };
    let feature_file_ids = BTreeMap::from([("foo".to_owned(), 7)]);
    let files = generate_v1_with_manifest_and_source(
        &module,
        &GoEmitOptions::default(),
        None,
        source_map_context(&source_map, &feature_file_ids),
    );
    let out = command_gen_contents(&files, "foo");

    let directive = out
        .find("//line features/foo.lzi:42:1")
        .expect("expected source //line directive");
    let declaration = out
        .find("var createResult = lazuli.Command[struct{}, struct{}]{")
        .expect("expected command declaration");
    assert!(
        directive < declaration,
        "directive must precede command declaration:\n{out}"
    );
    assert!(
        out.contains("ctx = lazuli.WithSource(ctx, lazuli.SourceTag{"),
        "command handler source hook must stamp SourceTag:\n{out}"
    );
    assert!(
        out.contains("Capsule: \"marketplace\",")
            && out.contains("Feature: \"foo\",")
            && out.contains("Kind:    \"command\",")
            && out.contains("Op:      \"create\",")
            && out.contains("Source:  \"features/foo.lzi:42:1\","),
        "command handler source hook must carry the originating op:\n{out}"
    );
}

#[test]
fn emit_command_without_span_emits_no_directive() {
    let mut module = minimal_module("marketplace", "foo");
    module.features[0]
        .commands
        .push(empty_command("create", None));

    let source_map = SourceMap {
        files: vec![SourceMap::build_source_file(
            7,
            "features/foo.lzi",
            "command create\n",
        )],
    };
    let feature_file_ids = BTreeMap::from([("foo".to_owned(), 7)]);
    let files = generate_v1_with_manifest_and_source(
        &module,
        &GoEmitOptions::default(),
        None,
        source_map_context(&source_map, &feature_file_ids),
    );
    let out = command_gen_contents(&files, "foo");

    assert!(
        !out.contains("//line "),
        "missing SpanRef should fall back to generated Go locations:\n{out}"
    );
}

#[test]
fn emit_command_resets_to_gen_file_after_body() {
    let mut module = minimal_module("marketplace", "foo");
    module.features[0]
        .commands
        .push(empty_command("create", Some(SpanRef { start: 0, end: 14 })));

    let source_map = SourceMap {
        files: vec![SourceMap::build_source_file(
            7,
            "features/foo.lzi",
            "command create\n",
        )],
    };
    let feature_file_ids = BTreeMap::from([("foo".to_owned(), 7)]);
    let files = generate_v1_with_manifest_and_source(
        &module,
        &GoEmitOptions::default(),
        None,
        source_map_context(&source_map, &feature_file_ids),
    );
    let out = command_gen_contents(&files, "foo");

    assert!(
        out.contains("}\n//line foo/command.gen.go:1:1\n"),
        "expected reset directive after command value body:\n{out}"
    );
}

#[test]
fn multiple_handlers_in_same_feature_each_get_directive_pair() {
    let mut module = minimal_module("marketplace", "foo");
    module.features[0]
        .commands
        .push(empty_command("create", Some(SpanRef { start: 0, end: 14 })));
    module.features[0].commands.push(empty_command(
        "update",
        Some(SpanRef { start: 15, end: 29 }),
    ));

    let source = "command create\ncommand update\n";
    let source_map = SourceMap {
        files: vec![SourceMap::build_source_file(7, "features/foo.lzi", source)],
    };
    let feature_file_ids = BTreeMap::from([("foo".to_owned(), 7)]);
    let files = generate_v1_with_manifest_and_source(
        &module,
        &GoEmitOptions::default(),
        None,
        source_map_context(&source_map, &feature_file_ids),
    );
    let out = command_gen_contents(&files, "foo");

    assert_eq!(out.matches("//line features/foo.lzi:").count(), 2, "{out}");
    assert_eq!(
        out.matches("//line foo/command.gen.go:1:1").count(),
        2,
        "{out}"
    );
}

#[test]
fn emits_go_mod_and_feature_stub() {
    let module = minimal_module("test_app", "customer");
    let files = generate_v1(&module, &GoEmitOptions::default());

    // Invariant 1: at least go.mod + one feature stub.
    assert!(
        files.len() >= 2,
        "expected go.mod plus at least one feature stub, got {} files",
        files.len()
    );

    let go_mod = files
        .iter()
        .find(|f| f.path == "go.mod")
        .expect("go.mod missing from emitter output");
    let feature_file = files
        .iter()
        .find(|f| f.path == "customer/customer.gen.go")
        .expect("customer feature stub missing");

    // Invariant 2: go.mod resolves the derived module path and the
    // crate-pinned Lazuli Go version.
    assert!(
        go_mod.contents.contains("module lazuli/test-app"),
        "expected `module lazuli/test-app` in go.mod, got:\n{}",
        go_mod.contents
    );
    assert!(
        go_mod
            .contents
            .contains(&format!("lazuli.dev/runtime {}", LAZULI_GO_VERSION)),
        "expected `lazuli.dev/runtime {LAZULI_GO_VERSION}` in go.mod, got:\n{}",
        go_mod.contents
    );

    // Invariant 3: each .gen.go opens with the banner + the feature
    // package directive.
    assert!(
        feature_file
            .contents
            .contains("// Code generated by lazuli; DO NOT EDIT."),
        "missing Code Connect-style banner in feature stub:\n{}",
        feature_file.contents
    );
    assert!(
        feature_file.contents.contains("\npackage customergen\n"),
        "expected `package customergen` in feature stub:\n{}",
        feature_file.contents
    );
}

#[test]
fn module_name_override_wins_over_app_name() {
    let module = minimal_module("test_app", "customer");
    let options = GoEmitOptions {
        module_name: Some("github.com/acme/custom-name".to_owned()),
        lazuli_go_version: LAZULI_GO_VERSION.to_owned(),
        check: false,
        plan_gate: None,
    };
    let files = generate_v1(&module, &options);
    let go_mod = files
        .iter()
        .find(|f| f.path == "go.mod")
        .expect("go.mod missing");
    assert!(go_mod
        .contents
        .contains("module github.com/acme/custom-name"));
}

#[test]
fn deterministic_output_across_runs() {
    let module = minimal_module("marketplace", "customer");
    let a = generate_v1(&module, &GoEmitOptions::default());
    let b = generate_v1(&module, &GoEmitOptions::default());
    assert_eq!(a.len(), b.len());
    for (left, right) in a.iter().zip(b.iter()) {
        assert_eq!(left.path, right.path);
        assert_eq!(left.contents, right.contents);
    }
}

#[test]
fn resource_kind_emits_typed_struct_and_resource_value() {
    // Cell E2 integration smoke: a feature carrying one resource
    // surfaces an extra `<feature>/resource.gen.go` alongside the
    // stub. Typed struct + `lazuli.Resource[T]` value land per
    // proposal §3.1.
    let mut module = minimal_module("marketplace", "customer");
    let resource = Resource {
        name: "customer".to_owned(),
        public_contract: None,
        tenancy: None,
        soft_delete: false,
        timestamps: None,
        fields: vec![Field {
            name: "name".to_owned(),
            type_ref: TypeRef::Builtin(BuiltinType::Text),
            required: true,
            unique: false,
            slug: false,
            default: None,
            derived_from: None,
            constraints: FieldConstraints::default(),
            full_text: false,
            previous_names: Vec::new(),
            span_ref: None,
        }],
        constraints: Vec::new(),
        validate: None,
        validates: Vec::new(),
        retention: None,
        previous_names: Vec::new(),
        span_ref: None,
        lifecycle: None,
        invariants: vec![],
        lock: None,
        composite_key: None,
    };
    module.features[0].resources.push(resource);

    let files = generate_v1(&module, &GoEmitOptions::default());
    let resource_file = files
        .iter()
        .find(|f| f.path == "customer/resource.gen.go")
        .expect("expected customer/resource.gen.go alongside the stub");
    assert!(
        resource_file.contents.contains("type Customer struct"),
        "expected struct declaration in resource.gen.go:\n{}",
        resource_file.contents
    );
    assert!(
        resource_file
            .contents
            .contains("var customerResource = lazuli.Resource[Customer]"),
        "expected `var customerResource = lazuli.Resource[Customer]` in resource.gen.go:\n{}",
        resource_file.contents
    );
}

#[test]
fn resource_kind_skips_file_when_feature_declares_no_resources_or_records() {
    // A bare feature stays at the `<feature>.gen.go` stub only; we
    // don't materialise an empty `resource.gen.go` because a single
    // `package <feature>` line provides no signal and would clutter
    // the listing.
    let module = minimal_module("marketplace", "customer");
    let files = generate_v1(&module, &GoEmitOptions::default());
    assert!(
        files.iter().all(|f| f.path != "customer/resource.gen.go"),
        "expected no resource.gen.go for an empty feature, got files: {:?}",
        files.iter().map(|f| &f.path).collect::<Vec<_>>()
    );
}

#[test]
fn enum_kind_emits_typed_alias_and_const_block() {
    // Cell E2.5 integration smoke: a feature carrying one int-typed
    // enum surfaces an extra `<feature>/enum.gen.go` alongside the
    // stub. Typed alias + aligned const block land per proposal §3.
    let mut module = minimal_module("marketplace", "customer");
    module.features[0].enums.push(EnumDecl {
        name: "CustomerStatus".to_owned(),
        public_contract: None,
        variants: vec![
            EnumVariant {
                name: "lead".to_owned(),
                storage_value: Some(StorageValue::Integer(10)),
                previous_names: Vec::new(),
            },
            EnumVariant {
                name: "active".to_owned(),
                storage_value: Some(StorageValue::Integer(20)),
                previous_names: Vec::new(),
            },
        ],
        previous_names: Vec::new(),
        span_ref: None,
    });

    let files = generate_v1(&module, &GoEmitOptions::default());
    let enum_file = files
        .iter()
        .find(|f| f.path == "customer/enum.gen.go")
        .expect("expected customer/enum.gen.go alongside the stub");
    assert!(
        enum_file.contents.contains("type CustomerStatus int64"),
        "expected typed alias in enum.gen.go:\n{}",
        enum_file.contents
    );
    assert!(
        enum_file.contents.contains("const ("),
        "expected const block in enum.gen.go:\n{}",
        enum_file.contents
    );
    assert!(
        enum_file
            .contents
            .contains("CustomerStatusLead   CustomerStatus = 10"),
        "expected aligned const row in enum.gen.go:\n{}",
        enum_file.contents
    );
}

#[test]
fn enum_kind_skips_file_when_feature_declares_no_enums() {
    // A bare feature should not materialise `enum.gen.go`. Mirrors
    // the resource-side skip rule so the output listing stays
    // signal-rich.
    let module = minimal_module("marketplace", "customer");
    let files = generate_v1(&module, &GoEmitOptions::default());
    assert!(
        files.iter().all(|f| f.path != "customer/enum.gen.go"),
        "expected no enum.gen.go for an empty feature, got files: {:?}",
        files.iter().map(|f| &f.path).collect::<Vec<_>>()
    );
}

#[test]
fn lazuli_go_version_override_lands_in_go_mod() {
    let module = minimal_module("marketplace", "customer");
    let options = GoEmitOptions {
        module_name: None,
        lazuli_go_version: "v9.9.9".to_owned(),
        check: false,
        plan_gate: None,
    };
    let files = generate_v1(&module, &options);
    let go_mod = files
        .iter()
        .find(|f| f.path == "go.mod")
        .expect("go.mod missing");
    // Require names the Lazuli Go module (`lazuli.dev/runtime`); the
    // generated code imports the per-bucket subpackages
    // (`lazuli.dev/runtime/lazuli`, `lazuli.dev/runtime/lazuli/storage`,
    // ...) against it.
    assert!(go_mod.contents.contains("lazuli.dev/runtime v9.9.9"));
}

#[test]
fn cross_feature_user_defined_ref_emits_qualified_type_and_import() {
    // Phase Prep §1.1 — two features. `customer` declares
    // `Customer`; `org` declares `User`. A `Customer.owner: User`
    // field should emit `*org.User` plus a `lazuli/test-app/org`
    // import in `customer/resource.gen.go`. The analyzer leaves
    // `qname.feature = None` for these refs; codegen resolves them
    // via the cross-feature index.
    let mut module = minimal_module("test_app", "customer");
    module.features.push(empty_feature("org"));

    // Add Customer{owner: User} on `customer` feature.
    module.features[0].resources.push(Resource {
        name: "Customer".to_owned(),
        public_contract: None,
        tenancy: None,
        soft_delete: false,
        timestamps: None,
        fields: vec![Field {
            name: "owner".to_owned(),
            type_ref: TypeRef::UserDefined(lazuli_ir::QualifiedName {
                feature: None,
                name: "User".to_owned(),
            }),
            required: true,
            unique: false,
            slug: false,
            default: None,
            derived_from: None,
            constraints: FieldConstraints::default(),
            full_text: false,
            previous_names: Vec::new(),
            span_ref: None,
        }],
        constraints: Vec::new(),
        validate: None,
        validates: Vec::new(),
        retention: None,
        previous_names: Vec::new(),
        span_ref: None,
        lifecycle: None,
        invariants: vec![],
        lock: None,
        composite_key: None,
    });

    // Add User on `org` feature.
    module.features[1].resources.push(Resource {
        name: "User".to_owned(),
        public_contract: None,
        tenancy: None,
        soft_delete: false,
        timestamps: None,
        fields: vec![Field {
            name: "name".to_owned(),
            type_ref: TypeRef::Builtin(BuiltinType::Text),
            required: true,
            unique: false,
            slug: false,
            default: None,
            derived_from: None,
            constraints: FieldConstraints::default(),
            full_text: false,
            previous_names: Vec::new(),
            span_ref: None,
        }],
        constraints: Vec::new(),
        validate: None,
        validates: Vec::new(),
        retention: None,
        previous_names: Vec::new(),
        span_ref: None,
        lifecycle: None,
        invariants: vec![],
        lock: None,
        composite_key: None,
    });

    let files = generate_v1(&module, &GoEmitOptions::default());
    let customer_resource = files
        .iter()
        .find(|f| f.path == "customer/resource.gen.go")
        .expect("expected customer/resource.gen.go");

    assert!(
        customer_resource.contents.contains("Owner orggen.User"),
        "expected cross-feature `orggen.User` ref, got:\n{}",
        customer_resource.contents
    );
    assert!(
        customer_resource
            .contents
            .contains("\"lazuli/test-app/org\""),
        "expected cross-feature import path `lazuli/test-app/org`, got:\n{}",
        customer_resource.contents
    );

    // Sanity: the `org` feature's resource file still emits `User`
    // bare (same-package).
    let org_resource = files
        .iter()
        .find(|f| f.path == "org/resource.gen.go")
        .expect("expected org/resource.gen.go");
    assert!(
        org_resource.contents.contains("type User struct"),
        "expected `type User struct` in org/resource.gen.go, got:\n{}",
        org_resource.contents
    );
}

#[test]
fn command_kind_emits_typed_input_struct_and_command_value() {
    // Cell E3 integration smoke: a feature carrying one Command with
    // a typed input + Creates effect surfaces an extra
    // `<feature>/command.gen.go` alongside the resource file. The
    // shape mirrors `dist/go/customer/customer.gen.go:48-68` (proven
    // by the runtime spike). Per proposal §3.2 we land the typed
    // `<Verb><Resource>Input` struct plus the
    // `lazuli.Command[I, O]` value with `Effect: lazuli.Creates(...)`.
    let mut module = minimal_module("marketplace", "customer");

    // Resource the command targets — same feature.
    module.features[0].resources.push(Resource {
        name: "Customer".to_owned(),
        public_contract: None,
        tenancy: None,
        soft_delete: false,
        timestamps: None,
        fields: vec![
            Field {
                name: "name".to_owned(),
                type_ref: TypeRef::Builtin(BuiltinType::Text),
                required: true,
                unique: false,
                slug: false,
                default: None,
                derived_from: None,
                constraints: FieldConstraints::default(),
                full_text: false,
                previous_names: Vec::new(),
                span_ref: None,
            },
            Field {
                name: "email".to_owned(),
                type_ref: TypeRef::Builtin(BuiltinType::SemanticEmail),
                required: true,
                unique: false,
                slug: false,
                default: None,
                derived_from: None,
                constraints: FieldConstraints::default(),
                full_text: false,
                previous_names: Vec::new(),
                span_ref: None,
            },
        ],
        constraints: Vec::new(),
        validate: None,
        validates: Vec::new(),
        retention: None,
        previous_names: Vec::new(),
        span_ref: None,
        lifecycle: None,
        invariants: vec![],
        lock: None,
        composite_key: None,
    });

    // Command — `customer.create` with typed input + Creates effect.
    module.features[0].commands.push(Command {
        name: "create".to_owned(),
        public_contract: None,
        kind: CommandKind::Create,
        route: Vec::new(),
        input: CommandInput::Typed(vec![
            TypedSlot {
                name: "name".to_owned(),
                type_ref: TypeRef::Builtin(BuiltinType::Text),
                required: true,
                constraints: FieldConstraints::default(),
            },
            TypedSlot {
                name: "email".to_owned(),
                type_ref: TypeRef::Builtin(BuiltinType::SemanticEmail),
                required: true,
                constraints: FieldConstraints::default(),
            },
        ]),
        target: None,
        lets: Vec::new(),
        effect: CommandEffect::Creates(CreateEffect {
            resource: QualifiedName {
                feature: None,
                name: "Customer".to_owned(),
            },
            from_input: false,
            assignments: vec![
                Assignment {
                    field: "name".to_owned(),
                    value: Expr::Path(Path::from_segments(["input", "name"])),
                },
                Assignment {
                    field: "email".to_owned(),
                    value: Expr::Path(Path::from_segments(["input", "email"])),
                },
            ],
        }),
        policy: PolicyRef::Atom("@role.admin".to_owned()),
        policy_expr: None,
        emits: vec!["customer_created".to_owned()],
        rate_limit: Some("30 per hour per ip".to_owned()),
        audit: None,
        approval: None,
        invalidates: Vec::new(),
        external_calls: Vec::new(),
        timeout: None,
        retry: None,
        idempotency: None,
        write_window: None,
        deprecated: None,
        handler: None,
        tests: None,
        previous_names: Vec::new(),
        span_ref: None,
    });

    let files = generate_v1(&module, &GoEmitOptions::default());
    let command_file = files
        .iter()
        .find(|f| f.path == "customer/command.gen.go")
        .expect("expected customer/command.gen.go alongside the resource file");

    // Banner + package directive.
    assert!(
        command_file
            .contents
            .contains("// Code generated by lazuli; DO NOT EDIT."),
        "missing banner in command.gen.go:\n{}",
        command_file.contents
    );
    assert!(
        command_file.contents.contains("\npackage customergen\n"),
        "expected `package customergen` in command.gen.go:\n{}",
        command_file.contents
    );

    // Input struct shape — typed slots with JSON tags.
    assert!(
        command_file
            .contents
            .contains("type CreateCustomerInput struct {"),
        "expected `type CreateCustomerInput struct` in command.gen.go:\n{}",
        command_file.contents
    );
    assert!(
        command_file.contents.contains("Email lazuli.Email"),
        "expected `Email lazuli.Email` field row in CreateCustomerInput:\n{}",
        command_file.contents
    );

    // Command value shape — generic over input/output, with Creates effect.
    assert!(
        command_file
            .contents
            .contains("var createCustomer = lazuli.Command[CreateCustomerInput, Customer]{"),
        "expected `var createCustomer = lazuli.Command[CreateCustomerInput, Customer]` in command.gen.go:\n{}",
        command_file.contents
    );
    assert!(
        command_file
            .contents
            .contains("Effect: lazuli.Creates(&customerResource, lazuli.Bindings{"),
        "expected `Effect: lazuli.Creates(...)` block in command.gen.go:\n{}",
        command_file.contents
    );
    assert!(
        command_file
            .contents
            .contains("\"email\": lazuli.FromInput(\"email\"),"),
        "expected `email` binding row in command.gen.go:\n{}",
        command_file.contents
    );
    assert!(
        command_file
            .contents
            .contains("{Name: \"customer_created\", From: lazuli.FromExplicit},"),
        "expected emits row in command.gen.go:\n{}",
        command_file.contents
    );
    // Policy.Atom rendering — `@role.admin` splits into namespace/name.
    assert!(
        command_file
            .contents
            .contains("lazuli.PolicyAtom{{Namespace: \"role\", Name: \"admin\"}}"),
        "expected `PolicyAtom{{Namespace: \"role\", Name: \"admin\"}}` in command.gen.go:\n{}",
        command_file.contents
    );
}

#[test]
fn command_kind_skips_file_when_feature_declares_no_commands() {
    // Mirrors the resource / enum skip rule — a feature without
    // commands should not materialise `command.gen.go`.
    let module = minimal_module("marketplace", "customer");
    let files = generate_v1(&module, &GoEmitOptions::default());
    assert!(
        files.iter().all(|f| f.path != "customer/command.gen.go"),
        "expected no command.gen.go for an empty feature, got files: {:?}",
        files.iter().map(|f| &f.path).collect::<Vec<_>>()
    );
}

#[test]
fn root_main_go_is_emitted_with_package_main_and_boot_call() {
    // Cell I2 integration smoke — every module materialises a root
    // `main.go` with a `package main` directive and the `lazuli.Boot`
    // call so `go build ./...` links a binary. Proven by the spike's
    // `dist/go/main.go`; the emitter now lifts that shape from raw
    // hand-written into deterministic codegen output.
    let module = minimal_module("test_app", "customer");
    let files = generate_v1(&module, &GoEmitOptions::default());
    let main = files
        .iter()
        .find(|f| f.path == "main.go")
        .expect("expected root main.go alongside go.mod");

    assert!(
        main.contents
            .contains("// Code generated by lazuli; DO NOT EDIT."),
        "missing Code Connect-style banner in main.go:\n{}",
        main.contents
    );
    assert!(
        main.contents.contains("\npackage main\n"),
        "expected `package main` in main.go:\n{}",
        main.contents
    );
    assert!(
        main.contents.contains("lazuli.Boot(ctx, dbURL)"),
        "expected `lazuli.Boot(ctx, dbURL)` invocation in main.go:\n{}",
        main.contents
    );
    // Feature side-effect import flips `init()` registrations on at
    // process start. `_` alias prevents Go's unused-import check from
    // failing the build.
    assert!(
        main.contents.contains("_ \"lazuli/test-app/customer\""),
        "expected side-effect feature import in main.go:\n{}",
        main.contents
    );
}

#[test]
fn root_main_go_sorts_feature_imports_lexicographically() {
    // Cell I2 invariant — feature side-effect imports walk the IR via
    // a `BTreeMap`, so the prelude is byte-stable regardless of how
    // the IR `Vec` happened to be populated.
    let mut module = minimal_module("marketplace", "zebra");
    module.features.push(empty_feature("alpha"));
    module.features.push(empty_feature("mango"));
    let files = generate_v1(&module, &GoEmitOptions::default());
    let main = files
        .iter()
        .find(|f| f.path == "main.go")
        .expect("expected root main.go");

    let alpha = main
        .contents
        .find("\"lazuli/marketplace/alpha\"")
        .expect("alpha import present");
    let mango = main
        .contents
        .find("\"lazuli/marketplace/mango\"")
        .expect("mango import present");
    let zebra = main
        .contents
        .find("\"lazuli/marketplace/zebra\"")
        .expect("zebra import present");
    assert!(
        alpha < mango && mango < zebra,
        "expected alpha < mango < zebra order, got positions {alpha}/{mango}/{zebra}"
    );
}

#[test]
fn emit_v1_with_manifest_plugins_emits_anonymous_imports() {
    let module = minimal_module("test_app", "customer");
    let manifest = lazurite_manifest(
        vec![
            (
                "@plugin/mercadopago",
                "github.com/lazuli-lang/lazuli-plugin-mercadopago",
            ),
            (
                "@plugin/expo_push",
                "github.com/lazuli-lang/lazuli-plugin-expo-push",
            ),
        ],
        Some(LazuriteGenerateGo {
            emit_main: true,
            submodule: true,
            dev_replace: None,
            dev_work_replace: None,
        }),
        Vec::new(),
    );
    let files = generate_v1_with_manifest(&module, &GoEmitOptions::default(), Some(&manifest));
    let main = files
        .iter()
        .find(|f| f.path == "main.go")
        .expect("expected main.go");

    let expo = main
        .contents
        .find("_ \"github.com/lazuli-lang/lazuli-plugin-expo-push\"")
        .expect("expo push plugin import");
    let mercado = main
        .contents
        .find("_ \"github.com/lazuli-lang/lazuli-plugin-mercadopago\"")
        .expect("mercadopago plugin import");
    assert!(expo < mercado, "expected plugin imports sorted by ref");
    assert!(main
        .contents
        .contains("// Plugin imports - registered at init time via lazuli.RegisterAdapter."));
}

#[test]
fn emit_v1_with_submodule_false_skips_dist_go_mod() {
    let module = minimal_module("test_app", "customer");
    let manifest = lazurite_manifest(
        Vec::new(),
        Some(LazuriteGenerateGo {
            emit_main: true,
            submodule: false,
            dev_replace: None,
            dev_work_replace: None,
        }),
        Vec::new(),
    );
    let files = generate_v1_with_manifest(&module, &GoEmitOptions::default(), Some(&manifest));

    assert!(
        files.iter().all(|f| f.path != "go.mod"),
        "expected no dist/go/go.mod when submodule=false, got {:?}",
        files.iter().map(|f| &f.path).collect::<Vec<_>>()
    );
    assert!(
        files.iter().all(|f| f.path != "go.work"),
        "expected no go.work when submodule=false"
    );
}

#[test]
fn emit_v1_with_emit_main_false_skips_main_go() {
    let module = minimal_module("test_app", "customer");
    let manifest = lazurite_manifest(
        Vec::new(),
        Some(LazuriteGenerateGo {
            emit_main: false,
            submodule: true,
            dev_replace: None,
            dev_work_replace: None,
        }),
        Vec::new(),
    );
    let files = generate_v1_with_manifest(&module, &GoEmitOptions::default(), Some(&manifest));

    assert!(
        files.iter().all(|f| f.path != "main.go"),
        "expected no main.go when emit_main=false"
    );
}

#[test]
fn emit_v1_with_local_plugin_paths_emits_replace_directives() {
    let module = minimal_module("test_app", "customer");
    let manifest = lazurite_manifest(
        vec![(
            "@plugin/mercadopago",
            "github.com/lazuli-lang/lazuli-plugin-mercadopago",
        )],
        Some(LazuriteGenerateGo {
            emit_main: true,
            submodule: true,
            dev_replace: None,
            dev_work_replace: None,
        }),
        vec![("@plugin/mercadopago", "../lazuli-plugin-mercadopago")],
    );
    let files = generate_v1_with_manifest(&module, &GoEmitOptions::default(), Some(&manifest));
    let go_mod = files
        .iter()
        .find(|f| f.path == "go.mod")
        .expect("expected generated go.mod");
    let go_work = files
        .iter()
        .find(|f| f.path == "go.work")
        .expect("expected top-level go.work companion");

    assert!(go_mod
        .contents
        .contains("module github.com/acme/test-app/generated"));
    assert!(go_mod.contents.contains(
        "replace github.com/lazuli-lang/lazuli-plugin-mercadopago => ../lazuli-plugin-mercadopago"
    ));
    assert!(go_work.contents.contains("./dist/go"));
}

#[test]
fn emit_go_mod_with_plugins_emits_require_lines() {
    let module = minimal_module("test_app", "customer");
    let manifest = lazurite_manifest(
        vec![("@plugin/foo", "github.com/lazuli-lang/lazuli-plugin-foo")],
        Some(LazuriteGenerateGo {
            emit_main: true,
            submodule: true,
            dev_replace: None,
            dev_work_replace: None,
        }),
        Vec::new(),
    );
    let files = generate_v1_with_manifest(&module, &GoEmitOptions::default(), Some(&manifest));
    let go_mod = files
        .iter()
        .find(|f| f.path == "go.mod")
        .expect("expected generated go.mod");

    assert!(go_mod
        .contents
        .contains("github.com/lazuli-lang/lazuli-plugin-foo v0.1.0"));
}

#[test]
fn emit_go_mod_with_geopoint_resource_adds_postgis_require() {
    let mut module = minimal_module("marketplace", "listing");
    module.features[0].resources.push(Resource {
        name: "Listing".to_owned(),
        public_contract: None,
        tenancy: None,
        soft_delete: false,
        timestamps: None,
        fields: vec![Field {
            name: "location".to_owned(),
            type_ref: TypeRef::Builtin(BuiltinType::SemanticGeoPoint),
            required: true,
            unique: false,
            slug: false,
            default: None,
            derived_from: None,
            constraints: FieldConstraints::default(),
            full_text: false,
            previous_names: Vec::new(),
            span_ref: None,
        }],
        constraints: Vec::new(),
        validate: None,
        validates: Vec::new(),
        retention: None,
        previous_names: Vec::new(),
        span_ref: None,
        lifecycle: None,
        invariants: vec![],
        lock: None,
        composite_key: None,
    });

    let files = generate_v1(&module, &GoEmitOptions::default());
    let go_mod = files
        .iter()
        .find(|f| f.path == "go.mod")
        .expect("expected generated go.mod");

    assert!(go_mod
        .contents
        .contains("github.com/cridenour/go-postgis v1.0.2"));
}

#[test]
fn emit_go_mod_with_dev_replace_skips_replace_in_workspace_mode() {
    // Workspace mode (manifest + submodule) writes a sibling `go.work`
    // that `use`s the runtime directly. `dist/go/go.mod` therefore
    // omits the `require lazuli.dev/runtime` line — and the
    // corresponding `replace` directive would be a no-op (replacing a
    // module that isn't required has no effect). The runtime pin
    // surfaces in `go.work` via `emit_go_work_with_dev_replace_*`
    // instead.
    let module = minimal_module("test_app", "customer");
    let manifest = lazurite_manifest(
        Vec::new(),
        Some(LazuriteGenerateGo {
            emit_main: true,
            submodule: true,
            dev_replace: Some("../../runtime/go".to_owned()),
            dev_work_replace: None,
        }),
        Vec::new(),
    );
    let files = generate_v1_with_manifest(&module, &GoEmitOptions::default(), Some(&manifest));
    let go_mod = files
        .iter()
        .find(|f| f.path == "go.mod")
        .expect("expected generated go.mod");

    assert!(
        !go_mod.contents.contains("lazuli.dev/runtime"),
        "workspace mode must not name `lazuli.dev/runtime` in dist/go/go.mod:\n{}",
        go_mod.contents
    );

}

#[test]
fn emit_go_work_with_dev_replace_includes_runtime_path() {
    let module = minimal_module("test_app", "customer");
    let manifest = lazurite_manifest(
        Vec::new(),
        Some(LazuriteGenerateGo {
            emit_main: true,
            submodule: true,
            dev_replace: Some("../../runtime/go".to_owned()),
            dev_work_replace: None,
        }),
        Vec::new(),
    );
    let files = generate_v1_with_manifest(&module, &GoEmitOptions::default(), Some(&manifest));
    let go_work = files
        .iter()
        .find(|f| f.path == "go.work")
        .expect("expected generated go.work");

    assert!(go_work.contents.contains("../../runtime/go"));
}

#[test]
fn emit_go_mod_without_manifest_falls_back_to_legacy_behavior() {
    let module = minimal_module("test_app", "customer");
    let files = generate_v1(&module, &GoEmitOptions::default());
    let go_mod = files
        .iter()
        .find(|f| f.path == "go.mod")
        .expect("expected generated go.mod");

    assert!(go_mod.contents.contains("lazuli.dev/runtime"));
    assert!(!go_mod.contents.contains("replace lazuli.dev/runtime"));
    assert!(!go_mod
        .contents
        .contains("github.com/lazuli-lang/lazuli-plugin"));
    assert!(!go_mod.contents.contains("github.com/cridenour/go-postgis"));
}

#[test]
fn root_lazuli_app_gen_emits_app_name_and_locale_contract() {
    // Cell I2 — when `module.app: Option<AppManifest>` carries an
    // `app.locale` block the emitter renders an `i18n.LocaleContract`
    // value matching the runtime team's hand-rolled contract type
    // (`runtime/go/lazuli/i18n/contract.go`).
    let mut module = minimal_module("test_app", "customer");
    if let Some(app) = module.app.as_mut() {
        app.locale = Some(AppLocale {
            default: "pt-BR".to_owned(),
            supported: vec!["pt-BR".to_owned(), "en-US".to_owned()],
            fallbacks: Vec::new(),
        });
    }
    let files = generate_v1(&module, &GoEmitOptions::default());
    let app_gen = files
        .iter()
        .find(|f| f.path == "lazuli_app.gen.go")
        .expect("expected root lazuli_app.gen.go");
    assert!(
        app_gen.contents.contains("\npackage main\n"),
        "expected `package main` in lazuli_app.gen.go:\n{}",
        app_gen.contents
    );
    assert!(
        app_gen.contents.contains("const AppName = \"test_app\""),
        "expected `AppName` constant in lazuli_app.gen.go:\n{}",
        app_gen.contents
    );
    assert!(
        app_gen
            .contents
            .contains("var LocaleContract = i18n.LocaleContract{"),
        "expected `LocaleContract` declaration in lazuli_app.gen.go:\n{}",
        app_gen.contents
    );
    assert!(
        app_gen.contents.contains("Default: \"pt-BR\","),
        "expected lowered default locale tag:\n{}",
        app_gen.contents
    );
}

#[test]
fn root_lazuli_app_gen_emits_logging_and_tracing_contracts() {
    // Cell I2 — `app.logging` + `app.tracing` lower to the runtime's
    // `observability` package contract values (already declared in
    // `runtime/go/lazuli/observability/`).
    let mut module = minimal_module("AcmeCRM", "customer");
    if let Some(app) = module.app.as_mut() {
        app.logging = Some(AppLogging {
            level: Some("info".to_owned()),
            format: Some("json".to_owned()),
            redact: Some("pii".to_owned()),
            sample_rate: None,
            span_ref: None,
        });
        app.tracing = Some(AppTracing {
            propagate: Some(true),
            sample_rate: Some(0.1),
            exporter: Some("@adapter.otlp".to_owned()),
            span_ref: None,
        });
    }
    let files = generate_v1(&module, &GoEmitOptions::default());
    let app_gen = files
        .iter()
        .find(|f| f.path == "lazuli_app.gen.go")
        .expect("expected root lazuli_app.gen.go");

    assert!(
        app_gen
            .contents
            .contains("\"lazuli.dev/runtime/lazuli/observability\""),
        "expected observability import in lazuli_app.gen.go:\n{}",
        app_gen.contents
    );
    assert!(
        app_gen
            .contents
            .contains("var LoggingContract = observability.LoggingContract{"),
        "expected `LoggingContract` declaration:\n{}",
        app_gen.contents
    );
    // The struct-literal block aligns `Level:`/`Format:`/`Redact:` to
    // the widest key in the block. The integration fixture omits
    // `SampleRate`, so the widest key here is `Format:` (7 chars).
    assert!(
        app_gen
            .contents
            .contains("Level:  observability.LogLevelInfo,"),
        "expected lowered LogLevel constant:\n{}",
        app_gen.contents
    );
    assert!(
        app_gen
            .contents
            .contains("var TracingContract = observability.TracingContract{"),
        "expected `TracingContract` declaration:\n{}",
        app_gen.contents
    );
    // `SampleRate:` is the widest key in the tracing block, so
    // `Exporter:` (9 chars) gets two trailing spaces before the
    // value column.
    assert!(
        app_gen.contents.contains("Exporter:   \"@adapter.otlp\","),
        "expected adapter exporter literal:\n{}",
        app_gen.contents
    );
}

#[test]
fn root_lazuli_app_gen_skipped_when_manifest_has_no_observable_surface() {
    // Cell I2 — if the only thing in `AppManifest` is an empty name
    // and no sub-blocks, emitting the file is noise. Mirrors the
    // per-feature skip rules (`resource.gen.go` / `enum.gen.go` /
    // `command.gen.go`).
    let mut module = minimal_module("", "customer");
    // Clear every sub-block — the helper already left them None.
    if let Some(app) = module.app.as_mut() {
        app.locale = None;
        app.logging = None;
        app.tracing = None;
    }
    let files = generate_v1(&module, &GoEmitOptions::default());
    assert!(
        files.iter().all(|f| f.path != "lazuli_app.gen.go"),
        "expected no lazuli_app.gen.go when manifest carries no observable surface, got files: {:?}",
        files.iter().map(|f| &f.path).collect::<Vec<_>>()
    );
    // But main.go should still be present — the binary entry point is
    // mandatory even on a bare module.
    assert!(
        files.iter().any(|f| f.path == "main.go"),
        "expected root main.go regardless of manifest surface"
    );
}

#[test]
fn full_capsule_emits_expected_integration_snapshot_structure() {
    let repo_root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("crate should live under <repo>/crates/lazuli_codegen_go");
    let fixture_dir = repo_root.join("examples").join("full-capsule");

    let app_source = std::fs::read_to_string(fixture_dir.join("app.lzi"))
        .expect("expected examples/full-capsule/app.lzi to be readable");
    let app_name = app_source
        .lines()
        .find_map(|line| line.trim().strip_prefix("app "))
        .expect("expected full-capsule app.lzi to declare `app <Name>`");

    let feature_source = std::fs::read_to_string(fixture_dir.join("full-capsule.lzi"))
        .expect("expected examples/full-capsule/full-capsule.lzi to be readable");
    let features = lazuli_syntax::parse_feature_skeletons(&feature_source)
        .expect("expected full-capsule feature skeletons to parse")
        .into_iter()
        .map(|ast| {
            lazuli_analyzer::lower_feature_skeleton(&ast)
                .expect("expected full-capsule feature skeleton to lower")
        })
        .collect();

    let module = Module {
        workspace: None,
        contracts: Vec::new(),
        app: Some(minimal_app_manifest(app_name)),
        registry: None,
        profiles: Vec::new(),
        design: None,
        rbac: None,
        features,
    };
    let files = generate_v1(&module, &GoEmitOptions::default());
    let paths = files
        .iter()
        .map(|file| file.path.as_str())
        .collect::<Vec<_>>();

    assert!(
        files.len() >= 40,
        "expected at least 40 full-capsule files, got {}: {:?}",
        files.len(),
        paths
    );

    for feature in [
        "account",
        "customer",
        "customer_auth",
        "customer_import",
        "customer_outreach",
        "customer_tags",
    ] {
        assert!(
            paths
                .iter()
                .any(|path| path.starts_with(&format!("{feature}/"))),
            "expected generated directory for feature `{feature}`, got: {:?}",
            paths
        );
    }

    for root_file in ["go.mod", "main.go", "lazuli_app.gen.go"] {
        assert!(
            paths.contains(&root_file),
            "expected root file `{root_file}`, got: {:?}",
            paths
        );
    }

    assert!(
        paths
            .iter()
            .any(|path| path.starts_with("migrations/") && path.ends_with(".sql")),
        "expected at least one N3 DDL migration file, got: {:?}",
        paths
    );
}
