//! Smoke test for `generate_v1` (cell E1). Constructs a minimal IR
//! `Module` by hand (one feature, no kinds), runs the emitter, and
//! verifies the structural invariants the proposal locks in:
//!
//! 1. At least one feature `.gen.go` plus the root `go.mod`.
//! 2. `go.mod` carries the resolved module path and the
//!    `require lazuli.dev/runtime/lazuli <version>` line.
//! 3. Each `.gen.go` opens with the Code Connect-style banner
//!    (`// Code generated by lazuli; DO NOT EDIT.`) and a
//!    matching `package <feature_name>` directive.
//!
//! Hand-rolled IR (not via the analyzer) keeps the test
//! deliberately decoupled from grammar-side drift.

use lazuli_codegen_go::{GoEmitOptions, LAZULI_GO_VERSION, generate_v1};
use lazuli_ir::{AppManifest, Defaults, Feature, Module, Policies};

fn empty_feature(name: &str) -> Feature {
    Feature {
        name: name.to_owned(),
        purpose: None,
        non_goals: Vec::new(),
        context_path: None,
        defaults: Defaults {
            tenancy: None,
            timestamps: false,
            policy: None,
        },
        uses: Vec::new(),
        requirements: Vec::new(),
        enums: Vec::new(),
        resources: Vec::new(),
        events: Vec::new(),
        rules: Vec::new(),
        policies: Policies {
            categories: Vec::new(),
            fields: Vec::new(),
            span_ref: None,
        },
        commands: Vec::new(),
        apis: Vec::new(),
        records: Vec::new(),
        queries: Vec::new(),
        workflows: Vec::new(),
        jobs: Vec::new(),
        webhooks: Vec::new(),
        notifications: Vec::new(),
        event_groups: Vec::new(),
        tenant_migrations: Vec::new(),
        translation: None,
        auth: None,
        surfaces: Vec::new(),
        extensions: Vec::new(),
        escape_routes: Vec::new(),
        agents: Vec::new(),
        previous_names: Vec::new(),
        span_ref: None,
    }
}

fn minimal_app_manifest(name: &str) -> AppManifest {
    // `AppManifest` has no `Default` impl (the bucket-observability
    // cycle dropped `Eq` derive so `f64` sample-rate fields can
    // coexist). Build the whole shape explicitly.
    AppManifest {
        name: name.to_owned(),
        title: None,
        version: None,
        targets: Vec::new(),
        default_locale: None,
        default_timezone: None,
        auth_failed_redirect: None,
        not_found: None,
        uses: Vec::new(),
        packs: Vec::new(),
        bindings: Vec::new(),
        architecture: None,
        services: Vec::new(),
        communication: None,
        environments: Vec::new(),
        urls: Vec::new(),
        cors: None,
        env: Vec::new(),
        integrations: Vec::new(),
        capabilities: Vec::new(),
        runtime: Vec::new(),
        deploy: None,
        logging: None,
        tracing: None,
        locale: None,
        span_ref: None,
    }
}

fn minimal_module(app_name: &str, feature_name: &str) -> Module {
    Module {
        workspace: None,
        contracts: Vec::new(),
        app: Some(minimal_app_manifest(app_name)),
        registry: None,
        profiles: Vec::new(),
        features: vec![empty_feature(feature_name)],
    }
}

#[test]
fn emits_go_mod_and_feature_stub() {
    let module = minimal_module("test_app", "customer");
    let files = generate_v1(&module, &GoEmitOptions::default());

    // Invariant 1: at least go.mod + one feature stub.
    assert!(
        files.len() >= 2,
        "expected go.mod plus at least one feature stub, got {} files",
        files.len()
    );

    let go_mod = files
        .iter()
        .find(|f| f.path == "go.mod")
        .expect("go.mod missing from emitter output");
    let feature_file = files
        .iter()
        .find(|f| f.path == "customer/customer.gen.go")
        .expect("customer feature stub missing");

    // Invariant 2: go.mod resolves the derived module path and the
    // crate-pinned Lazuli Go version.
    assert!(
        go_mod.contents.contains("module lazuli/test-app"),
        "expected `module lazuli/test-app` in go.mod, got:\n{}",
        go_mod.contents
    );
    assert!(
        go_mod
            .contents
            .contains(&format!("lazuli.dev/runtime/lazuli {}", LAZULI_GO_VERSION)),
        "expected `lazuli.dev/runtime/lazuli {LAZULI_GO_VERSION}` in go.mod, got:\n{}",
        go_mod.contents
    );

    // Invariant 3: each .gen.go opens with the banner + the feature
    // package directive.
    assert!(
        feature_file
            .contents
            .contains("// Code generated by lazuli; DO NOT EDIT."),
        "missing Code Connect-style banner in feature stub:\n{}",
        feature_file.contents
    );
    assert!(
        feature_file.contents.contains("\npackage customer\n"),
        "expected `package customer` in feature stub:\n{}",
        feature_file.contents
    );
}

#[test]
fn module_name_override_wins_over_app_name() {
    let module = minimal_module("test_app", "customer");
    let options = GoEmitOptions {
        module_name: Some("github.com/acme/custom-name".to_owned()),
        lazuli_go_version: LAZULI_GO_VERSION.to_owned(),
        check: false,
    };
    let files = generate_v1(&module, &options);
    let go_mod = files
        .iter()
        .find(|f| f.path == "go.mod")
        .expect("go.mod missing");
    assert!(go_mod.contents.contains("module github.com/acme/custom-name"));
}

#[test]
fn deterministic_output_across_runs() {
    let module = minimal_module("hostpoint", "customer");
    let a = generate_v1(&module, &GoEmitOptions::default());
    let b = generate_v1(&module, &GoEmitOptions::default());
    assert_eq!(a.len(), b.len());
    for (left, right) in a.iter().zip(b.iter()) {
        assert_eq!(left.path, right.path);
        assert_eq!(left.contents, right.contents);
    }
}

#[test]
fn lazuli_go_version_override_lands_in_go_mod() {
    let module = minimal_module("hostpoint", "customer");
    let options = GoEmitOptions {
        module_name: None,
        lazuli_go_version: "v9.9.9".to_owned(),
        check: false,
    };
    let files = generate_v1(&module, &options);
    let go_mod = files
        .iter()
        .find(|f| f.path == "go.mod")
        .expect("go.mod missing");
    assert!(go_mod.contents.contains("lazuli.dev/runtime/lazuli v9.9.9"));
}
