//! Integration test for cell A8 (`LAZ-record-column-jsonb-codegen`).
//!
//! Parses a capsule containing a `record <X>` declaration plus a
//! resource that references it, runs the migration emitter, and snaps
//! the lifted SQL against
//! `crates/lazuli_codegen_go/tests/fixtures/expected/record_column_jsonb_host.sql`.
//!
//! The assertion is two-pronged:
//!
//! 1. **Behavioural** — the emitted migration contains
//!    `address JSONB NOT NULL` (the bug fix; previously it emitted
//!    `address TEXT NOT NULL`, which crashed
//!    `pgx.RowToStructByName` at query.lookup time because a Go `*X`
//!    struct cannot deserialize from a TEXT column).
//! 2. **Snapshot** — the full migration body matches the byte-for-byte
//!    golden under `tests/fixtures/expected/`. Maintenance of the
//!    snapshot is intentionally cheap: when the column-emit DDL
//!    shifts (e.g. a future trailing comment becomes default), the
//!    golden is regenerated by copying the new emitter output.
//!
//! Companion unit tests live in
//! `crates/lazuli_codegen_go/src/emitter/migration_ddl.rs` under
//! `mod tests`. Those cover the optional + nested + `many <Record>` +
//! FK-takes-priority edges; this file pins the canonical surface a
//! pilot author would write.

use lazuli_codegen_go::{GoEmitOptions, generate_v1};
use lazuli_ir::Module;

/// Source capsule the cell brief calls out verbatim — a `Host` resource
/// pulling in a same-feature `Address` record.
const HOST_FEATURE: &str = r#"feature host
  domain
    record Address
      cep: Text required
      street: Text required

    resource Host
      address: Address required
      created_at: DateTime required
"#;

const HOST_GOLDEN: &str = include_str!("fixtures/expected/record_column_jsonb_host.sql");

fn parsed_module(source: &str) -> Module {
    let features = lazuli_syntax::parse_feature_skeletons(source)
        .expect("feature source should parse")
        .into_iter()
        .map(|feature| {
            lazuli_analyzer::lower_feature_skeleton(&feature).expect("feature source should lower")
        })
        .collect();
    Module {
        workspace: None,
        contracts: Vec::new(),
        app: None,
        registry: None,
        profiles: Vec::new(),
        design: None,
        rbac: None,
        doctor_allows: Vec::new(),
        features,
    }
}

#[test]
fn record_field_lowers_to_jsonb_in_emitted_migration() {
    let module = parsed_module(HOST_FEATURE);
    // Sanity — the analyzer lifted the record alongside the resource;
    // if either is missing the rest of the test would silently degrade
    // to "no migration emitted" and produce a confusing failure.
    let feature = &module.features[0];
    assert_eq!(feature.name, "host", "expected `host` feature");
    assert_eq!(
        feature.records.len(),
        1,
        "expected one record (Address) lifted from the capsule"
    );
    assert_eq!(feature.records[0].name, "Address");
    assert_eq!(
        feature.resources.len(),
        1,
        "expected one resource (Host) lifted from the capsule"
    );

    let options = GoEmitOptions::default();
    let files = generate_v1(&module, &options);

    let migration = files
        .iter()
        .find(|file| file.path == "migrations/001_host_host.sql")
        .expect("expected host host migration to be emitted");

    // Behavioural — the bug repro line is `address TEXT NOT NULL`,
    // post-fix it must be `address JSONB NOT NULL`.
    assert!(
        migration.contents.contains("address JSONB NOT NULL"),
        "record-typed field must lower to `address JSONB NOT NULL`; \
         got:\n{}",
        migration.contents
    );
    assert!(
        !migration.contents.contains("address TEXT"),
        "record-typed field must NOT lower to `address TEXT`; \
         got:\n{}",
        migration.contents
    );

    // Snapshot — full migration body matches the golden fixture so
    // unintended drift (header order, trailing semicolons, FK clauses)
    // is caught at the same gate.
    assert_eq!(
        migration.contents.replace("\r\n", "\n"),
        HOST_GOLDEN.replace("\r\n", "\n"),
        "migration body drifted from \
         tests/fixtures/expected/record_column_jsonb_host.sql"
    );
}
