package lazuli

import (
	"errors"
	"fmt"
	"strings"
)

var (
	errDBBulkNoColumns                   = errors.New("lazuli: db bulk insert requires at least one column")
	errDBBulkNoRows                      = errors.New("lazuli: db bulk insert requires at least one row")
	errDBBulkConflictUpdateWithoutTarget = errors.New("lazuli: db bulk insert conflict update columns require a conflict target")
)

// DBBulkInsertOptions configures SQL generated by BuildDBBulkInsertSQL.
type DBBulkInsertOptions struct {
	// Table is an unqualified or schema-qualified table name.
	Table string
	// Columns is the ordered set of inserted columns. Every row must match this
	// width, and Args follows this same column order row by row.
	Columns []string
	// Rows contains the row values to bind into the VALUES placeholders.
	Rows [][]any
	// ConflictTarget enables an ON CONFLICT clause when non-empty.
	ConflictTarget []string
	// ConflictUpdateColumns switches ON CONFLICT from DO NOTHING to DO UPDATE
	// SET for the listed columns.
	ConflictUpdateColumns []string
}

// DBBulkInsertStatement is the SQL and bind arguments produced by
// BuildDBBulkInsertSQL.
type DBBulkInsertStatement struct {
	SQL  string
	Args []any
}

// BuildDBBulkInsertSQL builds a PostgreSQL bulk INSERT or UPSERT statement.
//
// Identifiers must be generated SQL identifiers made from ASCII letters,
// digits, and underscores, starting with a letter or underscore. Table names
// may contain one schema separator, such as "app.users". The builder never
// opens a database connection; callers execute the returned SQL with Args.
func BuildDBBulkInsertSQL(opts DBBulkInsertOptions) (DBBulkInsertStatement, error) {
	table, err := quoteDBBulkTable(opts.Table)
	if err != nil {
		return DBBulkInsertStatement{}, err
	}

	columns, err := quoteDBBulkIdentifiers(opts.Columns, "column")
	if err != nil {
		return DBBulkInsertStatement{}, err
	}
	if len(columns) == 0 {
		return DBBulkInsertStatement{}, errDBBulkNoColumns
	}
	if len(opts.Rows) == 0 {
		return DBBulkInsertStatement{}, errDBBulkNoRows
	}

	values, args, err := buildDBBulkValues(opts.Rows, len(columns))
	if err != nil {
		return DBBulkInsertStatement{}, err
	}

	conflict, err := buildDBBulkConflict(opts.ConflictTarget, opts.ConflictUpdateColumns)
	if err != nil {
		return DBBulkInsertStatement{}, err
	}

	sql := "INSERT INTO " + table + " (" + strings.Join(columns, ", ") + ") VALUES " + strings.Join(values, ", ") + conflict
	return DBBulkInsertStatement{
		SQL:  sql,
		Args: args,
	}, nil
}

func buildDBBulkValues(rows [][]any, width int) ([]string, []any, error) {
	values := make([]string, 0, len(rows))
	args := make([]any, 0, len(rows)*width)
	placeholder := 1

	for rowIndex, row := range rows {
		if len(row) != width {
			return nil, nil, fmt.Errorf("lazuli: db bulk insert row %d has %d values, want %d", rowIndex, len(row), width)
		}

		rowPlaceholders := make([]string, 0, width)
		for _, value := range row {
			rowPlaceholders = append(rowPlaceholders, dbBulkPlaceholder(placeholder))
			args = append(args, value)
			placeholder++
		}
		values = append(values, "("+strings.Join(rowPlaceholders, ", ")+")")
	}

	return values, args, nil
}

func buildDBBulkConflict(target, updateColumns []string) (string, error) {
	if len(target) == 0 {
		if len(updateColumns) > 0 {
			return "", errDBBulkConflictUpdateWithoutTarget
		}
		return "", nil
	}

	quotedTarget, err := quoteDBBulkIdentifiers(target, "conflict target")
	if err != nil {
		return "", err
	}

	if len(updateColumns) == 0 {
		return " ON CONFLICT (" + strings.Join(quotedTarget, ", ") + ") DO NOTHING", nil
	}

	quotedUpdateColumns, err := quoteDBBulkIdentifiers(updateColumns, "conflict update column")
	if err != nil {
		return "", err
	}

	assignments := make([]string, 0, len(quotedUpdateColumns))
	for _, column := range quotedUpdateColumns {
		assignments = append(assignments, column+" = EXCLUDED."+column)
	}

	return " ON CONFLICT (" + strings.Join(quotedTarget, ", ") + ") DO UPDATE SET " + strings.Join(assignments, ", "), nil
}

func quoteDBBulkTable(table string) (string, error) {
	parts := strings.Split(table, ".")
	if len(parts) == 0 || len(parts) > 2 {
		return "", fmt.Errorf("lazuli: invalid db bulk insert table name %q", table)
	}

	quoted := make([]string, 0, len(parts))
	for _, part := range parts {
		quotedPart, err := quoteDBBulkIdentifier(part)
		if err != nil {
			return "", fmt.Errorf("lazuli: invalid db bulk insert table name %q", table)
		}
		quoted = append(quoted, quotedPart)
	}
	return strings.Join(quoted, "."), nil
}

func quoteDBBulkIdentifiers(identifiers []string, label string) ([]string, error) {
	quoted := make([]string, 0, len(identifiers))
	for _, identifier := range identifiers {
		quotedIdentifier, err := quoteDBBulkIdentifier(identifier)
		if err != nil {
			return nil, fmt.Errorf("lazuli: invalid db bulk insert %s %q", label, identifier)
		}
		quoted = append(quoted, quotedIdentifier)
	}
	return quoted, nil
}

func quoteDBBulkIdentifier(identifier string) (string, error) {
	if !validDBBulkIdentifier(identifier) {
		return "", fmt.Errorf("invalid identifier %q", identifier)
	}
	return `"` + identifier + `"`, nil
}

func validDBBulkIdentifier(identifier string) bool {
	if identifier == "" {
		return false
	}
	for i := 0; i < len(identifier); i++ {
		c := identifier[i]
		if i == 0 {
			if !isDBBulkIdentifierLetter(c) && c != '_' {
				return false
			}
			continue
		}
		if !isDBBulkIdentifierLetter(c) && !isDBBulkIdentifierDigit(c) && c != '_' {
			return false
		}
	}
	return true
}

func isDBBulkIdentifierLetter(c byte) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
}

func isDBBulkIdentifierDigit(c byte) bool {
	return c >= '0' && c <= '9'
}

func dbBulkPlaceholder(n int) string {
	return fmt.Sprintf("$%d", n)
}
