package lazuli

import (
	"errors"
	"fmt"
	"strings"

	"lazuli.dev/runtime/lazuli/security"
)

var (
	errInvalidDBViewIdentifier    = errors.New("lazuli: invalid db view identifier")
	errInvalidDBViewOptions       = errors.New("lazuli: invalid db view options")
	errInvalidDBViewQuery         = errors.New("lazuli: invalid db view query")
	errInvalidDBViewRefreshPolicy = errors.New("lazuli: invalid db view refresh policy")
	errInvalidDBViewDropBehavior  = errors.New("lazuli: invalid db view drop behavior")
)

// DBViewKind selects whether a helper targets a regular or materialized view.
type DBViewKind int

const (
	// DBViewRegular builds regular VIEW statements.
	DBViewRegular DBViewKind = iota
	// DBViewMaterialized builds MATERIALIZED VIEW statements.
	DBViewMaterialized
)

// DBViewCheckOption controls the optional WITH CHECK OPTION clause for regular
// views.
type DBViewCheckOption int

const (
	// DBViewNoCheckOption omits WITH CHECK OPTION.
	DBViewNoCheckOption DBViewCheckOption = iota
	// DBViewLocalCheckOption appends WITH LOCAL CHECK OPTION.
	DBViewLocalCheckOption
	// DBViewCascadedCheckOption appends WITH CASCADED CHECK OPTION.
	DBViewCascadedCheckOption
)

// DBViewRefreshPolicy controls the data clause on REFRESH MATERIALIZED VIEW.
type DBViewRefreshPolicy int

const (
	// DBViewRefreshDefault omits WITH DATA/WITH NO DATA.
	DBViewRefreshDefault DBViewRefreshPolicy = iota
	// DBViewRefreshWithData appends WITH DATA.
	DBViewRefreshWithData
	// DBViewRefreshWithNoData appends WITH NO DATA.
	DBViewRefreshWithNoData
)

// DBViewDropBehavior controls the optional dependency behavior on DROP VIEW.
type DBViewDropBehavior string

const (
	// DBViewDropDefault leaves DROP behavior unspecified.
	DBViewDropDefault DBViewDropBehavior = ""
	// DBViewDropRestrict appends RESTRICT.
	DBViewDropRestrict DBViewDropBehavior = "restrict"
	// DBViewDropCascade appends CASCADE.
	DBViewDropCascade DBViewDropBehavior = "cascade"
)

// DBViewCreateOptions configures SQL generated by BuildDBCreateViewSQL.
type DBViewCreateOptions struct {
	// Name is an unqualified or schema-qualified view name.
	Name string
	// Kind selects regular or materialized view DDL. The zero value is regular.
	Kind DBViewKind
	// Columns optionally names the view output columns.
	Columns []string
	// Query is the generated SELECT/WITH query used after AS. It must be a
	// single generated SQL fragment without a statement terminator.
	Query string
	// OrReplace adds OR REPLACE. PostgreSQL supports this only for regular views.
	OrReplace bool
	// IfNotExists adds IF NOT EXISTS. PostgreSQL supports this only for
	// materialized views.
	IfNotExists bool
	// CheckOption appends WITH LOCAL/CASCADED CHECK OPTION for regular views.
	CheckOption DBViewCheckOption
	// WithNoData appends WITH NO DATA for materialized views.
	WithNoData bool
}

// DBMaterializedViewRefreshOptions configures
// BuildDBRefreshMaterializedViewSQL.
type DBMaterializedViewRefreshOptions struct {
	// Concurrently adds CONCURRENTLY.
	Concurrently bool
	// Policy controls WITH DATA/WITH NO DATA.
	Policy DBViewRefreshPolicy
}

// DBViewDropOptions configures BuildDBDropViewSQL.
type DBViewDropOptions struct {
	// Kind selects DROP VIEW or DROP MATERIALIZED VIEW. The zero value is regular.
	Kind DBViewKind
	// IfExists adds IF EXISTS.
	IfExists bool
	// Behavior optionally appends RESTRICT or CASCADE.
	Behavior DBViewDropBehavior
}

// DBViewDependencyNotesOptions configures BuildDBViewDependencyNotes.
type DBViewDependencyNotesOptions struct {
	// View is the view the notes describe.
	View string
	// Kind selects the view label used in generated notes.
	Kind DBViewKind
	// Dependencies are schema-qualified or unqualified tables/views that the
	// view query depends on.
	Dependencies []string
	// Refresh, when set for a materialized view, adds a refresh policy note.
	Refresh *DBMaterializedViewRefreshOptions
}

// BuildDBCreateViewSQL builds a PostgreSQL CREATE VIEW or CREATE MATERIALIZED
// VIEW statement.
//
// Identifiers must be generated SQL identifiers made from ASCII letters,
// digits, and underscores, starting with a letter or underscore. View names may
// contain one schema separator, such as "app.active_users". The helper never
// opens a database connection; callers execute the returned SQL themselves.
func BuildDBCreateViewSQL(opts DBViewCreateOptions) (string, error) {
	viewKind, err := dbViewKindSQL(opts.Kind)
	if err != nil {
		return "", err
	}
	if err := validateDBViewCreateOptions(opts); err != nil {
		return "", err
	}

	name, err := quoteDBViewName("view name", opts.Name)
	if err != nil {
		return "", err
	}
	columns, err := quoteDBViewIdentifiers("column", opts.Columns)
	if err != nil {
		return "", err
	}
	query, err := validateDBViewQuery(opts.Query)
	if err != nil {
		return "", err
	}
	checkOption, err := dbViewCheckOptionSQL(opts.CheckOption)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("CREATE ")
	if opts.OrReplace {
		b.WriteString("OR REPLACE ")
	}
	b.WriteString(viewKind)
	b.WriteByte(' ')
	if opts.IfNotExists {
		b.WriteString("IF NOT EXISTS ")
	}
	b.WriteString(name)
	if len(columns) > 0 {
		b.WriteString(" (")
		b.WriteString(strings.Join(columns, ", "))
		b.WriteByte(')')
	}
	b.WriteString(" AS ")
	b.WriteString(query)
	if opts.WithNoData {
		b.WriteString(" WITH NO DATA")
	}
	b.WriteString(checkOption)
	return b.String(), nil
}

// BuildDBRefreshMaterializedViewSQL builds a PostgreSQL REFRESH MATERIALIZED
// VIEW statement. It only builds SQL and never opens a database connection.
func BuildDBRefreshMaterializedViewSQL(name string, opts DBMaterializedViewRefreshOptions) (string, error) {
	view, err := quoteDBViewName("materialized view name", name)
	if err != nil {
		return "", err
	}
	policy, err := dbViewRefreshPolicySQL(opts)
	if err != nil {
		return "", err
	}

	statement := "REFRESH MATERIALIZED VIEW "
	if opts.Concurrently {
		statement += "CONCURRENTLY "
	}
	return statement + view + policy, nil
}

// BuildDBDropViewSQL builds a PostgreSQL DROP VIEW or DROP MATERIALIZED VIEW
// statement. It only builds SQL and never opens a database connection.
func BuildDBDropViewSQL(name string, opts DBViewDropOptions) (string, error) {
	viewKind, err := dbViewKindSQL(opts.Kind)
	if err != nil {
		return "", err
	}
	view, err := quoteDBViewName("view name", name)
	if err != nil {
		return "", err
	}
	behavior, err := dbViewDropBehaviorSQL(opts.Behavior)
	if err != nil {
		return "", err
	}

	statement := "DROP " + viewKind + " "
	if opts.IfExists {
		statement += "IF EXISTS "
	}
	return statement + view + behavior, nil
}

// BuildDBViewDependencyNotes builds SQL comment lines that document generated
// view dependencies and optional materialized-view refresh policy metadata.
// These notes are intended for migration files; they do not execute database
// metadata changes.
func BuildDBViewDependencyNotes(opts DBViewDependencyNotesOptions) ([]string, error) {
	kindLabel, err := dbViewKindLabel(opts.Kind)
	if err != nil {
		return nil, err
	}
	view, err := quoteDBViewName("view name", opts.View)
	if err != nil {
		return nil, err
	}
	dependencies, err := quoteDBViewNames("dependency", opts.Dependencies)
	if err != nil {
		return nil, err
	}

	notes := make([]string, 0, 2)
	if len(dependencies) > 0 {
		notes = append(notes, "-- lazuli: "+kindLabel+" "+view+" depends on "+strings.Join(dependencies, ", "))
	}
	if opts.Refresh != nil {
		if opts.Kind != DBViewMaterialized {
			return nil, errInvalidDBViewOptions
		}
		refresh, err := dbViewRefreshPolicyNote(*opts.Refresh)
		if err != nil {
			return nil, err
		}
		notes = append(notes, "-- lazuli: materialized view "+view+" refresh "+refresh)
	}
	return notes, nil
}

func validateDBViewCreateOptions(opts DBViewCreateOptions) error {
	switch opts.Kind {
	case DBViewRegular:
		if opts.IfNotExists || opts.WithNoData {
			return errInvalidDBViewOptions
		}
	case DBViewMaterialized:
		if opts.OrReplace || opts.CheckOption != DBViewNoCheckOption {
			return errInvalidDBViewOptions
		}
	default:
		return errInvalidDBViewOptions
	}
	return nil
}

func dbViewKindSQL(kind DBViewKind) (string, error) {
	switch kind {
	case DBViewRegular:
		return "VIEW", nil
	case DBViewMaterialized:
		return "MATERIALIZED VIEW", nil
	default:
		return "", errInvalidDBViewOptions
	}
}

func dbViewKindLabel(kind DBViewKind) (string, error) {
	switch kind {
	case DBViewRegular:
		return "view", nil
	case DBViewMaterialized:
		return "materialized view", nil
	default:
		return "", errInvalidDBViewOptions
	}
}

func dbViewCheckOptionSQL(option DBViewCheckOption) (string, error) {
	switch option {
	case DBViewNoCheckOption:
		return "", nil
	case DBViewLocalCheckOption:
		return " WITH LOCAL CHECK OPTION", nil
	case DBViewCascadedCheckOption:
		return " WITH CASCADED CHECK OPTION", nil
	default:
		return "", errInvalidDBViewOptions
	}
}

func dbViewRefreshPolicySQL(opts DBMaterializedViewRefreshOptions) (string, error) {
	if opts.Concurrently && opts.Policy == DBViewRefreshWithNoData {
		return "", errInvalidDBViewRefreshPolicy
	}
	switch opts.Policy {
	case DBViewRefreshDefault:
		return "", nil
	case DBViewRefreshWithData:
		return " WITH DATA", nil
	case DBViewRefreshWithNoData:
		return " WITH NO DATA", nil
	default:
		return "", errInvalidDBViewRefreshPolicy
	}
}

func dbViewRefreshPolicyNote(opts DBMaterializedViewRefreshOptions) (string, error) {
	if _, err := dbViewRefreshPolicySQL(opts); err != nil {
		return "", err
	}

	parts := make([]string, 0, 3)
	if opts.Concurrently {
		parts = append(parts, "concurrently")
	}
	switch opts.Policy {
	case DBViewRefreshDefault:
		if len(parts) == 0 {
			parts = append(parts, "default")
		}
	case DBViewRefreshWithData:
		parts = append(parts, "with data")
	case DBViewRefreshWithNoData:
		parts = append(parts, "with no data")
	}
	return strings.Join(parts, " "), nil
}

func dbViewDropBehaviorSQL(behavior DBViewDropBehavior) (string, error) {
	switch behavior {
	case DBViewDropDefault:
		return "", nil
	case DBViewDropRestrict:
		return " RESTRICT", nil
	case DBViewDropCascade:
		return " CASCADE", nil
	default:
		return "", fmt.Errorf("%w %q", errInvalidDBViewDropBehavior, behavior)
	}
}

func validateDBViewQuery(query string) (string, error) {
	sql := strings.TrimSpace(query)
	if sql == "" {
		return "", errInvalidDBViewQuery
	}
	if err := security.ValidateGeneratedSQLFragment(sql); err != nil {
		return "", fmt.Errorf("%w: %v", errInvalidDBViewQuery, err)
	}

	switch first := dbViewFirstKeyword(sql); first {
	case "SELECT", "WITH":
		return sql, nil
	default:
		return "", fmt.Errorf("%w: query must start with SELECT or WITH", errInvalidDBViewQuery)
	}
}

func dbViewFirstKeyword(sql string) string {
	for i := 0; i < len(sql); i++ {
		c := sql[i]
		if !isDBViewIdentifierLetter(c) && c != '_' {
			if c == ' ' || c == '\t' || c == '\n' || c == '\r' || c == '\f' {
				continue
			}
			return ""
		}

		start := i
		i++
		for i < len(sql) && (isDBViewIdentifierLetter(sql[i]) || isDBViewIdentifierDigit(sql[i]) || sql[i] == '_') {
			i++
		}
		return strings.ToUpper(sql[start:i])
	}
	return ""
}

func quoteDBViewNames(kind string, names []string) ([]string, error) {
	quoted := make([]string, 0, len(names))
	for _, name := range names {
		quotedName, err := quoteDBViewName(kind, name)
		if err != nil {
			return nil, err
		}
		quoted = append(quoted, quotedName)
	}
	return quoted, nil
}

func quoteDBViewName(kind, name string) (string, error) {
	parts := strings.Split(name, ".")
	if len(parts) > 2 {
		return "", fmt.Errorf("%w: %s %q", errInvalidDBViewIdentifier, kind, name)
	}

	quoted := make([]string, 0, len(parts))
	for _, part := range parts {
		quotedPart, err := quoteDBViewIdentifier(kind, part)
		if err != nil {
			return "", fmt.Errorf("%w: %s %q", errInvalidDBViewIdentifier, kind, name)
		}
		quoted = append(quoted, quotedPart)
	}
	return strings.Join(quoted, "."), nil
}

func quoteDBViewIdentifiers(kind string, identifiers []string) ([]string, error) {
	quoted := make([]string, 0, len(identifiers))
	for _, identifier := range identifiers {
		quotedIdentifier, err := quoteDBViewIdentifier(kind, identifier)
		if err != nil {
			return nil, err
		}
		quoted = append(quoted, quotedIdentifier)
	}
	return quoted, nil
}

func quoteDBViewIdentifier(kind, identifier string) (string, error) {
	if !validDBViewIdentifier(identifier) {
		return "", fmt.Errorf("%w: %s %q", errInvalidDBViewIdentifier, kind, identifier)
	}
	return `"` + identifier + `"`, nil
}

func validDBViewIdentifier(identifier string) bool {
	if identifier == "" {
		return false
	}
	for i := 0; i < len(identifier); i++ {
		c := identifier[i]
		if i == 0 {
			if !isDBViewIdentifierLetter(c) && c != '_' {
				return false
			}
			continue
		}
		if !isDBViewIdentifierLetter(c) && !isDBViewIdentifierDigit(c) && c != '_' {
			return false
		}
	}
	return true
}

func isDBViewIdentifierLetter(c byte) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
}

func isDBViewIdentifierDigit(c byte) bool {
	return c >= '0' && c <= '9'
}
